charts/consul/templates/connect-inject-deployment.yaml, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/subcommand/inject-connect/command.go
- Add `connectInject.consulNode.meta` to values file to allow users to provide custom metadata to append to the NodeMeta. Pipe those values through into the NodeMeta of the service and proxy registrations for both services and gateways.
- Unit tests and bats tests.
- 👀 
Does this need a changelog?
Checklist:
=> Add support for node meta field

charts/consul/values.yaml
This switches imageConsulDataplane to the released 1.0.0-beta4 image. This image is identical in functionality to the latest hashicorppreview image, so no other changes should be needed.
CI tests
Checklist:
=> Update to consul-dataplane:1.0.0-beta4

CHANGELOG.md, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/templates/api-gateway-gatewayclassconfig.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats, charts/consul/test/unit/api-gateway-gatewayclassconfig.bats, charts/consul/values.yaml
- Add a key to the Helm chart `externalServers.httpPort`.
- Set `CONSUL_HTTP_ADDR` to the first external server host when `externalServers` is enabled.
- Set `CONSUL_HTTP_ADDR` using Kube DNS when running with local servers.
- Change addresses to not have `http(s)://` and instead set this using the [`CONSUL_HTTP_SSL`](https://developer.hashicorp.com/consul/commands#consul_http_ssl) environment variable.
- Add environment variable to API Gateway controller deployment for `CONSUL_TLS_SERVER_NAME` to support SNI with external servers.
- Set the `consul.address` for the GatewayClassConfig whether using external or local servers.
- Set ports for the three protocols when running with external servers.
- Add the BATS tests for these changes. …
=> Update Helm Chart for running API Gateways in Agentless config and with external servers

control-plane/connect-inject/endpoints_controller_test.go, control-plane/connect-inject/peering_dialer_controller_test.go
- use "global" for proxydefaults name to fix tests not finding the proxydefaults
- disable https for peering establishment because the connection was failing due to the acceptor expecting it when using consul 1.13.3
We'll need to make sure unit tests pass here before merging.
=> fix unit tests with consul 1.13.3

control-plane/connect-inject/metrics/metrics_configuration.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
- Pass a default `/metrics` path to the consul-dataplane use the `-telemetry-prom-scrape-path` flag.
- Added a little test case that simulates setting a custom path as a flag.
- No CHANGELOG required as this was the default behaviour in the past.
- unit & acceptance tests
👀 
Checklist:
=> Fix: Set default path for prometheus scrape path to /metrics

CHANGELOG.md, control-plane/Dockerfile
- New UBI Image was released, 9.1: https://catalog.redhat.com/software/containers/ubi9-minimal/
- No need to bump alpine as latest branch is still 3.16.x
Checklist:
=> Dockerfile: bump up ubi-minimal image to 9.1

control-plane/connect-inject/controllers/endpoints/consul_client_health_checks.go, control-plane/connect-inject/controllers/endpoints/consul_client_health_checks_test.go
- Default to consul-dataplane being supported even when the version annotation is malformed. If the version annotation exists, it already means we're running consul-k8s 1.0.0+.
Eric ran into this when using an image built from our pipeline that builds images from main. It has a version formatted like "v1.0.0-dev (<GITSHA>)" which is not a recognized version by the client health checks code and causes endpoints controller to think that consul-dataplane is not supported and attempt to register client health checks which won't work. 
We would have run into this with our released image as well since they are built the same way as the images from main. We did NOT run into this in acceptance tests because the images built for acceptance tests are built differently …
=> default to dataplane being supported when checking version annotation

CHANGELOG.md, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats
For backwards compatibility with old helm charts where we only ever talk to the agent nodes which don't have gRPC APIs for Consul dataplane, we need to use our old login/logout flow and the static agent node address rather than leveraging the consul server connection manager. This PR coincides with the changes introduced in https://github.com/hashicorp/consul-api-gateway/pull/454.
Manually verified in explicitly agent-based and agentless installation modes and added unit tests.
Checklist:
=> Add opt-in server discovery for API Gateway Controller

charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/templates/api-gateway-gatewayclassconfig.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats, charts/consul/test/unit/api-gateway-gatewayclassconfig.bats, charts/consul/values.yaml
- Unify usage of httpsPort across the project to avoid confusion as `httpPort` is used solely for the API gateway and setting this value would lead to confusion amongst end users who would expect all consul-k8s components to use that value and they wouldn't.
- BATS
- 👀 
Checklist:
=> Replace httpPort with httpsPort to avoid confusion.

.circleci/config.yml, CHANGELOG.md, charts/consul/templates/webhook-cert-manager-podsecuritypolicy.yaml, charts/consul/test/unit/webhook-cert-manager-podsecuritypolicy.bats
- Update CI to test with Kubernetes-1.25 for acceptance tests.
- Adds a fix to the webhook-cert-manager PSP so that it is not deployed unless PSP are enabled + bats tests.
acceptance tests still pass: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/9531/workflows/75acb13f-c9ea-4838-8f38-a994da93f860/jobs/66796
👀 
Checklist:
=> update kind to kubernetes-1.25 and mark Kubernetes-1.25 supported

charts/consul/templates/_helpers.tpl, charts/consul/test/unit/client-daemonset.bats, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/test/unit/terminating-gateways-deployment.bats
- Setting CONSUL_TLS_SERVER_NAME when global.gloud.enabled is set.
-
- manually installed the cloud preset to test this works.
- unit tests
👀 
Checklist:
=> Setting CONSUL_TLS_SERVER_NAME when global.gloud.enabled is set.

.circleci/config.yml, control-plane/subcommand/server-acl-init/rules.go, control-plane/subcommand/server-acl-init/rules_test.go
- On a non-default partition, this rule errors with this log on server-acl-init
```
Failure: creating mesh-gateway-policy policy: err="Unexpected response code: 500 (rpc error making call: Invalid policy rules: partitioned policy cannot use partition_prefix rules)"
```
This only happens on a non-default partition when peering and partitions are both enabled, so I found this when testing non-default partitions with ACLs. So this adds a condition to the partition_prefix rule
manually, on non-default partitions, acceptance tests for other cases
Checklist:
=> fix acls when peering and partitions are both enabled

README.md, charts/consul/README.md
- Removing warning previously posted and update K8s versions 
- Add CLI install flow 
- Remove link to raw binaries since its not recommended to use raw binaries alone
- Re-order pre-requisites and update headings for Install flows
Checklist:
=> README: Update readme for 1.0 GA

.circleci/config.yml
=> make the acceptance test run for stable branches 0.49.x and 1.0.x

CHANGELOG.md, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats
This adds some logic that was forgotten around leveraging `externalServers.useSystemRoots`. Without it, attempting to use something like HCP as an external server without agents causes the gateway controller to fail validating the Consul server connection since it's using the wrong certificate authority.
Validated against HCP with the api-gateway changes in https://github.com/hashicorp/consul-api-gateway/pull/459
Checklist:
=> Add fix for api-gateway when using system-wide trusted CAs for external servers

acceptance/tests/vault/vault_test.go, charts/consul/templates/_helpers.tpl, charts/consul/templates/webhook-cert-manager-clusterrole.yaml, charts/consul/templates/webhook-cert-manager-clusterrolebinding.yaml, charts/consul/templates/webhook-cert-manager-configmap.yaml, charts/consul/templates/webhook-cert-manager-deployment.yaml, charts/consul/templates/webhook-cert-manager-podsecuritypolicy.yaml, charts/consul/templates/webhook-cert-manager-serviceaccount.yaml, charts/consul/test/unit/connect-inject-clusterrole.bats, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/test/unit/webhook-cert-manager-clusterrole.bats, charts/consul/test/unit/webhook-cert-manager-clusterrolebinding.bats, charts/consul/test/unit/webhook-cert-manager-configmap.bats, charts/consul/test/unit/webhook-cert-manager-deployment.bats, charts/consul/test/unit/webhook-cert-manager-podsecuritypolicy.bats, charts/consul/test/unit/webhook-cert-manager-serviceaccount.bats, charts/consul/values.yaml
The CRD controller deployment no longer exists as it was merged into connect-inject.
- Removes the webhook cert roles for the controller from the vault test
- updates values.yaml to not reference this field
👀 
👀 
Checklist:
=> remove controller webhook cert roles from vault test and the values.yaml

CHANGELOG.md, control-plane/Dockerfile
- Adds the go-discover binary to /bin
- unit & acceptance tests
- manually exec'd into the image I created to make sure that the `discover` binary was there and would run
👀 
Checklist:
=> add go-discover binary to control-plane image

CHANGELOG.md, acceptance/go.mod, acceptance/go.sum, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/cni/go.mod, control-plane/go.mod, control-plane/go.sum, control-plane/version/version.go
- The last PR went wonky on me during the rebase. This is much nicer.
- This branch is never in dev mode...
Checklist:
=> Prepare for 1.0.1 release

CHANGELOG.md, charts/consul/templates/cni-clusterrole.yaml, charts/consul/templates/cni-clusterrolebinding.yaml, charts/consul/templates/cni-daemonset.yaml, charts/consul/templates/cni-networkattachmentdefinition.yaml, charts/consul/templates/cni-podsecuritypolicy.yaml, charts/consul/templates/cni-resourcequota.yaml, charts/consul/templates/cni-securitycontextconstraints.yaml, charts/consul/templates/cni-serviceaccount.yaml, charts/consul/test/unit/cni-clusterrole.bats, charts/consul/test/unit/cni-clusterrolebinding.bats, charts/consul/test/unit/cni-daemonset.bats, charts/consul/test/unit/cni-networkattachmentdefinition.bats, charts/consul/test/unit/cni-podsecuritypolicy.bats, charts/consul/test/unit/cni-resourcequota.bats, charts/consul/test/unit/cni-securitycontextcontstraints.bats, charts/consul/test/unit/cni-serviceaccount.bats, charts/consul/values.yaml
Kubernetes 1.25 uses the PSA system which controls pod security standards at the namespace level.
The CNI plugin requires elevated permissions which would otherwise interfere with setting the rest of the consul-k8s resources compliant with `restricted` modes of the PSA.
By allowing the CNI plugin to be installed into another namespace, like `kube-system` or `consul-system` we can still run the rest of Consul in `restricted` mode while the CNI plugin runs in another elevated namespace.
This is a common workflow for other CNI plugins:
```
demo $ k get pods -A
NAMESPACE            NAME                                        READY   STATUS    RESTARTS      AGE
calico-apiserver     calico-apiserver-db5d9d654-hlf62            1/1     Running   0             19h
calico-apiserver …
```
=> Add support for setting the namespace that the CNI plugin is installed

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- 1.0.3 is the next release
- Sets things to dev mode
👀 
👀 
Checklist:
=> 1.0.3 dev mode

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- 0.49.3 is the next release
- set to dev mode
👀 
👀 
Checklist:
=> 0.49.3 dev mode

cli/cmd/install/install_test.go, cli/cmd/status/status_test.go, cli/cmd/upgrade/upgrade_test.go, cli/preset/demo.go, cli/preset/quickstart.go, cli/preset/secure.go
- Removed `controller: true` from the preset values file as the controller is now part of connectInject [1697](https://github.com/hashicorp/consul-k8s/pull/1697)
I built a binary and tried installing using the modified presets.
Checklist:
=> Remove controller from preset values file

.github/workflows/jira.yaml
- Downgrade to tomhjp/gh-action-jira-create@v0.1.3 to get past deserialization error 
Checklist:
=> JIRA sync: downgrade to tomhjp/gh-action-jira-create@v0.1.3

.github/workflows/jira.yaml
- Adding this in towards end of create JIRA action
```
env:
JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
-
```
Checklist:
=> JIRA: Use env when creating with custom fields

.github/workflows/jira.yaml
- Re-using previous structure from labels from hcdiag
Checklist:
=> JIRA: Re-use previous structure from labels 

.github/workflows/jira-issues.yaml, .github/workflows/jira-pr.yaml, .github/workflows/jira.yaml
- Add work stream
```
2022/12/13 23:27:56 API call POST /rest/api/2/issue failed (400): {"errorMessages":[],"errors":{"customfield_10535":"Consul WS is required."}}
```
Checklist:
=> JIRA: Add default work stream when syncing JIRA issues

.github/workflows/jira-pr.yaml
- Should be "GH Issue" instead of "Github Issue"
Checklist:
=> JIRA: fix for search issue

.github/workflows/jira-pr.yaml
- Adding "Service Mesh" value for Workstream custom field that is causing issue on PR sync.
Checklist:
=> JIRA: Add work stream to PR sync

charts/consul/values.yaml
- Missing changes from https://github.com/hashicorp/consul/pull/15452 that were not back ported to values.yaml also see https://github.com/hashicorp/consul/pull/15849
Checklist:
=> values.yaml - helm chart docs edits for 0.49.x

.circleci/config.yml, acceptance/tests/fixtures/bases/crds-oss/proxydefaults.yaml, acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml
- Upgrading from `1.14-dev` to `1.15-dev`.  `1.15-dev` is where the consul main builds target. `1.15-dev` is currently broken, so tagging it to a working 1.15 sha for the moment. Will need to update to `1.15-dev` eventually.
- Now that I'm using 1.15, I've added the 1.15 supported EnvoyExtensions and the previously missing balanceInboundConnections to the acceptance test fixtures
- Ran pipeline
👀
Checklist:
=> updated tests to use 1.15-dev

CHANGELOG.md, acceptance/tests/sync/sync_catalog_test.go, control-plane/catalog/to-consul/resource.go, control-plane/catalog/to-consul/resource_test.go, control-plane/go.sum
- When the type of the service is ClusterIP, a health check will be added to the catalog registration with the health info of the service based on the state of the readiness probe of the pod associated with the service.
- Replace `apiv1` with `corev1` to be consistent across the project.
- Run `go mod tidy`.
- Unit tests
- 👀 
Checklist:
=> Add health checks for services that are synced

CHANGELOG.md, acceptance/tests/sync/sync_catalog_test.go, control-plane/catalog/to-consul/resource.go, control-plane/catalog/to-consul/resource_test.go
* Add health checks for services that are synced
- When the type of the service is ClusterIP, a health check will be added to the catalog registration with the health info of the service based on the state of the readiness probe of the pod associated with the service.
- Replace `apiv1` with `corev1` to be consistent across the project.
- Run `go mod tidy`.
=> Add health checks for services that are synced (#1821)

control-plane/subcommand/inject-connect/command.go
- Minor fix in inject-connect/command.go: refactored a duplicate package import (sigs.k8s.io/controller-runtime/pkg/webhook package was imported twice).
Checklist:
=> Refactor Package Import in inject-connect/command.go

CHANGELOG.md, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go, control-plane/connect-inject/webhook/redirect_traffic.go, control-plane/connect-inject/webhook/redirect_traffic_test.go
- When a service is configured with the correct annotation, a readiness endpoint with be configured in Consul dataplane, and the readiness probe of the sidecar will be configured to use that endpoint to determine the health of the system. Additionally, when t-proxy is enabled, that port shall be in the ExcludeList for inbound connections.
- By deploying zookeeper with and without this annotation and noticing the absence of the lack of the following exception.
```
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
at …
```
=> When configured, use the health check of the proxy

CHANGELOG.md, control-plane/connect-inject/container_init.go, control-plane/connect-inject/container_init_test.go, control-plane/connect-inject/endpoints_controller.go, control-plane/connect-inject/endpoints_controller_test.go, control-plane/connect-inject/envoy_sidecar.go, control-plane/connect-inject/envoy_sidecar_test.go, control-plane/connect-inject/redirect_traffic.go, control-plane/connect-inject/redirect_traffic_test.go
This is a semantic backport of #1841 that supports "agentful" consul.
- When a service is configured with the correct annotation, a readiness endpoint with be configured in Consul dataplane, and the readiness probe of the sidecar will be configured to use that endpoint to determine the health of the system. Additionally, when t-proxy is enabled, that port shall be in the ExcludeList for inbound connections.
- Unit tests
- Zookeeper deployment to test with: https://gist.github.com/thisisnotashwin/e81939e62225e61c37ac5e2e3423a7c8
- Code Review
Checklist:
=> Use Proxy Healthchecks when configured.

.circleci/config.yml, CHANGELOG.md, README.md, charts/consul/README.md, charts/consul/test/terraform/aks/main.tf, charts/consul/test/terraform/eks/main.tf, charts/consul/test/terraform/gke/main.tf
- Bump the version of K8s on the pipelines
- https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/10356/workflows/21b91c9b-2fd4-4a6e-aeef-bc267bb62b3b for AKS and GKE
- https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/10362/workflows/0c656b2b-44aa-4d13-b346-77181663aec3 for EKS
- https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/10367/workflows/905bd862-0255-488b-bca0-f5d1688f884e latest kind
look at them pipelines and how pretty and green they are and then hit approve 😛
=> Bump Kubernetes versions to existing +2 for clouds

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- checked the backports to make sure they line up with the CHANGELOG entries and they do 👍
- Update version to 1.0.3 in go and and chart.
- Set the consul version to 1.14.4 (released Jan 27th)
- Set consul-dataplane version to 1.0.1 (release Jan 27th)
- Update CHANGELOG to tomorrows date as the release.
Note: no update to API Gateways envoy version in this one.
👀 
:eyes:
Checklist:
=> Pre-release 1.0.3

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- I checked the backports to make sure they line up with the CHANGELOG entries and they do 👍 
- Update version to 0.49.3 in go and and chart.
- Set the consul version to 1.13.6 (released Jan 27th)
- Update CHANGELOG to tomorrows date as the release.
- Note: no update to envoy version in this one.
:eyes:
:eyes:
Checklist:
=> Pre-release 0.49.3

CHANGELOG.md, charts/consul/values.yaml
OpenEBS is a Kubernetes storage solution. When you spin up a PVC, under the hood OpenEBS creates a pod to handle the necessary storage operations. If the openebs namespace is not excluded from injection, that pod can't start because our mutatingwebhook config requires all pod scheduling requests make it to our webhook and our webhook isn't running yet because the consul servers aren't running.
This is a breaking change but I think it's worth it because it's very unlikely anyone is using the openebs namespace for anything other than openebs.
Fixes https://github.com/hashicorp/consul-k8s/issues/1867
Checklist:
=> Exclude openebs namespace from injection.

CHANGELOG.md, charts/consul/values.yaml
* Exclude openebs namespace from injection.
OpenEBS is a Kubernetes storage solution. When you spin up a PVC, under the hood OpenEBS creates a pod to handle the necessary storage operations. If the openebs namespace is not excluded from injection, that pod can't start because our mutatingwebhook config requires all pod scheduling requests make it to our webhook and our webhook isn't running yet because the consul servers aren't running.
This is a breaking change but I think it's worth it because it's very unlikely anyone is using the openebs namespace for anything other than openebs.
* Changelog
-
-
Checklist:
> Entries …
=> Exclude openebs namespace from injection. (#1869)

CHANGELOG.md, charts/consul/templates/crd-servicedefaults.yaml, control-plane/api/v1alpha1/servicedefaults_types.go, control-plane/api/v1alpha1/servicedefaults_types_test.go, control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml, control-plane/go.mod, control-plane/go.sum, hack/copy-crds-to-chart/main.go
- Adds a new `Peer` field to serviceDefaults.upstreamConig.Overrides that disambiguates overrides for local vs. peered services. 
- Fixes CRD generation for peeringDialer and peeringAcceptor
Unit tests.
👁️ 👄 👁️ 
Checklist:
=> Add Peer to serviceDefaults

acceptance/framework/vault/helpers.go
The generate_lease=true configuration is unnecessary and generates a note about performance implications in Vault logs. Remove this configuration from the acceptance tests so that the default value of generate_lease=false is used instead.
A follow on PR will update the public Consul docs to reflect this change in recommendation.
- I'm relying on the existing k8s acceptance tests to ensure the integration still works
Checklist:
=> Refine server TLS Vault PKI role config in acceptance tests

CHANGELOG.md, control-plane/Dockerfile
- `gnupg` is likely an artifact from pre-CRT days when we used to validate Consul K8s releases ourselves for publishing with Docker. This is is likely not needed so will attempt removing it. 
Checklist:
=> Dockerfile: Remove gnupg from Consul k8s container

CHANGELOG.md, control-plane/Dockerfile
- Follow up to https://github.com/hashicorp/consul-k8s/pull/1882 to remove `gnupg` from dev Docker container image
- Fix Changelog typo
Checklist:
=> Dockerfile: remove `gnupg` from dev image

CONTRIBUTING.md
Recommend using `-v` as new folks probably want to see what is going on rather than 3 minutes of time passing and then getting a single line of output.
=> Minor fixes to docs for acceptance tests

.circleci/config.yml, acceptance/tests/fixtures/bases/crds-oss/proxydefaults.yaml, acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml
Undoes https://github.com/hashicorp/consul-k8s/pull/1831 to use the latest consul-ent 1.15 dev images for circli ci acceptance tests so that I can truly verify that NET-2343 is fixed.
Also:
- created a new variable for setting the consul test image used for the majority of tests
- fixed some incorrect spacing
If the pipeline passes we're good to go
👀
Checklist:
=> pinned consul test image to latest dev nightly

CHANGELOG.md, control-plane/subcommand/server-acl-init/connect_inject.go, control-plane/subcommand/server-acl-init/connect_inject_test.go
=> server-acl-init to always check for the deployed serviceAccountToken secret (#1770)

CHANGELOG.md, cli/cmd/proxy/loglevel/command.go, cli/common/envoy/http_test.go, cli/common/envoy/logger_params.go
- Allow users to reset log levels for envoy in a given pod to the envoy default of "info", (docs on default level: https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy#debugging-envoy) 
-
* Unit tests
* ran consul on k8's locally using kind https://gist.github.com/jm96441n/a56cd2ebd53f4484c3b40e725e305372
* create a cluster using kind: `kind create cluster`
* install consul on that cluster using the `consul-values.yml` file in the above gist: `consul-k8s install -config-file=consul-values.yaml -set global.image=hashicorp/consul:1.14.3`
* once that is up apply the `server.yaml` to your cluster `kubectl apply server.yaml`
* once that is setup get one of the server pod names using `kubectl get pods`
* in another …
=> DRAFT: Reset log levels per pod

.github/workflows/reusable-golangci-lint.yml
- updates golangci-lint-action to latest to support go 1.20+
👀
👀
Checklist:
=> updated golangci-lint-action to latest

CHANGELOG.md
- GH-1770 was in the changelog under release 1.0.2, moving to UNRELEASED. 
Checklist:
=> CHANGELOG: move GH-1770 to unreleased

.github/workflows/test.yml, charts/consul/templates/connect-inject-deployment.yaml, charts/consul/templates/sync-catalog-deployment.yaml
Currently we use an init container to create a consul ACL token via an auth method. We configure a preStop lifecycle hook to delete this token to avoid leaking it but this executes when containers get restarted, not just when the pod is destroyed.
This means that if a container livenessProbe fails and triggers a container to be restarted in place the token it was using will be destroyed but not recreated.
=> [0.49.x] remove livenessProbe from pods with preStop lifecycle hooks that delete ACL tokens

.github/workflows/test.yml
Update github actions to use local branches reusable tests. We previously would import the reusable test from the main branch which caused confusion.
These changes have already been made to the `release/0.49.x` branch 
see https://github.com/hashicorp/consul-k8s/pull/1914 
If the GHA CI runs then we are good to go
👀 
Checklist:
=> GitHub actions now uses branch local reusable tests

cli/cmd/troubleshoot/upstreams/upstreams.go
When using maps as input, the order is not guaranteed in go, and s our tests are flakey because we're asserting on specific order in the output. This changes the formatClusterNames function to sort the cluster names array first.
unit tests
👀 
Checklist:
- N/A Tests added
- N/A CHANGELOG entry added 
=> Fix flakey test in troubleshoot/upstreams_test.go

CHANGELOG.md, control-plane/Dockerfile
- Bump alpine base image to `alpine:3.17`
Checklist:
=> Dockerfile: bump Alpine base image to 3.17

cli/cmd/install/install.go, cli/cmd/install/install_test.go, cli/cmd/upgrade/upgrade.go
```
consul-k8s install -preset demo
'demo' is not a valid preset
```
=>
```
consul-k8s install -preset demo                                                                                                                                                                                                                                                                                                                      
'demo' is not a valid preset (valid presets: cloud, quickstart, secure)
```
- manually and with tests added
- :eyes:
Checklist:
=> Include allowed presets in err msg

charts/consul/values.yaml
It's no longer required since https://github.com/hashicorp/consul-helm/pull/1046
=> Update docs for global.tls.caKey

charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/test/unit/ingress-gateways-deployment.bats, charts/consul/test/unit/mesh-gateway-deployment.bats, charts/consul/test/unit/terminating-gateways-deployment.bats, control-plane/connect-inject/container_init.go, control-plane/connect-inject/container_init_test.go
- Enable the Envoy bootstrap config logging flag added in https://github.com/hashicorp/consul/pull/15988 when `global.logLevel` is `debug`.
Unit tests
CI/Unit tests
Checklist:
=> Enable envoy bootstrap config logging if global.logLevel == debug

CHANGELOG.md, charts/consul/values.yaml
- Bump Consul Dataplane to 1.1.0 to allow for longer timeline for a supported Consul dataplane proxy. 
Checklist:
=> consul-dataplane: bump consul-dataplane to 1.1.0 for consul k8s 1.0.x

.changelog/changelog.tmpl, .changelog/note.tmpl, .github/workflows/changelog-checker.yml, CONTRIBUTING.md, Makefile, control-plane/build-support/functions/10-util.sh
I always add details to my commits and there isn't any crossover, so reviewing commit by commit is usually the best way to review my PRs
This PR adds go-changelog support to the Consul-K8s repo. This will be a new way of managing changelog items throughout the release cycle.
* added `go-changelog` required templates and directories
* added pipeline checks for unintended missing changelogs
* added a label `pr/no-changelog` for ignoring missing changelogs if necessary otherwise a changelog is now required
* added contribution instructions for adding changelogs using the `go-changelog` tool
* modified `prepare-release` to automatically run `go-changelog` and add the changes to the `CHANGELOG.MD` file
1. Verified that pipeline fails when missing a changelog file
2. Temporarily commited a …
=> Added support for go-changelog automations

.changelog/changelog.tmpl, .changelog/note.tmpl, .github/workflows/changelog-checker.yml, CONTRIBUTING.md, Makefile, control-plane/build-support/functions/10-util.sh
- manual cherry pick since cherry pick failed
-
Checklist:
=> Cherry pick go changelog 1 0

.github/workflows/test.yml, Makefile, charts/consul/test/terraform/aks/variables.tf, charts/consul/test/terraform/eks/variables.tf, charts/consul/test/terraform/gke/variables.tf, charts/consul/test/terraform/openshift/variables.tf, control-plane/build-support/scripts/terraformfmtcheck.sh
- manual cherry pick
-
Checklist:
=> Cherry pick terraform checks

.changelog/changelog.tmpl, .changelog/note.tmpl, .github/workflows/changelog-checker.yml, CONTRIBUTING.md, Makefile, control-plane/build-support/functions/10-util.sh
- manual cherry pick since the backport failed
-
Checklist:
=> Cherry pick go changelog 0 49

.release/security-scan.hcl
- Updated the security scan to have parity with consul-dataplane: https://github.com/hashicorp/consul-dataplane/blob/main/.release/security-scan.hcl
👀 
👀 
Checklist:
=> updated security scan to have parity with consul-dataplane

control-plane/subcommand/tls-init/command_test.go
- There was an issue where adding 1 year to the time check would fail if it was March 1st because the certificate would be expired Feb 29th. Fixed test to use 365 day increment instead of 1 year increment.
👀 
👀 
Checklist:
=> add 365 days instead of 1 year to account for leap years

.release/security-scan.hcl
- Temporarily disable go mod security scanning until after the patch release
👀 
👀 
Checklist:
=> disable go mod scanning

.changelog/1770.txt, .changelog/1914.txt, .changelog/1934.txt, CHANGELOG.md
- removed unreleased section, we'll now be generating changelog entries as part of the release process
- added changelog files for next release
Checklist:
=> added changelog files

.changelog/1934.txt, .changelog/1953.txt, CHANGELOG.md
=> Fix changelog for 1.0.5

charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- get ready for 1.0.6 dev
Checklist:
=> ready for 1.0.6 dev

charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- get ready for 0.49.6 dev
-
Checklist:
=> ready for 0.49.6 dev

acceptance/framework/consul/cli_cluster.go, acceptance/framework/consul/helm_cluster.go, acceptance/framework/helpers/helpers.go, acceptance/framework/portforward/port_forward.go
- Added some additional retries to tests around port forwarding and calls to the kubernetes client
- Ran these with my manually triggered pipelines the other night, seemed to help reduce flakiness... but still flaky
👀 
Checklist:
=> added more retries for tests

.changelog/2013.txt, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats
This adds a fix for where we were injecting an server name env variable to the gateway controller in the case of trying to connect to client agent nodes when we had an external server with an SNI override.
What that results in is a TLS certificate verification error because the controller, when attempting to talk to the client node, then winds up expecting the client certificate to match the external server's name.
Unit tested.
Checklist:
=> Add SNI skip for client node configuration

.changelog/2013.txt, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats
This PR is a manual backport from #2013 to release/1.1.x since the backport bot failed to generate a backport PR for it.
---
This adds a fix for where we were injecting an server name env variable to the gateway controller in the case of trying to connect to client agent nodes when we had an external server with an SNI override.
What that results in is a TLS certificate verification error because the controller, when attempting to talk to the client node, then winds up expecting the client certificate to match the external server's name.
Unit tested.
Checklist:
---
<details>
- e23dbb65afe8226d756de4510016ac4a7a6f469f  - …
=> Backport of Add SNI skip for client node configuration into release/1.1.x

.changelog/2008.txt, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml
- Based on internal investigations allowing the connect-inject-init container to utilize more cpu will allow registration times to Consul to improve registration times from 3.5 seconds to 0.25 seconds. This PR removes the default cpu limits of 50 millicores to allow the the init container to temporarily eat up more CPU to speed up registration times during the init container lifecycle.
Tested manually on kind as shown below following the kind Consul k8s learn guide: https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-kind 
```
dyu@dyu-JRXHVGG467 kind-consulk8s % kind create cluster --name dc1
Creating cluster "dc1" ...
✓ Ensuring node image (kindest/node:v1.25.3) 🖼
✓ Preparing nodes 📦
✓ Writing configuration 📜
✓ …
```
=> values.yaml - set default connect inject init cpu resource limits to `null` to increase service registration times

.changelog/2008.txt, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml
- Backport of #2008 to 1.0.x
-
Checklist:
=> values.yaml - set default connect inject init cpu resource limits to null, backport to 1.0.x

.changelog/2008.txt, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml
- Backport of #2008 to 1.1.x
-
Checklist:
=> values.yaml - set default connect inject init cpu resource limits to null, backport to 1.1.x

charts/consul/values.yaml
Clients are not required for ingress/terminating gateways.
=> Remove client.enabled requirement in docs

hack/helm-reference-gen/main.go
Website has linting that errors when links have the developer.hashicorp.com prefix.
=> Remove website prefix from generated docs

.changelog/2029.txt, charts/consul/templates/api-gateway-controller-clusterrole.yaml, control-plane/subcommand/server-acl-init/rules.go, control-plane/subcommand/server-acl-init/rules_test.go
- Resolve bug described in https://github.com/hashicorp/consul-k8s/issues/1911 where api-gateway controller is unable to create new namespaces
- Installed API gateway using a local version of this repository using the reproduction steps described in https://github.com/hashicorp/consul-k8s/issues/1911 and consul API image set to 1.5.2. (ACL permission is missing, but this change is also reliant on a bux fix with how partitions are handled in 1.5.2)
- CI passes
Checklist:
- [ X ] CHANGELOG entry added 
=> Update ACLs, add namespace.write permission

charts/consul/values.yaml
- Fixes the docs example where `copyAnnotations.service.annotation` has the wrong indentation. This caused some confusion for a customer recently. Just needs an extra two spaces.
=> Fix the indentation of the copyAnnotations example

.github/workflows/backport.yml
- Add -gh-automerge to backport assistant so that it will automerge GH style
Compared it against what Consul has.
👀 
Checklist:
=> Update backport assistant to support -gh-automerge

.github/workflows/nightly-cleanup.yml
- Adding a nightly cleanup job that will dispatch to consul-k8s-workflows every night
- This is the same schedule that CircleCI had
👀 
👀 
Checklist:
=> Add a cleanup cron job

CONTRIBUTING.md, Makefile, charts/consul/.helmignore, charts/consul/crds/gatewayclasses.gateway.networking.k8s.io.yaml, charts/consul/crds/gateways.gateway.networking.k8s.io.yaml, charts/consul/crds/grpcroutes.gateway.networking.k8s.io.yaml, charts/consul/crds/httproutes.gateway.networking.k8s.io.yaml, charts/consul/crds/kustomization.yaml, charts/consul/crds/referencegrants.gateway.networking.k8s.io.yaml, charts/consul/crds/tcproutes.gateway.networking.k8s.io.yaml, charts/consul/crds/tlsroutes.gateway.networking.k8s.io.yaml, charts/consul/crds/udproutes.gateway.networking.k8s.io.yaml
For the Gateway API implementation to work, the target Kubernetes cluster must have the relevant CRDs installed. These CRDs are managed by the SIG Network group. We'll want to generate copies of these CRDs and store them in the `/crds` directory in our Helm chart so they can be installed for our users automatically.
This PR adds a `kustomization.yaml` file for managing external dependencies and a `generate-external-crds` command which will load in the dependencies and nicely format them in our `/crds` directory.
This will make it easy for us to keep the CRDs up to date and allows for extensibility if we ever need to add another set of external CRDs to the project in the future.
- Add `generate-external-crds`
- I ran the hack and it …
=> Add Hack for Generating CRDs from external sources

.github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/jira-issues.yaml, .github/workflows/merge.yml, .github/workflows/nightly-acceptance.yml, .github/workflows/nightly-cleanup.yml, .github/workflows/pr.yml, .github/workflows/weekly-acceptance-0-49-x.yml, .github/workflows/weekly-acceptance-1-0-x.yml, .github/workflows/weekly-acceptance-1-1-x.yml
- As part of security best practices, we lock down what versions of Github Actions we use.
- This updates our actions to use approved versions.
:octocat: 
👀 
Checklist:
=> Supply chain updates for Github Actions

charts/consul/templates/sync-catalog-deployment.yaml, charts/consul/test/unit/sync-catalog-deployment.bats
- Change the environment variable name for the ACL token secret to match what is expected by the control plane. (Fixes #1891)
- Currently, the chart is setting the `CONSUL_HTTP_TOKEN` environment variable which is not used by the Consul client within the control plane.
- The control plane is instead reading `CONSUL_ACL_TOKEN`: https://github.com/hashicorp/consul-k8s/blob/11f842cbe94b5df544c03e2441a1820397f92b9b/control-plane/subcommand/flags/consul.go#L153-L155 
- Deployed the chart with the included changes and observed the control plane properly loaded the provided Consul token and used it to register services. 
- Deploy an external Consul server that has ACLs enabled.
- Create a policy and …
=> Fix Sync Catalog ACL Token Environment Var Name

.changelog/2083.txt, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats
Consider whether Vault is being used as a secrets backend when determining whether to mount a TLS cert into the API gateway controller deployment.
Largely, this change is based off of how other deployments already handle Vault as a secrets backend. For example:
https://github.com/hashicorp/consul-k8s/blob/112ad18e12683559413c058d8e52f28d66597b07/charts/consul/templates/connect-inject-deployment.yaml#L293-L297
The only unique aspect here is that the api-gateway-controller communicates directly with agents when `client.enabled=true`, so we require some additional gating to make sure that we're using the correct cert in this case.
Install Consul w/ API gateway enabled in configurations both with and without Vault used as a secrets …
=> Adjust API gateway controller deployment appropriately when Vault configured as secrets backend

.changelog/2093.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/server-clusterrole.yaml, charts/consul/templates/server-clusterrolebinding.yaml, charts/consul/templates/server-statefulset.yaml, control-plane/commands.go, control-plane/subcommand/fetch-server-region/command.go, control-plane/subcommand/fetch-server-region/command_test.go
- Set Consul server locality From its topology region label.
- Unit tests
I have 4 K8s clusters that I'm using to test sameness and locality aware failover. I'll be automating this setup into an acceptance test over the next few weeks. Here are the steps I took:
1. I added labels to the nodes for each K8s cluster with:
* `kubectl --context k3d-c1 label node k3d-c1-server-0 topology.kubernetes.io/region="us-east-1"`
* `kubectl --context k3d-c3 label node k3d-c3-server-0 topology.kubernetes.io/region="us-east-2"`
* `kubectl --context k3d-c4 label node k3d-c4-server-0 topology.kubernetes.io/region="us-west-2"`
2. I then peered the partition in `k3d-c1` to the the clusters in `k3d-c3` and `k3d-c4`
3. Run `curl -k …
=> Set Consul Server Locality From Node Label

charts/consul/templates/crd-exportedservices.yaml, charts/consul/templates/crd-serviceintentions.yaml, control-plane/api/v1alpha1/serviceintentions_types.go, control-plane/api/v1alpha1/serviceintentions_types_test.go, control-plane/api/v1alpha1/shared_types.go, control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml, control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml, control-plane/go.sum
- added samenessgroup to source intention
- updated source intention validation 
- updated tests on validation 
How I tested it:
Followed instructions on testing a new CRD: tested docker image and added an intention with samenessgroup. 
Checklist:
- NA CHANGELOG entry added 
=> add sameness group to source intention

.github/workflows/changelog-checker.yml
- Fix the changelog checker action for when the base branch is not `main`. In this case the regex gets split because of the lack of quotes, causing an error. Also, the diff should be performed against the desired base branch in this case.
* This one is failing: https://github.com/hashicorp/consul-k8s/actions/runs/4887457091
* This one is passing with the changes: https://github.com/hashicorp/consul-k8s/actions/runs/4887398414
Checklist:
=> chore(ci): fix changelog action for non-main base branches

.github/workflows/backport.yml
- Backport-assistant is erroring out because it tries to check out a branch immediately after it creates it. [Example](https://github.com/hashicorp/consul-k8s/actions/runs/4916113298). This is fixed in 0.3.3.
I will manually backport to the other branches considering the nature of the changes.
=> chore(ci): fix backport assistant not finding new branches

charts/consul/templates/connect-inject-clusterrole.yaml, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/controllers/gateway_controller_test.go, control-plane/api-gateway/controllers/index.go, control-plane/subcommand/inject-connect/command.go
- Adds a stub-out of the Gateway Controller
With the steps below. Basically wanted to make sure the permissions and schemes were there for the controller to be able to react to changes on the object types.
```
kind create cluster
make control-plane-dev-docker
docker tag consul-k8s-control-plane-dev consul-k8s-control-plane-dev:local
kind load docker-image consul-k8s-control-plane-dev:local
kubectl create namespace consul
helm install consul ./charts/consul -n consul --set global.imageK8S=consul-k8s-control-plane-dev:local
```
Then watch the logs for the connect-inject pod when you apply the following resource types, there shouldn't be any errors about access/nonexistent types.
`kubectl apply -f …
=> Net 3508/gateway controller

.changelog/2078.txt, cli/cmd/config/command.go, cli/cmd/config/read/command.go, cli/cmd/config/read/command_test.go, cli/commands.go
-
For CCM Linking existing clusters we were trying to find a good way of retrieving the helm config from consul-k8s, but there was none. Following @lkysow 's suggestion, this PR adds `consul-k8s config read` command that returns helm configuration.
Checklist:
=> add config read command

.changelog/2100.txt, charts/consul/templates/crd-meshes.yaml, charts/consul/templates/crd-proxydefaults.yaml, charts/consul/templates/crd-servicedefaults.yaml, control-plane/api/v1alpha1/mesh_types.go, control-plane/api/v1alpha1/mesh_types_test.go, control-plane/api/v1alpha1/proxydefaults_types.go, control-plane/api/v1alpha1/proxydefaults_types_test.go, control-plane/api/v1alpha1/servicedefaults_types.go, control-plane/api/v1alpha1/servicedefaults_types_test.go, control-plane/api/v1alpha1/shared_types.go, control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml, control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml, control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
* Add the `mutualTLSMode` field to the ProxyDefaults and ServiceDefaults CRDs
* Add the `allowEnablingPermissiveMutualTLS` field to the Mesh CRD
* Unit tests
* Local manual testing (see below)
👀 
Checklist:
---
Manual testing
* Setup Kind with a [local docker registry](https://kind.sigs.k8s.io/docs/user/local-registry/)
* Build dev consul and consul-k8s-control-plane images, and push images to the local registry
<details>
<summary>build-images.sh</summary>
```shell
#!/usr/bin/env bash
set -ex
(
cd ~/code/consul-k8s/
GOPATH=$(go env GOPATH) make cli-dev …
```
=> Update CRDs for Permissive mTLS

control-plane/api-gateway/controllers/gateway_class_config_controller_test.go, control-plane/api-gateway/controllers/gateway_controller_test.go, control-plane/api-gateway/controllers/gatewayclass_controller_test.go
- Use the Logr test "constructor" that is _not_ deprecated
=> Use the non-deprecated logr test

.github/workflows/changelog-checker.yml
Fixes a typo that causes the changelog checker action to fail. @curtbushko I know you have a fix for this in one of your PRs, but I thought I would PR this separately since it needs to be backported.
=> chore(ci): fix typo in changelog checker

.changelog/2078.txt, cli/cmd/config/command.go, cli/cmd/config/read/command.go, cli/cmd/config/read/command_test.go, cli/commands.go
This is a manual backport of 2078, because the automatic PR #2120 did not succeed.
Checklist:
=> Manual backport of #2078

control-plane/api-gateway/controllers/reference_validator.go, control-plane/api-gateway/controllers/reference_validator_test.go
- Adds a validator for reference grants. The following scenarios are included
- Gateway can reference a secret
- HTTPRoute can reference a Gateway
- HTTPRoute can reference a Backend (Services)  
- TCPRoute can reference a Gateway
- TCPRoute can reference a Backend (Services)  
Tests
Tests
Checklist:
=> Net 3490/reference grants

.changelog/2098.txt, .github/workflows/changelog-checker.yml, charts/consul/templates/sync-catalog-clusterrole.yaml, charts/consul/templates/sync-catalog-deployment.yaml, charts/consul/test/unit/sync-catalog-deployment.bats, charts/consul/values.yaml, control-plane/catalog/to-consul/resource.go, control-plane/catalog/to-consul/resource_test.go, control-plane/subcommand/sync-catalog/command.go
- Add support for Kubernetes Ingress resources where the hostname or the LoadBalancer IP of the ingress LB are synced as the address of the services that the ingress is in front of. Flags are used to determine whether to sync the hostname or the loadbalancer IP. The only supported path is `/` since Consul does not currently support path-based routing only valid DNS entries are supported as service addresses.
- The hostname of a service is compared against the list of hosts in the TLS section of the Ingress resource to determine if TLS is enabled/disabled. The 443 port is registered as the service port if TLS is enabled, otherwise it is port 80.
Usage:
```yaml
syncCatalog:
ingress:
syncIngress: true         # Enables syncing the hostname from the Ingress …
```
=> Add support for syncing Ingress hostname to the Consul Catalog

.changelog/2140.txt, charts/consul/Chart.yaml, charts/consul/values.yaml
- Staging updates for the 1.0.7 release this week.
- consul-dataplane 1.0.2 was released with security fixes
- consul 1.14.7 is currently in the release pipeline
How I've tested this PR: CI
How I expect reviewers to test this PR: 👁️ 👁️ 👁️ 
Checklist:
=> feat: update dataplane and consul images for 1.0.7 release

Makefile, control-plane/build-support/scripts/consul-version.sh
- The release branches are running the wrong version of consul in the tests.
-  This let's us run `make consul-version` to pull the consul version out of the values.yaml file so that we can use the correct consul version on the release branches.
- I will do a change on the github actions side once this is merged and backported
- Ran the make target locally (yq is installed on the runners so it should succeed there too)
👀 
Checklist:
=> GHA: Get the consul version from values.yaml

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- Prepare for 0.49.6
Checklist:
=> Prep release 0.49.6

CHANGELOG.md, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- Prepare for 1.0.7
Checklist:
=> Prep release 1.0.7

control-plane/api-gateway/gatekeeper/role.go
- Adds a little stub where the OpenShift role info will go. Just wanted to get it merged in before we come back to it.
=> Stub out where the openshift role info will go

.changelog/2170.txt, charts/consul/templates/server-config-configmap.yaml, charts/consul/test/unit/server-config-configmap.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/values.yaml
- add helm chart values for:
- 
- add templating and bats tests to ensure that the the server-config-configmap.yml adds the configuration
- unit tests
- CI
👀 
Checklist:
=> add helm chart values to configure global server side rate limiting

control-plane/api-gateway/controllers/gateway_controller.go, control-plane/cache/consul.go, control-plane/cache/consul_test.go
- Add config entry deletion/upsert for changed consul resources
-
- Run tests
- Ran https://github.com/jm96441n/consul-experiments/blob/main/k8s/apigw4conk8s/deploy.sh and then modified and deleted the http route and checked that changes showed up in consul
Read code
Potentially run locally
Checklist:
=> Net 4124/handle syncing consul lifecycle events

charts/consul/templates/connect-inject-clusterrole.yaml, control-plane/api-gateway/binding/binder.go, control-plane/api-gateway/binding/binder_test.go, control-plane/api-gateway/binding/snapshot.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/controllers/gateway_controller_test.go, control-plane/api-gateway/gatekeeper/deployment.go, control-plane/api-gateway/gatekeeper/gatekeeper.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/role.go, control-plane/api-gateway/gatekeeper/service.go, control-plane/api-gateway/gatekeeper/serviceaccount.go
Hooks up gatekeeper with new snapshot.
Manual testing, added tests.
```
make control-plane-dev-docker
docker tag consul-k8s-control-plane-dev consul-k8s-control-plane-dev:local
kind load docker-image consul-k8s-control-plane-dev:local
kubectl create namespace consul
helm install consul ./charts/consul -n consul --set global.image=hashicorppreview/consul:1.16-dev --set global.imageK8S=consul-k8s-control-plane-dev:local
```
Make a gateway
Checklist:
=> Net 4125/hookup gatekeeper with snapshot

.changelog/2176.txt, acceptance/tests/connect/connect_inject_test.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go, control-plane/connect-inject/webhook/container_init.go, control-plane/connect-inject/webhook/container_init_test.go, control-plane/connect-inject/webhook/mesh_webhook.go, control-plane/connect-inject/webhook/mesh_webhook_test.go, control-plane/connect-inject/webhook/redirect_traffic.go
- DNS redirection and the various settings that make that possible (like
the dataplane binding to a port for DNS) is only useful if tproxy is
enabled. Most of the code checked if tproxy was enabled but there
was one location where we didn't check. This resulted in a bug
with our multiport support where even though tproxy is disabled,
we tried to setup the dataplane to proxy DNS. This meant each dataplane
tried to bind to 8600 but because there are >1 dataplanes with
multiport, there was a port conflict.
This PR fixes the location where we didn't check if tproxy was enabled
and as a result fixes the multiport issue.
- the reason this wasn't caught in our acceptance tests is because we don't run the multiport test when global tproxy is enabled and this bug only …
=> Disable DNS redirection when tproxy is disabled

charts/consul/Chart.yaml, charts/consul/values.yaml
- Splitting this from [#2180](https://github.com/hashicorp/consul-k8s/pull/2180) so that it is easier to backport.
- running tests in other PRs
:eyes:
Checklist:
=> Update consul image so that acceptance tests run

.github/workflows/pr.yml, Makefile, charts/consul/Chart.yaml, charts/consul/values.yaml, control-plane/build-support/functions/10-util.sh, control-plane/build-support/scripts/consul-version.sh
My apologies on the formatting. I think I might be the only person that uses the bash language server and it 'fixed' everything. See my comments in the 10-utils.sh script for the important changes.
The purpose of this PR is to fix a long standing bug (pre-GHA) so that the correct consul image is set on every release branch. Our automation will use the correct version that matches the consul release that a release branch is paired with. The consul already repo correctly creates `-dev` images when a PR is merged on a release branch.
- Update the consul-version.sh script and make target to get the full image version from the helm chart. This will be used in consul-k8s-workflows to be passed aroudn the tests.
- I will need to put up a consul-k8s-workflows PR …
=> Update consul image on prepare-dev and prepare-release

.changelog/2205.txt, charts/consul/values.yaml, cli/preset/cloud_preset.go, cli/preset/cloud_preset_test.go
- adds `telemetryCollector` values to cloud preset
- local dry run testing validating the expected helm values
- updated unit tests to expect updated helm values
Checklist:
=> update cloud preset to enable telemetry collector

.changelog/2194.txt, control-plane/api/v1alpha1/serviceintentions_types.go, control-plane/api/v1alpha1/serviceintentions_types_test.go
- Include partition and namespace in intention source equality checks
- Include namespace in intention destination equality checks.
This code was originally added [here](https://github.com/hashicorp/consul-k8s/pull/1804) to avoid modifying all intentions when upgrading from Consul pre-1.12 to 1.12+. Consul-K8s 1.0.x is compatible with Consul 1.14.x and Consul-K8s 1.1.x is compatible with Consul 1.15.x, so users should be past 1.12 when upgrading to either of the backported versions ([compatibility matrix](https://developer.hashicorp.com/consul/docs/k8s/compatibility#supported-consul-and-kubernetes-versions)).
- Unit tests
- Manual tests in the sameness group demo environment.
Checklist:
=> Fix bug on service intention CRDs causing missed updates

.changelog/2213.txt, charts/consul/templates/crd-serviceintentions.yaml, control-plane/api/v1alpha1/serviceintentions_types.go, control-plane/api/v1alpha1/serviceintentions_types_test.go, control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
* This updates the ServiceIntentions CRD with the new fields for JWT auth.
* Unit tests
Checklist:
=> Update ServiceIntentions CRD for JWT auth

charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/test/unit/telemetry-collector-deployment.bats
Either the docker container or the execution method for the telemetry-collector is making the args not get included on the process. Switch to putting it directly in the command so we can ensure this works as expected
- Set the telemetry-collector args in the command field instead of the args field
- Change the unit test
[x] - manually
[x] - bats
Checklist:
=> Fix setting args for the telemetry-collector

charts/consul/test/unit/connect-inject-deployment.bats, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
- Check for nil on proxy config. It appears in Mesh Gateways , Terminating Gateways and Ingress Gateways if we do not enable metrics then we will not have a service proxy enabled
- unit tested
Checklist:
- [] CHANGELOG entry added 
=> Fix telemetry collector issue and fix for bat test

control-plane/subcommand/create-federation-secret/command_test.go
improving tests by removing waits and adding retries. I encountered these tests as the flakiest ones but I can update more tests if needed. 
Checklist:
=> improve code readability and fix flaky tests re acl token generation

control-plane/subcommand/get-consul-client-ca/command_test.go
- reduce flakiness of unit test with more retries with larger backoff.
Unit test improvement
Checklist:
=> Increase timeout and backoff for retry on flaky test

charts/demo/crds/blank, charts/demo/templates/intentions.yaml, charts/embed_chart.go
- this adds a fake `demo/crds` directory for embedding so the install doesn't error out
```
==> Installing Consul demo application
✓ Downloaded charts.
--> creating 1 resource(s)
--> creating 32 resource(s)
--> beginning wait for 32 resources with timeout of 10m0s
✓ Consul demo application installed in namespace "consul".
==> Accessing Consul Demo Application UI
kubectl port-forward service/nginx 8080:80 --namespace consul
Browse to http://localhost:8080.
```
Checklist:
=> Add fake demo/crds to get around that expectation in chart install

acceptance/tests/api-gateway/api_gateway_test.go, acceptance/tests/fixtures/bases/api-gateway/apigateway.yaml, control-plane/api-gateway/gatekeeper/dataplane.go
Previously we weren't able to bind API gateways to privileged ports due to running as non-root users without proper linux capabilities in the context of the running container.
I attempted to just set the `NET_BIND_SERVICE` capability directly on the container while running as non-root, unfortunately this isn't supported due to how Docker passes off the ambient capability set to the underlying container when you're running non-root. So, the only real option is explicitly running as root and then dropping all privileges other than what we need, which is `NET_BIND_SERVICE`.
The only other alternative if we want to keep this to non-root users is for someone to configure every single one of their Kubernetes nodes (as in the host machines) with the unprivileged port …
=> Allow API Gateways to bind to privileged ports

acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
To reduce the likelihood of flakes.
- Extend `retryCheck` timeouts in the API Gateway lifecycle acceptance test from 10s to 30s.
Checklist:
=> acceptance: extend api gateway lifecycle test retryCheck timeouts

charts/consul/templates/connect-inject-clusterrole.yaml, control-plane/api-gateway/gatekeeper/deployment.go, control-plane/api-gateway/gatekeeper/gatekeeper.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/role.go, control-plane/api-gateway/gatekeeper/rolebinding.go, control-plane/api-gateway/gatekeeper/service.go, control-plane/api-gateway/gatekeeper/serviceaccount.go
We create a `Role` and `ServiceAccount` for the api-gateway `Deployment` in certain scenarios; however, we do not create a `RoleBinding` to bind them together.
This is causing issues when deploying to OpenShift where the `ServiceAccount` needs a `SecurityContextConstraints` resource attached, and that chain needs to go:
SecurityContextConstraints => Role => RoleBinding => ServiceAccount
Deploy into K8s with system-managed ACLs enabled and verify that the `RoleBinding` is now created alongside the `Role`, `ServiceAccount`, etc.
See above
Checklist:
=> api-gateway: create RoleBinding attaching Role to ServiceAccount

.changelog/2262.txt, charts/demo/templates/intentions.yaml
- This allowlists all traffic to consul-telemetry-collector for with using `consul-k8s -demo`
- Used this off main in yesterday's testing: https://github.com/hashicorp/consul-k8s/pull/2245
```
export HCP_API_HOST=https://api.hcp.dev
export HCP_AUTH_URL=https://auth.idp.hcp.dev
export HCP_SCADA_ADDRESS=scada.internal.hcp.dev:7224
HCP_CLIENT_ID=x HCP_CLIENT_SECRET=y consul-k8s install -preset cloud -hcp-resource-id $RESOURCE_ID -demo \
--set="global.enterpriseLicense.secretName=consul-license" \
--set="global.enterpriseLicense.secretKey=key" \
--set="global.image=hashicorp/consul:1.15.3" \
--set="server.replicas=3" \
--set="peering.enabled=true" \
--set="meshGateway.enabled=true" \ …
```
=> Add allow all intention for consul-telemetry-collector for -demo

acceptance/tests/api-gateway/api_gateway_tenancy_test.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/controllers/gateway_controller_test.go
The original lifecycle test looks like it was flaky (and rarely passes) due to a bug with fetching the proper gateways to reconcile when a referenced secret is updated. This fixes the indexing error that was causing that, so the Lifecycle tests should pass regularly now.
Checklist:
=> Fix Gateway trigger for when secret is modified

.changelog/2266.txt, acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml, charts/consul/templates/crd-servicedefaults.yaml, control-plane/api/v1alpha1/servicedefaults_types.go, control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
- Fix casing of the field `EnforcingConsecutive5xx` from snake case to camel case and fix the acceptance test fixtures as well.
- Acceptance tests.
- Acceptance tests.
Checklist:
=> Update casing of json tag for ServiceDefault field

charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- Set the release/1.1.x branch back to dev mode
-
Checklist:
=> Set release 1.1.x to dev mode for 1.1.3

CHANGELOG.md
- We were missing several entries in the main CHANGELOG
-
Checklist:
=> Add missing entries to main CHANGELOG

.changelog/2195.txt
- Found during the release 1.1.2
- go-changelog didn't categorize this one
Checklist:
=> Fixing changelog for 2195

.changelog/2284.txt, control-plane/Dockerfile
- Our security scanners reported:
>  » Dependency Scanner
⚠︎ found reported vulnerability CVE-2023-2650 from Alpine Linux's Security Issue Tracker in openssl@3.0.8-r4
/lib/apk/db/installed:0:0
- Upgrading to alpine:3:18 fixes the issue.
Built the release-default image and scanned it:
Before:
> Scanned docker:{owner:"curtbushko"  name:"consul-k8s-control-plane-dev"}  tag:"scan" in 46.7s - found 1 result(s)
» Dependency Scanner
⚠︎ found reported vulnerability CVE-2023-2650 from Alpine Linux's Security Issue Tracker in openssl@3.0.8-r4
/lib/apk/db/installed:0:0
After:
> ✓ Scanned docker:{owner:"curtbushko"  name:"consul-k8s-control-plane-dev"}  tag:"scan" in 45s - no results found
Checklist:
> …
=> Update alpine to 3.18 to fix CVE-2023-2650

acceptance/tests/fixtures/bases/api-gateway/kustomization.yaml, acceptance/tests/fixtures/bases/api-gateway/meshservice.yaml, acceptance/tests/fixtures/cases/api-gateways/mesh/kustomization.yaml, acceptance/tests/fixtures/cases/api-gateways/mesh/proxydefaults.yaml, acceptance/tests/fixtures/cases/api-gateways/resolver/kustomization.yaml, acceptance/tests/fixtures/cases/api-gateways/resolver/serviceresolver.yaml, acceptance/tests/partitions/partitions_gateway_test.go, control-plane/api-gateway/cache/consul.go, control-plane/api-gateway/common/labels.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/api-gateway/gatekeeper/init.go, control-plane/subcommand/inject-connect/command.go
This adds a test where a gateway targets a service in a separate partition using a combination of a MeshService CRD, a ServiceResolver, and an ExportedServices entry. It depends on https://github.com/hashicorp/consul/pull/17581 landing, as we had a bug in our core partition handling.
Additionally, I had to revamp the way that authentication was getting handled in deployed services with ACLs enabled.
Acceptance test passes.
Checklist:
=> [API Gateway] Add partition test

.changelog/2249.txt, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/values.yaml
We're [subscribing to a lot of resources](https://github.com/hashicorp/consul-k8s/blob/46055a324f8b1fcfb6e6debf95f5d059d7b50fe4/control-plane/api-gateway/controllers/gateway_controller.go#L341-L397) for API Gateways because of the complexity of what can trigger reconciliation due to the nature of distributed references within the spec. Running the controller on OpenShift got the controller OOM killed almost immediately. This gives the pod generally more headroom.
Marking as a draft for now to make sure that we verify that this is plenty of space for the controller.
Checklist:
=> Update memory defaults for connect inject controller

.changelog/2194.txt
- I found this during release/1.1.2
- go-changelog doesn't work correctly if the changelog is missing a category.
Checklist:
=> Fix changelog for 2194

.github/workflows/build.yml, Makefile, cli/version/fips_build.go, cli/version/non_fips_build.go, cli/version/version.go, control-plane/Dockerfile, control-plane/build-support/functions/20-build.sh, control-plane/build-support/scripts/build-local.sh, control-plane/consul/consul.go, control-plane/subcommand/connect-init/command.go, control-plane/version/fips_build.go, control-plane/version/non_fips_build.go, control-plane/version/version.go
These are CI and build tooling changes (no feature changes) to support FIPS builds of consul-k8s in our pipeline.
https://github.com/hashicorp/consul-k8s/actions/runs/5192486001 and manually
https://github.com/hashicorp/consul-k8s/actions/runs/5192486001 and manually if you like
Checklist:
=> Add FIPS builds

.changelog/2304.txt, README.md, charts/consul/test/terraform/aks/main.tf, charts/consul/test/terraform/gke/main.tf
- I used this branch to test 1.27 support in the workflow, the acceptance tests passing demonstrates that that works correctly
- I also updated the cloud tests to cover 1.24, 1.25 and 1.26. EKS seems to not support setting a patch version for kubernetes? In the past we haven't set it, so I've left it set to `1.26`. GKE and AKS, I have pinned to a patch number in order to help with repro-ability.
- I temporarily enabled cloud tests on this PR, here are the results (they didn't all pass, but I just wanted to verify that they setup with no issues with the version changes): https://github.com/hashicorp/consul-k8s-workflows/actions/runs/5216611633/jobs/9415586427
👀 
Checklist:
> HashiCorp engineers …
=> Mw/net 3598 update kind for consul k8s acceptance tests with latest version of kind and k8s 1.27

acceptance/tests/fixtures/cases/api-gateways/dc1-to-dc2-resolver/kustomization.yaml, acceptance/tests/fixtures/cases/api-gateways/dc1-to-dc2-resolver/serviceresolver.yaml, acceptance/tests/fixtures/cases/api-gateways/dc2-to-dc1-resolver/kustomization.yaml, acceptance/tests/fixtures/cases/api-gateways/dc2-to-dc1-resolver/serviceresolver.yaml, acceptance/tests/wan-federation/wan_federation_gateway_test.go, control-plane/api-gateway/cache/consul.go, control-plane/api-gateway/cache/consul_test.go, control-plane/api-gateway/common/helm_config.go, control-plane/api-gateway/common/translation.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api/v1alpha1/serviceresolver_types.go, control-plane/connect-inject/constants/constants.go, control-plane/subcommand/inject-connect/command.go
This adds a WAN federation acceptance test for API Gateways. A few fixes went into it:
1. We were disallowing ServiceResolver cross-DC redirects unless someone was explicitly in the default partition, but were only checking for "default" when an empty string means the same thing
2. We needed to normalize the auth method name that we use for our deployments so that we use the DC-local one that we attach our binding rules to.
3. Due to the way we watch and GC config entries, we needed to pass some additional metadata to ignore anything coming from a sync to a federated DC -- basically we were removing config entries if we didn't have the corresponding Kubernetes object backing them in our DC, when we shouldn't touch them because a corresponding Kubernetes object …
=> [API Gateway] WAN Federation test and fixes

control-plane/api-gateway/cache/gateway.go, control-plane/api-gateway/controllers/gateway_controller.go
This bypasses the cache on gateway deletion to make sure we have dropped any registered services in Consul even if we haven't been informed about them via the cache yet. We had a race condition where if a pod was just registered with Consul we might not know about it if the gateway was deleted right away. I noticed this scenario when running conformance tests when we were leaving around services that were no longer there.
Ran conformance tests and made sure that quickly deleted gateways are cleaned up in Consul
Checklist:
=> [API Gateway] fix dangling service registrations

control-plane/api-gateway/gatekeeper/gatekeeper_test.go
Add unit test coverage ensuring that `Deployment` for a `Gateway` has its replica count clamped to the min + max specified on the `GatewayClassConfig`.
🤖 tests pass
See above
Checklist:
=> api-gateway: add unit tests verifying scaling parameters on GatewayClassConfig are obeyed

.github/workflows/build.yml, control-plane/Dockerfile
build: https://github.com/hashicorp/consul-k8s/actions/runs/5227978283
=> Add CRT docker changes for release workflow

.github/workflows/build.yml
Duplicate of https://github.com/hashicorp/consul-k8s/pull/2337, targeting just the `release/1.2.x` branch to unblock `1.2.0-rc1` while integration test issue is sorted out in `main`.
=> update redhat registry id (1.2.x)

.changelog/2346.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
- Set localities on service instances similarly to Consul servers https://github.com/hashicorp/consul-k8s/blob/main/control-plane/subcommand/fetch-server-region/command.go
- The connect injector already has permissions to read nodes https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/connect-inject-clusterrole.yaml#L68-L76
I manually tested that localities are properly set using the sameness demo.
👁️ 
Checklist:
=> Set Consul Service Instance Localities from K8s Node Labels

control-plane/api-gateway/cache/gateway.go, control-plane/api-gateway/common/translation.go, control-plane/api-gateway/common/translation_test.go, control-plane/api-gateway/controllers/gateway_controller.go
Fix use of incorrect config flag when translating namespaces
Run conformance tests defined in kubernetes-sigs/gateway-api. These were previously failing because every test involves deleting a Gateway - now they're passing.
See above
**Checklist:**
=> fix: use correct flag when translating namespaces

.github/workflows/backport.yml
This brings consul-k8s in line with consul.
Most importantly, the backport assistant was updated to automatically assign created PRs to the person who merged the PR that is being backported. This enables us to ask engineers to simply "check for any PRs assigned to you".
This version has been successfully running in consul for a few weeks, since https://github.com/hashicorp/consul/pull/17486
**Checklist:**
=> ci: update backport assistant to 0.3.4

acceptance/tests/connect/connect_inject_test.go
- Use linter to fix usage of `t` in retry loops with the context `r`
- `go install github.com/hashicorp/lint-consul-retry@master`
- `lint-consul-retry`
- 👀 
Checklist:
=> Fix retry loops that use `t`

acceptance/tests/cli/cli_install_test.go, control-plane/subcommand/create-federation-secret/command_test.go
- Use linter to fix usage of `t` in retry loops with the context `r`
- `go install github.com/hashicorp/lint-consul-retry@master`
- `lint-consul-retry`
- 👀 
Checklist:
=> Fix retry loops that use `t` (release/1.1.x)

.github/workflows/nightly-api-gateway-conformance.yml
- Every night trigger API Gateway conformance test github action from consul-k8s-workflows
- Conformance tests will likely not pass in this current iteration, need to update conformance test target to latest
- CI action runs
- CI Action runs
Checklist:
=> api-gateway: nightly conformance test action

.changelog/2357.txt, charts/consul/templates/crd-serviceresolvers.yaml, control-plane/api/v1alpha1/serviceresolver_types.go, control-plane/api/v1alpha1/serviceresolver_types_test.go, control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
- Add `prioritizeByLocality` to `ServiceResolver` CRD
I spun up a consul-k8s cluster and tried setting this field to different values.
👁️ 
Checklist:
=> Add CRDs for `ProritizeByLocality` Routing

Makefile, control-plane/build-support/functions/10-util.sh, control-plane/build-support/scripts/consul-enterprise-version.sh
- Update values.yaml to use the consul OSS version
- add/update make targets to do the following:
> $ make consul-version
> docker.mirror.hashicorp.services/hashicorppreview/consul:1.16-dev
>
> $ make consul-enterprise-version
> docker.mirror.hashicorp.services/hashicorppreview/consul-enterprise:1.16-dev
This way we can use this in the pipelines to make sure that the correct consul version is passed into the tests.
:eyes:
:eyes: 
Checklist:
=> [CI] update unit tests to use enterprise

acceptance/go.mod, acceptance/go.sum, acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go, control-plane/api-gateway/binding/binder.go, control-plane/api-gateway/binding/binder_test.go, control-plane/api-gateway/cache/gateway.go
- Fixes a bug where deleting a Pod would not delete the corresponding service for a Gateway.
🐞 *Bug*
When a user would manually delete a Pod running Consul Dataplane for a gateway, the corresponding service in Consul was not getting deleted. This was due to a caching issue where the controller was not updating its store of active Consul services to diff against existing Consul Dataplane pods.
- Ran the test locally in Kind, manually deleting Pod and ensuring that stale services don't hang around.
- Ran the tests against all acceptance tests.
- Ran the test against a new acceptance test that catches this error (SO to @sarahalsmiller)
Checklist:
> Entries should …
=> api-gateway: fix cache and service deletion issue

acceptance/go.mod, acceptance/go.sum, acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go, control-plane/api-gateway/binding/binder.go, control-plane/api-gateway/binding/binder_test.go, control-plane/api-gateway/cache/gateway.go
This PR merges in the fix in #2377 to release 1.2.0.
Checklist:
=> Fix Gateway Service Deregistration

Makefile, control-plane/build-support/scripts/consul-enterprise-version.sh
- this is a release branch version of #2342
- add/update make targets to do the following:
> $ make consul-version
> docker.mirror.hashicorp.services/hashicorppreview/consul:1.16-dev
>
> $ make consul-enterprise-version
> docker.mirror.hashicorp.services/hashicorppreview/consul-enterprise:1.16-dev
This way we can use this in the pipelines to make sure that the correct consul version is passed into the tests.
Checklist:
=> [CI] Use different consul versions (release/1.2.0)

.changelog/2370.txt, charts/consul/templates/server-config-configmap.yaml, charts/consul/test/unit/server-config-configmap.bats, charts/consul/values.yaml
This PR is manually created from #2265 to be assessed for backporting targeting the release/1.2.x.
---
- Adds the relevant inputs in values.yaml to configure audit logging in Consul enterprise.
- Behind the scenes, values get translated to the json configuration present [here](https://developer.hashicorp.com/consul/docs/agent/config/config-files#audit) and the whole configuration is added as a file in the Consul server's config map.
- Unit tests
- CI
- I've added the `auditLog` field under `server`. Should the same be added to `client`?
Checklist:
> Entries should …
=> Manual backport of Improvement- Added helm inputs for managing audit logs into release/1.2.x

.changelog/2369.txt, charts/consul/templates/server-config-configmap.yaml, charts/consul/test/unit/server-config-configmap.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/values.yaml
This PR is manually created from #2265 to be assessed for backporting targeting the release/1.1.x.
---
- Adds the relevant inputs in values.yaml to configure audit logging in Consul enterprise.
- Behind the scenes, values get translated to the json configuration present [here](https://developer.hashicorp.com/consul/docs/agent/config/config-files#audit) and the whole configuration is added as a file in the Consul server's config map.
- Unit tests
- CI
- I've added the `auditLog` field under `server`. Should the same be added to `client`?
Checklist:
> Entries should …
=> Manual backport of Improvement- Added helm inputs for managing audit logs into release/1.1.x

.changelog/2390.txt, CHANGELOG.md, control-plane/Dockerfile
- Updating `go-discover` to the latest head ref. https://github.com/hashicorp/go-discover
* `make control-plane-dev-docker`
* Just verify the the container is building properly in CI.
* I'm unsure if there are breaking changes in go-discover, since it doesn't use semver.
Checklist:
=> Bumping go-discover to the lastest version

.github/workflows/pr.yml, Makefile, acceptance/ci-inputs/kind-inputs.yaml, control-plane/build-support/scripts/read-yaml-config.sh
This pins the KIND version to the Consul-K8s branch
- created a yaml file with the desired pinned versions
- created a script to read the yaml
- added a make target which can be used in CI to get the desired kind inputs/config
- ran this against branch in https://github.com/hashicorp/consul-k8s-workflows/pull/17 and verified the pinned kind config was being picked up
- Success Run: https://github.com/hashicorp/consul-k8s-workflows/actions/runs/5293009439
👀 
Checklist:
=> Pin Kind versions on release branches

.changelog/2390.txt, control-plane/Dockerfile
- Manual backport of https://github.com/hashicorp/consul-k8s/pull/2390
👀 
:eyes:
Checklist:
=> Backport Bumping go-discover to the latest version

charts/consul/Chart.yaml, charts/consul/values.yaml
- I believe that main should be using consul-dataplane 1.2-dev (which is the latest dev version)
- Use our own docker mirror to prevent docker from rate limiting us
Checklist:
=> update consul-dataplane on main to use 1.2-dev

acceptance/tests/connect/permissive_mtls_test.go, acceptance/tests/fixtures/cases/permissive-mtls/mesh-config-permissive-allowed.yaml, acceptance/tests/fixtures/cases/permissive-mtls/mesh-config-permissive-disallowed.yaml, acceptance/tests/fixtures/cases/permissive-mtls/service-defaults-static-server-permissive.yaml, acceptance/tests/fixtures/cases/permissive-mtls/service-defaults-static-server-strict.yaml
This adds a basic acceptance test for permissive mTLS that tests:
* An inbound non-mTLS connection is rejected in strict mode
* An inbound non-mTLS connection is accepted in permissive mode
* Ran it locally with kind
👀 
Checklist:
=> Acceptance test for permissive mTLS

control-plane/connect-inject/webhook/container_volume.go, control-plane/connect-inject/webhook/container_volume_test.go, control-plane/connect-inject/webhook/mesh_webhook.go, control-plane/connect-inject/webhook/mesh_webhook_test.go
- using defaultStorageMedium("") for consul-connect-inject-data volume incase of windows os.
-
built a new control plane image and installed consul in gke windows using helm  
Checklist:
=> Net 4616/windows volume medium fix

.changelog/2310.txt, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/templates/api-gateway-gatewayclassconfig.yaml, charts/consul/templates/client-daemonset.yaml, charts/consul/templates/cni-daemonset.yaml, charts/consul/templates/enterprise-license-job.yaml, charts/consul/templates/gateway-cleanup-job.yaml, charts/consul/templates/gateway-resources-job.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/templates/partition-init-job.yaml, charts/consul/templates/server-acl-init-cleanup-job.yaml, charts/consul/templates/server-acl-init-job.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/templates/webhook-cert-manager-deployment.yaml, charts/consul/values.yaml
This reverts commit 285096241e0d5c5b6d53dd8a37889ab3ea5a8af2.
- The above PR missed some places to add support for the imagePullPolicy leading to inconsistent behavior across the helm chart. This change will be reintroduced in a future PR once we have implemented it completely.
=> Revert "added imagePullPolicy for images in values.yaml (#2310)"

Makefile, acceptance/ci-inputs/aks_acceptance_test_packages.yaml, acceptance/ci-inputs/eks_acceptance_test_packages.yaml, acceptance/ci-inputs/gke_acceptance_test_packages.yaml, acceptance/ci-inputs/kind_acceptance_test_packages.yaml, control-plane/build-support/scripts/set_test_package_matrix.sh
- This PR adds a configurable acceptance test matrix to the repo that can be fetched via the following make targets ( depending on the test):
- `make kind-test-packages`
- `make aks-test-packages` 
-  `make eks-test-packages`
- `make gke-test-packages`
- Each branch can now have their own defined list of acceptance tests allowing branches to have different packages 
- Ran against this workflow: https://github.com/hashicorp/consul-k8s-workflows/pull/19
- Will point the pr.yaml file back at main after review
- I wasn't able to test the cloud tests because cloud test security does not allow for point tests to any other branch than main
👀 
Checklist:
> HashiCorp …
=> Mw/net 4622 release 0.49.x acceptance tests broken missing packages

Makefile, acceptance/ci-inputs/aks_acceptance_test_packages.yaml, acceptance/ci-inputs/eks_acceptance_test_packages.yaml, acceptance/ci-inputs/gke_acceptance_test_packages.yaml, acceptance/ci-inputs/kind_acceptance_test_packages.yaml, control-plane/build-support/scripts/set_test_package_matrix.sh
- This is a port of https://github.com/hashicorp/consul-k8s/pull/2411
Checklist:
=> Mw/net 4622 1 2 0 cp release 0.49.x acceptance tests broken missing packages

.changelog/2416.txt, charts/consul/templates/server-acl-init-cleanup-job.yaml, charts/consul/templates/server-acl-init-job.yaml, charts/consul/test/unit/server-acl-init-cleanup-job.bats, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/values.yaml
- Exposes resource configuration for `server-acl-init` and `sercer-acl-init-cleanup` Jobs as helm values with existing defaults. 
How I've tested this PR: unit tests
Checklist:
=> feat(helm): add configurable server-acl-init and cleanup resource limits

.github/workflows/build.yml
- Follow up #2337 
- The redhat repo created in https://github.com/hashicorp/consul-k8s/pull/2333 missed a setting (have the registry be hosted by redhat) that cannot be changed after repo creation, so the repo had to be recreated.
👀 
👀 
Checklist:
=> update redhat registry id

charts/consul/templates/server-config-configmap.yaml
- Change the `"true"` value in audit log config to `true`. 
The bug shows up when `server.auditLogs.enable=true`. This creates a JSON config in the `server-config-configmap` that configures audit logs. This JSON used `"true"` to enable the audit logs. Consul Enterprise would try to parse this JSON and fail on startup.
This error would be seen on startup:
```
==> failed to parse /consul/config/..2023_06_23_03_17_33.2371016911/audit-logging.json: 1 error(s) decoding:
* 'audit.enabled' expected type 'bool', got unconvertible type 'string', value: 'true'
```
Now with the value set to `true`, audit logging works just fine :) 
I installed Consul Enterprise in Kind with the following command.
```sh
helm install consul $HELM_CHART -n consul \ …
```
=> Fix Audit Log Config for Consul Enterprise

charts/consul/Chart.yaml, charts/consul/values.yaml
- The Consul-k8s 1.2 branches point to dataplane 1.1. We should be testing with 1.2, so this bumps it.
-
👀 acceptance tests passing (except CNI which is a known issue not fixed by this PR)
👀 
Checklist:
=> use latest 1.2 dataplane

.github/workflows/build.yml
- Manual backport of #2337 
👀 
👀 
Checklist:
=> Manual backport of 2337 into release/1.1.x

acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go, acceptance/tests/api-gateway/api_gateway_tenancy_test.go
- Add retryCheckWithWait func
- Fix retry timing on GatewayClassConfig test
- Running Acceptance tests locally
Checklist:
=> Fix GatewayClassConfig Test Timing Issue

.changelog/2392.txt, control-plane/subcommand/server-acl-init/create_or_update.go, control-plane/subcommand/server-acl-init/create_or_update_test.go
- removed c.flagEnableNamespaces || c.flagSyncCatalog check to always allow  acl update
Context :- 
Between 0.49.0 and 1.0.x: we don't update ACL policies unless namespaces or sync catalog is enabled but between those versions, we merged controller and connect-inject. This meant we added required ACL rules to connect inject but those don't actually get updated and so now the controller can't do things like create intention CRDs.
- deploy 0.49.x with connect inject enabled and acls enabled
- Get the acl policy for connect injector and save it locally
- build a control plane image and set imageK8s  with it.
- upgrade to 1.0.x with your changes
- Check the acl policy again and check that it has updated rules as opposed to the one from …
=> always update acl policy if it exists

acceptance/go.mod, acceptance/go.sum, acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go, control-plane/api-gateway/binding/binder.go, control-plane/api-gateway/binding/binder_test.go, control-plane/api-gateway/cache/gateway.go
- Backport of #2377 
- Fixes issues from manual backport #2387 
Checklist:
=> Backport of #2377

acceptance/tests/api-gateway/api_gateway_gatewayclassconfig_test.go, acceptance/tests/api-gateway/api_gateway_tenancy_test.go
- Manual backport of https://github.com/hashicorp/consul-k8s/pull/2458
- Fixed a flaking API Gateway acceptance test. 
- Not a critical bug fix, so it doesn't need to go into release/1.2.0
-CI tests pass
- CI tests pass
Checklist:
=> Manual backport gatewayclassconfigtest fix

control-plane/api-gateway/binding/route_binding.go, control-plane/api-gateway/controllers/gateway_controller_integration_test.go
- Adds back tests from https://github.com/hashicorp/consul-k8s/pull/2305 that started failing after the merge and was reverted here (https://github.com/hashicorp/consul-k8s/pull/2341).
Ran the test.
Run the test!
Checklist:
=> Adds back gateway controller integration test

control-plane/api-gateway/common/translation.go, control-plane/api-gateway/common/translation_test.go
This is a backport of https://github.com/hashicorp/consul-k8s/pull/2487 targeting the 1.2.0 release
🤖 tests
🤖 tests
**Checklist:**
=> [release/1.2.0] Backport api-gateway: Fix nil pointer exception panic

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/build-support/scripts/consul-enterprise-version.sh, control-plane/version/version.go
=> Setup 1.0.8 for release

.changelog/2487.txt, control-plane/api-gateway/common/translation.go, control-plane/api-gateway/common/translation_test.go, control-plane/api-gateway/controllers/gateway_controller_integration_test.go
- Fix nil pointer exception thrown whenever the user uses an httpfilter that does not have RequestHeaderModifier set. 
- Created unit test that replicated the error and saw that it is resolved with this fix
- Unit tests pass
Checklist:
=> api-gateway: Fix nil pointer exception panic

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/build-support/scripts/consul-enterprise-version.sh, control-plane/version/version.go
- Have consul-enterprise-version work for both preview and prod images
- Prepare Consul K8s 1.1.3 release
-
-
Checklist:
=> Set up 1.1.3 for release

.changelog/2478.txt, control-plane/api-gateway/binding/binder_test.go, control-plane/api-gateway/binding/result.go, control-plane/api-gateway/binding/validation.go, control-plane/api-gateway/common/secrets.go, control-plane/api-gateway/common/secrets_test.go, control-plane/api-gateway/common/translation.go
- Ensure RSA keys are of the correct length when creating an inline cert
- unit tests
- read the code
Checklist:
=> APIGW: Validate length of RSA Keys

.changelog/2476.txt
- Add changelog for dataplane and consul version updates to helm
-
Checklist:
=> add changelog for 1.2.0 dataplane and consul 1.16.0

.github/workflows/build.yml
- Reverts `redhat_tag` to be the non-fips version
=> Fix RedHat Tag

charts/consul/values.yaml
- Fixes #2502 in the 1.0.8 Helm chart where `image` was set to the enterprise version.
=> Set imageConsul to non-ent image

hack/aws-acceptance-test-cleanup/main.go
- cleans up oidc providers associated with our pipeline terraform
- ran it locally and it deleted the oidc providers
- 👀
=> ci: fix eks terraform quota error by cleaning up oidc providers

.changelog/2514.txt, charts/consul/templates/connect-inject-deployment.yaml, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml
Set to true before performing an upgrade to a consul-dataplanes compatible consul-k8s version. This will ensure that the ACL tokens used to register non-dataplane services won't get deleted during the upgrade to dataplanes. If these ACL tokens are deleted, non-dataplane services won't be able to resolve their upstreams. During a normal non-dataplane upgrade this isn't an issue because the new injector re-registers all services using its new ACL token, but during an upgrade to dataplanes, the injector ignores all non-dataplane services and so doesn't re-register them with its latest token.
- ran the upgrade and confirmed old non-dataplane services have their upstreams updated
- code
Checklist:
> HashiCorp engineers only, …
=> Add connectInject.prepareDataplanesUpgrade value

.github/pull_request_template.md
- 3rd party contributors should add their own changelog. Link to instructions included.
=> docs: self service changelog instructions

.changelog/2525.txt, charts/consul/templates/gateway-cleanup-job.yaml, charts/consul/templates/gateway-resources-job.yaml, charts/consul/templates/server-acl-init-cleanup-job.yaml, charts/consul/templates/server-acl-init-job.yaml, charts/consul/templates/tls-init-cleanup-job.yaml, charts/consul/templates/tls-init-job.yaml, charts/consul/test/unit/gateway-cleanup-job.bats, charts/consul/test/unit/gateway-resources-job.bats, charts/consul/test/unit/server-acl-init-cleanup-job.bats, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/test/unit/tls-init-cleanup-job.bats, charts/consul/test/unit/tls-init-job.bats, charts/consul/values.yaml
Duplicate of #2508. 
Adds Security Context and Annotations to TLS and ACL cleanup and init jobs.
Closes #1433 #670
=> feat: adding security context and annotations to tls and acl init/cleanup jobs

.changelog/2520.txt, acceptance/framework/connhelper/connect_helper.go, acceptance/tests/connect/connect_inject_test.go, acceptance/tests/fixtures/bases/resolver-redirect/intention.yaml, acceptance/tests/fixtures/bases/resolver-redirect/kustomization.yaml, acceptance/tests/fixtures/bases/resolver-redirect/resolver.yaml, acceptance/tests/fixtures/bases/resolver-redirect/service.yaml, acceptance/tests/fixtures/bases/resolver-redirect/serviceaccount.yaml, acceptance/tests/fixtures/cases/resolver-redirect-virtualip/kustomization.yaml, control-plane/subcommand/server-acl-init/rules.go, control-plane/subcommand/server-acl-init/rules_test.go
When partitions were not enabled, the ACL token for the connect-inject pod would have insufficient privileges to persist virtual IP addresses to Consul. This PR ensures that connect-inject always has `mesh:write` access, so that transparent proxy can correctly utilize KubeDNS names.
=> NET-4813: Fix issue where virtual IP saving had insufficient ACLs.

acceptance/tests/connect/connect_proxy_lifecycle_test.go
- This reactivates a broken proxy-lifecycle test now that is has been fixed
-
Checklist:
=> reactivate proxy-lifecycle tests

charts/consul/values.yaml
- Our helm chart should be using the consul OSS image by default so that everyone can pull it.
- I had set it to enterprise during the GHA migration but that is no longer required because we have make targets to determine the correct OSS or ENT images.
CI
👀 
Checklist:
=> chore: Update chart to use OSS image

cli/preset/cloud_preset.go, cli/preset/cloud_preset_test.go
- downcase the HCP bootstrap response to be lowercase
- added tests cases to validate.
Manually tested with a e2e test of the cluster bootstrapping.
Checklist:
=> HCP bootstrap preset to always downcase datacenter

.changelog/2413.txt, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/service.go
A valid `Gateway` can have multiple listeners with the same port. When this happens, we loop through the listeners and add each listener's port to the list of ports for the corresponding Kubernetes `Service`, resulting in an invalid resource that can't be created.
This change just tracks which ports have already been added so that we only add each port once.
🤖 tests pass
🤖 tests pass
Checklist:
=> NET-4638: when multiple listeners have the same port, only add to K8s Service once

.changelog/2420.txt, control-plane/api-gateway/binding/result.go, control-plane/api-gateway/binding/result_test.go, control-plane/api-gateway/binding/route_binding.go
When a `HTTPRoute` declares a parent `Gateway`, it's allowed to specify a specific listener on that `Gateway` to attach to. If a listener doesn't exist matching that parent reference, then we need to set the `HTTPRoute` acceptance condition appropriately.
- Added unit tests pass
- Previously failing conformance test now passes
See above
**Checklist:**
=> NET-4482: set route condition appropriately when parent ref includes non-existent section

.github/workflows/build.yml
- I inadvertently changed this to the incorrect project in the 1.16 time frame
- The incorrect value caused problems with the 0.49.8 release (but we worked around it)
👀 
👀 
Checklist:
=> Set redhat project to non-fips project

Makefile, charts/consul/values.yaml, control-plane/build-support/functions/10-util.sh
NOTE TO REVIEWER: You can go through my PR commit by commit, I've organized changes to be isolated to each commit. You can often get more context from them.
- update environment variables with `CONSUL_K8s` prefix. This will let us check that we have all the environment variables set more easily with `printenv | grep "CONSUL_K8S"`
- also added a make target that just runs printenv | grep "CONSUL_K8S"
- update `imageConsulDataplane` without quotes. This makes it consistent with the other images and allows scripting to work similarly to other images
- updated utils script
- handle replace case where consul-enterprise is in the values.yaml file and charts.yaml file
- handle adding pre-release tag in changelog
- handle updating consul-dataplane
How I've tested this …
=> Update Release Scripts

CHANGELOG.md
- added missing changelogs 
-
Checklist:
=> added missing changelogs

CONTRIBUTING.md, Makefile, acceptance/framework/config/config.go, acceptance/framework/config/config_test.go, acceptance/framework/consul/cli_cluster.go, acceptance/framework/environment/environment.go, acceptance/framework/flags/flags.go, acceptance/framework/flags/flags_test.go, acceptance/tests/partitions/main_test.go, acceptance/tests/partitions/partitions_connect_test.go, acceptance/tests/partitions/partitions_gateway_test.go, acceptance/tests/partitions/partitions_sync_test.go, acceptance/tests/peering/main_test.go, acceptance/tests/peering/peering_connect_namespaces_test.go, acceptance/tests/peering/peering_connect_test.go, acceptance/tests/peering/peering_gateway_test.go, acceptance/tests/vault/main_test.go, acceptance/tests/vault/vault_partitions_test.go, acceptance/tests/vault/vault_wan_fed_test.go, acceptance/tests/wan-federation/main_test.go, acceptance/tests/wan-federation/wan_federation_gateway_test.go, acceptance/tests/wan-federation/wan_federation_test.go
**Note to reviewer** I have been very particular about my commits, for an easier time reviewing I suggest going through commit by commit. I have added extra notes, and it breaks up the context of the changes so that it's easier to review.
- To support sameness tests we need to be able to run 3 Consul clusters during the acceptance tests. Instead of adding an addition flag to accomodate this, this PR instead refactors the original flags to instead be flags that accept comma separated lists:
```
- -kubeconfig string
The path to a kubeconfig file. If this is blank, the default kubeconfig path (~/.kube/config) will be used.
- -kubecontext string
The name of the Kubernetes context to use. If this is blank, the context set as the current context will be used by …
```
=> Refactor test framework to allow for more than two kube contexts

charts/consul/test/terraform/eks/main.tf
- Replacing the deprecated [`resolve_conflicts`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#resolve_conflicts) with the new attributes. I don't know if we really need this setting since it is optional and the addon has no user-defined config, but I'm keeping this to keep the behavior consistent.
How I've tested this PR: I did not.
Checklist:
=> test(eks): fix deprecated CSI driver terraform

control-plane/catalog/to-consul/resource.go
- Add a check to prevent a nil-pointer dereference on Ingress LB
- Deployed an improper Ingress config and validated that it does not crash the sync catalog.
- 👀
=> Add a check to prevent a nil-pointer dereference on Ingress LB

.github/workflows/build.yml, .github/workflows/changelog-checker.yml
- Update actions that are out of date
👀 
👀 
Checklist:
=> chore: Update actions for security

charts/consul/values.yaml
Add guidance for proper configuration when joining to a secondary cluster using WAN fed with external servers also enabled.
Also clarify federation requirements and fix formatting for an unrelated value.
- Update base content for generating Helm chart docs to clarify the use case encountered in https://github.com/hashicorp/consul-k8s/issues/2138
- Minor additional fixes
- _Follow-up: propagate generated doc changes to `consul` and additionally update https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/servers-outside-kubernetes there_
How I've tested this PR: N/A (docs only)
Checklist:
=> [NET-4122] Doc guidance for federation with externalServers

.github/workflows/merge.yml, .github/workflows/nightly-acceptance.yml, .github/workflows/pr.yml, .github/workflows/weekly-acceptance-0-49-x.yml, .github/workflows/weekly-acceptance-1-0-x.yml, .github/workflows/weekly-acceptance-1-1-x.yml
I think this should resolve errors like https://github.com/hashicorp/consul-k8s/actions/runs/5615117399/job/15215290442?pr=2604#step:2:17 due to the missing arg in the target workflow.
Follow-up to #2589.
Checklist:
=> Manual backport of test: remove unused workflow inputs (#2589) into release/0.49.x

.github/workflows/merge.yml, .github/workflows/nightly-acceptance.yml, .github/workflows/nightly-cleanup.yml, .github/workflows/weekly-acceptance-0-49-x.yml, .github/workflows/weekly-acceptance-1-0-x.yml, .github/workflows/weekly-acceptance-1-1-x.yml
I think this should resolve errors like https://github.com/hashicorp/consul-k8s/actions/runs/5615117399/job/15215290442?pr=2604#step:2:17 due to the missing arg in the target workflow.
Follow-up to #2589.
Checklist:
=> Manual backport of test: remove unused workflow inputs (#2589) into release/1.2.x

.changelog/2571.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
Possible fix for: 
https://github.com/hashicorp/consul-k8s/issues/2085 
https://github.com/hashicorp/consul-k8s/issues/2065 
https://github.com/hashicorp/consul/issues/15908 
https://github.com/hashicorp/consul-k8s/issues/1935 
https://github.com/hashicorp/consul-k8s/issues/1817 
which are all the same issue of ghost services left in the catalog when nodes are recycled. 
Associated issue: https://github.com/hashicorp/consul-k8s/issues/2491
- In the past, kubernetes nodes were used as the source of truth to determine the list of services that should exist in Consul. 
- In most cases this was ok but becomes a problem when nodes are quickly deleted from kubernetes such as the case when using spot instances.
- Instead, use consul synthetic-nodes to get the list of …
=> Handle errors properly when services are de-registered from the catalog

.github/workflows/build.yml
This avoids a name collision in linux package managers, allowing people to get non-FIPSs with i.e. "apt-get install consul-k8s" and FIPS with "apt-get install consul-k8s-fips
=> Differentiate FIPS linux package names

Makefile, control-plane/build-support/scripts/check-hashicorppreview.sh
- Adds a make target to check for hashicorppreview images in the charts. This will help verify release steps.
Example output where hashicorppreview is found
```
$ make check-preview-containers
./charts/consul/Chart.yaml:19:      image: docker.mirror.hashicorp.services/hashicorppreview/consul-enterprise:1.17-dev
./charts/consul/Chart.yaml:21:      image: docker.mirror.hashicorp.services/hashicorppreview/consul-k8s-control-plane:1.3.0-dev
./charts/consul/Chart.yaml:23:      image: docker.mirror.hashicorp.services/hashicorppreview/consul-dataplane:1.3-dev
./charts/consul/values.yaml:69:  image: docker.mirror.hashicorp.services/hashicorppreview/consul:1.17-dev
./charts/consul/values.yaml:89:  imageK8S: …
```
=> added make target for checking for hashicorppreview

.golangci.yml
This is meant to solve for recurrent timeouts in several steps, particularly `golangci-lint-control-plane` and `golang-ci-lint-cli`.
An [accompanying change](https://github.com/hashicorp/consul-k8s-workflows/pull/29) in `consul-k8s-workflows` should disable caching until the (unclear) root of the issue can be resolved, or we can disable or clear cache in a more targeted way that solves for these cases.
Note from @DanStough : we've also done this in `consul`
https://github.com/hashicorp/consul-k8s/pull/2621
https://github.com/hashicorp/consul/pull/17459
- Disable `golangci-lint` caching
- Example passing workflow after combined fix: https://github.com/hashicorp/consul-k8s-workflows/actions/runs/5624313593/job/15240886287
How I expect …
=> Increase golangci-lint timeout to 10m

.github/workflows/merge.yml, .github/workflows/nightly-acceptance.yml, .github/workflows/pr.yml, .github/workflows/weekly-acceptance-0-49-x.yml, .github/workflows/weekly-acceptance-1-0-x.yml, .github/workflows/weekly-acceptance-1-1-x.yml, .golangci.yml
I think this should resolve errors like https://github.com/hashicorp/consul-k8s/actions/runs/5615117399/job/15215290442?pr=2604#step:2:17 due to the missing arg in the target workflow.
Follow-up to #2589.
Checklist:
=> Manual backport of test: remove unused workflow inputs (#2589) into release/1.1.x

.changelog/2652.txt, charts/consul/templates/client-daemonset.yaml, charts/consul/test/unit/client-daemonset.bats
- Update the CONSUL_LOGIN_DATACENTER logic for client daemonset to only login to the local datacenter as it uses a local authmethod and not a global authmethod.
- This led to errors when attempting to deploy clients in a federated cluster.
- @natemollica-nm was able to replicate the error and this fix fixed it in his federated cluster
- 👀 
Checklist:
=> Consul client always logs into the local datacenter

CHANGELOG.md
* Add a changelog entry to callout the Cloud Auto-Join change in `externalServers.hosts`
Checklist:
=> Update changelog to address cloud auto-join change in 1.0.0

.changelog/2687.txt, charts/consul/templates/ui-ingress.yaml
- blank line between `rules:` and `- host:`
- `ingressClass` was present when no value was specified
-
Fix malformed ingress when using the helm chart. 
Given this values.yaml snippet:
```yaml
ui:
enabled: true
ingress:
enabled: true
hosts:
- host: consul.localhost
```
Output before changes:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: vault-consul-ui
namespace: consul
labels:
app: consul
chart: consul-helm
heritage: Helm
release: vault
component: ui
spec:
ingressClassName: 
rules:
- host: "consul.localhost"
http:
paths:
- backend:
service:
name: vault-consul-ui
port:
number: 80
path: /
pathType: Prefix
```
Output after changes:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: consul-consul-ui
namespace: …
```
=> Fix ingress

Makefile, acceptance/framework/config/config.go, acceptance/framework/config/config_test.go
Rather than hard-coding the Docker repository and parsing the non-Ent image tag for a version, simply replace the image name and retain other coordinates. This is consistent with our tagging scheme introduced in https://github.com/hashicorp/consul/pull/13541 and will allow for using `hashicorppreview` images seamlessly regardless of whether OSS or Ent is being tested.
Also add a `make` target to help with testing local images in multi-cluster scenarios.
- Align `consul-enterprise` image tag derivation with our OSS + Ent tagging scheme
- Add a `make` target for loading dev images across `kind` clusters
- Updated unit tests
- Tested manually:
```shell
❯ go test ./sameness/... -v -timeout 2h -failfast -use-kind -no-cleanup-on-failure …
```
=> Fix default Ent image tag in acceptance tests

.changelog/2678.txt, charts/consul/templates/_helpers.tpl, charts/consul/test/unit/server-statefulset.bats
- This is going into `release/1.1.x`, and will be backported into `release/1.0.x` because both of those Consul K8s versions support K8s < 1.23.x and therefore support OpenShift <= 4.10
- Do not set securityContext on OpenShift < 4.11 because the restricted SCC disallows setting some of those settings. I broke this in https://github.com/hashicorp/consul-k8s/pull/2572. In OpenShift >= 4.11, setting the securityContext is okay because the new restricted-v2 SCC is available to all users/accounts and allows setting the fields we want to set, and doing so avoids warnings.
- We determine the OpenShift version in Helm using the Kube version because there is a 1:1 mapping of OpenShift to Kube versions.
- Ran the connect tests with openshift …
=> Do not set securityContext on Openshift < 4.11

Makefile, acceptance/framework/config/config.go, acceptance/framework/config/config_test.go
Manual backport of da99ce404f3f35f87dd51ace4fb11f68097fdfc8 due to partially failed backport assistant run.
Original PR: https://github.com/hashicorp/consul-k8s/pull/2683
=> Backport of Fix default Ent image tag in acceptance tests into release/1.2.x

.changelog/2302.txt, charts/consul/templates/client-config-configmap.yaml, charts/consul/templates/create-federation-secret-job.yaml, charts/consul/templates/gossip-encryption-autogenerate-job.yaml, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/templates/server-acl-init-cleanup-job.yaml, charts/consul/templates/server-acl-init-job.yaml, charts/consul/templates/server-config-configmap.yaml, charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/templates/tls-init-job.yaml, charts/consul/test/unit/client-config-configmap.bats, charts/consul/test/unit/client-daemonset.bats, charts/consul/test/unit/create-federation-secret-job.bats, charts/consul/test/unit/gossip-encryption-autogenerate-job.bats, charts/consul/test/unit/ingress-gateways-deployment.bats, charts/consul/test/unit/mesh-gateway-deployment.bats, charts/consul/test/unit/server-acl-init-cleanup-job.bats, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/test/unit/server-config-configmap.bats, charts/consul/test/unit/telemetry-collector-deployment.bats, charts/consul/test/unit/terminating-gateways-deployment.bats, charts/consul/test/unit/tls-init-job.bats, charts/consul/values.yaml
- Manually backporting the changes in #2302 to the `1.1.x` release branch
Unit tests & CI
Checklist:
=> Manual backport of Added logLevel field for components  (#2302)

.changelog/2678.txt, charts/consul/templates/_helpers.tpl, charts/consul/test/unit/server-statefulset.bats
Backport of https://github.com/hashicorp/consul-k8s/pull/2678 to release/1.0.x
- This is going into `release/1.1.x`, and will be backported into `release/1.0.x` because both of those Consul K8s versions support K8s < 1.23.x and therefore support OpenShift <= 4.10
- Do not set securityContext on OpenShift < 4.11 because the restricted SCC disallows setting some of those settings. I broke this in https://github.com/hashicorp/consul-k8s/pull/2572. In OpenShift >= 4.11, setting the securityContext is okay because the new restricted-v2 SCC is available to all users/accounts and allows setting the fields we want to set, and doing so avoids warnings.
- We determine the OpenShift version in Helm using the Kube version because there is a 1:1 mapping of OpenShift to …
=> Backport of do not set securityContext on Openshift < 4.11 (#2678)

acceptance/framework/vault/vault_cluster.go
- Increase the timeout when waiting for the vault server to be started
- Also, the error was backwards so fix the argument order for the pod status check.
- Ran CI 
👀 
Checklist:
=> Increase timeout while waiting for vault server to be ready

acceptance/tests/api-gateway/api_gateway_external_servers_test.go, acceptance/tests/api-gateway/api_gateway_lifecycle_test.go, acceptance/tests/api-gateway/api_gateway_tenancy_test.go, acceptance/tests/api-gateway/api_gateway_test.go, acceptance/tests/partitions/partitions_gateway_test.go
- Increase retry timing and add a retry to getting config entries
- I still saw one flake related to xDS rate limiting but I wasn't able to reproduce it
- ran it through CI several times
:eyes:
Checklist:
=> Acceptance tests: increase api-gateway retries

acceptance/framework/connhelper/connect_helper.go, acceptance/framework/k8s/helpers.go, acceptance/tests/wan-federation/wan_federation_test.go, charts/consul/templates/create-federation-secret-job.yaml, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/partition-init-job.yaml, charts/consul/templates/sync-catalog-deployment.yaml, charts/consul/templates/terminating-gateways-deployment.yaml
Manual backport of #2702 in release/1.1x because the backport job failed to generate a PR.
---
Part 2 of https://github.com/hashicorp/consul-k8s/pull/2572.
Update the following to set a "restricted" security context:
* create-federation-secret-job.yaml
* ingress-gateways-deployment.yaml
* ~mesh-gateway-deployment.yaml~
* This is not included because adding the "restricted" security context settings to MGW makes it impossible to use hostNetwork=true
* partition-init-job.yaml
* terminating-gateways-deployment.yaml
* sync-catalog-deployment.yaml
Also, fix a WAN federation test to run on kind
Run acceptance tests on kind with restricted PSA enforcement enabled on the consul …
=> Backport of Support restricted PSA enforcement part 2 into release/1.1.x

acceptance/framework/connhelper/connect_helper.go, acceptance/framework/k8s/helpers.go, acceptance/tests/wan-federation/wan_federation_test.go, charts/consul/templates/create-federation-secret-job.yaml, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/partition-init-job.yaml, charts/consul/templates/sync-catalog-deployment.yaml, charts/consul/templates/terminating-gateways-deployment.yaml
Manual backport of #2702 into release/1.2.x because the backport job failed to generate a PR.
---
Part 2 of https://github.com/hashicorp/consul-k8s/pull/2572.
Update the following to set a "restricted" security context:
* create-federation-secret-job.yaml
* ingress-gateways-deployment.yaml
* ~mesh-gateway-deployment.yaml~
* This is not included because adding the "restricted" security context settings to MGW makes it impossible to use hostNetwork=true
* partition-init-job.yaml
* terminating-gateways-deployment.yaml
* sync-catalog-deployment.yaml
Also, fix a WAN federation test to run on kind
Run acceptance tests on kind with restricted PSA enforcement enabled on the …
=> Backport of Support restricted PSA enforcement part 2 into release/1.2.x

.changelog/2711.txt, control-plane/api-gateway/binding/result.go, control-plane/api-gateway/binding/validation.go, control-plane/api-gateway/binding/validation_test.go, control-plane/api-gateway/common/constants.go, control-plane/api-gateway/common/translation.go, control-plane/api-gateway/common/translation_test.go
- Update translation logic to pull TLS min version, max version + cipher suites from the `Gateway` resource in K8s and write them to the `api-gateway` config entry in Consul
- Update validation logic to compare TLS options against allowed values + combinations of values
- Added unit tests covering changes in translation + validation logic
- 🤖 tests pass
- Visual comparison with the [legacy implementation of translation + validation](https://github.com/hashicorp/consul-api-gateway/blob/a0774e4543104267009b034164d9bf50c5b498e8/internal/k8s/reconciler/validator/gateway.go#L402-L451) which were combined in the same code path at the time
**Checklist:**
=> NET-4413 Implement translation + validation of TLS options

.release/release-metadata.hcl, CONTRIBUTING.md, README.md, acceptance/framework/vault/helpers.go, charts/consul/Chart.yaml, charts/consul/README.md, charts/consul/templates/NOTES.txt, charts/consul/templates/crd-proxydefaults.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/test/unit/mesh-gateway-deployment.bats, cli/cmd/install/install.go, control-plane/api/v1alpha1/proxydefaults_types.go, control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml, control-plane/subcommand/common/common.go, hack/helm-reference-gen/fixtures/full-values.golden, hack/helm-reference-gen/fixtures/full-values.yaml
Update outdated consul.io links that now redirect to https://developer.hashicorp.com/consul/docs and https://developer.hashicorp.com/consul/api-docs
NA, documentation update
NA, documentation update
Checklist:
=> docs: Update outdated `consul.io` links

.changelog/2755.txt, control-plane/connect-inject/webhook/container_init.go, control-plane/connect-inject/webhook/container_init_test.go
- Sets privileged=false for regular transparent proxy connect injects
- Also false when CNI is used 
- True for OpenShift with transparent proxy
- unit tests and accpetance, manual tests on OpenShift
👀 
Checklist:
=> Set privileged to false unless on OpenShift without CNI

.changelog/2755.txt, control-plane/connect-inject/webhook/container_init.go, control-plane/connect-inject/webhook/container_init_test.go
Manual backport of #2755 
Checklist:
=> Backport of Set privileged to false unless on OpenShift without CNI into release/1.1.x

CHANGELOG.md
Adds changelog for 1.2.1, reorders 1.1.4 and 1.0.9
=> Adds changelog for 1.2.1, reorders 1.1.4 and 1.0.9

charts/consul/templates/_helpers.tpl, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/test/unit/server-statefulset.bats
- Explicitly label container security context as having a readonly root filesystem
I was attempting to run consul in a restricted namespace and our gatekeeper policy tripper on this.  I found I could not add the context by manipulating the helm values and so a PR was required,
I have tested it by deploying my updated package and confirming gatekeeper was not tripped
Confirm it deploys fine in a standard test environment just for sanity: as the components don't write this labelling doesn't affect functionality and so is a no-op for anyone not already blocked by  security context.
Checklist:
=> Add readOnlyRootFilesystem to security context

charts/consul/test/terraform/aks/main.tf, charts/consul/test/terraform/aks/variables.tf
- Updating kubernetes on AKS.
- Nightly acceptance are failing
Checklist:
=> AKS 1.24 is deprecated, update to latest 1.25 patch

acceptance/tests/fixtures/bases/sameness/cluster-03-a-default-ns/sameness.yaml, acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/kustomization.yaml, acceptance/tests/fixtures/cases/sameness/static-client/ap1-partition-tproxy/patch.yaml, acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/kustomization.yaml, acceptance/tests/fixtures/cases/sameness/static-client/default-partition-tproxy/patch.yaml, acceptance/tests/sameness/sameness_test.go
- This is a backport of https://github.com/hashicorp/consul-k8s/pull/2776
Checklist:
=> Automate the k8s sameness tests add peering (#2725)

hack/helm-reference-gen/fixtures/full-values.golden, hack/helm-reference-gen/fixtures/full-values.yaml
Fix `consul.io/docs` links missed as part of https://github.com/hashicorp/consul-k8s/pull/2708
Checklist:
=> docs: Fix missed consul.io/docs links

acceptance/framework/k8s/kubectl.go, acceptance/tests/sameness/sameness_test.go
Verify that we propagate locality (region and zone) from standard k8s annotations to services registered by consul-k8s.
This will later be expanded to exercise multi-cluster locality-based failover.
- Add locality labels to k8s cluster nodes
- Assert that registered services receive corresponding locality config
How I've tested this PR: run locally and in CI
Checklist:
=> [NET-4498] Test locality propagation to services from k8s

charts/consul/test/terraform/aks/variables.tf
- Just use 1.25 in AKS to give us some breathing room
-
Checklist:
=> Use Kubernetes 1.25 on AKS

charts/consul/test/terraform/aks/main.tf, charts/consul/test/terraform/aks/variables.tf
- Manual backport of AKS 1.25 changes into 1.2.x
-
Checklist:
=> manual backport of AKS 1.25 into 1.2.x

charts/consul/test/terraform/aks/main.tf, charts/consul/test/terraform/aks/variables.tf
- Backports failed so manual backport of AKS changes
-
Checklist:
=> manual backport of AKS 1.25 into 1.0.x

charts/consul/test/terraform/aks/main.tf, charts/consul/test/terraform/aks/variables.tf
- Manually backporting changes into 1.1.x
- The files weren't exactly the same for some reason so make that happen.
Checklist:
=> manual backport of AKS 1.25 into 1.1.x

control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go, control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go
This commit fixes an issue where the peering tests would flake due to the fact that we were concurrently modifying a global map. It also adds in retry logic so that the consul servers have sufficient time to initialize before attempting to generate peering tokens.
=> Fix peer test flakes.

.changelog/2743.txt, acceptance/framework/connhelper/connect_helper.go, acceptance/tests/connect/connect_external_servers_test.go, acceptance/tests/connect/connect_inject_namespaces_test.go, acceptance/tests/connect/connect_inject_test.go, acceptance/tests/metrics/metrics_test.go, acceptance/tests/partitions/partitions_connect_test.go, control-plane/connect-inject/webhook/mesh_webhook.go, control-plane/connect-inject/webhook/mesh_webhook_test.go
- If lifecycle setting is enabled, inject consul-dataplane as the first container in the pod. Add unit tests where lifecycle is enabled in multiport enabled/disabled setting. 
I've added tests that specifically check the container ordering when lifecycle is turned on. 
Checklist:
=> Net 1784 inject sidecar first

.changelog/2789.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/test/unit/server-statefulset.bats
* Manual backport of https://github.com/hashicorp/consul-k8s/pull/2789 to Add readOnlyRootFilesystem to security context from (#2771)
---------
-
-
Checklist:
=> Add readOnlyRootFilesystem to security context (#2771) backport to 1.2.x

charts/consul/templates/_helpers.tpl, charts/consul/templates/connect-inject-deployment.yaml, charts/consul/templates/partition-init-job.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/test/unit/helpers.bats, charts/consul/test/unit/partition-init-job.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/values.yaml, control-plane/subcommand/inject-connect/command.go, control-plane/subcommand/partition-init/command.go
- Add a value to the Helm chart that allows free-form feature flags, similar to [Consul](https://github.com/hashicorp/consul/blob/main/agent/config/config.go#L186-L186).
- Add placeholder flags for relevant components when `resource-apis` is enabled.
- Helm unit tests
How I expect reviewers to test this PR: 👀 + CI/CD is green
Checklist:
=> feat: add helm value for consul resource-apis experiment

acceptance/framework/connhelper/connect_helper.go, acceptance/framework/k8s/deploy.go, acceptance/tests/connect/connect_proxy_lifecycle_test.go, acceptance/tests/fixtures/bases/job-client/job.yaml, acceptance/tests/fixtures/bases/job-client/kustomization.yaml, acceptance/tests/fixtures/bases/job-client/service.yaml, acceptance/tests/fixtures/bases/job-client/serviceaccount.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/patch.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/patch.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject/patch.yaml
Manual backport of #2669 into release 1.2.x. Addresses backport failure #2826.
=> Manual Backport of #2669 into 1.2.x

acceptance/tests/sameness/sameness_test.go
- Add parallelism in some of the "longer" portions of the testing code, this will dramatically decrease the runtime of the test
Before:
After:
- Locally and in pipeline
- Pipeline is no longer working, going to confirm that I ran the sameness tests locally:
👀 
Checklist:
=> add sameness testing performance enhancement

.changelog/2787.txt, charts/consul/templates/_helpers.tpl, charts/consul/test/unit/server-statefulset.bats
- Add the `NET_BIND_SERVICE` capability for consul-dataplane related to https://github.com/hashicorp/consul-dataplane/pull/238
- Install consul w/ ingress-gateway serving on a privileged port such as `443`
- Install consul under restricted pod security policy
- Install consul under restricted[-v2] OpenShift security context constraints
- See above
Checklist:
=> NET-5186 Add NET_BIND_SERVICE capability to Consul's restricted securityContext

acceptance/tests/sameness/sameness_test.go
- There was a bug we were seeing previously which caused DNS queries to not work when specifying a sameness group and a partition. After manual testing with both agentless and agentful scenarios, this appears to not be happening anymore. I added some tests to exercise the `sg` + `ap` dns scenario, they are all passing.
- Did some refactoring
- added receivers where we were previously passing in the cluster under test
- added the concept of a `primary cluster` in order to enable dns testing for partitions
The diff shows more changes than were actually changed because of moving things around. I added some comments to the code to help you navigate a bit easier.
- added tests
- :eyes
Checklist:
=> Added tests for partition dns/pq

acceptance/framework/connhelper/connect_helper.go, control-plane/connect-inject/webhook/mesh_webhook.go, control-plane/connect-inject/webhook/mesh_webhook_test.go, control-plane/connect-inject/webhook/redirect_traffic.go
- Fixed the indexing between the iptables rules and the overwriteProbes to reference the same number regardless of when dataplane is injected.
- I wrote a unit test that failed w/o this fix, then added the fix (TDD)
- consul-k8s CLI test is now passing because it explicitly enables tproxy
Checklist:
=> fix: lifecycle enabled iptables mismatch

control-plane/consul/resource_client.go, control-plane/consul/resource_client_test.go, control-plane/subcommand/inject-connect/command.go, control-plane/subcommand/inject-connect/v1controllers.go, control-plane/subcommand/inject-connect/v2controllers.go
- Refactor the inject-connect command to clean up the`Run` function
- Move controller/webhook initialization to separate files
- Incorporate V1/V2 switch to start controllers.
- CI/CD
- Eyes
Checklist:
=> refactor: make space for v2 controllers

.changelog/2789.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/test/unit/server-statefulset.bats
Reverts hashicorp/consul-k8s#2789
Causing problems in our acceptance tests since Envoy needs to write to disk for bootstrap config.
=> Revert "Add readOnlyRootFilesystem to security context (#2771)"

acceptance/tests/cli/cli_install_test.go
- Removes the case where transparent proxy is enabled in the test -- it should be set outside of the test with the flag
- Acceptance
- Acceptance
Checklist:
=> Fix issue where CLI install test was running Tproxy manually

.changelog/2782.txt, charts/consul/templates/server-statefulset.yaml, charts/consul/test/unit/server-statefulset.bats
Fixing #1856 
- Correct prometheus port ( 8501) and scheme ( https) annotations if tls is enabled.
- Setting prometheus scheme to http if tls is disabled. 
Created a local cluster using kind and checked prometheus annotations on consul-server  pod using kubectl.
kubectl get pod consul-server-0 --namespace consul -o jsonpath='{.metadata.annotations}'
Checklist:
=> correct prometheus port and scheme annotations if tls is enabled

.changelog/2796.txt, acceptance/tests/fixtures/bases/job-client/job.yaml, acceptance/tests/fixtures/bases/job-client/service.yaml, acceptance/tests/fixtures/bases/job-client/serviceaccount.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/patch.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/patch.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject/patch.yaml, charts/consul/templates/crd-ingressgateways.yaml, charts/consul/templates/crd-proxydefaults.yaml, charts/consul/templates/crd-routeretryfilters.yaml, charts/consul/templates/crd-routetimeoutfilters.yaml, charts/consul/templates/crd-servicedefaults.yaml, control-plane/api/v1alpha1/ingressgateway_types.go, control-plane/api/v1alpha1/ingressgateway_types_test.go, control-plane/api/v1alpha1/servicedefaults_types.go, control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml, control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml, control-plane/config/crd/bases/consul.hashicorp.com_routeretryfilters.yaml, control-plane/config/crd/bases/consul.hashicorp.com_routetimeoutfilters.yaml, control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml, control-plane/consul/resource_client.go, control-plane/consul/resource_client_test.go
- This adds the PassiveHealthCheck onto IngressGateways. The fields were missing from the CRD.
- Related Docs PR: https://github.com/hashicorp/consul/pull/18532
Install Consul locally with the following values:
```
global:
image: hashicorppreview/consul:1.17-dev
imageK8S: YOUR_LOCALLY_BUILT_IMAGE_FROM_THIS_PR
ingressGateways:
enabled: true
defaults:
replicas: 1
gateways:
- name: ingress-gateway
service:
type: ClusterIP
```
Running kubectl apply on the following IngressGateway configuration:
```
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
name: ingress-gateway
spec:
defaults:
passiveHealthCheck:
interval: "10s"
maxFailures: 5
enforcingConsecutive5xx: 100
maxEjectionPercent: 10
baseEjectionTime: "10s"
```
The …
=> Adds fields for PassiveHealthCheck on IngressGateway

.changelog/2790.txt, control-plane/subcommand/server-acl-init/anonymous_token.go, control-plane/subcommand/server-acl-init/anonymous_token_test.go
Prevent updating anonymous token if it already exists and is attached to the anonymous token policy
- setup the deafault partiton and create a non-default partition called my-partition.
- modified the anonymous token policy rule.
- created helm deployment in my-partiton using acl bootstrap token with following policies.
```hcl
acl = "read"
operator = "read"
agent_prefix "" {
policy = "read"
}
```
```hcl
partition "my-partition" {
acl = "write"
mesh = "write"
peering = "write"
namespace_prefix "" {
policy = "write"
}
service_prefix "" {
policy = "write"
}
}
```
- server-acl-acl init was successfull and anonymous token policy rule didn't get updated
Checklist:
=> added check if anonymous token policy exists

.changelog/2785.txt, charts/consul/templates/server-acl-init-job.yaml, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/values.yaml
* Add support for global.argocd.enabled flag in values.yaml which adds the 
```
"argocd.argoproj.io/hook": "Sync"
"argocd.argoproj.io/hook-delete-policy": "HookSucceeded"
```
in the jobs -
server-acl-init-job
* Bats Tests
Manual Tests - 
* Created github pages to host helm charts following [this medium article](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417)
* Forked the repo and created a new branch - https://github.com/absolutelightning/consul-minikubes/tree/test-argocd.
* Updated the repo with values from github helm charts created in step 1
* Ran `bash argocd.sh`
* kubectl port-forward svc/argocd-server -n argocd 8087:443
* argocd admin initial-password -n argocd
* Input username …
=> Backport of Net 5229 create dedicated argocd stanza (#2785) in release 1.2.x

.changelog/2785.txt, charts/consul/templates/server-acl-init-job.yaml, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/values.yaml
* Add support for global.argocd.enabled flag in values.yaml which adds the 
```
"argocd.argoproj.io/hook": "Sync"
"argocd.argoproj.io/hook-delete-policy": "HookSucceeded"
```
in the jobs -
server-acl-init-job
* Bats Tests
Manual Tests - 
* Created github pages to host helm charts following [this medium article](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417)
* Forked the repo and created a new branch - https://github.com/absolutelightning/consul-minikubes/tree/test-argocd.
* Updated the repo with values from github helm charts created in step 1
* Ran `bash argocd.sh`
* kubectl port-forward svc/argocd-server -n argocd 8087:443
* argocd admin initial-password -n argocd
* Input username …
=> Backport - Net 5229 create dedicated argocd stanza (#2785) in release 1.1.x

.changelog/2785.txt, charts/consul/templates/server-acl-init-job.yaml, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/values.yaml
* Add support for global.argocd.enabled flag in values.yaml which adds the 
```
"argocd.argoproj.io/hook": "Sync"
"argocd.argoproj.io/hook-delete-policy": "HookSucceeded"
```
in the jobs -
server-acl-init-job
* Bats Tests
Manual Tests - 
* Created github pages to host helm charts following [this medium article](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417)
* Forked the repo and created a new branch - https://github.com/absolutelightning/consul-minikubes/tree/test-argocd.
* Updated the repo with values from github helm charts created in step 1
* Ran `bash argocd.sh`
* kubectl port-forward svc/argocd-server -n argocd 8087:443
* argocd admin initial-password -n argocd
* Input username …
=> Backport - Net 5229 create dedicated argocd stanza (#2785) in release 1.0.x

.changelog/2782.txt, charts/consul/templates/server-statefulset.yaml, charts/consul/test/unit/server-statefulset.bats
Fixing https://github.com/hashicorp/consul-k8s/issues/1856
- Correct prometheus port ( 8501) and scheme ( https) annotations if tls is enabled.
- Setting prometheus scheme to http if tls is disabled.
Created a local cluster using kind and checked prometheus annotations on consul-server pod using kubectl.
kubectl get pod consul-server-0 --namespace consul -o jsonpath='{.metadata.annotations}'
Checklist:
=> Manual backport of correct prometheus port and scheme annotations if tls is enabled (#2782)

charts/consul/values.yaml
- Describes that it changes the logLevel for both the `consul-dataplane` sidecar and `consul-connect-inject-init` container. 
Checklist:
=> docs - Update connectInject.logLevel docs

.changelog/2869.txt, charts/consul/templates/gateway-cleanup-job.yaml, charts/consul/templates/gateway-resources-job.yaml, charts/consul/test/unit/gateway-cleanup-job.bats, charts/consul/test/unit/gateway-resources-job.bats
Remove global.acls.nodeSelector and global.acls.annotations from the Gateway Resources Job and Gateway Cleanup Job
Checklist:
=> NET-5389- Remove global.acls.nodeSelector and global.acls.annotations from Gateway Resources Jobs

.changelog/2880.txt, control-plane/api-gateway/cache/consul.go
- I noticed this when I was working on a customer issue and it made debugging more difficult
- I was working on an issue that was reproduced by deleting the consul-server-0 pod and the api-gateway logging spit out about 20k log lines in about 5 seconds
- I don't think we need to log these errors out at the api-gateway level as other parts of the controller will log a similar error out but less frequently.
- The customer will still see that the consul server is unreachable in the logs (see below)
Instead of 20k of these:
> 2023-08-31T14:33:54.861Z        ERROR   error fetching config entries for kind: http-route      {"error": "Get \"http://10.244.0.8:8500/v1/config/http-route?dc=dc1&index=10\": dial tcp 10.244.0.8:8500: connect: connection refused"}
They still …
=> Filter api-gateway cache logging to reduce log output on server disconnect

acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-0s/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject-grace-period-10s/kustomization.yaml, acceptance/tests/fixtures/cases/jobs/job-client-inject/kustomization.yaml, acceptance/tests/fixtures/cases/wan-federation/dc1-ns2-static-server/kustomization.yaml, acceptance/tests/fixtures/cases/wan-federation/dc1-static-server/kustomization.yaml, acceptance/tests/fixtures/cases/wan-federation/dc2-static-server/kustomization.yaml, acceptance/tests/fixtures/cases/wan-federation/service-resolver/kustomization.yaml, acceptance/tests/fixtures/cases/wan-federation/static-client/kustomization.yaml
- Removed some more deprecated uses of `patchesStrategicMerge` added after Thomas's PR to remove the majority https://github.com/hashicorp/consul-k8s/pull/2786
@t-eckert Thanks for the script :)
Checklist:
=> removed deprecated `patchesStrategicMerge`

charts/consul/templates/ingress-gateways-podsecuritypolicy.yaml, charts/consul/templates/mesh-gateway-podsecuritypolicy.yaml, charts/consul/templates/telemetry-collector-podsecuritypolicy.yaml, charts/consul/templates/terminating-gateways-podsecuritypolicy.yaml
PodSecurityPolicy needs to add the `NET_BIND_SERVICE` capability for any Deployment that includes consul-dataplane.
A search for these in the consul-k8s repo yields:
1. Create a GKE cluster with PodSecurityPolicy enforcement enabled
```shell
$ gcloud beta container clusters create cluster-1 --cluster-version=1.24 --enable-pod-security-policy
```
3. Deploy Consul with PodSecurityPolicy enabled as well as the various gateway types and the telemetry collector
```yaml
global:
enablePodSecurityPolicies: true
telemetryCollector:
enabled: true
meshGateway:
enabled: true
terminatingGateways:
enabled: true
ingressGateways:
enabled: true
gateways:
- name: ingress-gateway
service:
type: LoadBalancer
ports:
- port: 80
```
4. Verify that …
=> NET-5186 Add NET_BIND_SERVICE to built-in PSPs for consul-dataplane deployments

control-plane/api-gateway/cache/consul_test.go, control-plane/catalog/to-consul/syncer_test.go, control-plane/connect-inject/common/common.go, control-plane/connect-inject/common/common_test.go, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/controllers/endpoints/consul_client_health_checks.go, control-plane/connect-inject/controllers/endpoints/consul_client_health_checks_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go, control-plane/connect-inject/webhook/mesh_webhook.go, control-plane/connect-inject/webhook/mesh_webhook_test.go, control-plane/consul/resource_client.go, control-plane/go.mod, control-plane/go.sum, control-plane/helper/test/test_util.go, control-plane/subcommand/inject-connect/v2controllers.go, control-plane/subcommand/server-acl-init/command_test.go
This PR is part of a series of PRs that add functionality to the V2 Pod Controller. For the MVP task to be complete, there will be one additional PR to fill in the lifecycle of HealthStatus and ProxyConfiguration resources. 
`TODO(dans)` comments are needed for the MVP tasks. Other `TODOs` are captured in future stories.
- Add the V2 Pod Controller
- Add enough logic in the controller to manage Consul Workloads
- pod controller test framework, borrowed from the endpoints controller.
How I've tested this PR: Unit tests
How I expect reviewers to test this PR: 👓 
Checklist:
=> feat: add v2 pod controller w/ workload lifecycle

charts/consul/values.yaml
- Addresses issue https://github.com/hashicorp/consul-k8s/issues/1285#issuecomment-1160461529. Ingress Gateways are deprecated so the limitation will remain. 
Checklist:
=> Address issue #1285 via docs

Makefile
- Adds a check that the controller-gen binary is the correct version before generating CRDs
- I ran this with no controller-gen binary installed and the Makefile installed the correct version for me.
- I ran this with the correct controller-gen binary installed and the Makefile used it.
- I ran this with an incorrect version of the controller-gen binary installed and the Makefile stopped me and told me how to fix the problem.
Checklist:
=> Force a check on controller-gen version

.changelog/2905.txt, charts/consul/templates/server-config-configmap.yaml, charts/consul/test/unit/server-config-configmap.bats
This PR is manually backported from the #2905 and raised against `1.1.x`.
---
- Fixes a bug in parsing the following audit log helm configuration
```yaml
server:
auditLogs:
enabled: true
sinks:
- name: My Sink
type: file
format: json
path: /tmp/audit.json
delivery_guarantee: best-effort
rotate_duration: 24h
rotate_max_files: 15
rotate_bytes: 25165824
```
where `rotate_max_files` and `rotate_bytes` get passed as string inputs to the server configuration file. This PR makes sure to perform special handling for `rotate_max_files` and `rotate_bytes` where they don't get passed with quotes.
**Generated config (Before the fix)**
```json
{
"audit": {
"enabled": true,
"sink": {
"MySink": { …
```
=> Manual backport of #2905 into release/1.1.x

.changelog/2910.txt, acceptance/go.mod, acceptance/go.sum, acceptance/tests/connect/connect_inject_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/go.mod, control-plane/go.sum
Prior to this change, the endpoints controller would list all ACL tokens in a namespace when a service instance is being deleted. This commit improves the performance by querying only the necessary subset of tokens by service-identity / service-name.
- Update the Consul API version
- Modify the endpoints controller to utilize the new API and fetch fewer tokens.
- Ensured that calling `/v1/acl/tokens?servicename=mysvc` does not throw an error on prior versions of Consul 1.16 and simply returns the full list of tokens. This means that updating consul-k8s to use the new query param will still be backwards compatible (because it can still loop and filter on the full list of tokens in-memory, rather than looping on the subset).
- Ensured …
=> [NET-5399] Improve token fetching performance for endpoints controller.

README.md
-  Include Consul API Gateway as a use case. 
- Update links from README. 
Checklist:
=> Update README.md - include Consul API Gateway as a use case

.changelog/2905.txt, charts/consul/templates/server-config-configmap.yaml, charts/consul/test/unit/server-config-configmap.bats
This PR is manually backported from the #2905 and raised against `1.2.x`.
---
- Fixes a bug in parsing the following audit log helm configuration
```yaml
server:
auditLogs:
enabled: true
sinks:
- name: My Sink
type: file
format: json
path: /tmp/audit.json
delivery_guarantee: best-effort
rotate_duration: 24h
rotate_max_files: 15
rotate_bytes: 25165824
```
where `rotate_max_files` and `rotate_bytes` get passed as string inputs to the server configuration file. This PR makes sure to perform special handling for `rotate_max_files` and `rotate_bytes` where they don't get passed with quotes.
**Generated config (Before the fix)**
```json
{
"audit": {
"enabled": true,
"sink": {
"MySink": { …
```
=> Manual backport of #2905 into release/1.2.x

control-plane/connect-inject/common/common.go, control-plane/connect-inject/common/common_test.go, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go, control-plane/subcommand/inject-connect/v2controllers.go
_Follows pattern of iterative review in https://github.com/hashicorp/consul-k8s/pull/2868, and currently targets that branch due to dependence on common code added there_
------------
This PR is part of a series of PRs that add functionality to the V2 Endpoints Controller. For the MVP task to be complete, there will be a few additional changes to resolve TODOs, debounce upsert writes if needed, and add further tests.
- Add the V2 Endpoints Controller
- Add enough logic in the controller to manage Consul Services
- Endpoints controller test framework, borrowed from linked Pod Controller PR (thanks @DanStough!)
How I've tested this PR: Unit tests
How I expect reviewers to test this PR: 👁️‍🗨️👃🏻👁️‍🗨️ 
Checklist:
=> feat: add v2 endpoints controller

acceptance/framework/connhelper/connect_helper.go, acceptance/framework/consul/helm_cluster.go, acceptance/framework/flags/flags.go
In the acceptance tests:
- fix: Deploy apps to a separate namespace in ConnectHelper when not on OpenShift and `-enable-restricted-psa-enforcement` is set
- improvement: Auto-configure the restricted PSA enforcement label when `-enable-restricted-psa-enforcement` is set
Run the following commands:
```
$ make kind-cni
$ ./test-psa-kind.sh -cni
```
Where the `./test-psa-kind.sh` script is the following
<details>
<summary>Test script</summary>
```shell
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export CONSUL_LICENSE=$(cat ~/.consul-ent-license)
export CONSUL_ENT_LICENSE=$CONSUL_LICENSE
for context in kind-dc1 kind-dc2 ; do
kubectl --context $context get ns \
| grep …
```
=> Tests: Fix/improve tests with Restricted PSA enforcement

acceptance/tests/connect/local_rate_limit_test.go, acceptance/tests/fixtures/cases/local-rate-limiting/service-defaults-static-server.yaml
This PR adds a local rate limiting acceptance test to the `connect` folder. It is a follow on to #2844. 
- Successfully ran the acceptance tests locally
:eyes: 
Checklist:
=> Add local rate limiting acceptance test

control-plane/api-gateway/common/diff.go, control-plane/api-gateway/common/diff_test.go, control-plane/api-gateway/common/resources.go, control-plane/api-gateway/controllers/gateway_controller.go
- Add comparison of gateway policies to diffing logic
-
Ran kind cluster to see diffs being generated and sent to consul correctly:
1. run start script from https://github.com/jm96441n/consul-experiments/blob/main/k8s/jwts/README.md
2. shell into the `consul-server-0` pod and run `consul config read -kind api-gateway -name api-gateway` to see the gw without the JWT info
3. run `kubectl apply -f ./consul/gatewaypolicy.yaml` from the root of this above repo
4. again run `consul config read -kind api-gateway -name api-gateway` from the `consul-server-0` shell to see the gw config entry updated with the JWT info
read the code
run the above steps
Checklist:
=> [APIGW] Add comparison of gateway policies to diffing logic

charts/consul/templates/connect-inject-clusterrole.yaml, control-plane/api-gateway/common/diff.go, control-plane/api-gateway/common/helpers.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/controllers/index.go
- Triggers reconciliation and syncing of JWT configuration for an HTTP Route when a RouteAuthFilter is modified.
- Group indices by resource
- Add index for HTTPRoutes referencing RouteAuthFilters
- Add watch for HTTPRoutes referencing RouteAuthFilters
- Add permissions to connect-inject clusterrole
- Compare JWT filters for equality
- Add RouteAuthFilter to resource translator
In a local K8s cluster, I created a Gateway with an HTTP Route that points to a RouteAuthFilter.
When that RouteAuthFilter is created/updated/deleted, I can see that the controller runs to reconcile the change.
I then looked at the configuration in the Consul server. It matches the expected configuration based on the change.
How I expect reviewers to test this …
=> Reconcile Route Auth Filter changes

control-plane/api-gateway/binding/binder_test.go, control-plane/api-gateway/binding/result.go, control-plane/api-gateway/binding/validation.go, control-plane/api-gateway/binding/validation_test.go, control-plane/api-gateway/cache/consul.go, control-plane/api-gateway/cache/consul_test.go, control-plane/api-gateway/common/resources.go, control-plane/api-gateway/common/resources_test.go, control-plane/api-gateway/controllers/gateway_controller.go
- Adds status conditions translation for JWT related issues on Gateways (gateway policy will be a follow up PR)
- Sets up the reconcile workflow for when changes to a referenced JWT provider occur
1. clone the following repo https://github.com/jm96441n/consul-experiments/tree/main/k8s/jwts
1. from the `k8s/jwts` directory run the `start` script, this sets up a k8s cluster with an apigw, 3 services, a httproute, and a jwt provider named "local"
1. after that finishes run `kubectl describe gateway api-gateway` to see all the statuses as valid
1. run `kubectl apply ./consul/gatewaypolicy-okta.yaml`, this will add a policy to the gateway listener that references a non-existent jwt provider named `okta`
1. run `kubectl describe gateway …
=> [NET-5017] APIGW Status Conditions for Gateway for JWT/Reconcile on JWTProvider Changes

.changelog/2952.txt, acceptance/framework/config/config.go, acceptance/framework/consul/helm_cluster.go, acceptance/framework/flags/flags.go, charts/consul/templates/crd-tcproutes.yaml, charts/consul/test/unit/crd-tcproutes.bats, charts/consul/values.yaml
- This adds a first pass of support for running on GKE Autopilot.
- We won't know how things fully work until we are certified with 1.2.2 (next patch release)
- I tried to do this without any helm chart values changes but it would have been considerably more messy than it is now.
- went through an initial acceptance pass with the Autopilot team
- installed consul-k8s using the following helm values:
```
global:
name: consul
logLevel: "debug"
tls:
enabled: false
ingress:
enabled: false
server:
replicas: 1
resources:
requests:
memory: "200Mi"
cpu: "500m"
limits:
memory: "200Mi"
cpu: "500m"
connectInject:
enabled: true
default: true
replicas: 1
transparentProxy:
defaultEnabled: true
apiGateway:
manageExternalCRDs: false …
```
=> GKE Autopilot support

charts/consul/test/unit/telemetry-collector-v2-deployment.bats
- This `bats` test is failing because I disabled admin partitions for V2 deployments in a PR merged around the same time.
How I've tested this PR: running test locally
How I expect reviewers to test this PR: 👀 + CI
=> test(chart): fix telemetry V2 bats

control-plane/connect-inject/common/config.go, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_ent_test.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go, control-plane/go.mod, control-plane/go.sum, control-plane/helper/test/test_util.go, control-plane/subcommand/inject-connect/v2controllers.go
Implement the basic requirements of a new Service Account controller that registers Workload Identities via Consul's V2 API.
Also lightly refactor some of the shared controller data in V2.
Further tests and `TODO`s will be addressed in follow-up changes.
- Add the controller and implement basic CruD logic
- Add tests 
- _Now fully operational since protos were merged_
- Light refactoring of some shared data
How I've tested this PR: Existing tests should continue to pass post-refactoring
Checklist:
=> [NET-5318] feat: add v2 service account controller

control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
The missing constant somehow slipped by in CI. Are we not running v2 tests? Fixing first before digging.
Also fixes test that is breaking due to a protocol defaulting fix in Consul merged today.
=> Fix endpoints controller v2 tests

control-plane/connect-inject/common/common.go, control-plane/connect-inject/common/common_test.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go
- Add requeue logic when the namespace is missing, which could be the case before the namespace controller has reconciled it.
How I've tested this PR: Unit tests on the helper func, but not the controller. We have a task to come back to the enterprise tests. I'm also fine lumping that into this PR.
Checklist:
=> feat(control-plane): v2 backoff on missing namespace

control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
These were necessary to get tests to pass during the merge of several PRs across `consul` and `consul-k8s` but are no longer needed.
- Undo test commenting added in https://github.com/hashicorp/consul-k8s/pull/2960
How I've tested this PR: Local + CI
How I expect reviewers to test this PR: 👓
Checklist:
=> Revert temporary fixes to endpoints v2 tests

.changelog/2796.txt, CHANGELOG.md, acceptance/go.mod, acceptance/go.sum, charts/consul/Chart.yaml, charts/consul/templates/crd-ingressgateways.yaml, charts/consul/templates/crd-servicedefaults.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/api/v1alpha1/ingressgateway_types.go, control-plane/api/v1alpha1/ingressgateway_types_test.go, control-plane/api/v1alpha1/servicedefaults_types.go, control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml, control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml, control-plane/go.mod, control-plane/go.sum, control-plane/version/version.go
=> Prepare release v1.0.10

control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go
- Adding Enterprise tests for the pod controller. These tests are fairly repetitive from a coverage standpoint, but I opted to include them anyway since they are a good contract test with the Consul resource API.
- Refactored some of the existing test helpers to be more suitable for Consul tenancy.
In a (distant) future PR, there is probably a world where I refactor all the Pod controller reconcile tests to use the same `run` function, but in the interest of time and smaller PRs, I opted not to do that here.
**How I've tested this PR**: Running these unit/integration tests
- CI + 👀 
Checklist:
=> test(control-plane): add ENT tests for pod controller

acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml, acceptance/tests/fixtures/bases/v2-multiport-app/service.yaml, control-plane/connect-inject/common/common.go, control-plane/connect-inject/common/common_test.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go
When choosing a Consul service TargetPort (name) in the v2 Endpoints Controller, attempt to find the best match among endpoint container ports when the K8s service target port value is a number.
This bridges an existing gap between Consul (which always expects a Workload port to be named), and K8s (where container ports need not be named, and names are ignored when the K8s service targets by number).
This change will be mostly reverted in a future release once Consul's v2 data model allows for target ports to be a name or number in alignment w/ K8s behavior: [NET-5585](https://hashicorp.atlassian.net/browse/NET-5585)
- Conditionally choose Consul target port based on container port names when K8s target port is numeric.
- Small `nil` safety check for …
=> [NET-5674] v2: Conditional target port when numeric in k8s

acceptance/tests-v2/mesh/mesh_inject_test.go, control-plane/connect-inject/controllers/pod/pod_controller.go
- ~~needed to tweak pod controller to report unhealthy if any container is unhealthy, and healthy only if all containers are healthy~~
- add health status check in acceptance test. This was failing before the pod controller fix and the consul fix here: https://github.com/hashicorp/consul/pull/18958
built images off of this branch and this consul branch with a fix in consul: https://github.com/hashicorp/consul/pull/18958 and the acceptance test passes.
Checklist:
=> add health status syncing check in acceptance test

control-plane/config-entries/controllersv2/meshconfig_controller_test.go
Consul now will default tenancy for traffic permission sources. This PR changes unit tests to account for that
- unit tests
👀 
Checklist:
=> traffic-permissions: fix unit tests to account for mutation hook

acceptance/tests/connect/connect_proxy_lifecycle_test.go, acceptance/tests/connect/local_rate_limit_test.go
- Disabling flaky/non-working tests. Will try and have them fixed this week. I've labeled them slightly differently than the standard because I want to make sure we address these for 1.17
- we are aware mesh_v2 is broken but it is isolated to it's own runner so leaving it enabled, actively being fixed
Checklist:
=> Disable Flaky Acceptance Tests

control-plane/cni/main.go, control-plane/cni/main_test.go
- include the "consul.hashicorp.com/mesh-inject-status" when checking if traffic redirection can be skipped
-
Checklist:
=> support mesh v2 annotations in cni

control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_ent_test.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go
Add backoff for missing Consul NS similar to other v2 controllers.
- Add backoff for Service Account controller as follow-up to https://github.com/hashicorp/consul-k8s/pull/2960
How I've tested this PR: Testing follow-up ticket for non-default NS covers these similar to original PR.
Checklist:
=> [NET-5718] feat(control-plane): ServiceAccount v2 backoff on missing Consul NS

acceptance/tests/wan-federation/wan_federation_test.go
- This PR addresses a flaky test that resulted from performing a CURL without a retry
👀 / pipeline
👀 
Checklist:
=> Fix Flaky Wan Federation Failover Test

acceptance/tests/fixtures/cases/crd-partitions/default-partition-default/kustomization.yaml, acceptance/tests/fixtures/cases/crd-partitions/default-partition-ns1/kustomization.yaml, acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-default/kustomization.yaml, acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-ns1/kustomization.yaml, acceptance/tests/fixtures/cases/crd-peers/default-namespace/kustomization.yaml, acceptance/tests/fixtures/cases/crd-peers/default/kustomization.yaml, acceptance/tests/fixtures/cases/crd-peers/non-default-namespace/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-inject-multiport/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-inject/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-multi-dc/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-namespaces/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-partitions/default-ns-default-partition/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-partitions/default-ns-partition/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-partitions/ns-default-partition/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-partitions/ns-partition/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-peers/default-namespace/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-peers/default/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-peers/non-default-namespace/kustomization.yaml, acceptance/tests/fixtures/cases/static-client-tproxy/kustomization.yaml, acceptance/tests/fixtures/cases/static-server-inject/kustomization.yaml
- Removed some additional uses of deprecated strategic merge from 1.0.x
-
Checklist:
=> fix deprecated kustomize strategic merge

control-plane/go.mod, control-plane/go.sum, control-plane/helper/webhook-configuration/webhook_configuration.go, control-plane/helper/webhook-configuration/webhook_configuration_test.go
- Fix replace statements for proto-public to point to an existing commit
- Fix cert issue on validating webhooks
Ran setup locally using https://github.com/hashicorp/shared-consul-examples/tree/main/k8s/jwts and saw prior to these changes we had webhook cert errors, after we no longer have them
Checklist:
=> [NET-5805] Fixing validating cert webhooks, fixing replace statements for go mod

control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go, control-plane/subcommand/connect-init/command.go
- Fix the path where CA certs are copied to the new `/consul/mesh-init` directory.
I need to figure out a way to backport to the RC.
How I've tested this PR: 👀 
Checklist:
=> fix(v2): ca cert mounting path in mesh-init and dataplane

control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go, control-plane/subcommand/connect-init/command.go
Backport of #3044. This came up in RC testing today.
Need approval from @NicoletaPopoviciu and @wilkermichael to merge.
=> fix(v2): ca cert mounting path in mesh-init and dataplane (#3044)

.github/workflows/jira-pr.yaml
- Change from hub to gh for checking member roles. https://mislav.net/2020/01/github-cli/
Checklist:
=> Change from 'hub' to 'gh' for member checks on JIRA PR syncs

charts/consul/templates/crd-gatewaypolicies.yaml, control-plane/api-gateway/binding/binder.go, control-plane/api-gateway/binding/binder_test.go, control-plane/api/v1alpha1/gatewaypolicy_types.go, control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml
- Fixes status for Gateway Policies when the gateway they reference is removed. Previously we set some default values, now we show no status to mimic the behavior on routes when a gateway they reference cannot be found 
Ran locally
Checklist:
=> [NET-5818] Fix Status for Gateway Policy 

.github/workflows/backport.yml
Setting this environment variable causes the backport assistant to use the merge commit instead of individual commits when backporting a PR. This should prevent the assistant from trying to backport 100s of commits. Nomad uses this flag and it has helped a lot.
From the docs:
> BACKPORT_MERGE_COMMIT: When nonempty, backport-assistant will try to backport the merge commit instead of the individual commits that make of the PR. This will only work if you exclusively use the squash-merge commit
strategy for PRs that get backported.
Checklist:
=> Update backport assistant to use merge commits

.github/workflows/backport.yml
Setting this environment variable causes the backport assistant to use the merge commit instead of individual commits when backporting a PR. This should prevent the assistant from trying to backport 100s of commits. Nomad uses this flag and it has helped a lot.
From the docs:
> BACKPORT_MERGE_COMMIT: When nonempty, backport-assistant will try to backport the merge commit instead of the individual commits that make of the PR. This will only work if you exclusively use the squash-merge commit
strategy for PRs that get backported.
Checklist:
=> Manual backport of update backport assistant to use merge commits to 1.1.x

.github/workflows/backport.yml
Setting this environment variable causes the backport assistant to use the merge commit instead of individual commits when backporting a PR. This should prevent the assistant from trying to backport 100s of commits. Nomad uses this flag and it has helped a lot.
From the docs:
> BACKPORT_MERGE_COMMIT: When nonempty, backport-assistant will try to backport the merge commit instead of the individual commits that make of the PR. This will only work if you exclusively use the squash-merge commit
strategy for PRs that get backported.
Checklist:
=> Manual backport of update backport assistant to use merge commits to 1.0.x

.copywrite.hcl, control-plane/config/crd/external/.yml, control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/gateways.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/grpcroutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/httproutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/referencegrants.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/tcproutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/tlsroutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/udproutes.gateway.networking.k8s.io.yaml
It looks like the `copywrite` CLI deleted the Gateway CRDs we install. This would have broken us if it was released. I regenerated the external CRDs and added them to the Copywrite ignore given they are just pulled in from the Gateway SIG anyway and are not our IP.
- Regenerate external Gateway CRDs
- Remove errant .yml
- Add external CRDs to copywrite ignore
=> Fix Gateway API CRDs

control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller.go
- Add missing meta key per RFC
How I've tested this PR: Unit tests pass
Checklist:
=> [NET-5717] feat(control-plane): v2 add service account name to workload identity meta

acceptance/tests/connect/local_rate_limit_test.go
- This PR fixes the failing local rate limiting tests for tproxy and CNI.
- There was a bug in the test when tproxy was enabled where it would try to reach the `static-server` via `localhost:1234` (explict upstream) instead of using the service name. 
- Locally
- CI
:eyes: 
Checklist:
=> Fix local rate limiting acceptance tests

control-plane/go.mod, control-plane/go.sum, control-plane/helper/test/test_util.go, control-plane/namespaces/namespaces_test.go
- Fixes tests now that Consul doesn't run V1 catalog endpoints in V2 mode.
How I've tested this PR: running locally
How I expect reviewers to test this PR: check CI
=> test: fix tests now that v1 catalog disabled in v2 mode

.changelog/3070.txt, control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go
**Why this change is needed:**
This capability became a requirement for consul-dataplane, which api-gateway uses under the hood, as of https://github.com/hashicorp/consul-dataplane/pull/238. Since the `securityContext` created for each consul-dataplane `Pod` was not requesting the `NET_BIND_SERVICE` capability specifically when deploying onto OpenShift, it was not being granted, and the `Pod` was failing to start with a permission denied error.
- Always add required `NET_BIND_SERVICE` capability to the `securityContext` for each api-gateway `Pod`
- Added unit test coverage verifying `securityContext` is _always_ set appropriately on `Pod`
- @missylbytes tested it live on OpenShift 4.11 and 4.12 clusters, verifying that the …
=> NET-5947 Add NET_BIND_SERVICE capability in security context for api-gateway pod on OpenShift

control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go, control-plane/connect-inject/controllers/endpointsv2/write_cache.go, control-plane/connect-inject/controllers/endpointsv2/write_cache_test.go, control-plane/subcommand/inject-connect/v2controllers.go
Endpoints Controller v2 should not write services every time endpoints change, as this can occur far more frequently and be subject to rapid updates in the case of large clusters or flapping pod health.
Instead, track writes by storing a fingerprint of the written payload along with the Consul resource generation, and compare each potential write and existing Consul resource to them, writing only if a discrepancy is detected or the fingerprint read/compare itself fails (pessimistically fall back to blind writes).
- Add `WriteCache` to Endpoints Controller V2 and use to debounce writes from redundant reconciles
- Add test hook to verify write/no-write scenarios
How I've tested this PR: New tests, acceptance test for V2 should continue to pass
How I expect …
=> [NET-5681] v2: Debounce unnecessary Service writes to Consul

control-plane/config-entries/controllers/configentry_controller_ent_test.go, control-plane/config-entries/controllersv2/meshconfig_controller_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go, control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go, control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go, control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go, control-plane/connect-inject/controllers/serviceaccount/serviceaccount_controller_test.go, control-plane/subcommand/server-acl-init/command_ent_test.go
ENT tests were just turned back on in CI. This revealed some failing test cases. This PR attempts to get everything in working order.
=> Fix ENT Tests Now that They Are Running Again 🏃 

control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go, control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go, control-plane/controllers/configentry_controller_ent_test.go, control-plane/subcommand/server-acl-init/command_ent_test.go
This PR is manually generated from #3077 to be assessed for backporting.
---
ENT tests were just turned back on in CI. This revealed some failing test cases. This PR attempts to get everything in working order.
=> Backport of Fix ENT Tests Now that They Are Running Again 🏃 into release/1.2.x

control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/connect-inject/controllers/peering/peering_acceptor_controller_test.go, control-plane/connect-inject/controllers/peering/peering_dialer_controller_test.go, control-plane/subcommand/server-acl-init/command_ent_test.go
This PR is manually generated from #3077 to be assessed for backporting.
---
ENT tests were just turned back on in CI. This revealed some failing test cases. This PR attempts to get everything in working order.
=> Backport of Fix ENT Tests Now that They Are Running Again 🏃 into release/1.1.x

charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- Remove dev tag so that we don't race against 1.3.x preview image
-
Checklist:
=> remove dev tag

acceptance/tests/partitions/partitions_connect_test.go
- Disable a flaky test until we have a fix
👀 
👀 
Checklist:
=> disable TestPartitions_Connect for CNI due to flake

acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml, acceptance/tests/mesh_v2/mesh_inject_test.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
- Add http probes to acceptance test
- Made fixes in consul here: https://github.com/hashicorp/consul/pull/19257 
Checklist:
=> add probes now that expose paths are supported

acceptance/tests/fixtures/bases/v2-multiport-app/deployment.yaml, acceptance/tests/mesh_v2/mesh_inject_test.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go
- Backport of #3096 
- Adds probe support for tproxy
=> add probes now that expose paths are supported (#3096)

.changelog/3117.txt, charts/consul/Chart.yaml, charts/consul/values.yaml
=> release/1.3.0 - Update Envoy

.changelog/3118.txt, charts/consul/Chart.yaml, charts/consul/values.yaml
=> release/1.3.x - Update Envoy

.changelog/3119.txt, charts/consul/Chart.yaml, charts/consul/values.yaml
=> release/1.2.x - Update Envoy

.changelog/3121.txt, charts/consul/Chart.yaml, charts/consul/values.yaml
=> release/1.0.x - Update Envoy

.changelog/3120.txt, charts/consul/Chart.yaml, charts/consul/values.yaml
=> release/1.1.x - Update Envoy

.copywrite.hcl, control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/gateways.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/grpcroutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/httproutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/referencegrants.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/tcproutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/tlsroutes.gateway.networking.k8s.io.yaml, control-plane/config/crd/external/udproutes.gateway.networking.k8s.io.yaml
**Context**
#3065 removed the copyright headers in the generated external CRD definitions because they are defined by the Gateway API Kubernetes SIG, not by HashiCorp.
#3019 then accidentally re-introduced the headers that were removed due to unfortunate timing.
These headers would have been re-introduced later anyway due to the fact that the exclude path in `.copywrite.hcl` was a little off.
In addition, the comment in `.copywrite.hcl` was a little misleading as the problem is caused by the _tool that generates the copyright headers_ as opposed to the copyright headers themselves.
- Visual inspection
- `$ make generate-external-crds` produces no diff
See above
**Checklist:**
=> Remove copyright headers from external crds

acceptance/tests/mesh_v2/mesh_inject_test.go
- Add a check to the acceptance test that makes sure tokens are deleted.
How I've tested this PR: 🟢 
Checklist:
=> test(v2): check for token deletion in acceptance test

.changelog/3128.txt, control-plane/api-gateway/cache/gateway.go
-dont error on timeouts in gateway 
Setup a consul server and let it sit for >5 minutes, we should not see this error pop up
Checklist:
=> NET-6204- Repeating error log in consul-connect-injector

acceptance/go.mod, acceptance/go.sum, acceptance/tests/cloud/fakeserver_client.go, acceptance/tests/cloud/http_client.go, acceptance/tests/cloud/metrics_validation.go, acceptance/tests/cloud/observability_test.go, acceptance/tests/fixtures/bases/cloud/hcp-mock/deployment.yaml
Impact of this test in reality is minimal as this test currently **does not run** in CI yet, it is used locally for confidence in our Consul Core changes.
1. Rename the test `TestBasicCloud` to `TestObservabilityCloud` and filename`cloud/test_observability.go`
2. Refactor (cleanup) the test with a fakeserver http client object
3. Add a table driven set of scenarios to the Cloud tests for observability:
- Collector exports metrics
- Consul exports metrics
- Periodic refresh: metrics configuration changes, Consul exports metrics with this new config (new filters and label)
- Periodic refresh : disabled metrics, configuration changes to disable metrics, Consul stops exporting metrics
- Ran tests locally using custom docker images for both …
=> [CC 5965] Improve HCP Observability E2E tests and add periodic tests

.github/workflows/build.yml
- Fixes a[ build error ](https://github.com/hashicorp/consul-k8s/actions/runs/6697671470/job/18201205351)because of an extra `actions-docker-build` step
=> build(docker): remove extraneous docker build for UBI

.changelog/3138.txt, .github/workflows/pr.yml, README.md, acceptance/ci-inputs/kind-inputs.yaml, charts/consul/Chart.yaml, charts/consul/test/terraform/gke/main.tf, charts/consul/test/terraform/gke/outputs.tf
- Update kind to 1.28.0
Checklist:
=> Update kubernetes to 1.28.x in release/1.3.0

.release/ci.hcl
Backport of https://github.com/hashicorp/consul-k8s/pull/3036.
This update, moves consul-k8s to use the prepare workflow. This workflow encapsulates several previous workflows, running jobs in parallel to reduce the artifact processing time. See https://hashicorp.atlassian.net/wiki/spaces/RELENG/pages/2489712686/Dec+7th+2022+-+Introducing+the+new+Prepare+workflow for more info.
-
-
Checklist:
=> Update ci.hcl (#3036)

.changelog/3162.txt, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go
- Fixes an extraneous error log when a pod is first scheduled but not yet allocated an IP.
How I've tested this PR: unit tests and manual integration.
Checklist:
=> fix(controller): v2 pod controller error log for missing ip

.changelog/3172.txt, control-plane/config-entries/controllersv2/meshconfig_controller_test.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go, control-plane/subcommand/connect-init/command.go, control-plane/subcommand/mesh-init/command.go
- Don't error out if a token is missing metadata.
- Make sure dataplane is injected with the correct metadata so that the ACL token is created with metadata on login.
- Explicitly call stop when in the init container when re-direction is enabled.
How I've tested this PR: manual K8S testing plus unit tests.
How I expect reviewers to test this PR: 👁️ 👃 👁️ 
Checklist:
=> fix(controller): v2 pod controller errors for acl deletion

control-plane/api-gateway/common/diff.go, control-plane/api-gateway/common/translation.go, control-plane/api-gateway/common/translation_test.go, control-plane/api/mesh/v2beta1/proxy_configuration_types_test.go, control-plane/go.mod, control-plane/go.sum
Some dependencies were previously pinned to utilize unreleased features of the Consul SDK.
This replaces those with the tagged releases containing those features
**Checklist:**
=> NET-5392 Replace dev dependencies w/ latest release tags

control-plane/go.mod, control-plane/go.sum
This is a change that we should only keep until we publish the next version of the `proto-public` submodule. 
- Reference the latest `main` commit for the `proto-public` submodule.
I am now able to reference code that is in the latest version of the submodule.
=> Add replace directive in Go mod for Control Plane so that we pull in the latest Consul submodules

control-plane/api/v1alpha1/routetimeoutfilter_types.go, control-plane/config/crd/bases/consul.hashicorp.com_routetimeoutfilters.yaml
- At some point prior to release the types on filters changed from time.Duration to metav1.Duration
- This is a perfectly valid change, but it modified the behavior of how the CRD was being parsed from as an integer to a string. This feature is not broken, but is currently fragile based on user input. This adds additional safeguards to make sure the user won't accidentally pass anything that will cause the controller to break. 
- https://github.com/hashicorp/consul/pull/19601 This PR updates the docs to match the behavior change as well. 
- Built locally and applied new filters ensuring that the validation failed
- CI passes. 
Checklist:
=> Add validation to account for type change

Makefile, control-plane/Dockerfile.dev
- Adds a new make target and Dockerfile meant for dev builds or skaffold
[See this repo for usage](https://github.com/DanStough/blorp)
Checklist:
=> chore: skaffold build experiment

.changelog/3209.txt, control-plane/subcommand/inject-connect/command.go
Fixes #3205 
- Fixes a bug with the control-plane CLI validation where the consul-dataplane sidecar CPU request is compared against the memory limit instead of the CPU limit.
* Unit tests + 👁️ 
The test only validated failure cases and I didn't think it was the effort to create a new suite that test successful cross-validation of memory and CPU allocations.
Checklist:
=> fix(control-plane): sidecar CPU limit incorrectly validated against CPU request

acceptance/tests/connect/local_rate_limit_test.go
- Fix tests to reduce overhead of exec-ing into pods in CI which was causing rate limiting tests to flake
Passed tests locally
👀
=> Update rate limiting acceptance test to burst requests in one exec

.changelog/3219.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/templates/telemetry-collector-v2-deployment.yaml, charts/consul/test/unit/telemetry-collector-deployment.bats, charts/consul/test/unit/telemetry-collector-v2-deployment.bats, charts/consul/values.yaml
@eddie-rowe reported that he was unable to deploy the Consul Telemetry Collector when `global.cloud.enabled` was false. This should be possible, but right now the telemetry-collector deployment pulls its resourceId out of `global.cloud.resourceId`, which may not be set even when a user is trying to use the collector.
For example, a user may link their cluster to HCP using `externalServers`, while `global.cloud` is empty (because there are no servers in the deployment), but then the `telemetryCollector` will fail to deploy for lack of `global.cloud.resourceId`
The change here is to add a new field, `telemetryCollector.cloud.resourceId` that's settable. If set, it's used in the consul-telemetry-collector deployment
JIRA: https://hashicorp.atlassian.net/browse/CC-6866
Time willing, in a …
=> Add `telemetryCollector.cloud.resourceId` field that works even when `global.cloud.enabled` is false

charts/consul/templates/crd-meshgateways.yaml, control-plane/api/mesh/v2beta1/mesh_gateway_types.go, control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
- Change the scope of the `MeshGateway` CRD to `Cluster` due to the fact that the resource is partition-scoped in Consul and thus should not have a namespace
Using [this setup](https://github.com/nathancoleman/consul-lab/tree/main/k8s/mesh-gateway-v2)
```shell
$ helm upgrade --install consul <path_to_local_main_checkout>/charts/consul --values ./values.yaml
$ kubectl apply -f gateway.yaml
```
Instead of the namespace declaration error previously caused by the `Namespaced` scope, you'll see an error in the controller logs indicating that the create/update function is not yet implemented, which is expected.
```log
ERROR    Reconciler error    {"controller": "meshgateway", "controllerGroup": "mesh.consul.hashicorp.com", …
```
=> NET-6664 Specify cluster scope for MeshGateway CRD

.changelog/3137.txt, control-plane/consul/dynamic.go, control-plane/consul/dynamic_test.go, control-plane/subcommand/server-acl-init/anonymous_token.go, control-plane/subcommand/server-acl-init/anonymous_token_test.go, control-plane/subcommand/server-acl-init/command.go, control-plane/subcommand/server-acl-init/command_test.go, control-plane/subcommand/server-acl-init/connect_inject.go, control-plane/subcommand/server-acl-init/create_or_update.go, control-plane/subcommand/server-acl-init/create_or_update_test.go, control-plane/subcommand/server-acl-init/servers.go
- When the server-acl-init job runs it boostraps ACL tokens and sets a bunch of things on the server up
- It gets the static IPs for the servers, creates a boostrap token and sets a policy using that IP
- Then consul-server-connection-manager runs and other ACLs get set up using the consul client
- Usually this is fine.
- But during upgrades the servers statefulsets can change and thus the server IPs change.
- Our code was set to retry over and over again and would eventually timeout after 10 minutes
- This does not work as it forces customers to run the upgrades several times in hopes that the server IPs do not change.
- I've created a wrapper around the consul client called DynamicClient that allows you to refresh the IPs using …
=> Add refreshes and retries to server-acl-init job

.changelog/3237.txt, cli/go.mod, cli/go.sum
This version is accepted by Prisma/Twistlock, resolving scan results for issue PRISMA-2022-0270. Chosen over later versions to avoid a major version with breaking changes that is otherwise unnecessary.
Note that in practice this is a false positive (see https://github.com/golang-jwt/jwt/issues/258), but we should update the version to aid customers relying on scanners that flag it.
c.f. Consul change here: https://github.com/hashicorp/consul/pull/19705
- Resolves proprietary scanner reported vulnerability.
I've reviewed the changelog from `4.2.0` to `4.5.0` and don't see any evidence of breaking changes.
How I've tested this PR: Unit tests
Checklist:
=> [NET-6617] security: Bump github.com/golang-jwt/jwt/v4 to 4.5.0

.changelog/3219.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/test/unit/telemetry-collector-deployment.bats, charts/consul/values.yaml
This is a cherry-picked backport since the automatically generated one failed (I changed files in that PR that don't exist in 1.1.x release branch): https://github.com/hashicorp/consul-k8s/pull/3238
Checklist:
=> Backport of Add telemetryCollector.cloud.resourceId field that works even when global.cloud.enabled is false into release/1.1.x

charts/consul/templates/connect-inject-clusterrole.yaml, control-plane/api/common/common.go, control-plane/api/mesh/v2beta1/gateway_class_types.go, control-plane/config-entries/controllersv2/gateway_class_controller.go, control-plane/config/rbac/role.yaml, control-plane/subcommand/inject-connect/v2controllers.go
- Adds stub of GatewayClass controller into v2 controllers
👀 
👀
=> NET-6536 Adds stub of GatewayClass controller into v2 controllers

.github/workflows/build.yml
This PR is intended to avoid a [production incident](https://github.com/hashicorp/releng-support/issues/123) where there are duplicate tags (auto-assigned) to UBI images. The entire issue is described [here](https://github.com/hashicorp/crt-workflows-common/pull/407#issue-1999804835), and can be avoided by building `UBI`s (intended for both `Dockerhub` and `Redhat`) in one step.
=> Remove Duplicate UBI Tags

control-plane/api/mesh/v2beta1/mesh_gateway_types.go, control-plane/config-entries/controllersv2/mesh_gateway_controller.go, control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go, control-plane/gateways/builder.go, control-plane/gateways/labels.go, control-plane/gateways/serviceaccount.go, control-plane/gateways/serviceaccount_test.go
When reconciling a `MeshGateway` resource in the v2 API, create/update/delete a corresponding `ServiceAccount`.
Notably, we need to ensure we aren't updating or deleting resources that our controller didn't create simply because they have the expected name.
Added unit test coverage
See above
**Checklist:**
=> NET-6394 Create/update/delete ServiceAccount on MeshGateway reconcile

.changelog/3215.txt, acceptance/go.mod, acceptance/go.sum, acceptance/tests/cloud/basic_test.go, acceptance/tests/cloud/fakeserver_client.go, acceptance/tests/cloud/metrics_validation.go, acceptance/tests/cloud/observability_test.go, charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/templates/telemetry-collector-v2-deployment.yaml, charts/consul/test/unit/telemetry-collector-deployment.bats, charts/consul/test/unit/telemetry-collector-v2-deployment.bats, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
This is a manual backport for the auto-gen one that failed
This backports this PR: https://github.com/hashicorp/consul-k8s/pull/3215
In a previous PR to consul-k8s the cloud observability tests were changed, but that wasn't backported. Because this backport includes acceptance test changes.. I'm also backporting those changes: https://github.com/hashicorp/consul-k8s/pull/2946
=> Backport of Fix consul-telemetry-collector deployments to non-default namespaces into release/1.3.x

.changelog/3137.txt, control-plane/consul/dynamic.go, control-plane/consul/dynamic_test.go, control-plane/subcommand/server-acl-init/anonymous_token.go, control-plane/subcommand/server-acl-init/anonymous_token_test.go, control-plane/subcommand/server-acl-init/command.go, control-plane/subcommand/server-acl-init/command_test.go, control-plane/subcommand/server-acl-init/connect_inject.go, control-plane/subcommand/server-acl-init/create_or_update.go, control-plane/subcommand/server-acl-init/create_or_update_test.go, control-plane/subcommand/server-acl-init/servers.go
Add refreshes and retries to server-acl-init job
-
-
Checklist:
=> Backport of Add refreshes and retries to server-acl-init job (#3137) to release/1.2.x

.changelog/3137.txt, control-plane/consul/dynamic.go, control-plane/consul/dynamic_test.go, control-plane/subcommand/server-acl-init/anonymous_token.go, control-plane/subcommand/server-acl-init/anonymous_token_test.go, control-plane/subcommand/server-acl-init/command.go, control-plane/subcommand/server-acl-init/command_test.go, control-plane/subcommand/server-acl-init/connect_inject.go, control-plane/subcommand/server-acl-init/create_or_update.go, control-plane/subcommand/server-acl-init/create_or_update_test.go, control-plane/subcommand/server-acl-init/servers.go
Add refreshes and retries to server-acl-init job
-
-
Checklist:
=> Backport of Add refreshes and retries to server-acl-init job (#3137) to release/1.1.x

.github/workflows/weekly-acceptance-1-1-x.yml, .github/workflows/weekly-acceptance-1-2-x.yml, .github/workflows/weekly-acceptance-1-3-x.yml
- The 'weekly' jobs were changed to run nightly. Set them back to nightly.
👀 
👀 
Checklist:
=> Set cron jobs for release branches back to weekly

.changelog/3284.txt, control-plane/api/v1alpha1/exportedservices_types.go, control-plane/api/v1alpha1/exportedservices_types_test.go, control-plane/api/v1alpha1/ingressgateway_types.go, control-plane/api/v1alpha1/ingressgateway_types_test.go, control-plane/api/v1alpha1/samenessgroup_types.go, control-plane/api/v1alpha1/samenessgroup_types_test.go, control-plane/api/v1alpha1/servicedefaults_types.go, control-plane/api/v1alpha1/servicedefaults_types_test.go, control-plane/api/v1alpha1/serviceresolver_types.go, control-plane/api/v1alpha1/serviceresolver_types_test.go, control-plane/api/v1alpha1/servicerouter_types.go, control-plane/api/v1alpha1/servicerouter_types_test.go, control-plane/api/v1alpha1/servicesplitter_types.go, control-plane/api/v1alpha1/servicesplitter_types_test.go
When setup as a secondary in WAN federation, Consul migrates config entries from the primary datacenter into the kubernetes secondaries. When the config entries are saved, the `partition` field in the spec of the config entries that have them, gets normalized to the value `default` if it was previously `""` in Consul Enterprise. CRDs for these resources then constantly re-sync themselves since the `MatchesConsul` method, which is responsible for identifying diffs, evaluates the match incorrectly.
To normalize this behavior, the comparison operation for the impacted CRDs has been updated so that when the Partition fields are compared, empty strings are normalized to the value `default`. This should ensure that those two values are considered symmetrical and …
=> Update MatchesConsul to normalize partitions during comparison.

control-plane/config-entries/controllersv2/gateway_class_config_controller.go, control-plane/config-entries/controllersv2/gateway_class_controller.go, control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go
Stop syncing `GatewayClass` and `GatewayClassConfig` into Consul, which has no use for them
- Create a `GatewayClass` and `GatewayClassConfig` resource in k8s, verify they're successfully reconciled
See above
**Checklist:**
=> Stop syncing GatewayClass + GatewayClassConfig into Consul

control-plane/config-entries/controllersv2/mesh_gateway_controller.go, control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go, control-plane/gateways/role.go
This creates proper k8s roles and role-bindings for mesh gateways. ~It does raise a question about how we're modeling mesh gateway CRDs though. Specifically in the `v1` implementation we were creating cluster-scoped roles rather than namespace-scoped. Presumably this is because a mesh gateway should be associated with a installation rather than having the ability to run per-namespace. I know that we've changed the modeling around registered gateway "instances" from v1 to the resource api "workloads", but just wondering if said mesh gateway "workloads" are considered "partition-scoped" or still allow for carrying namespace information.~
~If they allow for namespace information, then we're good on the Role/RoleBinding approach, otherwise, I think most of these …
=> Create role and role binding for mesh gateways

charts/consul/templates/gateway-cleanup-job.yaml
- Ran make lint to make sure the yaml file was formatted correctly with the new addition 
- Installed chart locally onto a kind cluster to ensure it still installs appropriately. 
- BATs helm tests pass as expected
- If desired, reviewer can check out branch, and run the following commands to do a helm install locally
```
kind create cluster 
helm install consul $PATH_TO_CONSUL_K8s/charts/consul -n consul --create-namespace
```
Checklist:
=> NET-6575- Add ConfigMap volume mount to gateway cleanup job

charts/consul/templates/connect-inject-clusterrole.yaml, control-plane/api/common/common.go, control-plane/api/mesh/v2beta1/mesh_configuration_types.go, control-plane/config-entries/controllersv2/mesh_configuration_controller.go, control-plane/config/rbac/role.yaml, control-plane/subcommand/inject-connect/v2controllers.go
Adds basic stubbing/syncing of "MeshConfiguration" resources to Consul.
Manually created a CRD and saw it propagate to Consul:
```yaml
apiVersion: mesh.consul.hashicorp.com/v2beta1
kind: MeshConfiguration
metadata:
name: configuration
```
and then with `consul resource list mesh.v2beta1.meshconfiguration`:
```json
{
"resources": [
{
"data": {},
"generation": "01HGXDYZTYK20821Q9Z6JMT9YS",
"id": {
"name": "configuration",
"tenancy": {
"partition": "default",
"peerName": "local"
},
"type": {
"group": "mesh",
"groupVersion": "v2beta1",
"kind": "MeshConfiguration"
},
"uid": "01HGXDYZTYK20821Q9Z4BJPSHR"
},
"metadata": {
"external-source": "kubernetes"
},
"version": "154"
}
]
}
```
Checklist:
=> Stub mesh configuration resource controller

charts/consul/templates/gateway-cleanup-clusterrole.yaml, charts/consul/templates/gateway-cleanup-job.yaml, control-plane/subcommand/gateway-cleanup/command.go, control-plane/subcommand/gateway-cleanup/command_test.go
- Add v2 resources to gateway cleanup job
- Local kind helm install/uninstall while running
```kubectl logs job/consul-consul-gateway-cleanup -n consul```
In order to make sure the cleanup job didn't actually error.
- Updated unit test to cover v2 config map method
- Local kind helm install/uninstall from this branch
- CI passes
Checklist:
=> Net 6575- Modify Gateways Cleanup Job to cleanup v2 resources

acceptance/tests/peering/peering_connect_namespaces_test.go, acceptance/tests/peering/peering_connect_test.go, acceptance/tests/peering/peering_gateway_test.go
- test was performing the wrong connection check, since http should be checking for a '403'
- added cluster creation in parallel to speed up peering tests
-
-
=> fixed incorrect test validation with peering test

.changelog/3347.txt, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
This introduces an annotation `consul.hashicorp.com/proxy-config-map` that allows for generically setting data in the opaque config map for proxy service registrations. Use of this annotation is not encouraged in most situations, but it is necessary for certain circumstances.
Notably, this new annotation allows users to specify the `xds_fetch_timeout_ms` configuration during service registration, which is sometimes needed by proxies with a large number of upstreams.
=> Add `consul.hashicorp.com/proxy-config-map` annotation.

.changelog/3307.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
- When deregistering a service in Consul we would leave the virtual node sitting around
- This PR checks if a node has an empty service list and if so deletes 
- manually testing in kind to make sure nodes are cleaned up
- unit tests. The enpoints controller tests have a lot of coverage for service interactions.
👀 
Checklist:
=> [NET-6588] Remove abandoned virtual nodes from Consul Catalog

.changelog/3315.txt, charts/consul/templates/connect-inject-deployment.yaml, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml
This reintroduces #3218 with an additional small change to ensure Helm template validation is applied with necessary short-circuits. I've added the fix as a separate commit to simplify review based on the original.
Original PR description below:
---------------------------------
If we set `externalServers.hosts` to the public or private address of an HCP-manged cluster, we run into the following because we're hardcoding `-tls-server-name` to `server.{{ .Values.global.datacenter}}.{{ .Values.global.domain}}`:
> 2023-11-10T01:32:31.386Z [ERROR] consul-server-connection-manager: connection error: error="rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for …
=> Add validation that externalServers.hosts is not set to HCP-managed cluster's addresses when global.cloud.enabled

charts/consul/templates/gateway-resources-configmap.yaml, control-plane/config-entries/controllersv2/mesh_gateway_controller.go, control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go, control-plane/gateways/deployment.go, control-plane/gateways/deployment_test.go
- Add support for priorityClassName to deployment generation
Ran a local install with the following consul values set on the helm.
```
global:
tls:
enabled: true
imageK8S: consul-k8s-control-plane-dev:gauntlet #or whatever you're tagging your local build image as
logLevel: "debug"
experiments:
- "resource-apis"
server:
replicas: 1
ui:
enabled: false
meshGateway:
enabled: true
priorityClassName: "hellotest"
```
Ran
```kubectl get deployments mesh-gateway -n consul -o yaml```
```apiVersion: apps/v1
kind: Deployment
... <removed for brevity> 
priorityClassName: hellotest
```
- Local install
- Looking over
- CI passes
=> Net 6742 - consul k8s mgw deployment priority class name support

control-plane/gateways/deployment.go, control-plane/subcommand/gateway-resources/command_test.go
- Add support for replicas config for meshgw v2 deployments
- currently draft because base branch https://github.com/hashicorp/consul-k8s/pull/3363 has an open PR
- :eye: 
- ran tests
- deployed kind cluster with replicas, saw them show up on deployment
- :eye: 
- ran tests
- deployed kind cluster with replicas, saw them show up on deployment
=> [NET-6721] Replicas support for MeshGW v2 Deployments

control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/gateways/deployment.go, control-plane/gateways/deployment_test.go
By setting the gateway-kind annotation on the Pods for a MeshGateway, we indicate to the Pod controller in consul-k8s that the Pod represents a mesh gateway (or api/terminating in the future). The Pod controller then passes this along as metadata on the Workload that it creates in Consul.
The end result is that the sidecar and gateway proxy controllers can determine which Workloads they should generate ProxyStateTemplates for and which should be left to the other.
When combined with https://github.com/hashicorp/consul/pull/19902, the sidecar proxy controller should skip any Workloads created for a `MeshGateway` when `meshGateway.enabled=true` and `experiments: [resource-apis]` in values.yaml.
See above
=> NET-6663 Set gateway-kind in Workload metadata when it represents a xGateway Pod

charts/consul/templates/crd-gatewayclassconfigs.yaml, charts/consul/templates/gateway-resources-configmap.yaml, control-plane/api/mesh/v2beta1/gateway_class_config_types.go, control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml, control-plane/gateways/deployment.go, control-plane/subcommand/gateway-resources/command_test.go
- Adds host network support for v2 mesh gw deployments
-
- ran local kind cluster with hostNetwork enabled
- tests
- :eye: 
- run tests
=> [NET-6787] HostNetwork support for meshgw deployments

control-plane/api/mesh/v2beta1/gateway_class_config_types.go, control-plane/config-entries/controllersv2/mesh_gateway_controller.go, control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go, control-plane/gateways/annotations.go, control-plane/gateways/service.go, control-plane/gateways/service_test.go, control-plane/subcommand/gateway-resources/command.go
When reconciling a MeshGateway resource in the v2 API, create/update/delete a corresponding Service.
- Unit Test in code for review
**Manual Test Steps Below**
- Checkout and build consul-k8s using this branch;
- Run `make control-plane-dev-docker` to ensure you're using a `local` control-plane-dev image with changes
- [If required] Update consul values.yaml with ` imageK8S: consul-k8s-control-plane-dev:local`
- Then do a local kind helm install/uninstall of Consul
- Add `v2beta1` gateway resource
**RESULT**
```
$ k get gatewayclass.mesh -A
gateway-class2                               32m
```
Then get the gatewayclass.mesh resource yaml output
```
apiVersion: mesh.consul.hashicorp.com/v2beta1
kind: GatewayClass
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: | …
```
=> NET-6393: Create/update/delete Service on MeshGateway reconcile

acceptance/tests/sameness/sameness_test.go
Update test to assert the fixed behavior of PR #7773 in Consul Enterprise.
https://github.com/hashicorp/consul/pull/19970
=> Update test to match PreparedQuery SamenessGroup bugfix.

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, cli/version/version.go, control-plane/version/version.go
- Updates the changelog
- Preps for the release 1.3.1
=> Prepare 1.3.1 for release

control-plane/connect-inject/common/common.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_ent_test.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go, control-plane/gateways/deployment.go, control-plane/gateways/deployment_test.go
The `Pod` controller currently only creates `Workloads` in Consul for mesh-injected `Pods`.
`Pods` for xGateways are not mesh-injected because it doesn't make sense to add a proxy sidecar to a `Pod` that's already running a proxy as its primary workload; however, they still require `Workloads` to be registered in Consul so that we can generate `ProxyStateTemplates` for them (in a future PR).
This PR modifies the `Pod` controller to create `Workloads` in Consul for xGateway pods as well, relying on the fact that a known annotation specifying the `gateway-kind` is added to all v2 xGateway `Pods`.
Notably, this also results in a `ProxyConfiguration` being created for the mesh gateway workload, and I disabled the health endpoint override functionality by adding a predefined annotation to the …
=> [NET-6938] Create workloads in Consul for mesh gateway pods

Makefile
This make command did not get backported to `release/1.1.x`. I need to add it to reset the branch for dev.
=> Add `prepare-release-dev` make command to `release/1.1.x`

.changelog/3362.txt, control-plane/config-entries/controllers/configentry_controller.go, control-plane/config-entries/controllers/controlplanerequestlimit_controller.go, control-plane/config-entries/controllers/exportedservices_controller.go, control-plane/config-entries/controllers/finalizer_patch.go, control-plane/config-entries/controllers/finalizer_patch_test.go, control-plane/config-entries/controllers/ingressgateway_controller.go, control-plane/config-entries/controllers/jwtprovider_controller.go, control-plane/config-entries/controllers/mesh_controller.go, control-plane/config-entries/controllers/proxydefaults_controller.go, control-plane/config-entries/controllers/samenessgroups_controller.go, control-plane/config-entries/controllers/servicedefaults_controller.go, control-plane/config-entries/controllers/serviceintentions_controller.go, control-plane/config-entries/controllers/serviceresolver_controller.go, control-plane/config-entries/controllers/servicerouter_controller.go, control-plane/config-entries/controllers/servicesplitter_controller.go, control-plane/config-entries/controllers/terminatinggateway_controller.go
Issue: ArgoCD will flap when configured with replace mode, which causes zero values to get defaulted and the applied config to differ from the state in K8s.
This is how the ArgoCD flapping problem happens:
1. Argo triggers a replace
2. A replace operation will remove all finalizers, including the one that we add to all config entries in the config entry controller
3. This triggers our config entry controller to run a reconcile to add the finalizer
4. When our controller adds the finalizer, it updates the whole object, causing the zero values to get defaulted. (json omit empty does not kick in because the object is not being serialized/deserialized like it does when you first apply the config).
This PR: 
- Only patches finalizers in the metadata of the CRD, rather than updating the entire …
=> [Net-5510][Net-5455]: CRD controller should only patch the finalizer in the metadata of a CRD, rather than the whole object

control-plane/gateways/deployment_test.go, control-plane/gateways/service_test.go
- Adds chart related labels for mesh gateway deployments
-
- ran tests
- ran local kind cluster and checked config
- :eye: 
- run tests
- run local kind cluster and checked config
=> [NET-6809] Add chart related labels for mesh gateway deployments

control-plane/build-support/functions/10-util.sh
- Add automation to generate a compatibility note in the changelog on `.0` releases
- Fix a minor bug with prerelease version in non-prerelease changelog entries
Results [here](https://github.com/hashicorp/consul-k8s/commit/ea6f2314a05c3c4c5310b2c38d29c98c901721f8#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR41) from running with `1.3.0` and then `1.3.1` env vars:
```shell
export CONSUL_K8S_RELEASE_VERSION=1.3.0
export CONSUL_K8S_PRODUCT_VERSION=1.3.0
export CONSUL_K8S_RELEASE_BRANCH=release/1.3.x
export CONSUL_K8S_RELEASE_DATE="December 20, 2099"
export CONSUL_K8S_LAST_RELEASE_GIT_TAG="v1.2.2"
export CONSUL_K8S_CONSUL_VERSION=1.17.0
export CONSUL_K8S_CONSUL_DATAPLANE_VERSION=1.3.0
make prepare-release
export CONSUL_K8S_RELEASE_VERSION=1.3.1
export …
```
=> chore: add compatibility note to .0 changelogs

.changelog/3418.txt, control-plane/Dockerfile
- Dockerfile: bump up to `ubi-minimal:9.3` to remediate vulnerabilities. The current `ubi-minimal:9.2` image is not actively maintained and CVEs fixes are not backported.
=> Dockerfile: update to ubi-minimal:9.3

.changelog/3418.txt, control-plane/Dockerfile
- Dockerfile: backport #3418 to 1.1.x
---
<details>
- 0c0c828534fe62f5e831fcc5051ccd83ed5c1305  - ccdb253121e3dd43e809734fd6df53cfd76a0794  - 7223f519f10966db9fcf105c507fe58b3a32a9ed  - 6b26bf347e81f3222364fda9f4983be8d7c358fc  - 40cbf0598bcd629e0ce2855610ca0d79f9230e5f 
</details>
=> Dockerfile: backport #3418 to 1.1.x

charts/consul/templates/gateway-resources-configmap.yaml, charts/consul/test/unit/gateway-resources-configmap.bats, charts/consul/values.yaml, control-plane/gateways/deployment.go, control-plane/gateways/deployment_test.go
- Add wanAddress configuration to the configmap
- Set the annotations on the mesh gateway CRD
- Patch through the annotations from the Mesh Gateway
I added BATs and I ran a deployment with the following configuration:
```yaml
global:
imageK8S: consul-k8s-control-plane:local
experiments:
- resource-apis
meshGateway:
enabled: true
ui:
enabled: false
```
Which produced a mesh gateway with the correct configuration.
=> Support WAN Address Annotations

acceptance/tests/connect/local_rate_limit_test.go
- This PR disables the local rate limiting tests for cloud providers. This test is time sensitive and was consistently flaking on cloud. This doesn't test any features specific to cloud, so I think it is safe to disable this in our nightlies.
-
=> disable TestConnectInject_LocalRateLimiting for cloud provider tests

.changelog/3440.txt, control-plane/api-gateway/cache/consul.go
- include namespace/partition on request context when deleting resources from consul
Ran examples here https://github.com/jm96441n/consul-experiments/tree/main/k8s/http-route-bug
1. make a build of the main branch of this repo by running `make control-plane-dev-docker`
1. clone down this repo https://github.com/jm96441n/consul-experiments/tree/main/k8s/http-route-bug 
1. run the `start` script in the repo
1. once resources finish spinning up check that the route exists by running ` consul config read -kind http-route -name backend-route-default -namespace=app`
1. delete the route by running `kubectl delete -f ./resources/route.yaml`
1. run ` consul config read -kind http-route -name backend-route-default -namespace=app` again to see the route still exists
1. tear down the kind cluster
1. …
=> [NET-6702] HTTPRoute not being deleted from consul bug

control-plane/gateways/deployment.go, control-plane/gateways/deployment_init_container.go, control-plane/gateways/deployment_test.go
- Make initConfig an associated function to the builder
- Pass in init container resources if they are set
- Use values from the builder now that initContainer is associated with it
Updated the happy path unit test to exercise the resource setting.
=> Pass gateway init resources from config to the container

acceptance/framework/consul/helm_cluster.go
- We often have acceptance tests that fail because resources are left behind. At this time I do not trust that helm delete is deleting everything it created.
- This is a first pass attempt to nuke all the helm things for a release.
- Ran through acceptance tests (all green)
👀
=> Add acceptance test cleanup

.changelog/3322.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/namespaces/namespaces.go
Rather than fetching all nodes in a cluster then listing services per-node, fetch all service instances directly by name.
_Diff best viewed with [?w=1](https://github.com/hashicorp/consul-k8s/pull/3322/files?diff=unified&w=1)_
This change is motivated by customers with larger K8s clusters (node counts) seeing performance issues (slow to execute, high CPU util on Consul server) with reconciles.
This should generally reduce the cost of deregistration in endpoints controller reconciles (in terms of network calls) from N calls (N=node count) to 3-6 calls regardless of K8s cluster size:
* 1-2 calls to fetch service names matching meta (default NS + non-default NS if applicable)
* For the service and its proxy (2 catalog entries), 1-2 calls to fetch service instances (default NS + non-default …
=> [NET-6581] perf: Fetch services once rather than per-node on deregister

acceptance/tests/cloud/observability_test.go
- In the cloud observability tests, set the namespace in the query parameters only if enterprise is enabled.
Ran the tests with a Community Edition version of Consul and without `-enable-enterprise`:
```
--- PASS: TestObservabilityCloud (357.07s)
--- PASS: TestObservabilityCloud/default_namespace_and_partition (230.08s)
--- PASS: TestObservabilityCloud/default_namespace_and_partition/collectorExportsMetrics (109.46s)
--- PASS: TestObservabilityCloud/default_namespace_and_partition/consulPeriodicRefreshUpdateConfig (28.12s)
--- PASS: TestObservabilityCloud/default_namespace_and_partition/consulPeriodicRefreshDisabled (0.01s)
--- PASS: TestObservabilityCloud/default_namespace_and_partition;_secure (126.99s)
--- SKIP: TestObservabilityCloud/default_namespace_and_partition;_secure/consulPeriod …
```
=> Fix to support non-enterprise HCP observability testing 

charts/consul/templates/crd-meshgateways.yaml, charts/consul/templates/gateway-resources-configmap.yaml, control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml, control-plane/gateways/service.go, control-plane/gateways/service_test.go, control-plane/go.mod, control-plane/go.sum
- Add protocol to listener config 
Spun up locally and ensured the mesh gateway service had the following values correctly set
```  ports:
- name: wan
nodePort: 31220
port: 443
protocol: TCP
targetPort: 8443
```
- Local install, look over
=> Net 7189 Consul k8s add protocol to listeners on the mesh gateway

.changelog/2962.txt, .changelog/3000.txt, acceptance/ci-inputs/aks_acceptance_test_packages.yaml, acceptance/ci-inputs/eks_acceptance_test_packages.yaml, acceptance/ci-inputs/gke_acceptance_test_packages.yaml, acceptance/ci-inputs/kind_acceptance_test_packages.yaml, acceptance/tests/example/main_test.go, acceptance/tests/server/main_test.go, acceptance/tests/server/server_test.go, charts/consul/templates/_helpers.tpl, charts/consul/templates/server-config-configmap.yaml, charts/consul/templates/server-disruptionbudget.yaml, charts/consul/test/unit/server-config-configmap.bats, charts/consul/test/unit/server-disruptionbudget.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/values.yaml
When leave_on_terminate=false (default), rolling the statefulset is
disruptive because the new servers come up with the same node IDs but
different IP addresses. They can't join the server cluster until the old
server's node ID is marked as failed by serf. During this time, they continually
start leader elections because they don't know there's a leader. When
they eventually join the cluster, their election term is higher, and so
they trigger a leadership swap. The leadership swap happens at the same
time as the next node to be rolled is being stopped, and so the cluster
can end up without a leader.
With leave_on_terminate=true, the stopping server cleanly leaves the
cluster, so the new server can join smoothly, even though it has the
same node ID as the old server. This increases the …
=> Set leave_on_terminate=true for servers and hardcode maxUnavailable=1

.changelog/3437.txt, cli/cmd/proxy/list/command.go, cli/cmd/proxy/list/command_test.go, control-plane/api-gateway/common/labels.go, control-plane/api-gateway/gatekeeper/deployment.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
- Add annotations to the API Gateway that ensure 
- Local unit tests
- Local kind install
- Local kind install
- CI Passes
=> Net 6289 improve consul api gateway annotations

charts/consul/templates/crd-meshgateways.yaml, charts/consul/templates/gateway-resources-configmap.yaml, control-plane/api/mesh/v2beta1/mesh_gateway_types.go, control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml, control-plane/gateways/deployment_test.go, control-plane/go.mod, control-plane/go.sum, control-plane/subcommand/gateway-resources/command_test.go
- import the workload selector via go.mod  to be accessible in consul-k8s. See proto PR [here](https://github.com/hashicorp/consul/pull/20159) in Consul
- Ensure workloadSelector field is added to gateways CRD
local install and uninstall of Consul
=> NET-7179: Update MeshGateway to use new proto with workload selector

control-plane/Dockerfile
- armv6 was deprecated from the base golang docker images for 1.21.x so force golang:<version>-alpine tag instead
- consul-dataplane already uses the -alpine image.
👀 
:eyes:
=> Use golang -alpine image when building go-discover

.github/workflows/build.yml, control-plane/Dockerfile
- Manual backport of #3490 into release/1.3.x
- added in a dockerfile change that was breaking CRT on main instead of doing a separate PR.
CI
👀
=> Backport of CRT build failing for Go into release/1.3.x

.github/workflows/build.yml, control-plane/Dockerfile
- Manual backport of #3490 into release/1.2.x
- added in a dockerfile change that was breaking CRT on main instead of doing a separate PR.
CI
:eyes:
=> Backport of CRT build failing for Go into release/1.2.x

.github/workflows/build.yml, control-plane/Dockerfile
- Manual backport of #3490 into release/1.1.x
- added in a dockerfile change that was breaking CRT on main instead of doing a separate PR.
CI
:eyes:
=> Backport of CRT build failing for Go into release/1.1.x

.changelog/3502.txt, charts/consul/templates/crd-servicerouters.yaml, control-plane/api/v1alpha1/servicerouter_types.go, control-plane/api/v1alpha1/servicerouter_types_test.go, control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml, control-plane/go.mod, control-plane/go.sum
Consul-k8s updates for https://github.com/hashicorp/consul/pull/19647
=> Add CaseInsenstive field to ServiceRouter.

control-plane/controllers/resources/consul_resource_controller_ent_test.go, control-plane/controllers/resources/consul_resource_controller_test.go
=> Update tests of  traffic permission deny action to enterprise only

control-plane/gateways/constants.go, control-plane/gateways/deployment_dataplane_container.go, control-plane/gateways/deployment_test.go, control-plane/gateways/gateway_config.go, control-plane/subcommand/inject-connect/v2controllers.go
- Adjust envars for consul-dataplane to use the `-proxy-` args instead of the deprecated `-service-` args. This is important because it's either-or in consul-dataplane [here](https://github.com/hashicorp/consul-dataplane/blob/b80f2bf4a4876789ae0b524275b8201e692b7177/cmd/consul-dataplane/config.go#L270-L288) which is biting us because we set the `-proxy-id` arg today which pushes into the initial `if` case and ignores our `-service-*` flags.
- Add support for disabling server watch, which is used the the consul-servers are behind a load balancer, such as when a second admin partition communicates via the `expose-consul-servers` K8s `Service`.
Deploy a second admin partition with `externalServers.skipServerWatch: true` in your `values.yaml`. Verify that the arg is set on the mesh gateway's …
=> [NET-7492, NET-7495] Support -server-watch-disabled, use -proxy-* args instead of -service-*

control-plane/connect-inject/common/common.go, control-plane/connect-inject/common/common_test.go, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go, control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go, control-plane/connect-inject/controllers/pod/pod_controller.go, control-plane/connect-inject/controllers/pod/pod_controller_test.go, control-plane/connect-inject/webhookv2/mesh_webhook.go, control-plane/connect-inject/webhookv2/mesh_webhook_test.go
- [This change in consul](https://github.com/hashicorp/consul/pull/20371) involves now interpreting whether xRoute/FailoverPolicy/DestinationPolicy resource service references use either the service port (virtualPort in consul) or service target port (targetPort in consul). To make this decision unambiguously:
> This change updates our interpretation of these reference fields/keys (parent, backend, destination), s.t.:
>
> * A numeric value will be exclusively interpreted to indicate a ServicePort.virtual_port
> * A non-numeric value will be exclusively interpreted to indicate a ServicePort.target_port (this supports VMs/Nomad and other cases where network virtual ports are not used, and port names are expected to be in reference to workload ports, not service ports)
- If a K8s service …
=> [NET-7534] v2: Make port names in consul-k8s compatible with NET-5586

control-plane/controllers/resources/mesh_gateway_controller_test.go
- fixes tests for meshgw that were broken by adding https://github.com/hashicorp/consul/pull/20425 validation
ran tests
=> [NET-6417] Fix meshgw tests

.github/workflows/weekly-acceptance-1-4-0-rc1.yml, .github/workflows/weekly-acceptance-1-4-x.yml
=> add nightly for rc branch

charts/consul/templates/crd-apigateways.yaml, charts/consul/templates/crd-trafficpermissions.yaml, control-plane/api/mesh/v2beta1/api_gateway_types.go, control-plane/config/crd/bases/auth.consul.hashicorp.com_trafficpermissions.yaml, control-plane/config/crd/bases/mesh.consul.hashicorp.com_apigateways.yaml
Running `make ctrl-manifests` returns the following error on `main` branch
```     
make ensure-controller-gen-version
Found correct version: Version: v0.12.1
cd control-plane; /Users/anitaakaeze/go/bin/controller-gen "crd:ignoreUnexportedFields=true,allowDangerousTypes=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/anitaakaeze/hashicorp/consul-k8s/control-plane/api/mesh/v2beta1/api_gateway_types.go:46:2: encountered struct field "" without JSON tag in type "APIGatewayStatus"
/Users/anitaakaeze/hashicorp/consul-k8s/control-plane/api/mesh/v2beta1/api_gateway_types.go:47:2: encountered struct field "Addresses" without JSON tag in type "APIGatewayStatus"
/Users/anitaakaeze/hashicorp/consul-k8s/control-plane/api/mesh/v2beta1/api_gatew …
```
=> Add json tags to api-gateway types

control-plane/controllers/resources/mesh_gateway_controller.go, control-plane/gateways/deployment.go, control-plane/gateways/deployment_test.go, control-plane/gateways/service.go, control-plane/gateways/service_test.go
- Trigger a reconcile of the `MeshGateway` resource when a related `GatewayClassConfig` changes
- Trigger a reconcile of the `MeshGateway` resource when a related `GatewayClass` changes
=> [NET-7656] Add GatewayClassConfig watch for MeshGateway controller

.changelog/3548.txt, charts/consul/templates/api-gateway-controller-deployment.yaml, charts/consul/templates/client-daemonset.yaml, charts/consul/templates/connect-inject-deployment.yaml, charts/consul/templates/create-federation-secret-job.yaml, charts/consul/templates/enterprise-license-job.yaml, charts/consul/templates/gossip-encryption-autogenerate-job.yaml, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/templates/partition-init-job.yaml, charts/consul/templates/server-acl-init-job.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/templates/sync-catalog-deployment.yaml, charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/templates/telemetry-collector-v2-deployment.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/templates/tls-init-job.yaml, charts/consul/templates/webhook-cert-manager-deployment.yaml, charts/consul/test/unit/api-gateway-controller-deployment.bats, charts/consul/test/unit/client-daemonset.bats
Change `/bin/sh -ec "<command>"` to
`/bin/sh -ec "exec <command>"`. Adding `exec` ensures that `<command>` is not executed as a child process but replaces the `/bin/sh` process. This ensure that `<command>` receives any signals.
Specifically this is an issue when attempting to trap SIGTERMs as part of graceful pod shutdown. Without this change, we weren't receiving any signals because they aren't passed down by `/bin/sh -c`.
=> Ensure signals are passed to commands

.changelog/3531.txt, control-plane/api-gateway/common/helm_config.go, control-plane/api-gateway/gatekeeper/deployment.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/init.go, control-plane/subcommand/inject-connect/command.go
This PR is manually generated from #3531 to be assessed for backporting due to the inclusion of the label backport/1.2.x.
---
Apply the existing `connectInject.initContainer.resources` value to the init container for API gateway `Pods`.
Create an API Gateway having installed Consul into Kubernetes w/ the above field set in your `values.yaml`.
See above
---
<details>
- 9d89a7c101ca8550e6c68aeaf70f627d951bccb9  - 8a09d6e6ed88d3548ba402dc4e5ceb3c3b14d44f  - 0890d599bfc1f560196cdd9f0e93d47a7aab2d33 
</details>
=> Backport of [NET-6465] Respect connectInject.initContainer.resources for v1 API gateways into release/1.2.x

control-plane/api/mesh/v2beta1/api_gateway_types.go, control-plane/api/mesh/v2beta1/mesh_gateway_types.go, control-plane/controllers/resources/api-gateway-controller.go, control-plane/controllers/resources/gateway_controller_setup.go, control-plane/controllers/resources/gateway_indices.go, control-plane/controllers/resources/mesh_gateway_controller.go, control-plane/subcommand/inject-connect/v2controllers.go
- adds indices onto the gateway resources in k8s for faster lookups as well as easier to read code
- makes the setup for a gateway controller generic so it can be reused across gateway types
- ran mesh gateways before and after, all works the same
=> [NET-7156] Gateways Controllers Reusability

control-plane/api-gateway/gatekeeper/deployment.go, control-plane/api-gateway/gatekeeper/deployment_test.go
> [!NOTE]
> This is a followup to #3531 
When there's an existing `Deployment` in the cluster and we're comparing it against our desired state to determine if there's an update to be made, the comparison needs to consider whether the resources for the init container(s) have been updated.
1. Create a `Gateway` on a cluster having `helm install`-ed with or without a value for `.Values.connectInject.initContainer.resources`.
2. Change the value of `.Values.connectInject.initContainer.resources` and `helm upgrade`
3. Verify that cycling the gateway `Pod` triggers an update to the resources of the init container to match your values. This cycling requirement is consistent with how regular service Deployments in Consul mesh behave due to needing some action to trigger the reconciliation …
=> [NET-6465] Consider init container resources when determining if existing + desired deployments are equal

control-plane/go.mod, control-plane/go.sum
This is a followup to #3559 and https://github.com/hashicorp/consul/pull/20523 which removed the usage of and the model of `GatewayClass` and `GatewayClassConfig`, respectively.
🤖 tests pass
See above
=> [NET-7657] Consume version of proto-public with GatewayClass[Config] removed

control-plane/build-support/functions/10-util.sh
- Previous formatting (example), was not being rendered correctly 
_ Note: Consul K8s 1.4 is compatible with Consul 1.18 and Consul Dataplane 1.4. Refer to our [compatibility matrix](https://developer.hashicorp.com/consul/docs/k8s/compatibility) for more info._
- New formatting (example) 
> NOTE: Consul K8s 1.4.x is compatible with Consul 1.18.x and Consul Dataplane 1.4.x. Refer to our [compatibility matrix](https://developer.hashicorp.com/consul/docs/k8s/compatibility) for more info.
=> release: Update 10-util.sh to adjust formatting

Makefile, control-plane/build-support/scripts/mod_tidy.sh
This adds a script and a make target for running `go mod tidy` recursively. It also adds a new target that reports back an error if go mod tidy needs to be run. This is useful for CI.
I committed a change locally of an incorrect `go.mod` file then ran the script with and without the check. Verified check behaviour returns an error.
👀
=> add make target script

.github/workflows/lint.yaml
- This PR adds linting back to the source repo. This has some advantages as it allows for the linting workflow to mark errors in the `files changed`
=> add linting back

acceptance/ci-inputs/aks_acceptance_test_packages.yaml, acceptance/ci-inputs/eks_acceptance_test_packages.yaml, acceptance/ci-inputs/gke_acceptance_test_packages.yaml, acceptance/ci-inputs/kind_acceptance_test_packages.yaml
(cherry picked from commit f8f416da0c3ec5a65853a1609f71a794b00b09c4)
-
-
=> added comment about cloud test package (#3471)

charts/consul/templates/gateway-resources-configmap.yaml, charts/consul/test/unit/gateway-resources-configmap.bats
- Modifed gatewayconfig map to respect apiGateway helm values
- Because the code created for meshgateway was generic enough so long as the gateway parses correctly, no further updates needed to be made
- Local install with the following minimal helm values
```
global:
tls:
enabled: true
imageK8S: consul-k8s-control-plane-dev:gauntlet #or whatever you're tagging your local build image as
logLevel: "debug"
experiments:
- "resource-apis"
server:
replicas: 1
ui:
enabled: false
apiGateway:
managedGatewayClass:
replicas:
default: 1
```
- Local install, look over
=> Net 7238 - consul k8s modify gateway resources job to create apigw gatewayclass and gatewayclassconfig

.changelog/3407.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/datadog-agent-role.yaml, charts/consul/templates/datadog-agent-rolebinding.yaml, charts/consul/templates/server-acl-init-job.yaml, charts/consul/templates/server-config-configmap.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/templates/telemetry-collector-deployment.yaml, charts/consul/test/unit/server-acl-init-job.bats, charts/consul/test/unit/server-config-configmap.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/test/unit/telemetry-collector-deployment.bats, charts/consul/values.yaml, control-plane/subcommand/common/common.go, control-plane/subcommand/server-acl-init/command.go, control-plane/subcommand/server-acl-init/command_test.go, control-plane/subcommand/server-acl-init/rules.go
This cherry-picked PR has been manually generated from #3407 to be assessed for back porting as automatic cherry-picking using the label failed.
---
> _PR Resubmitted from Branch vice Fork for Automation Testing_
- Expose several metrics specific features on consul-k8s to include:
- agent [`enable_debug`](https://developer.hashicorp.com/consul/docs/agent/config/config-files#enable_debug)
- agent [`telemetry.disable_hostname`](https://developer.hashicorp.com/consul/docs/agent/config/config-files#telemetry-disable_hostname)
- agent [`telemetry.enable_host_metrics`](https://developer.hashicorp.com/consul/docs/agent/config/config-files#telemetry-enable_host_metrics)
- agent [`telemetry.prefix_filter`](https://developer.hashicorp.com/co …
=> Datadog Integration (#3407)

.release/security-scan.hcl, scan.hcl
Triage this scan result as `consul-k8s` should not be directly impacted and it is medium severity. Follow-up ticket filed for remediation.
- Triage CVE-2024-25620 security scan result
- Improve formatting of scan config since this change will be backported.
Local scan has no further Go Modules OSV results when applied. Same with repository scan in CI (see checks below).
👀
=> [NET-8174] security: add scan triage for CVE-2024-25620 (helm/v3)

CHANGELOG.md
- Updating main changelog with recent releases.
-
=> Update main changelog for 1.1.10, 1.2.6 and 1.3.3

charts/consul/templates/crd-apigateways.yaml, control-plane/api/mesh/v2beta1/api_gateway_types.go, control-plane/config/crd/bases/mesh.consul.hashicorp.com_apigateways.yaml, control-plane/controllers/resources/api-gateway-controller.go, control-plane/controllers/resources/api-gateway-controller_test.go, control-plane/controllers/resources/gateway_controller_crud.go, control-plane/controllers/resources/mesh_gateway_controller.go, control-plane/gateways/builder.go, control-plane/gateways/deployment.go, control-plane/gateways/deployment_test.go, control-plane/gateways/metadata_test.go, control-plane/gateways/serviceaccount_test.go, control-plane/subcommand/inject-connect/v2controllers.go
- modifies the api-gateway v2 controller to utilize the generic crud hooks
-
=> [NET-7450] setup crud hooks for APIGateway v2

Makefile
To enable more consistent and error-proof dependency management, add a Make target that will set a dependency version across all submodules that require it.
Replicates https://github.com/hashicorp/consul/pull/19785 in `consul-k8s`.
Example run:
```shell
❯ make go-mod-get DEP_VERSION=github.com/hashicorp/raft@v1.6.0
--> Running go get github.com/hashicorp/raft@v1.6.0 (./acceptance)
go: added github.com/hashicorp/go-msgpack/v2 v2.1.1
go: added github.com/hashicorp/raft v1.6.0
go: upgraded golang.org/x/mod v0.12.0 => v0.13.0
go: upgraded golang.org/x/tools v0.12.1-0.20230815132531-74c255bcf846 => v0.14.0
--> Running go mod tidy (./acceptance)
--> Running go get github.com/hashicorp/raft@v1.6.0 (./charts)
go: added github.com/armon/go-metrics v0.4.1
go: added github.com/fatih/color v1.13.0 …
```
=> [NET-6741] make: Add target for updating dependencies across all modules

.changelog/3668.txt, .github/workflows/build.yml
Some customers and practitioners would like AWS ECR images due the reduced cost of pulling images onto their EKS clusters. This PR makes puts back the publishing of the k8s images. 
- Previous builds were removed by https://github.com/hashicorp/consul-k8s/pull/1364/files
- Closes https://github.com/hashicorp/consul-k8s/issues/3091
=> build.yml: Add ECR images back

.release/security-scan.hcl, scan.hcl
- Add scan triage for additional CVE, which can be addressed by the same follow-up work as the previous CVE
=> [NET-8174] security: add scan triage for CVE-2024-26147 (helm/v3)

.changelog/3625.txt, CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml
- Update versions for release
- Add `CHANGELOG` for 1.4.0
- Minor fix to changelog entry (will port to `main` and other branches)
Created by running `make prepare-release` w/ the following:
```shell
CONSUL_K8S_PRODUCT_VERSION=1.4.0
CONSUL_K8S_LAST_RELEASE_GIT_TAG=v1.3.3
CONSUL_K8S_RELEASE_VERSION=1.4.0
CONSUL_K8S_CONSUL_DATAPLANE_VERSION=1.4.0
CONSUL_K8S_RELEASE_BRANCH=release/1.4.0
CONSUL_K8S_CONSUL_VERSION=1.18.0
CONSUL_K8S_RELEASE_DATE=February 29, 2024
```
=> Prepare 1.4.0 release

acceptance/go.mod, acceptance/go.sum, cli/go.mod, cli/go.sum, control-plane/go.mod, control-plane/go.sum
v1.28.0 was retracted due to double-publish, so upgrade to latest.
1.4.0 PR: https://github.com/hashicorp/consul-k8s/pull/3701
1.4.x PR: https://github.com/hashicorp/consul-k8s/pull/3703
=> chore: upgrade `consul/api` to latest

.release/security-scan.hcl, scan.hcl
This vulnerability was already triaged [via its GHSA alias](https://osv.dev/vulnerability/GO-2024-2554), but the scanner is flagging it under this name, so adding an explicit entry.
PR for `main` and release branches: https://github.com/hashicorp/consul-k8s/pull/3705
Scanner now passes locally.
👀
=> [NET-8174] security: add triage alias for GO-2024-2554 (1.4.0)

.release/security-scan.hcl, scan.hcl
This vulnerability was already triaged [via its GHSA alias](https://osv.dev/vulnerability/GO-2024-2554), but the scanner is flagging it under this name, so adding an explicit entry.
Scanner now passes locally.
👀 
cc @picatz @dduzgun-security for awareness since I haven't seen aliases re-emerge weeks later before - maybe out of our control?
=> [NET-8174] security: add triage alias for GO-2024-2554

CHANGELOG.md
- Add `CHANGELOG` for 1.4.0 to `main` and release branch
Visual inspection
👀
=> docs: update `CHANGELOG` for K8s 1.4.0 release

.changelog/3719.txt, acceptance/go.mod, acceptance/go.sum, cli/go.mod, cli/go.sum, control-plane/cni/go.mod, control-plane/cni/go.sum, control-plane/go.mod, control-plane/go.sum
Change made by running
```shell
make go-mod-get DEP_VERSION=google.golang.org/protobuf@v1.33.0
make go-mod-get DEP_VERSION=github.com/golang/protobuf@v1.5.4
```
to bump dependency across submodules
=> [NET-8367] security: upgrade google.golang.org/protobuf to 1.33.0 

.github/workflows/nightly-cleanup.yml, hack/aws-acceptance-test-cleanup/main.go
- Consul-K8s EKS cleanup tests fail regularly, see [here](https://github.com/hashicorp/consul-k8s-workflows/actions/runs/7861808199/job/21450617885)
**ISSUE**
This error was caused as a result of the network interface used as part of the cluster setup for testing to not be automatically cleaned up. 
**FIX**
Add a network interface cleanup step
✅  CI triggered by this PR automatically cleaning up attached network interface resource [here](https://github.com/hashicorp/consul-k8s-workflows/actions/runs/8237526039/job/22526542345#step:8:21)
See CI examples above
=> NET-8391: fix cleanup script - remove network interface(s)

.changelog/3736.txt, acceptance/framework/consul/helm_cluster.go, acceptance/framework/consul/helm_cluster_test.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go, control-plane/subcommand/inject-connect/v1controllers.go
- Users have reported that when GracefulShutdown is enabled, ACL tokens are deleted immediately when a pod goes in to TERMINATING, which can disrupt consul DNS and an app's shutdown procedure if that is required.
- The new behavior is that if a pod still exists and has GracefulShutdown enabled, we will skip ACL and node cleanup, instead re-queue the event for the longest shutdown period, plus some buffer to cut down on noise.
- Manual testing in a local kube cluster, deploying an app w/ ACLs and graceful shutdown. I delete a pod and watch the control-plane and consul-dataplane logs to verify when the ACL token is cleaned up.
- Additional unit tests added.
👀 ☕
=> fix(control-plane): acl tokens deleted while pods in graceful shutdown

acceptance/framework/helpers/helpers.go, acceptance/framework/k8s/deploy.go, acceptance/tests/peering/peering_gateway_test.go
At times, CRDs created as part of the test suite are not cleaned up properly causing the test to timeout and run for a really long time
- Switch from retrier based on time to a counter based retries for fast fail
- Add goroutine to the  remove finalizers, if "delete" resource command is called
CI should pass
CI should pass
=> NET-6878: Remove finalizers from CRDs during test resource cleanup

acceptance/tests/sync/sync_catalog_test.go
- Fix typo in acceptance test fixture which caused ingress tests to fail.
=> Fix typo in values file for sync catalog test

.release/security-scan.hcl, scan.hcl
- This PR addresses [CVE GHSA-jw44-4f3j-q396 ](https://github.com/advisories/GHSA-jw44-4f3j-q396). For now we will disable the scan to get the pipeline in order as there is currently no fix. `helm.sh/helm/v3` 3.14.4 will supposedly contain only bug fixes and will be released on April 10, 2024. So maybe it will be included with that.
=> upgraded helm v3 to address GHSA-jw44-4f3j-q396

charts/consul/templates/crd-terminatinggateways.yaml, control-plane/api/v1alpha1/terminatinggateway_types.go, control-plane/api/v1alpha1/terminatinggateway_types_test.go, control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml, control-plane/go.mod, control-plane/go.sum
- Regenerated CRD as a follow up to https://github.com/hashicorp/consul/pull/20802
=> Net 6821 - Regenerate Terminating Gateway CRD with new field 

acceptance/framework/consul/helm_cluster.go, acceptance/framework/helpers/helpers.go, acceptance/framework/k8s/deploy.go, acceptance/framework/k8s/kubectl.go
- Ensure that crd cleanup occurs in the correct namespace. Pass in appropriate `k8s.KubectlOptions` with all the required fields to build command
- Fix cloud nightly CI errors [runs](https://github.com/hashicorp/consul-k8s-workflows/actions/runs/8289219897)
- Clean up CRDs left over from previous test failure 
CI should pass
CI should pass
=> Add fixes for flaky-cni and failing cloud-nightly tests

acceptance/framework/helpers/helpers.go
- Increase timeout before returning errors in [tests](https://github.com/hashicorp/consul-k8s/pull/3784) 
CI should pass
CI should pass
=> Increase timeout for running commands in acceptance test

control-plane/catalog/to-consul/resource.go
- I recently contributed https://github.com/hashicorp/consul-k8s/pull/3693 only to discover a bug that will add every service to the serviceMap and trigger a registration in consul. This removes that bug.
Existing tests and a manual build/deploy in my environment to confirm we don't register everything
With my previous change, if spinning up consul catalog sync you'll see every k8s service become registered regardless of configuration. With this change you should only see intended services become registered.
=> Bugfix: Don't recreate servicemap for catalog sync

acceptance/tests/connect/connect_proxy_lifecycle_test.go
- I made some fixes in #3743 to stabilize this acceptance test based on the new graceful shutdown behavior. I am forward-porting it into the 1.4.x and 1.3.x branches.
- CI/CD
👁️ 🔍
=> test: fix TestConnectInject_ProxyLifecycleShutdown

control-plane/cni/main_test.go
In #1527, we added support for OpenShift and Multus, which meant that the `consul-cni` plugin was no longer necessarily the final CNI plugin run. While working on a patch to allow compatibility with Nomad transparent proxy, I discovered we'd never removed a now-failing unit test of the plugin for the validation step. It looks like the remaining unit tests still cover the remaining validation, so we can safely remove this test.
Ref: https://github.com/hashicorp/consul-k8s/pull/1527
Ref: https://github.com/hashicorp/nomad/issues/10628
```
cd ./control-plane/cni; go test .
```
As above
=> remove unit test for previously removed `consul-cni` validation

.changelog/3779.txt, control-plane/api-gateway/cache/consul.go
- cache role/policy for api-gateway so we know if we need to create so we avoid getting errors in consul around trying to create a role/policy that already exists
=> [NET-8412] Fix order of APIGW ACL policy/role creation

.changelog/3758.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
- When a pod fetch fails, we used to not add it to the endpointAddressMap resulting in it getting deregistered and its token deleted. 
- This PR makes the cases we deregister in more explicit-- only if the pod does not exist, we will deregister the service instance and delete the token. This PR also switches endpointAddressMap to a map that marks endpoints explicitly for deregistration (or not). And only entries explicitly marked in the map for deregistration are deregistered. 
Unit tests, Manually testing by changing the code to simulate pod fetch errors and with the fix in this PR it doesn't deregister the instance and delete the token
=> [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors

.changelog/3758.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
https://github.com/hashicorp/consul-k8s/pull/3758
=> backport 1.3.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors

acceptance/framework/helpers/helpers.go, acceptance/framework/k8s/kubectl.go, acceptance/framework/logger/logger.go, acceptance/go.mod, acceptance/go.sum
- Backport of https://github.com/hashicorp/consul-k8s/pull/3800, https://github.com/hashicorp/consul-k8s/pull/3784 and https://github.com/hashicorp/consul-k8s/pull/3764
CI should pass
CI should pass
=> Backport release/1.1.x

.github/workflows/merge.yml, .github/workflows/nightly-acceptance.yml, .github/workflows/weekly-acceptance-0-49-x.yml, .github/workflows/weekly-acceptance-1-0-x.yml, .github/workflows/weekly-acceptance-1-1-x.yml
=> [1.3.4] Disable all CE tests

.github/workflows/build.yml
- Amalgamate UBI with Dockerhub and Redhat tags into one step
- Avoids a production incident that errors on duplicate tags: hashicorp/releng-support#123
-
-
=> [1.2.7] Remove Duplicate UBI Tags (#3265)

.changelog/3635.txt, charts/consul/templates/server-statefulset.yaml, charts/consul/test/unit/server-statefulset.bats
Initial integration hard-coded Unix Domain Socket `hostPath` for the consul-server statefulset, making the Helm override `global.metrics.datadog.dogstatsd.dogstatsdAddr` not useful if users wanted/needed a custom UDS socket path beyond the default value of `/var/run/datadog`.
```yaml
...
volumes:
- name: dsdsocket
hostPath:
path: /var/run/datadog
type: DirectoryOrCreate
```
This PR updates this to use the helm override as intended for custom UDS paths
```yaml
...
volumes:
- name: dsdsocket
hostPath:
path: {{ dir .Values.global.metrics.datadog.dogstatsd.dogstatsdAddr | trimAll "\"" }}
type: DirectoryOrCreate
```
Updated `server-statefulset.bats` with the following tests for default and non-default paths:
- `"server/StatefulSet: datadog unix socket path name rendering for hostPath volume …
=> Datadog Unix Socket Path Custom Path fix

.github/workflows/build.yml
- Amalgamate UBI with Dockerhub and Redhat tags into one step
- Avoids a production incident that errors on duplicate tags: hashicorp/releng-support#123
-
-
=> [1.3.4] Remove Duplicate UBI Tags (#3265)

.github/workflows/build.yml
- readds the docker dev tags were deleted for FIPS UBI docker images in #3265. Also corrected the tags because previously they were [pushing](https://github.com/hashicorp/consul-k8s/pull/3265/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L475) to `consul-k8s-control-plane` instead of `consul-k8s-control-plane-fips`
N/A, the tags were correct previously but were removed.
=> readd dev image tags for fips ubi

.github/workflows/build.yml
This PR is a manual backport of #3837.
---
This PR is intended to avoid a [production incident](https://github.com/hashicorp/releng-support/issues/123) where there are duplicate tags (auto-assigned) to UBI images. The entire issue is described [here](https://github.com/hashicorp/crt-workflows-common/pull/407#issue-1999804835), and can be avoided by building `UBI`s (intended for both `Dockerhub` and `Redhat`) in one step.
---
<details>
- 88a917feefc8eb01884e1bae6fa84dd106582838
</details>
=> Manual backport of Remove Duplicate UBI Tags to release/1.1.x

.changelog/3846.txt, charts/consul/templates/client-daemonset.yaml, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/templates/server-statefulset.yaml, charts/consul/templates/terminating-gateways-deployment.yaml, charts/consul/test/unit/client-daemonset.bats, charts/consul/test/unit/ingress-gateways-deployment.bats, charts/consul/test/unit/mesh-gateway-deployment.bats, charts/consul/test/unit/server-statefulset.bats, charts/consul/test/unit/terminating-gateways-deployment.bats
- Addresses https://github.com/hashicorp/consul-k8s/issues/1970 
- The issue specifically mentions client prometheus annotations, but I went ahead and made the change for all the places we have the prometheus path annotation. I only included the path annotation (rather than scrape and port) because the scrape and port annotations shouldn't change-- if metrics are enabled then scrape should be true and the port is hardcoded.
=> [net-7710] don't overwrite prometheus path annotation if it's already been specified

.changelog/3878.txt, charts/consul/templates/connect-inject-deployment.yaml, charts/consul/test/unit/connect-inject-deployment.bats, charts/consul/values.yaml, cli/helm/values.go, control-plane/connect-inject/constants/annotations_and_labels.go, control-plane/connect-inject/constants/constants.go, control-plane/connect-inject/lifecycle/lifecycle_configuration.go, control-plane/connect-inject/lifecycle/lifecycle_configuration_test.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar.go, control-plane/connect-inject/webhookv2/consul_dataplane_sidecar_test.go, control-plane/subcommand/inject-connect/command.go, control-plane/subcommand/inject-connect/v1controllers.go, control-plane/subcommand/inject-connect/v2controllers.go
- Support for consul-dataplane startup-grace-period-seconds and graceful-startup-path arguments.
=> feat: Add startup-grace-period-seconds and graceful-startup-path

acceptance/tests/sync/sync_catalog_test.go
- Temporarily Disable `TestSyncCatalog` as it historically never passes in [CI](https://github.com/hashicorp/consul-k8s-workflows/actions/runs/8428680628/job/23081761926#step:20:928)  
- Follow up [ticket](https://hashicorp.atlassian.net/browse/NET-8594)
=> NET-8594: Disable TestSyncCatalog

acceptance/tests/sync/sync_catalog_test.go
- Temporarily Disable `TestSyncCatalogIngress` as it historically never passes in [CI](https://github.com/hashicorp/consul-k8s-workflows/actions/runs/8428680628/job/23081761926#step:20:928)  
- Follow up [ticket](https://hashicorp.atlassian.net/browse/NET-8594) 
Run test locally and CI should pass
CI should pass
=> NET-8594: Disable TestSyncCatalogIngress

.changelog/3905.txt, charts/consul/templates/sync-catalog-deployment.yaml, charts/consul/test/unit/sync-catalog-deployment.bats, charts/consul/values.yaml
This PR adds a test and fixes a minor issue in the original https://github.com/hashicorp/consul-k8s/pull/3875, plus runs privileged tests required to merge.
I intend to backport this change to all active versions as it exposes a feature that's existed in `consul-k8s` since well before those releases.
---------
- syncCatalog: add support for `sync-lb-services-endpoints` startup flag
helm template
Validate that if the helm value is set to true that it's correctly rendered in the deployment manifest
fixes #3899
=> Helm: support sync-lb-services-endpoints for sync catalog

CHANGELOG.md
=> Add post-release  changelogs

.github/workflows/build.yml, control-plane/Dockerfile
=> add missing license file

.github/workflows/build.yml
The main branch failed when building the binaries, use abs path to copy files instead of relative.
Build is successful in this [branch](https://github.com/hashicorp/consul-k8s/actions/runs/8789758855).
=> Net 9069/xw add license file to all bin

.changelog/3928.txt, charts/consul/templates/terminating-gateways-role.yaml, charts/consul/test/unit/terminating-gateways-role.bats
- remove secrets access from terminating gateway as this is no longer needed
1. build a local version of the control plane by running `make dev-docker` from the root of this repo
1. clone the following gist https://gist.github.com/jm96441n/8671cc5e73bf950955c96f7cd3281694
2. checkout this branch in consul-k8s repo on your machine
3. in `start.sh` replace the value for `CONSUL_K8S_CHART_LOCATION` with the path to the helm charts in consul-k8s on your system
4. run `start.sh`
5. once all the services are up exec into the bender service using:
```
kubectl exec -i -t $(kubectl get pods --selector=app=bender -o jsonpath='{.items[*].metadata.name}') -c bender -- /bin/sh
```
6. install `curl` onto the container using `apk add curl`
7. contact the zoidberg service fronted by the termgw using …
=> [NET-6466] Remove secrets from termgw role

.github/workflows/build.yml, control-plane/Dockerfile, control-plane/LICENSE
I tried several different approaches:
- script to copy
- pros: automated
- cons: 
- need to clean up LICENSE file
- make maintenance harder
- Use parent dir as build-context
- Can not load parent context
- copy license file directly to control plane
- LICENSE is rare to change
- even when needed, it's very easy to copy and replace
The ending story is to just make another copy of LICENSE to control plane.
=> Net 9069/fix local brokerage

charts/consul/test/terraform/aks/variables.tf
**Solution**: Update Kubernetes version from `1.26` -> `1.27`
**ISSUE**
❗ Acceptance-aks [CI](https://github.com/hashicorp/consul-k8s-workflows/actions/runs/8871366832/job/24354322593#step:17:345) tests is failing with error
```
Error: Code="AgentPoolK8sVersionNotSupported" Message="Version 1.26.12 is not supported in this region. 
```
[Link](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)
Wait for nightly CI Tests to run
=> NET-9154: Update Kubernetes version

.changelog/3956.txt, control-plane/connect-inject/webhook/container_env.go, control-plane/connect-inject/webhook/container_env_test.go
- Fix a panic when parsing a malformed upstream, now a malformed upstream will be ignored
- Support multiple separators between upstreams (<space>, <comma>, <return>).
Added unit tests to test multiple scenarios including malformed upstream lists
N/A
=> Fix a panic in connect-inject when the provided upstreams list is malformed

.changelog/3978.txt, control-plane/api-gateway/cache/consul.go
- If role already exists, don't error out of connect inject. 
- Local build, create api gateway, delete connect inject. Before this change, connect inject would crash with 'role already exists', after this change, connect inject ignores that the role already exists and continues to operate as expected. 
- Local Build, CI passes
=> NET-9178-Consul-api-gateway-not-starting-after-restart

CONTRIBUTING.md, charts/consul/templates/connect-inject-validatingwebhookconfiguration.yaml, charts/consul/templates/crd-registrations.yaml, control-plane/api/v1alpha1/registration_types.go, control-plane/api/v1alpha1/registration_webhook.go, control-plane/api/v1alpha1/registration_webhook_test.go, control-plane/config/crd/bases/consul.hashicorp.com_registrations.yaml, control-plane/config/webhook/manifests.yaml, control-plane/subcommand/inject-connect/v1controllers.go
- add validating webhook to catch configuration errors earlier
- requirements: `kubectl` and `yq` to be installed on your system, this branch checked out in consul-k8s
- set the following values in your shell, update the k8s chart location value to be the path to the consul-k8s charts on your machine
```
export CONSUL_K8S_CHARTS_LOCATION="$HOME/hashi/consul-k8s/charts/consul"
```
- build from this branch `make docker-dev`
- from the following gist run the `start.sh` file, this will set up your cluster and register the service: https://gist.github.com/jm96441n/43e526387fc83f7079a10a555f739177
- open up the consul ui at `https://localhost:8501` (you'll have to allow insecure traffic over …
=> [NET-9201] Validating webhook for registrations

acceptance/tests/peering/peering_gateway_test.go
- Testing out timeout changes to fix failing tests on `main`.
=> test: fix PeeringGateway acceptance

.changelog/4000.txt, .changelog/4003.txt, control-plane/api-gateway/cache/consul.go
- Update role with correct policy when creating a new gateway
- this works on upgrade process
- have `kubectl` on your system
1. clone the following gist: https://gist.github.com/jm96441n/c0645d345c4a92f8b5ea6af272a19d63
1. set the `imageK8s` field in the `consul_values.yaml` file to be `hashicorp/consul-k8s-control-plane:1.4`
1. run the `start.sh` script
1. run the following in your terminal 
```
export CONSUL_HTTP_TOKEN=$(kubectl get --namespace consul secrets/consul-consul-bootstrap-acl-token --template={{.data.token}} | base64 -d)
```
1. in a tool like k9s see that `api-gateway-2` is in an error state
1. open consul at `https://localhost:8501` (you'll need to allow the insecure …
=> [NET-9376] Fix issue with multiple APIGW

.changelog/4001.txt, control-plane/api-gateway/cache/consul.go
- Update role with correct policy when creating a new gateway
- this works on upgrade process
- have `kubectl` on your system
1. clone the following gist: https://gist.github.com/jm96441n/c0645d345c4a92f8b5ea6af272a19d63
1. set the `imageK8s` field in the `consul_values.yaml` file to be `hashicorp/consul-k8s-control-plane:1.3`
1. run the `start.sh` script
1. run the following in your terminal 
```
export CONSUL_HTTP_TOKEN=$(kubectl get --namespace consul secrets/consul-consul-bootstrap-acl-token --template={{.data.token}} | base64 -d)
```
1. in a tool like k9s see that `api-gateway-2` is in an error state
1. open consul at `https://localhost:8501` (you'll need to allow the insecure …
=> [NET-9376] Fix Issue with multiple APIGW's roles/policy

.changelog/4002.txt, control-plane/api-gateway/cache/consul.go
- Update role with correct policy when creating a new gateway
- this works on upgrade process
- have `kubectl` on your system
1. clone the following gist: https://gist.github.com/jm96441n/c0645d345c4a92f8b5ea6af272a19d63
1. set the `imageK8s` field in the `consul_values.yaml` file to be `hashicorp/consul-k8s-control-plane:1.3`
1. run the `start.sh` script
1. run the following in your terminal 
```
export CONSUL_HTTP_TOKEN=$(kubectl get --namespace consul secrets/consul-consul-bootstrap-acl-token --template={{.data.token}} | base64 -d)
```
1. in a tool like k9s see that `api-gateway-2` is in an error state
1. open consul at `https://localhost:8501` (you'll need to allow the insecure …
=>  [NET-9376] Fix Issue with multiple APIGW's roles/policy

.changelog/4003.txt, control-plane/api-gateway/cache/consul.go
- Update role with correct policy when creating a new gateway
- this works on upgrade process
- have `kubectl` on your system
1. clone the following gist: https://gist.github.com/jm96441n/c0645d345c4a92f8b5ea6af272a19d63
1. set the `imageK8s` field in the `consul_values.yaml` file to be `hashicorp/consul-k8s-control-plane:1.4`
1. run the `start.sh` script
1. run the following in your terminal 
```
export CONSUL_HTTP_TOKEN=$(kubectl get --namespace consul secrets/consul-consul-bootstrap-acl-token --template={{.data.token}} | base64 -d)
```
1. in a tool like k9s see that `api-gateway-2` is in an error state
1. open consul at `https://localhost:8501` (you'll need to allow the insecure …
=> update role policy for api-gateway when creating new gateway

control-plane/subcommand/inject-connect/command.go
There was a slight oversight in #3967 in which the `ServiceResolver` webhook registration wasn't updated to use the new `SetupWithManager()` pattern like all of the other webhooks were. This PR updates it.
The result was that the manager would never have a decoder assigned to it. This was previously implicitly done by controller-runtime but was removed, thus the introduction of `SetupWithManager()` on all of the webhooks.
🤖 tests pass
=> [NET-9097] Update service resolver webhook registration missed in previous backport

.changelog/4016.txt, control-plane/Dockerfile
Resolves CVE-2024-0727.
- Update `alpine:3.18` where used to `alpine:3.19` (currently inconsistent)
CI
👀
=> security: update alpine base image to 3.19

.release/security-scan.hcl
Temporarily triage openssl scanner results while we investigate base image pulls, which should have already addressed these vulnerabilities.
- Add scanner triage
CI
👀
=> security: temporary triage for alpine base image

charts/consul/templates/crd-gatewayclassconfigs-v1.yaml, charts/consul/templates/crd-gatewayclassconfigs.yaml, control-plane/api-gateway/gatekeeper/volumes.go, control-plane/catalog/registration/cache.go, control-plane/catalog/registration/result.go, control-plane/config/crd/bases/consul.hashicorp.com_gatewayclassconfigs.yaml, control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml, control-plane/config/webhook/manifests.yaml
=> run generators ctrl-manifests and ctrl-generate

charts/consul/values.yaml
- Hashicorp-managed is now HCP Consul Dedicated. The helm chart should reflect that. These changes are related to this PR in Consul: https://github.com/hashicorp/consul/pull/21026
** This only applies to 1.4.2+, as the changes did not go into affect until May 1.
=> Updates Helm chart comments with Consul Dedicated Rebrand changes

.changelog/4016.txt
The original change was made as a security fix, which was later determined to be unnecessary (both `alpine` 3.18 and 3.19 received the CVE fix in question). Recategorizing this as an improvement for the final changelog. The `alpine` upgrade is still worth doing, as is aligning all the base images in the Dockerfile on a single version.
I'll follow up w/ the same change on backports of https://github.com/hashicorp/consul-k8s/pull/4016.
=> chore: fix previous changelog for alpine upgrade

control-plane/api-gateway/gatekeeper/volumes.go
- when running a gateway with a TLS configuration on a listener the pods would consistently thrash due to inconsistent ordering of the volumes/mounts
- build the main branch of consul-k8s and of consul using `make dev-docker`
- clone the following gist: https://gist.github.com/jm96441n/b92a80c2251c7a54d1feada320c5eac6
- run the `start.sh` script
- open a tool like k9s and see the `gateway-2` pod thrash (you may have to delete the pod and re-apply the file as you can _occasionally_ get the same order of volumes/mounts on a re-reconcile)
- destroy that cluster
- build consul-k8s from this branch using `make dev-docker`
- run the `start.sh` script again
- open a tool like k9s and see the gateway pods not thrash (you can remove the second gateway multiple times to test this) 
read the code …
=> [NET-9605] fix issue where gateway pods with TLS block thrash

control-plane/api-gateway/common/diff_test.go
Replace remaining `api.InlineCertificate` references in test with `api.FileSystemCertificate`. There is no functional impact -- this just makes the codebase easier to reason about since consul-k8s no longer uses inline certificates as of #3767.
🤖  tests pass
=> [NET-8091] Replace InlineCertificate kind in test w/ FileSystemCertificate kind

.changelog/4053.txt, charts/consul/templates/partition-init-role.yaml
Remove `Secret` resource from partition-init `Role`
Deploy two k8s clusters with consul-k8s installed from this branch of the Helm chart. One should be a non-default partition utilizing the servers in the default partition cluster. The `partition-init` job should succeed.
<details>
<summary>Example</summary>
```yaml
global:
name: consul
peering:
enabled: true
tls:
enabled: true
acls:
image: hashicorppreview/consul-enterprise:1.19-dev
adminPartitions:
enabled: true
name: default  # required name for AP hosting consul-server
enableConsulNamespaces: true
enterpriseLicense:
secretName: 'enterprise-license'
secretKey: 'key'
connectInject:
default: true
transparentProxy:
defaultEnabled: true
meshGateway:
enabled: true
ui:
enabled: true
service:
enabled: …
```
=> [NET-6705] Remove Secrets resource from partition-init Role

.github/workflows/security-scan.yml
replacing the `ELEVATED_GITHUB_TOKEN` with `HASHIBOT_PRODSEC_GITHUB_TOKEN`
=> ci: update security-scanner token

.changelog/4059.txt, control-plane/connect-inject/controllers/endpoints/endpoints_controller.go, control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
The existing graceful shutdown logic checks for the pod with the same name and looks at its graceful shutdown time to mark the service instance as unhealthy in consul and delay its deletion. In the case of a statefulset rollout, a pod will go down and a new pod with the same name will come up, so we could run into a race condition where we try to mark the service instance as unhealthy thinking that the pod is terminating, but it's actually the new running pod, not the old terminating pod.
This change is to check whether the service instance we're proposing to deregister in consul should go through graceful shutdown or not. If the pod has a different UID from the pod UID used to register that service instance, then the service instance should be deregistered. 
- Unit tests
- I was not able …
=> fix: deregistration should not do graceful shutdown if there is a new pod

charts/consul/values.yaml
- This backports the change made in https://github.com/hashicorp/consul/pull/21278 to the source comments in k8s.
=> docs: remove mulitport docs, add v1dns flag

control-plane/api-gateway/common/translation.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/api-gateway/gatekeeper/gatekeeper.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/ownership.go, control-plane/api-gateway/gatekeeper/role.go, control-plane/api-gateway/gatekeeper/secret.go, control-plane/api-gateway/gatekeeper/volumes.go
In order to mount a volume from a `Secret` containing TLS certificates into the API gateway `Pod`, those `Secrets` must exist in the same namespace as the API gateway `Pod`. This centralizes all referenced TLS certificates into a `Secret` in the same namespace as the API gateway `Pod` to make that possible. This `Secret` is managed in the same way as other API gateway resources - such as `Role`, `Service`, etc. - in that it has an owner reference pointing to the `Gateway` that's consuming it. That owner reference is checked before any operations take place on the `Secret` to ensure that we aren't overwriting any pre-existing resources that we don't own.
Create a `Gateway` that references a TLS certificate `Secret` from a namespace _other than the one containing the `Gateway`._ Verify that …
=> [NET-9606] Use namespace-local Secret for mounting TLS certificates into api-gateway Pod

control-plane/api-gateway/common/translation.go, control-plane/api-gateway/controllers/gateway_controller.go, control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/api-gateway/gatekeeper/gatekeeper.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/ownership.go, control-plane/api-gateway/gatekeeper/secret.go, control-plane/api-gateway/gatekeeper/volumes.go
> [!NOTE]
> This is a backport of #4100 targeting the consul-k8s 1.5.0 release
In order to mount a volume from a `Secret` containing TLS certificates into the API gateway `Pod`, those `Secrets` must exist in the same namespace as the API gateway `Pod`. This centralizes all referenced TLS certificates into a `Secret` in the same namespace as the API gateway `Pod` to make that possible. This `Secret` is managed in the same way as other API gateway resources - such as `Role`, `Service`, etc. - in that it has an owner reference pointing to the `Gateway` that's consuming it. That owner reference is checked before any operations take place on the `Secret` to ensure that we aren't overwriting any pre-existing resources that we don't own.
Create a `Gateway` that references a TLS certificate …
=> Backport: [NET-9606] Use namespace-local Secret for mounting TLS certificates into api-gateway Pod

.github/workflows/merge.yml, .github/workflows/pr.yml
With the release of 1.19, this version is now Ent-only.
=> [NET-9446] chore: disable CE tests for Consul 1.18

.github/scripts/check_skip_ci.sh, .github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/reusable-conditional-skip.yml, .github/workflows/security-scan.yml
[Similar to consul](https://github.com/hashicorp/consul/blob/e9c983f36107b044fcd889f738b3d5ba2b922e7a/.github/workflows/go-tests.yml#L33), skip build and tests if we're only changing docs.
This should help speed up releases and daily work quick-fixes.
`consul-dataplane` PR with testing notes: https://github.com/hashicorp/consul-dataplane/pull/560
=> ci: add conditional skip for docs changes

.github/workflows/pr.yml
Unlike local job checks, these will not automatically be considered passing when skipped.
Follow-up to https://github.com/hashicorp/consul-k8s/pull/4127 after enabling required checks for acceptance tests.
- Skip newly required acceptance test checks (set by `consul-k8s-workflows`) when skipping CI due to docs-only changes
https://github.com/hashicorp/consul-k8s/pull/4146 (PR based on this branch, with skipping always on regardless of changed files, since this PR changes files that will not be skipped):
👀
=> ci: pass required consul-k8s-workflows checks on CI skip

.changelog/3989.txt, charts/consul/templates/server-acl-init-job.yaml, charts/consul/test/unit/server-acl-init-job.bats
ArgoCD hooks to be set to Job annotations and not at Job template spec level -> https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#usage 
If set at current Job template spec level when Job is finished ArgoCD detects back again diff entering into a loop, if ArgoCD AutoSync is enabled this will be a loop of init jobs running forever.
fix: #3831 
* Ran helm bats tests successfully.
* Deploy this chart using ArgoCD Application. Without the fix after the sync it will enter in a diff sync loop.
=> Fix ArgoCD hooks annotation location

acceptance/framework/flags/flags.go, acceptance/tests/consul-dns/consul_dns_test.go, charts/consul/templates/dns-proxy-deployment.yaml
- run consul-dns temporarily with connect injector service account so that it can get an ACL token.  (A follow up PR will map the appropriate service account)
- add test cases for `TestConsulDNS` for dnsproxy deployments
- acceptance test
👀
=> NET-10193 - add acceptance test for DNS proxy work

charts/consul/test/unit/dns-service.bats
- add test to ensure that the regular dns service is not deployed when dns proxy is enabled
-
locally and CI
👀
=> NET-10526 - consul-k8s - add test to ensure that the regular dns service is not deployed when dns proxy is enabled

charts/consul/test/unit/dns-proxy-deployment.bats
This is really a minor test change to set up and naming of the test so that it does not make readers think that in addition to setting `dns.proxy.enabled=true`, you also need to set `global.enabled=false` and `client.enabled=true`.
running locally and CI
👀
=> NET-10522 - consul-k8s - update test that makes it seem like global.enabled=false and client.enabled=true is required to enable dns proxy

.changelog/4210.txt, charts/consul/templates/gateway-cleanup-serviceaccount.yaml, charts/consul/templates/gateway-resources-serviceaccount.yaml, charts/consul/test/unit/gateway-cleanup-serviceaccount.bats, charts/consul/test/unit/gateway-resources-serviceaccount.bats
This fixes https://github.com/hashicorp/consul-k8s/issues/3862. When installing consul-k8s with a private image registry, the 'gateway-resources' and 'gateway-cleanup jobs could not pull the images as thier service accounts did not include the imagePull secrets
- Added bats test
- Manually tested with the following values and a private registry set up
*Do a helm install with the local chart from this branch*. If the jobs didn't have the required pull secrets, they would never spin up.
Also do a helm uninstall to see the cleanup-job run.
```
global:
name: consul
imageK8S: my-private-registry/consul-k8s-control-plane:latest
imagePullSecrets:
- name: consul-pull-secret
namespace: consul
imagePullPolicy: "Always" 
```
Test on your own cluster with a private registry using the above values.
=> NET-10548 Adds image pull secrets to the gateway cleanup and gateway resources job service account

acceptance/tests/consul-dns/consul_dns_partitions_test.go, acceptance/tests/consul-dns/consul_dns_test.go, acceptance/tests/consul-dns/coredns-original.yaml, acceptance/tests/consul-dns/coredns-template.yaml
- this changes the existing DNS test so rather than having the test use dig to specify the dns service address to use, the tests will update CoreDNS the way we recommend users should.
- this PR requires https://github.com/hashicorp/consul-k8s/pull/4174
- in the meantime this consul-dataplane image can be used: `jmurrethc/consul-dataplane-dev`
- this PR targets the branch of this PR as well: https://github.com/hashicorp/consul-dataplane/pull/593
CI
👀
=> NET-10576 - consul-k8s - configure acceptance test to configure CoreDNS the way a user would

.changelog/4213.txt, charts/consul/templates/crd-tcproutes-external.yaml, charts/consul/test/unit/crd-tcproutes-external.bats
- Adds back the manageNonStandardCRDs option to the Helm chart. Somehow got removed from tcp-routes
- Fixes https://github.com/hashicorp/consul/issues/20909 
- Start a GKE Autopilot cluster
- Install with the following values, should have no errors
```
global:
name: consul
connectInject:
enabled: true
apiGateway:
manageExternalCRDs: false
manageNonStandardCRDs: true
cni:
enabled: true
logLevel: debug
cniBinDir: "/home/kubernetes/bin"
cniNetDir: "/etc/cni/net.d"
server:
resources:
requests:
memory: "500Mi"
cpu: "500m"
limits:
memory: "500Mi"
cpu: "500m"
```
Can test on another type of cluster, you just need to notice that flipping the value of `manageNonStandardCRDs` will determine whether the tcp-route CRD gets installed.
=> Adds back manageNonStandardCRDs option to the helm chart

acceptance/tests/consul-dns/consul_dns_partitions_test.go, acceptance/tests/consul-dns/consul_dns_test.go, acceptance/tests/consul-dns/coredns-original.yaml, acceptance/tests/consul-dns/coredns-template.yaml, charts/consul/templates/dns-proxy-deployment.yaml
- this PR relies on https://github.com/hashicorp/consul-dataplane/pull/593
- this test adds TestConsulDNS_WithPartitionsAndCatalogSync
- running acceptance test locally with above dataplane image
👀
=> NET-10194 - dns proxy acceptance test for partitions

.changelog/4227.txt, charts/consul/templates/client-securitycontextconstraints.yaml, charts/consul/templates/cni-securitycontextconstraints.yaml
Due to logic in OpenShift's admissions hook that force-reorders explicit and implicit entries in this list, our `SecurityContextConstraints` entries will never successfully sync via tools like ArgoCD, which expect an exact input and output match when diff'ing.
More details on the problem addressed by this change and potential future improvements to avoid it in the future can be found in https://github.com/hashicorp/consul-k8s/issues/4208 (see comments).
- Reorder SCC `volumes` entries to match the post-reconciliation order persisted by OpenShift
- Spun up a local OpenShift CRC cluster w/ ArgoCD (GitOps Operator), deployed original and modified charts to verify fix results in a fully synced `consul-cni` SCC.
- Tested on Azure using community ArgoCD operator, same results.
👀
=> [NET-10547] openshift: re-order SCC volume list for Argo sync

.github/CODEOWNERS
- Adds a CODEOWNERS file that would request a review from the docs team when helm values are changed. This review is non-blocking as we don't set the required review setting in the branch protection rules.
It should take effect in the next PR.
~### How I expect reviewers to test this PR ###~
=> NET-5272/add docs team code owners to review helm values description

control-plane/Dockerfile
Fix the missing argument in the path of the LICENSE file
[ticket](https://hashicorp.atlassian.net/browse/NET-10782)
Follow-up to https://github.com/hashicorp/consul-k8s/pull/3938.
=> make missing changes in the backport

CHANGELOG.md, charts/consul/Chart.yaml, charts/consul/values.yaml, version/version.go
=> prepare release 1.3.8

.changelog/4287.txt, control-plane/Dockerfile
=> update ubi image and go-discover

.changelog/4300.txt, .gitignore, acceptance/tests/consul-dns/consul_dns_test.go, charts/consul/templates/dns-proxy-deployment.yaml, charts/consul/test/unit/dns-proxy-deployment.bats, charts/consul/values.yaml
- add the ability for users to set the ACL token on dns-proxy similiar to how catalog sync exposes the ability to set the ACL token in a secret
-
CI & unit tests
👀
=> NET-10763 - Allow DNS Proxy to configured with an ACL token when manageSystemACLs is false

.changelog/4307.txt, charts/consul/templates/connect-inject-clusterrole.yaml, charts/consul/test/unit/connect-inject-clusterrole.bats
Remove unnecessary permissions for `Namespace` and `Node` resources in the connect-inject controller's `ClusterRole`
- 🤖 tests pass
- Manual smoke test running a Consul installation with service mesh and API gateways enabled
- Validate against your mental model of Consul
- (See above)
=> NET-10871 Remove unnecessary resource permissions in connect-inject ClusterRole

.github/workflows/pr.yml, Makefile, charts/consul/test/docker/Test.dockerfile
- update the `bats-tests` make target so that you can pass in a specific test to run and to use the docker image we use in CI for reproducibility with CI runs
- Update version of bats, terraform, and go in the bats testing dockerfile
=> [NET-11106] Make bats testing more reproducible

.changelog/4333.txt, .github/scripts/check_skip_ci.sh, .github/workflows/pr.yml, CHANGELOG.md, Makefile, charts/consul/Chart.yaml, charts/consul/test/docker/Test.dockerfile, charts/consul/values.yaml
=> Backport prepare release rc1

.changelog/4316.txt, charts/consul/templates/connect-inject-configmap.yaml, charts/consul/templates/connect-inject-deployment.yaml, control-plane/api-gateway/common/helm_config.go, control-plane/api-gateway/gatekeeper/gatekeeper.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/api-gateway/gatekeeper/init.go, control-plane/api-gateway/gatekeeper/rolebinding.go, control-plane/api-gateway/gatekeeper/serviceaccount.go, control-plane/subcommand/inject-connect/command.go, control-plane/subcommand/inject-connect/v1controllers.go
Fixes #4312
> [!NOTE]
> In order for the pull secrets to work for a `Gateway`, they must be available in any namespace that a `Gateway` is deployed to. This is already the case with injected mesh sidecars if you, for example, consume consul-dataplane from a private image registry, so I have not made any special accomadations for `Gateways`.
Plumb `global.imagePullSecrets` onto the `ServiceAccount` created for each `Gateway`
1. Created a private registry on DockerHub for consul-dataplane, which is used by the gateway's `Deployment`
```shell
docker pull hashicorp/consul-dataplane:1.5.3
docker tag hashicorp/consul-dataplane:1.5.3 <your_dockerhub_username>/consul-dataplane:1.5.3
docker login
docker push <your_dockerhub_username>/consul-dataplane:1.5.3
```
1. [Created an image pull secret for …
=> [NET-10985] Fix bug where imagePullSecrets were not set up for Gateways

charts/consul/test/terraform/aks/variables.tf
Nightly acceptance test on AKS is currently failing with error 
```Code="K8sVersionNotSupported" Message="Managed cluster consul-k8s-2814350665 is on version 1.27.16 which is not supported in this region``` due to [end of life support for Kubernetes version 1.27.](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli)
Upgraded AKS kubernetes version to 1.28
=> bump kubernetes version for AKS

hack/aws-acceptance-test-cleanup/main.go
Acceptance test in CI are currently failing with error `LimitExceeded: Cannot exceed quota for RolesPerAccount: 1000`.
Update the `aws-acceptance-test-cleanup` script to include cleaning up iamroles created as part of test environment setup. 
Tested locally to ensure all exisiting iAMRoles created as part of previous acceptance test runs were cleaned up using this script
=> NO-JIRA: cleanup iamRoles as part of nightly test cleanup

charts/consul/test/unit/sync-catalog-cleanup-on-uninstall-job.bats, charts/consul/test/unit/sync-catalog-cleanup-on-upgrade-job.bats, charts/consul/test/unit/sync-catalog-cleanup-serviceaccount.bats
=> [NET-11297] added bats testing

.changelog/4426.txt, cli/cmd/proxy/list/command.go, cli/cmd/proxy/list/command_test.go
- API Gateways are now included in the `proxy list` command where they were not before due to a helm chart label that wasn't present. It doesn't make sense to include this label on created API gateways since they are not actually controlled by the helm chart.
- Proxies are now output in deterministic order based on their proxy type, namespace and name
Install an assortment of gateways and mesh-injected services, verify output matches (`go run ./cli proxy list -all-namespaces`, for example)
See above
=> Refactor `proxy list` command, ensuring api-gateway Pods are included

.changelog/4434.txt, control-plane/subcommand/server-acl-init/rules.go, control-plane/subcommand/server-acl-init/rules_test.go
Stop including a duplicate `acl = "write"` rule at the root level of the connect-inject ACL policy when namespaces are not enabled. The security patch in https://github.com/hashicorp/consul/pull/21908 led to the connect-injector being unable to start up as its ACL policy is rejected by Consul.
1. Expanded the test matrix to cover all possible flag combinations w/ current policy output
2. Fixed policy generation
3. Updated the test assertions to account for the bug fix, verifying that `acl = "write"` never appears twice at the root level of the policy with any combination of flags
Review commit-by-commit observing the above
=> Fix duplicate key in connect-inject ACL policy

.changelog/4433.txt, cli/cmd/gateway/list/command.go, cli/cmd/gateway/list/command_test.go, cli/commands.go
> [!NOTE]
> This PR is blocked by the bug fix in https://github.com/hashicorp/consul-k8s/pull/4434 which is preventing tests from passing
This PR adds a new command, `consul-k8s gateway list`, which collects the various components of configuration for all Gateways in a given K8s cluster or namespace – `Gateway`, attached `HTTPRoutes`, attached `TCPRoutes`, etc. – into a single zip file containing one yaml file per Gateway.
It can output an archive named `gateways.zip` into the current directory, or it can output JSON to the terminal.
```shell
$ consul-k8s gateway list --output archive
$ consul-k8s gateway list --namespace my-namespace --output json
$ consul-k8s gateway list --all-namespaces --output json
```
Create one or more Gateways in your Kube cluster. Example for this config is …
=> [NET-11256] Add `gateway list` command to consul-k8s CLI

.changelog/4471.txt, charts/consul/templates/server-statefulset.yaml, charts/consul/values.yaml
- Add support for server.snapshotAgent.extraEnvironment and server.snapshotAgent.extraVolume in the helm chart to allow for configuring google application credentials 
- Running locally against a kind cluster with the snapshot agent configured to point at a google bucket
Using the following config
Google application credentials loaded into cluster with the following secret name/secret key
```
name: snapshot-agent-google-app-creds
key: creds.json
```
configSecret
```
kubectl create secret generic snapshot-config --from-file=snapshot-agent=<path-to-config-below>/snapshotagentconfig.yaml
```
```
{
"snapshot_agent": {
"http_addr": "127.0.0.1:8500",
"token": "",
"datacenter": "",
"ca_file": "",
"ca_path": "",
"cert_file": "",
"key_file": "",
"license_path": "",
"tls_server_name": "",
"login": …
```
=> [NET-11567] Update Helm Chart to allow snapshotagent to support extraVolumes and extraEnvionmentVars

acceptance/tests/api-gateway/api_gateway_external_servers_test.go, acceptance/tests/api-gateway/api_gateway_kitchen_sink_test.go, acceptance/tests/api-gateway/api_gateway_test.go, acceptance/tests/fixtures/bases/api-gateway/gatewayclassconfig.yaml, acceptance/tests/fixtures/bases/static-client/deployment.yaml, acceptance/tests/fixtures/bases/static-server-https/deployment.yaml, acceptance/tests/fixtures/bases/static-server-tcp/deployment.yaml, acceptance/tests/fixtures/bases/static-server/deployment.yaml, acceptance/tests/fixtures/cases/api-gateways/jwt-auth/api-gateway.yaml, acceptance/tests/fixtures/cases/static-server-inject/patch.yaml, acceptance/tests/partitions/partitions_gateway_test.go, acceptance/tests/peering/peering_gateway_test.go, acceptance/tests/wan-federation/wan_federation_gateway_test.go, control-plane/connect-inject/webhook/container_init.go, control-plane/connect-inject/webhook/container_init_test.go
---
- Added acceptance test for running api gateway in PSA environment
- Added SecCompProfileUserType to connect inject container when CNI and TProxy are enabled
- Connect Inject will not run when tproxy is enabled because of additional permisions that are required 
- CI passes
- Local running of the acceptance tests
CI Passes
---
<details>
- bd770c6076ad51d5ee15b4f8a8ec0afeae1c6641  - dd06d2268d3b6b50a3cbf4a73099d76b34bf7e1c  - 459ab518f5444e703a7b72826afa113f56e547f0  - c331e8521e17cc9610e804329e80c92ab3205f7f  - 7e44e0bf1a063009661e3902b39abcdd54d7a664  - 1a8fa75a49c0675d1e4b97ccd23830d7d345066f  - 038b15c8a433a01d39b891d1c31eefac544d4fa1  - b548bf687df1d98422275392cb8e826eaa258ed0  - …
=> Backport of PSA Acceptance Tests into release/1.7.x

.github/CODEOWNERS, .github/workflows/reusable-conditional-skip.yml
Added `.github/CODEOWNERS` to the list of skippable files in the workflow configuration to prevent unnecessary workflow runs. Simplified CODEOWNERS file by removing redundant entries related to Helm Docs Review.
-
-
=> Update file skip logic and simplify CODEOWNERS config

.github/CODEOWNERS
Added `.github/CODEOWNERS` to the list of skippable files in the workflow configuration to prevent unnecessary workflow runs. Simplified CODEOWNERS file by removing redundant entries related to Helm Docs Review.
(cherry picked from commit 07a6476239f76abbc6cb82bef7d437ca9127459a)
-
-
=> Update file skip logic and simplify CODEOWNERS config (#4557)

.github/workflows/build.yml
- Updated ubuntu version for build workflow
- 20.04 has been deprecated by GitHub
- The change is already present in `release/1.7.x` and `release/1.5.x` and will only need backport for `release/1.6.x`
- The change is already tested in 1.7.0 release
- Build should create necessary artifacts
=> update ubuntu version for build workflow as 20.04 is deprecated in GH

.changelog/4468.txt, charts/consul/values.yaml, control-plane/controllers/configentries/configentry_controller.go, control-plane/controllers/configentries/configentry_controller_ent_test.go, control-plane/controllers/configentries/configentry_controller_test.go, control-plane/controllers/configentries/terminatinggateway_controller.go, control-plane/subcommand/inject-connect/v1controllers.go
- Introduce handling of Consul AdminPartition ACL policy rules when `global.adminPartitions.enabled: true`
Current workflow requires end users to manually update the Terminating Gateway policies applied by the TerminatingGateway resource controller when AdminPartitions are enabled from:
```hcl
namespace "default" {
service_prefix "" {
policy = "write"
}
}
```
to
```hcl
partition "default" {
namespace "default" {
service_prefix "" {
policy    = "write"
intention = "read"
}
}
}
```
- Clone [consul-k8s](https://github.com/hashicorp/consul-k8s.git) repository to $HOME/HashiCorp/consul-k8s
- Apply this branch's commits to locally cloned repo.
- Using https://github.com/hashicorp-support/consul-k3d-multicluster 
- From this repo, run `make install-dev` to deploy dev image with changes
- Verify …
=> Net 12039 terminating gateway acl policy fix

.changelog/4684.txt, control-plane/Dockerfile
- go discover version upgrade to 40c38fd658f0fd07ce74f2ee51b8abd3bfed01b3 as part of CVE(CVE-2024-45337 &
CVE-2025-22869)
-
- Ran Trivy scan to verify CVE fixed
=> go-discover version upgrade

.changelog/4745.txt, charts/consul/templates/_helpers.tpl, charts/consul/templates/dns-proxy-deployment.yaml, charts/consul/templates/ingress-gateways-deployment.yaml, charts/consul/templates/mesh-gateway-deployment.yaml, charts/consul/templates/mesh-gateway-podsecuritypolicy.yaml, charts/consul/templates/telemetry-collector-podsecuritypolicy.yaml, charts/consul/templates/terminating-gateways-podsecuritypolicy.yaml, charts/consul/test/unit/server-statefulset.bats, charts/consul/values.yaml, control-plane/api-gateway/gatekeeper/dataplane.go, control-plane/api-gateway/gatekeeper/dataplane_test.go, control-plane/api-gateway/gatekeeper/gatekeeper_test.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar.go, control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
> [!NOTE]
> This PR has a dependency on https://github.com/hashicorp/consul-dataplane/pull/652
The current implementation enables NET_BIND_SERVICE for all the uses cases of data plane (envoy). We do not need this capability to be added to the pod when there privileged ports are not used.
We have generated the new data plane image as part of <PR-TODO> which can take the command to invoke the privileged envoy binary which can support the NET_BIND_SERVICE capability.
The current set of changes uses that, privileged, entry point when privileged ports are used for the use case. Although the most common use case is Ingress gateways which historically supported binding to privileged ports, for backward compatibility, the support is extended to other use cases: API Gateway and Mesh Gateway where …
=> Use privileged dataplane entrypoint for consul-dataplane
