README.md

Also removes a reference to `Consul ESM`.

Update readme with Go version requirement and dev-docker command

---

subcommand/sync-catalog/command.go

This endpoint will be used for liveness and readiness checks on the
catalog sync pod within Kubernetes. It calls the Consul cluster and
checks if there is a leader in the cluster to determine the health of
its connection to Consul.
This leader query can occasionally fail
if there is currently a leader election, but the election period should
be relatively short. Additionally, the specific timing of when the lack
of a leader constitutes a failure is determined in the Helm chart's
liveness and readiness checks and can be modified if a user's cluster
behaves in a significantly different manner.

Add a /health/ready endpoint for catalog sync

---

subcommand/sync-catalog/command.go

Updates #35 to resolve rebase conflicts.

subcommand/sync-catalog: Add -log-level CLI flag

---

subcommand/server-acl-init/command.go

If ACLs are enabled on the cluster using the automatic bootstrapping,
the enterprise license application job needs an acl token to work
correctly. This allows that token to be optionally created.

Add the option to create an acl token for the enterprise license job

---

subcommand/server-acl-init/command.go

Additionally refactors the create ACL logic out in a reusable method
for most of the group tokens.
Adds a flag to allow the client ACL token to be optional, though it
still defaults to true.

Add the option to create an ACL token for snapshot agents

---

subcommand/server-acl-init/command.go

This flag will be used when bootstrapping Connect mesh gateways.

Add -create-mesh-gateway-token flag

---

subcommand/server-acl-init/command.go

Allow installation of consul-k8s into a non-default namespace

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go

Previously, we would re-use an existing bootstrap token if the Secret
already existed, by looking for the token in the StringData field of the
Secret.
Unfortunately, the StringData field of a Kubernetes Secret is only used as a
convenience when writing a Kubernetes Secret. When reading the secret it
is not populated and is converted to a []byte and moved to the Data
field. This conversion happens in a real Kubernetes cluster but not with
the testing 'fakeclient', hence not being caught by our tests.
This change removes all use of StringData to avoid confusion.

Fix bug looking for boot token in StringData field

---

catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go

Previously, if consul.hashicorp.com/service-sync was set to true and
then set to false, the service wouldn't get deleted.
Fixes #76

Fix: changing sync annotation=false should delete

---

helper/coalesce/coalesce_test.go

This test would occasionally fail in CI with the error:
coalesce_test.go:80: total should be 3 to 5: 2
The purpose of the test is to check if Coalesce respects the cancel
function of ctx. The test previously worked by having a sum function
read off a channel. The channel emmitted 1 every 50ms. The cancel
function was called at 200ms and so we expected the total to be between
3 and 5 since at t=200ms the function should have run 3, 4 or 5 times.
Unfortunately, depending on how the function got scheduled, it might
sleep for longer than 50ms, thus messing up the count.
The test has been changed so that the emitting function sleeps forever
(via an empty select). The cancel is called at 50ms and then we simply
check whether the Coalese function has exited within 150ms. Although
there could …

Fix flaky coalesce test

---

connect-inject/handler.go
subcommand/inject-connect/command.go

Update default Consul image to 1.7.1

---

connect-inject/container_init.go
connect-inject/container_init_test.go

Closes #231 
Signed-off-by: Ashwin Venkatesh <ashwin@hashicorp.com>

Add pod-name to consul metadata in connect

---

catalog/to-consul/resource_test.go

* Some tests in resource_test would fail intermittently in CI because the Sleep time was insufficient. Replacing the Sleep with retry.Run should ensure the tests run consistently.
* Potentially made the world a better place

Replace time.Sleep with retry.Run in resource_test.go

---

api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/serviceresolver_types_test.go

Fix bug with service-resolver validation

---

api/v1alpha1/proxydefaults_webhook.go

Ignore ProxyDefaultsValidator from DeepCopy

Ignore ProxyDefaultsValidator from deepcopy

---

api/v1alpha1/serviceresolver_types.go

I missed adding this during the code review

Clarify cookie docs

---

.circleci/config.yml

This PR allows arbitrarily testing against a particular dev SHA specified by `CONSUL_VERSION` and `CONSUL_ENT_VERSION` pulled from our s3 bucket.

Pull consul dev images

---

connect-inject/health_check_resource.go
connect-inject/health_check_resource_test.go
helper/controller/controller.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

Add test for command shutting down cleanly

---

api/v1alpha1/servicesplitter_types.go
api/v1alpha1/servicesplitter_types_test.go

For after beta release
Checklist:

Fix typo in splitter error

---

CHANGELOG.md

Update Changelog for 0.19.0 release

---

README.md

Update Readme with new links and re-order features

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

Also add back enterprise test build tag.

Update tests for health checks acls (and some refactoring)

---

CHANGELOG.md

Co-authored-by: Ashwin Venkatesh <ashwin@hashicorp.com>
- Add missing entries to changelog

Update changelog with missing entries

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

- Add issue templates
By reading a small sample of issues to try to figure out what to ask in the template that would be useful.
As people who have triaged lots of consul-k8s/consul-helm issues, please do offer suggestions about things you think would be helpful to reduce back and forth in issues.

Add issue templates

---

namespaces/namespaces.go
namespaces/namespaces_test.go

Don't try and create default namespace

---

controller/configentry_controller_test.go

Refactor the CRD controller test cases to make them smaller and easier to maintain.
Previously each test had a case for each config entry type. This PR leaves the cases for the CRUD tests but for the edge case tests it removes the cases and just uses `ServiceDefaults` because it's a simple config entry with no prereqs. This change was made to reduce the complexity of the edge case tests and because all the cases were testing the exact same code paths of the generic `configentry_controller`.
Adds one permutation to `TestConfigEntryControllers_doesNotDeleteUnownedConfig` to test what happens when the metadata key is empty.

Simplify controller test cases

---

connect-inject/handler.go
connect-inject/handler_test.go
subcommand/common/common.go
subcommand/common/common_test.go
subcommand/consul-sidecar/command.go
subcommand/consul-sidecar/command_test.go
subcommand/inject-connect/command.go

- Exits if the merged metrics server can't come up
- Clarify comments/error messages about unprivileged ports
Addresses additional comments from https://github.com/hashicorp/consul-k8s/pull/438
Unit tests
Code review

Consul sidecar will exit if merged metrics server is unable to start.

---

CHANGELOG.md
connect-inject/consul_sidecar.go
connect-inject/consul_sidecar_test.go
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go
connect-inject/handler_test.go
subcommand/common/common.go
subcommand/common/common_test.go
subcommand/consul-sidecar/command.go
subcommand/consul-sidecar/command_ent_test.go
subcommand/consul-sidecar/command_test.go
subcommand/inject-connect/command.go

- Add support for metrics merging
How I've tested this PR: These changes have been tested as a part of separate PRs. This is the merge PR for the feature.
Checklist:

Feature metrics

---

subcommand/consul-sidecar/command.go
subcommand/consul-sidecar/command_test.go

- Add flag for service registration in consul sidecar.
- This flag allows configuring the consul sidecar to run service
registration, or disable it in favor of a centralized service
regitstration controller.
Unit tests
Code review
Checklist:

Add flag for service registration in consul sidecar

---

connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
connect-inject/handler_ent_test.go
connect-inject/handler_test.go
go.mod
go.sum
subcommand/inject-connect/command.go

- Rebase master to get the latest updates to controller-runtime and associated libraries
- Update code and test fixtures to use the updated libraries.
Checklist:

Rebase master on feature-tproxy

---

go.mod
go.sum

Updating the API package to the latest version from current `master`
Checklist:

Update consul API package

---

.circleci/config.yml
go.mod
go.sum

bump consul version to 1.10.0-rc2

---

go.mod
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/create_or_update.go

- Suggestions from https://github.com/hashicorp/consul-k8s/pull/531
How I've tested this PR: Unit Tests
How I expect reviewers to test this PR: Code Review

Fix review comments from PR#531

---

CHANGELOG.md
go.mod
go.sum

How I expect reviewers to test this PR: Review content
Checklist:

Add changelog for consul 1.10.0 release

---

.circleci/config.yml

- Update CI config to use latest consul images.
How I've tested this PR: ci pipelines
How I expect reviewers to test this PR: hit approve

Upate consul images on ci config

---

CHANGELOG.md

- git bit my changelog
code review
code review
Checklist:

Fix changelog that got merged incorrectly

---

README.md

- add a security disclaimer to the README
-
Checklist:

add a security disclaimer to the README

---

CHANGELOG.md

- Update changelog with monorepo changes, and copy over the "Unreleased" section of consul-helm changelog
- Adds new prefixes to changelog entries
review, suggest any changes to the convention if you prefer a different style
Checklist:

Update changelog for 0.33.0

---

.circleci/config.yml

- add approval step for helm so eco-releases pipeline doesn't automatically kick off helm

Add approval step for helm pipeline

---

control-plane/build-support/functions/10-util.sh
control-plane/build-support/scripts/dev.sh

- The git functions were failing because they should be run from top level

Fix make dev-tree git functions

---

charts/consul/Chart.yaml
charts/consul/values.yaml

Co-authored-by: Saad Jamal <saad@hashicorp.com>
Co-authored-by: Iryna Shustava <iryna@hashicorp.com>

Release 0.33.0

---

charts/consul/README.md

- Adds a README file to be displayed on https://artifacthub.io/packages/helm/hashicorp/consul
Checklist:

Helm Chart readme

---

README.md
charts/consul/README.md

- Remove requires requires Consul 1.1 and Consul 1.1 statements from Service Mesh and Service Discovery.
- Update Helm chart version and app version
Checklist:

Readme.md cleanup

---

charts/consul/hack/aws-acceptance-test-cleanup/main.go

There's a race condition were even though the NAT gateway was just
deleted, AWS won't delete the VPC because it still sees the NAT gateway
as a dependency. This fix retries the VPC delete up to 10 times (waiting
1s between retries).
* I haven't been able to
* code

Fix issue where VPCs weren't deleted

---

CHANGELOG.md

- Change tense of current CHANGELOG entries
- Add Envoy update to CHANGELOG
:eyes:
:eyes:
Checklist:
- [-] Tests added

Change tense of current changelog and add Envoy update entry

---

charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats

- Add partition support to ingress and terminating gateway
- unit tests
- deployed the gateways to helm and watch them spin up successfully with the correct config.
- code review
- deploy it in a partition if you'd like but it could be complicated. I can drop in screen shots.
Checklist:

Add partition support to ingress and terminating gateways

---

charts/consul/Chart.yaml

- Update chart version for release

Update chart version to consul-k8s 0.34.0

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

Update version of image in values file

---

hack/helm-reference-gen/fixtures/full-values.golden
hack/helm-reference-gen/main.go
hack/helm-reference-gen/main_test.go

See `.golden` for the difference. As requested by @david-yu 
How I've tested this PR: unit tests
How I expect reviewers to test this PR: code review
Checklist:

Add table of contents to helm ref

---

charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats

- Fixed the test that I broke with the newline
- Ran the bats test that was failing
- You can run the bats test too
Checklist:

Fix Helm test that I broke

---

control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go

- remove acl:"write" from controller policy as it is not required.
How I've tested this PR: tests
How I expect reviewers to test this PR: 👀

Remove acl: "write" from controller policy

---

acceptance/go.mod
acceptance/go.sum
control-plane/go.mod
control-plane/go.sum

- Update go.mod to consul version 1.11.0-beta2
- Pipelines
- 👁️ 👁️

Update go.mod to the latest from consul-api

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go

Let's release 0.36.0
- Update `imageK8S` in `values.yaml` to `0.36.0`
- Update `image` in `values.yaml` to `1.11.0`

🚀🚀🚀 Release/0.36.0

---

CONTRIBUTING.md

- Update the CONTRIBUTING file to reflect the monorepo

Update CONTRIBUTING to reflect monorepo change

---

CONTRIBUTING.md

- Add section on making changes, following what Consul does in their CONTRIBUTING file 
Checklist:

CONTRIBUTING: Making changes

---

.circleci/config.yml
acceptance/go.mod
acceptance/go.sum
acceptance/tests/controller/controller_namespaces_test.go
acceptance/tests/partitions/partitions_test.go
control-plane/controller/partitionexports_controller_ent_test.go
control-plane/go.mod
control-plane/go.sum

- Update consul image from beta2 to beta3
- 👀 
- 👀

support 1.11.0-beta3

---

CHANGELOG.md
CONTRIBUTING.md

- Update contributing (I forgot to in the last PR) and add changelog

add changelog and update contributing guide for go version

---

charts/consul/values.yaml

Fixes https://github.com/hashicorp/consul-k8s/issues/899

Add docs about choosing storage class

---

charts/consul/Chart.yaml
charts/consul/values.yaml

Update version to 0.38.0

---

CHANGELOG.md

Tidying up the changelog. 
-
-
Checklist:

CHANGELOG: add CLI upgrade command to UNRELEASED and note UBI Image bump to ubi-minimal:8.5

---

CHANGELOG.md

Update CHANGELOG.md for #923

---

CHANGELOG.md

fix changelog to be more accurate

fix changelog to be more accurate

---

charts/consul/values.yaml

- Add some hints for changes i proposed in #956
Checklist:

charts/consul: Add some hints for consul sidecar annotations

---

CHANGELOG.md

- Add Changelog describing new API Gateway deployment
Checklist:

CHANGELOG: Add Consul API Gateway to features to Changelog

---

CHANGELOG.md

- Update PR link to https://github.com/hashicorp/consul-k8s/pull/993
Checklist:

CHANGELOG: update PR link

---

.circleci/config.yml
CHANGELOG.md

- Fix changelog
- Fix circle ci config

Fix changelog and circle ci config

---

acceptance/tests/partitions/partitions_test.go

- update the name of the service to reflect updated service name in helm chart.
- 👀 
- 👀 
https://github.com/hashicorp/consul-k8s/blob/c06e501662ce1589e6fc213e2fa0ea691d6d6267/charts/consul/templates/partition-service.yaml#L8

update partition service name to the correct service name.

---

charts/consul/Chart.yaml
charts/consul/values.yaml

Set chart version to 0.40.0

---

charts/consul/values.yaml

- Incorporate docs feedback from https://github.com/hashicorp/consul/pull/12224 from @karl-cardenas-coding, since the Helm configuration docs are generated from values.yaml comments 
Checklist:

values.yaml: feedback from consul PR#12224

---

charts/consul/templates/NOTES.txt

- Remove index.html from docs link
- Add CLI reference
Lookin'.
Lookin'.

Add CLI link to Helm startup

---

README.md
assets/logo.svg

- I added the Consul logo to the header of the README.
Looks like this:

Add logo to header of README

---

.github/workflows/issue-context-bot.yml

This fixes an issue that was causing the issue-context-bot to not trigger.

Fix an issue with the issue-context-bot trigger.

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/values.yaml

- Bump envoy image to 1.20.2
ran tests
👀 
Checklist:

Bump envoy version

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- this release upgrades Envoy to 1.20.2
-
Checklist:

release 0.41.1

---

CONTRIBUTING.md

- fixing incorrect links related to acceptance tests
- 👀 
- Selected View File in below CONTRIBUTING.md entry in this PR and clicked links in the Acceptance test section to ensure Page Not Found issues no longer occur.
👀

Correcting paths to accpetance tests.

---

control-plane/connect-inject/annotations.go

Update comment for annotationService to reflect the docs

---

acceptance/tests/vault/vault_test.go

- Incorporate changes from #1103 
👀 
Checklist:

Update vault acceptance test to use boot token from vault

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- Update imageK8s to 0.42.0
- Update versions in Chart
:eyes:
:eyes:

Prerelease 0.42.0

---

charts/consul/values.yaml

- Comment changes based on feedback in this [docs PR](https://github.com/hashicorp/consul/pull/12669) 
- generated docs and had them approved by docs team
- 👀

Making changes to values.yaml for docs generation based on docs PR feedback.

---

.github/workflows/build-and-test.yml
.github/workflows/reusable-golangci-lint.yml

- Update the golangci-lint action and linter
- Fixes the linting failures we had yesterday
- Ran the jobs
👀 
Checklist:

Upgrade golangci-lint action and linter version

---

charts/consul/values.yaml

- Comment changes to values.yaml in https://github.com/hashicorp/consul/pull/12689
Checklist:

values.yaml: Address comments on https://github.com/hashicorp/consul/pull/12689

---

CHANGELOG.md

- Add entry to changelog that I completely forgot in https://github.com/hashicorp/consul-k8s/pull/1148
- Verify changelog entry is appropriate for https://github.com/hashicorp/consul-k8s/pull/1148
Checklist:

Add forgotten changelog entry 🤦‍♂️

---

CHANGELOG.md
charts/consul/README.md

- Set link to https://github.com/hashicorp/consul-k8s/pull/1115
- Add section around Changelog note for CLI
- Update README.md that shows up in artifact.io to reflect K8s 1.19+ requirement
Checklist:

CHANGELOG: Add section for CLI Bug fix and correct link

---

.circleci/config.yml
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-config-configmap.bats
charts/consul/values.yaml

- Incorporate changes from https://github.com/hashicorp/consul/pull/12504
- Requires consul 1.12 GA
👀 
Checklist:

Support per-listener TLS configuration for servers and clients

---

.circleci/config.yml
charts/consul/Chart.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/values.yaml

-bump envoy, consul, and consul-k8s image versions
pipeline
Checklist:

Prerelease 0.43.0

---

acceptance/framework/k8s/debug.go

- Adding replicaset set data to artifacts that get uploaded in CI.
- local test failure
👀 
Checklist:

Adding replicaset set data to artifacts that get uploaded in CI.

---

CHANGELOG.md

- Correcting 2 PR links for changelog and small formatting edit.s
Checklist:

CHANGELOG: Correct PR links for UNRELEASED 

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- Update imageK8s to 0.44.0
- Update versions in Chart
:eyes:
:eyes:

Pre-release 0.44.0

---

CHANGELOG.md

- update changelog for changes from #1235 
Checklist:

update changelog for community pr GH-1235

---

.github/workflows/test.yml
charts/consul/templates/crd-serviceintentions.yaml
control-plane/api/v1alpha1/serviceintentions_types.go
control-plane/api/v1alpha1/serviceintentions_types_test.go
control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
control-plane/connect-inject/peering_dialer_controller.go
control-plane/connect-inject/peering_dialer_controller_test.go
control-plane/go.mod
control-plane/go.sum

- Add peer field to intention CRD
- Bump api module
- unit tests
Checklist:

Add Peer field to Intention CRD source intention

---

acceptance/go.sum
control-plane/connect-inject/peering_acceptor_controller.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller.go
control-plane/connect-inject/peering_dialer_controller_test.go

- Add finalizers to peering acceptor and dialer
- Remove ownerRef from secret created by acceptor.
- go mod tidy
- Unit tests
- 👀 
Checklist:

Add finalizers to peering acceptor and dialer

---

acceptance/tests/basic/basic_test.go

- Uncomment tests cases that I think were commented out by mistake
N/A
N/A
Checklist:

Bring back basic acceptance tests cases

---

.github/workflows/build.yml
.release/ci.hcl

- CRT Onboarding
Test run through the CRT pipeline. See statuses on fd8f38c
Review statuses on fd8f38c
Checklist:

CRT Onboarding

---

.github/workflows/build.yml

- fix the version of the docker build github action
pipeline
👀 
Checklist:

Fix UBI build

---

.github/workflows/build.yml

- We don't need to publish to ECR
Checklist:

Remove ECR tags for docker images

---

.circleci/config.yml
acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go
charts/consul/templates/server-config-configmap.yaml
charts/consul/templates/server-podsecuritypolicy.yaml
charts/consul/templates/server-service.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/server-podsecuritypolicy.bats
charts/consul/test/unit/server-statefulset.bats

- Support t-proxy in acceptance tests for peers
- Ran acceptance tests locally
- 👀 
Checklist:

T-Proxy for peering tests

---

CHANGELOG.md
control-plane/Dockerfile

- Update alpine to 3.16 in the base image
-
Checklist:

Update alpine to 3.16

---

hack/aws-acceptance-test-cleanup/main.go

- To try and fix a failure like: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/6814/workflows/44697441-c2c3-4468-a3b2-6321a048fbbc/jobs/56002
-
Checklist:

aws-acceptance-test-cleanup: Increase ELB propagation wait time

---

acceptance/tests/peering/peering_connect_test.go
charts/consul/values.yaml

peering: update helm value doc

---

CHANGELOG.md
cli/version/version.go
control-plane/version/version.go

put repo in dev mode

---

control-plane/build-support/functions/10-util.sh

- change the sed matching regex
- manually ran the make command after exporting the desired version env vars
- 👀

Update the sed match to replace image

---

charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats
control-plane/connect-inject/container_init_test.go
control-plane/go.mod
control-plane/go.sum

Fix failing unit tests after rebasing Cluster Peering

---

charts/consul/values.yaml

Changes from corresponding docs PR: https://github.com/hashicorp/consul/pull/14221/files
-
-
Checklist:

values.yaml: add more detail around using connectCA with vault namespaces

---

CHANGELOG.md

Add CHANGELOG entry for Pull 1452

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

release 0.48.0

---

CHANGELOG.md
cli/version/version.go
control-plane/version/version.go

- put source back into dev mode.
-
Checklist:

put main back into dev

---

cli/cmd/install/install.go

some commit

---

acceptance/framework/vault/vault_cluster.go

- pin vault helm chart version to v0.21.0 in Acceptance tests
-
CI
👀 
Checklist:
- N/A CHANGELOG entry added 

pin vault helm chart version to v0.21.0 in Acceptance tests

---

cli/cmd/install/install.go

test change

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- Update main for 0.49.0 pre-release.
Checklist:

0.49.0 Pre-release

---

.github/workflows/backport.yml

- Updates the backport assistant configuration to use the squash method when automatically resolving backport PRs
👀
👀
Checklist:
- [n/a ] Tests added
- [ n/a] CHANGELOG entry added 

Update backport squash

---

CHANGELOG.md

- Trigger the pre-staging release of artifacts
-
-
Checklist:

Trigger the pre-staging release of artifacts

---

.github/workflows/test.yml
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

- update chart values
Checklist:

pre-release steps for 1.0.0-beta1

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

- update values/charts with correct images, and changelog.
👀 
👀 
Checklist:

put main back into dev mode

---

control-plane/build-support/functions/10-util.sh

- Updated `make prepare-dev` and `make prepare-release` to set the correct docker images depending on if its in dev mode or release mode.
We expect dev to point to the docker images mirror library: `docker.mirror.hashicorp.services/hashicorppreview/consul-k8s-control-plane:<consul-k8s-version-dev>`
We expect release to point to the live docker images library: `hashicorp/consul-k8s-control-plane:<consul-k8s-version>`
- Ran `make prepare-dev` and `make prepare-release` locally
- Look at the example commits I've put up
Checklist:
> Entries should use present tense (e.g. Add …

Update make scripts to point to correct docker image library

---

charts/consul/test/unit/partition-init-job.bats

- fixes a bats test
bats should pass
👀 
Checklist:

fix unit test in partition-init-job

---

CHANGELOG.md
charts/consul/Chart.yaml

pre-release-1.0.0-beta2

---

CHANGELOG.md
charts/consul/Chart.yaml
cli/version/version.go
control-plane/version/version.go

put main back in dev

---

.github/ISSUE_TEMPLATE/config.yml

- Add link to discuss forum from our issue template 
Checklist:

ISSUE TEMPLATE: Add link to discuss forum

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- changes to images
- put cli and control-plane in dev version
👀 
👀 
Checklist:

pre-release 1.0.0-beta3

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Pre release 1.0.0 beta3

---

CHANGELOG.md

- Added a changelog entry for #1581
- :eyes:
- :eyes:
Checklist:

Add CHANGELOG entry for PR 1581

---

CHANGELOG.md

- Adds changelog for backported feature from #1581
Checklist:

Add CHANGELOG entry for PR 1581 (#1627)

---

.circleci/config.yml
.github/workflows/build.yml
.github/workflows/reusable-acceptance.yml
.github/workflows/reusable-unit.yml
.github/workflows/test.yml
acceptance/framework/cli/cli.go
acceptance/framework/config/config.go
acceptance/framework/k8s/debug.go
control-plane/Makefile

- This PR adds Github actions acceptance tests for new PRs
- I've added more detailed changes to each commit message
- Ran pipelines
👀
**Please go through this PR commit by commit, it'll be much easier than looking at all the files changed at once**
Checklist:
TODO: all instances of local reusable workflows (i.e. ./.github/workflows/reusable-acceptance.yml) need to be changed back to read from main only before this is merged in

PR GitHub Actions Acceptance Tests

---

.github/workflows/test.yml

- Fix the missing branch tag for the reusable tests in GitHub actions
Checklist:

fix missing main branch tag

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml

- Backport #1574 which I forgot to include the backport label on
👀 
👀 
Checklist:

Backport api-gateway: Allow controller to read MeshService resource (#1574)

---

.release/release-metadata.hcl

- Point to correct License in metadata file.

Update License URL in release metadata file

---

charts/consul/templates/api-gateway-gatewayclassconfig.yaml
charts/consul/test/unit/api-gateway-gatewayclassconfig.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/values.yaml
cli/helm/values.go

- Cleanup any places where we missed some helm values from the agentless changes.
- This is most easily reviewed by commit.
- I am going to do a CHANGELOG pass also for all the PRs this release (probably Monday)
- ran unit, bats & acceptance tests
👀 
Checklist:

Remaining helm values changes and cleanup

---

CHANGELOG.md

release 0.49.x was missing this changelog

add missing changelog from backport

---

.release/ci.hcl

Related Slack thread [1](https://hashicorp.slack.com/archives/CR024M999/p1668530627387029) and [2](https://hashicorp.slack.com/archives/CR024M999/p1668547796941339) 
Waiting for confirmation on whether we need to add this to the other promote staging step also

fix release step by adding config for promote staging

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

set release back into dev mode

---

charts/consul/values.yaml

Updated some of the inline documentation around helm values required for peering. Also replaced a broken link with a new overview page of mesh gateways.
N/A
N/A

docs(peering): update helm value docs for GA

---

CHANGELOG.md

- I went back through all the PRs until the last release in October when the last check was done.
:eyes:
Checklist:

CHANGELOG updates for 1.0

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Arbitrary date set for next release date 
- Next release is 1.1.0
Checklist:

set main back to dev mode

---

CHANGELOG.md

Fix changelog for main to include 1.0.1

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Set Consul version to 1.14.2
- Add missing cni.namespace CHANGELOG entry
- Update phrasing of a previous fix to match what is in 0.49.2
👀 
:eyes:
Checklist:

Release 1.0.2

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Set Consul version to 1.13.4
- Remove dev mode
- Add a couple CHANGELOG entries that were missing
👀 
👀 
Checklist:

Release 0.49.2

---

cli/cmd/status/status_test.go

- There was an extra space in the command test output.
unit test passes
👀 
Checklist:

fix failing cli test on main

---

CHANGELOG.md

- https://github.com/hashicorp/consul-k8s/pull/1778 changelog 
Checklist:

Update CHANGELOG.md to describe change global.extraLabels

---

.github/workflows/jira.yaml

- Attempt to sync JIRA issues to Github
Checklist:

Create JIRA Github Sync

---

.github/workflows/jira.yaml

JIRA: Forgot to close conditional 

---

.github/workflows/jira.yaml

- Getting further, I think this is the issue. 
Checklist:

JIRA: missing quotes on extraFields

---

charts/consul/values.yaml

- Add in canonical URL for links
- Follow up to https://github.com/hashicorp/consul-k8s/pull/1805
Checklist:

values.yaml - Fix helm docs for 1.0.x

---

.circleci/config.yml
CHANGELOG.md
README.md
charts/consul/README.md
charts/consul/test/terraform/aks/main.tf
charts/consul/test/terraform/eks/main.tf
charts/consul/test/terraform/gke/main.tf

Bump Kubernetes versions for clouds for acceptance tests (#1852)

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Change release branch to dev mode
Checklist:

Set dev mode for 0.49.4

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

- Update consul to 1.14.4 
- Updated consul-dataplane to 1.0.1
- Update CHANGELOG to include both releases
👀 
👀 
Checklist:

Update main to latest consul & consul-dataplane versions (late Jan 2023)

---

CHANGELOG.md

- I missed a line in the CHANGELOG
Checklist:

Missing a line in the changelog

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Update version to 1.0.4
- Update CHANGELOG
👀 
👀 
Checklist:

Pre-release update for 1.0.4

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Setting branch to dev mode
👀 
👀 
Checklist:

Prepare dev 0.49.5

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Prepare dev for 1.0.5
👀 
👀 
Checklist:

Prepare dev for 1.0.5

---

acceptance/tests/cli/cli_install_test.go
cli/cmd/troubleshoot/proxy/proxy.go
cli/cmd/troubleshoot/upstreams/upstreams.go
cli/go.mod
cli/go.sum

- update troubleshoot module and some messages for consistency across consul and consul-k8s
- ran it alongside the consul CLI to compare
- Review or run it as well

update troubleshoot module and some messages for consistency across consul and consul-k8s

---

charts/consul/values.yaml

Update links to support DevDot

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Update the version for this release branch to be 1.1.1
-
👁️ 👁️ 
👁️ 👁️ 
Checklist:

Set the next version to 1.1.1 for this release branch

---

.changelog/1770.txt
.changelog/1934.txt
.changelog/1953.txt
CHANGELOG.md

- removed unreleased section, we'll now be generating changelog entries as part of the release process
- added changelog files for next release
Checklist:

added changelog files

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- Updates to consul 1.13.7
👀 
👀 
Checklist:

update to consul 1.13.7

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- Update to Consul 1.14.5
👀 
👀 
Checklist:

update to consul 1.14.5

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- prepare for release
👀 
👀 
Checklist:

Prepare 1.0.5 Release

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Ready for release
-
👀 
👀 
Checklist:

Prepare for 0.49.5 Release

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Prepare for the 1.1.1 release
-
👀 
👀 
Checklist:

prepare for 1.1.1 release

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Prepare release of 1.1.1
Checklist:

Prepare Release 1.1.1

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Prepare for next release, 1.1.2

Prepares release branch for 1.1.2

---

.github/workflows/merge.yml
.github/workflows/pr.yml

- Doing some minor cleanup to hopefully make things a little easier to understand when you visit the actions page in consul-k8s-workflows
- I've run the pipelines several times
:eyes:
Checklist:

Update status on PRs

---

control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go

- control-plane unit tests are failing on the 1.1.x branch and we need this fix
Ran the automation
:eyes:
Checklist:

Backport ACL error changes

---

.changelog/2068.txt

- Add changelog for community PR #2068 
Checklist:

Add changelog for NET 2422

---

control-plane/api-gateway/consul/config_entry_translation.go
control-plane/api-gateway/consul/config_entry_translation_test.go

- translate k8s secret to inline certificate
Run unit tests
read the code/run unit tests
Checklist:

APIGW4CONK8S: k8s secret translation to inline secret

---

control-plane/api-gateway/controllers/gateway_class_config_controller.go

- Updates the GatewayClassConfig controller to use the common finalizer methods.
Tests
Tests

Updates GatewayClassConfig Controller to use common finalizer methods

---

.github/workflows/backport.yml

Manual Backport: fix backport assistant not finding new branches

---

.github/workflows/backport.yml
.github/workflows/changelog-checker.yml

- Backport of #2113
- Backport of #2105

Manual Backport: Update Backport Assistant and Changelog Checker

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- My other PR reverted a revert.
:eyes:
:eyes:
Checklist:

Fix dev mode on main

---

.changelog/2156.txt

- Changelog follow-on for #2156 
:eyes:
:eyes:
Checklist:

Changelog: add support for idleTimeout in Service Router config

---

.changelog/2204.txt
.github/workflows/build.yml
control-plane/Dockerfile

- Update UBI base image for the controller to 9.2, which has an active support window.
How I've tested this PR: XXXXX
Checklist:

build(deps): update controller UBI base to 9.2

---

control-plane/api/v1alpha1/servicedefaults_types.go
control-plane/api/v1alpha1/servicedefaults_types_test.go

- Pointer wasn't checked in translation. Now it is :) 
-
With the unit of tests.
👀 
Checklist:

NET-4285 add check for pointer

---

control-plane/controllers/configentry_controller.go

This PR expands upon some of the tproxy enhancements to better support sameness-groups. We now store the virtual IP if a service-defaults or intention targeting a specific destination service exists.

Persist virtual-ips for intentions / service-defaults.

---

CHANGELOG.md
acceptance/tests/fixtures/bases/crds-oss/servicedefaults.yaml
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Update values, charts and CHANGELOG for Release 1.1.2
:eyes:
:eyes:
Checklist:

Prerelease 1.1.2

---

control-plane/api-gateway/binding/binder.go
control-plane/api-gateway/binding/binder_test.go
control-plane/api-gateway/binding/result.go
control-plane/api-gateway/binding/validation.go

This is a PR to incorporate changes to bring our implementation within conformance of the upstream spec's conformance test suite.
Checklist:

[API Gateway] Conformance Test Fixes

---

control-plane/api-gateway/controllers/gateway_controller_integration_test.go

- Test for ensuring reconciliation does not go on infinitely
-
Wrote the test/ran the test
read the code/run the test
Checklist:

Ensure Reconciliation Stops

---

Makefile
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Put branch back in dev mode
-
Checklist:

Put branch back in dev mode 1.2.x

---

.github/workflows/build.yml
.github/workflows/jira-issues.yaml
.github/workflows/jira-pr.yaml

- ran the tsccr tool to update all actions. Actions are run from main so no need to backport
Checklist:

[chore]: Pin github action workflows

---

.changelog/2310.txt
charts/consul/templates/api-gateway-controller-deployment.yaml
charts/consul/templates/api-gateway-gatewayclassconfig.yaml
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/cni-daemonset.yaml
charts/consul/templates/enterprise-license-job.yaml
charts/consul/templates/gateway-cleanup-job.yaml
charts/consul/templates/gateway-resources-job.yaml
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/templates/partition-init-job.yaml
charts/consul/templates/server-acl-init-cleanup-job.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/templates/webhook-cert-manager-deployment.yaml
charts/consul/values.yaml

* added imagePullPolicy for images in values.yaml
* fix: renamed pullPolicy key according to image
* fixed dafault always in tmpl
* changed structure of image in yaml
* revert changes
* added global imagePullPolicy
* fixed typo
* added changelog file
-
-
Checklist:

added imagePullPolicy for images in values.yaml (#2310)

---

.changelog/2284.txt
control-plane/Dockerfile

- Manual backport of #2284 
-
👀 
👀 
Checklist:

Update Alpine to 3.18 for CVE-2023-2650

---

.github/workflows/pr.yml

point at main workflow

---

acceptance/ci-inputs/aks_acceptance_test_packages.yaml
acceptance/ci-inputs/eks_acceptance_test_packages.yaml
acceptance/ci-inputs/gke_acceptance_test_packages.yaml
acceptance/ci-inputs/kind_acceptance_test_packages.yaml

- Remove packages that don't exist
-
Checklist:

removed cli test package

---

acceptance/framework/config/config.go
acceptance/framework/flags/flags.go
acceptance/tests/fixtures/bases/ingress/ingress.yaml
acceptance/tests/fixtures/bases/ingress/kustomization.yaml
acceptance/tests/sync/sync_catalog_test.go

- Create a test for the ingress resource that runs against EKS
- Run against EKS locally
- 👀 
Checklist:

Add acceptance test to test sync + ingress

---

.github/workflows/build.yml

- Manual backport of #2337 
👀 
👀 
Checklist:

Manual backport of 2337 into release/1.0.x

---

.github/workflows/build.yml

- Manual backport of #2337 
👀 
👀 
Checklist:

Manual backport of 2337 into release/0.49.x

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- This ports https://github.com/hashicorp/consul-k8s/pull/2451
-
Checklist:

use latest 1.2 dataplane (#2451)

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- This fixes the failing ingress gateway tests
- Failures were caused from using an older version of consul dataplane, bumped the version to the latest nightly dev build of dataplane `1.0`
👀 
👀 
Checklist:

Fix failing ingress-gateway tests

---

.changelog/2392.txt

- Update changelog for #2392 
Checklist:

PR breaking change release note change

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/build-support/scripts/consul-enterprise-version.sh
control-plane/version/version.go

Prepare Release 1.2.0

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Updates Release branch 0.49.x to be ready for 0.49.8 dev

ready for 0.49.8 dev

---

CHANGELOG.md

Adds changelog value for 0.49.7

Adds changelog values for 0.49.7

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Updates artifacts to publish dev versions of 1.3.0
- Updates chart values to test 
How I've tested this PR: N/A
How I expect reviewers to test this PR: 👓

build: update versions to 1.3.0-dev

---

acceptance/framework/connhelper/connect_helper.go

Backport/derekm/fix test flakes/tightly leading coral

---

acceptance/framework/connhelper/connect_helper.go

Backport/derekm/fix test flakes/poorly powerful katydid

---

acceptance/tests/connect/connect_proxy_lifecycle_test.go

reactivate proxy-lifecycle tests

---

charts/consul/todo.txt

- Something left over from a merge
-
👀 
👀 
Checklist:

chore: Remove todo.txt

---

.github/workflows/merge.yml
.github/workflows/nightly-acceptance.yml
.github/workflows/nightly-api-gateway-conformance.yml

- Nightly tests should run against 1.17-dev

test: update nightly tests to consul 1.17-dev

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Prepares 1.1.x branch for dev
-
Checklist:

Prepare 1.1.x for dev

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Preparese 1.0.x branch for dev
-
Checklist:

Prepare 1.0.x for Dev

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Set release/0.49.x to dev mode
-
👀 
👀 
Checklist:

Set release/0.49.x to dev mode for 0.49.9

---

acceptance/framework/config/config.go
charts/consul/templates/tls-init-cleanup-job.yaml

some node selector fixes

---

.github/workflows/merge.yml
.github/workflows/nightly-acceptance.yml
.github/workflows/nightly-api-gateway-conformance.yml
.github/workflows/nightly-cleanup.yml
.github/workflows/weekly-acceptance-0-49-x.yml
.github/workflows/weekly-acceptance-1-0-x.yml
.github/workflows/weekly-acceptance-1-1-x.yml

- Removed unused workflow inputs.

test: remove unused workflow inputs

---

.github/workflows/merge.yml
.github/workflows/nightly-acceptance.yml
.github/workflows/pr.yml
.github/workflows/weekly-acceptance-0-49-x.yml
.github/workflows/weekly-acceptance-1-0-x.yml
.github/workflows/weekly-acceptance-1-1-x.yml

I think this should resolve errors like https://github.com/hashicorp/consul-k8s/actions/runs/5615117399/job/15215290442?pr=2604#step:2:17 due to the missing arg in the target workflow.
Follow-up to #2589.
Checklist:

Manual backport of test: remove unused workflow inputs (#2589) into release/1.0.x

---

charts/consul/test/terraform/eks/main.tf

windows eks terraform

---

charts/consul/templates/crd-exportedservices.yaml
charts/consul/templates/crd-ingressgateways.yaml
charts/consul/templates/crd-meshes.yaml
charts/consul/templates/crd-peeringacceptors.yaml
charts/consul/templates/crd-peeringdialers.yaml
charts/consul/templates/crd-proxydefaults.yaml
charts/consul/templates/crd-servicedefaults.yaml
charts/consul/templates/crd-serviceintentions.yaml
charts/consul/templates/crd-serviceresolvers.yaml
charts/consul/templates/crd-servicerouters.yaml
charts/consul/templates/crd-servicesplitters.yaml
charts/consul/templates/crd-terminatinggateways.yaml
control-plane/api/v1alpha1/serviceresolver_types.go
control-plane/api/v1alpha1/serviceresolver_types_test.go
control-plane/api/v1alpha1/zz_generated.deepcopy.go
control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
control-plane/config/crd/bases/consul.hashicorp.com_meshes.yaml
control-plane/config/crd/bases/consul.hashicorp.com_peeringacceptors.yaml
control-plane/config/crd/bases/consul.hashicorp.com_peeringdialers.yaml
control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml
control-plane/config/rbac/role.yaml
control-plane/config/webhook/manifests.yaml

Add support for requestTimeout in Service Resolver spec

---

.github/workflows/build.yml

- Adding missing entries for tsscr before July 31st deadline
:eyes:
:eyes:
Checklist:

Add missing tsccr entries

---

charts/consul/test/terraform/gke/main.tf
charts/consul/test/terraform/gke/variables.tf

terraform windows nodes for gke

---

.changelog/2302.txt
charts/consul/templates/client-config-configmap.yaml
charts/consul/templates/create-federation-secret-job.yaml
charts/consul/templates/gossip-encryption-autogenerate-job.yaml
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/templates/server-acl-init-cleanup-job.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/server-config-configmap.yaml
charts/consul/templates/telemetry-collector-deployment.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/templates/tls-init-job.yaml
charts/consul/test/unit/client-config-configmap.bats
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/create-federation-secret-job.bats
charts/consul/test/unit/gossip-encryption-autogenerate-job.bats
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/server-acl-init-cleanup-job.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/server-config-configmap.bats
charts/consul/test/unit/telemetry-collector-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/test/unit/tls-init-job.bats
charts/consul/values.yaml

- Manually backporting the changes in #2302 to the `1.2.x` release branch
Unit tests & CI
Checklist:

Manual backport of added logLevel field for components  

---

acceptance/tests/api-gateway/api_gateway_external_servers_test.go
acceptance/tests/api-gateway/api_gateway_lifecycle_test.go
acceptance/tests/api-gateway/api_gateway_tenancy_test.go
acceptance/tests/api-gateway/api_gateway_test.go
acceptance/tests/partitions/partitions_gateway_test.go

- Increase the retries and add config entry retries
- Manual backport of #2716 
:eyes:
👀 
Checklist:

Acceptance tests: increase api-gateway retries (#2716)

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Updates values for release of 1.1.4

Prerelease work for 1.1.4

---

CHANGELOG.md

Adds changelog for release of 1.1.4

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Reset to dev after release of 1.1.4

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Reset branch for dev after release of 1.0.9

Updates branch for dev

---

charts/consul/values.yaml

- Updates helm values based on review from docs team.

Update helm values based on review from docs team

---

charts/consul/values.yaml

- Updates helm values based on changes made here: https://github.com/hashicorp/consul/pull/18450

updates helm values based on review from docs team

---

.changelog/2781.txt
.changelog/2789.txt
charts/consul/templates/_helpers.tpl
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/test/unit/server-statefulset.bats

* Bring in PR #2771 and run with CI which fixes https://github.com/hashicorp/consul-k8s/issues/751 
-
-
Checklist:

Add readOnlyRootFilesystem to security context (#2771)

---

.changelog/2790.txt
control-plane/subcommand/server-acl-init/anonymous_token.go
control-plane/subcommand/server-acl-init/anonymous_token_test.go

Backport/net 5174/anonymous token policy/manual

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Prepare for 1.1.5 patch release
-
Checklist:

1.1.5 Pre-release

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- After release, swap branch back into dev mode
-
Checklist:

Prepare 1.1.x for next release cycle

---

.changelog/2952.txt
acceptance/framework/config/config.go
acceptance/framework/consul/helm_cluster.go
acceptance/framework/flags/flags.go
charts/consul/templates/crd-tcproutes.yaml
charts/consul/test/unit/crd-tcproutes.bats
charts/consul/values.yaml

- Manual backport of #2952 2952
-
Checklist:

Manual backport of GKE Autopilot support into release/1.2.x

---

control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go

Ignore non-TCP L4 ports in K8s services. This is expected behavior and also prevents unintended duplication of Service port values registered to Consul (which is not supported) when ports have multiplexed L4 traffic.
- Filter Service port registrations to L4 TCP protocol ports
- Retain debug logging that helped identify this issue
How I've tested this PR: Added a unit test and made it pass
Checklist:

[NET-5314] Limit v2 Service port registration to L4 TCP ports

---

charts/consul/values.yaml

- bumps to the latest consul collector image
1. Load tested and e2e tested with consul-k8s framework.
[CC-5899](https://hashicorp.atlassian.net/browse/CC-5899)
[CC-5899]: https://hashicorp.atlassian.net/browse/CC-5899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump default consul collector image

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

[1.0.x] Post-release steps

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

[1.1.x] Post-release steps

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

[1.2.x] Post-release steps

---

.changelog/2941.txt

- Changelog summarizing V2 highlights for the RC release.
[Consul version](https://github.com/hashicorp/consul/pull/18994/files)
How I've tested this PR: N/A
Checklist:

docs: add V2 RC changelog

---

control-plane/config-entries/controllersv2/meshconfig_controller_test.go

(cherry picked from commit 1c393284848ec574d27f1a298c1c2006440d6f0f)
-
-
Checklist:

fix test (#3009)

---

.github/workflows/nightly-acceptance-1-3-0-rc1.yml

activate rc nightly

---

acceptance/framework/consul/helm_cluster.go
acceptance/tests/cloud/load/main_test.go
acceptance/tests/cloud/load/remote.go
acceptance/tests/cloud/load/remote_load_test.go
acceptance/tests/fixtures/bases/pingpong/template.tmpl
charts/consul/values.yaml

- this change adds the load testing code into consul-k8s
- this is not meant to be part of the CI but it will export a fair number of metrics into HCP

Load test for CTGW

---

control-plane/build-support/scripts/consul-enterprise-version.sh

- Update enterprise version script to support repos that aren't hashicorp for custom enterprise images
-
Checklist:

make enterprise version script more flexible

---

charts/consul/Chart.yaml
charts/consul/values.yaml
control-plane/build-support/scripts/consul-enterprise-version.sh

- Going to point these to images built off of RC branches for the time being
-
Checklist:

use custom images

---

control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go

- Link TODO comments to tickets for easier tracking
Comments-only changes.

[NET-5559] Clean up TODOs in Endpoints Controller V2

---

Makefile
charts/consul/Chart.yaml
charts/consul/values.yaml
control-plane/build-support/functions/10-util.sh
control-plane/build-support/scripts/consul-enterprise-version.sh

- point RC to RC images now that they exist
- added some make targets for pointing to RC images a bit easier
👀 
- If acceptance tests run then it means we are pulling the right images
👀 
Checklist:

Point RC to RC Images

---

acceptance/tests/wan-federation/wan_federation_test.go

- Cherry pick of https://github.com/hashicorp/consul-k8s/pull/3032
-
Checklist:

Fix Flaky Wan Federation Failover Test (#3032)

---

control-plane/go.mod
control-plane/go.sum
control-plane/helper/webhook-configuration/webhook_configuration.go
control-plane/helper/webhook-configuration/webhook_configuration_test.go

- same as https://github.com/hashicorp/consul-k8s/pull/3033
-
see other PR
Checklist:

Fixing validating cert webhooks, fixing replace statements for go mod

---

control-plane/connect-inject/controllers/endpointsv2/endpoints_controller.go
control-plane/connect-inject/controllers/endpointsv2/endpoints_controller_test.go

Rather than indiscriminately registering any service that is not excluded due to NS allow/deny-listing, selectively register services that target injected pods (i.e. in alignment with the mesh webhook).
Do not deregister services that already exist when endpoints are empty; rather, predicate registration on pod injection and deletion on service deletion from Kubernetes. In the future, we can layer on explicit allow/deny annotations for services as needed.
This is already implemented by existing workload selector logic that filters on mesh-inject status; this change removes `TODO`s, updates comments, and adds tests for the desired behavior.
- Update `TODO`s and comments
- Add tests verifying behavior
How I've tested this PR: Added tests
How I expect reviewers …

[NET-5704] feat(control-plane): v2 only register services for injected pods

---

charts/consul/templates/crd-gatewaypolicies.yaml
control-plane/api-gateway/binding/binder.go
control-plane/api-gateway/binding/binder_test.go
control-plane/api/v1alpha1/gatewaypolicy_types.go
control-plane/config/crd/bases/consul.hashicorp.com_gatewaypolicies.yaml

- Main branch PR for https://github.com/hashicorp/consul-k8s/pull/3045
-
Checklist:

NET-5818 Gateway Policy Status

---

.github/workflows/backport.yml

- Reverting my changes from earlier as backport assistant has bugs and fails to cherry pick. 
- Keep the update though.
- I will backport after it is merged
Checklist:

revert backport assistant changes

---

control-plane/api-gateway/binding/binder_test.go
control-plane/api-gateway/binding/result.go
control-plane/api-gateway/binding/result_test.go
control-plane/api-gateway/binding/validation.go
control-plane/api-gateway/binding/validation_test.go

- 1.3-rc merge of https://github.com/hashicorp/consul-k8s/pull/3051
Checklist:

Net 5640 route binding unit tests 1 3 branch

---

control-plane/api-gateway/binding/binder_test.go
control-plane/api-gateway/binding/result.go
control-plane/api-gateway/binding/result_test.go
control-plane/api-gateway/binding/validation.go
control-plane/api-gateway/binding/validation_test.go

- Adds unit tests for Route Binding changes for JWT work
- fixes a small bug with error messaging for route binding errors
Checklist:

[Net-5640] Route Binding Unit Tests

---

.copywrite.hcl
control-plane/config/crd/external/.yml
control-plane/config/crd/external/gatewayclasses.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/gateways.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/grpcroutes.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/httproutes.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/referencegrants.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/tcproutes.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/tlsroutes.gateway.networking.k8s.io.yaml
control-plane/config/crd/external/udproutes.gateway.networking.k8s.io.yaml

* Regenerate external Gateway CRDs
* Remove errant .yml
* Add external CRDs to copywrite ignore

Manual backport of Fix Gateway API CRDs

---

Makefile

- Add a new make target to support preparing a release branch for dev.
-
Checklist:

Add New Make Target for prepare release dev

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

bump patch version

---

control-plane/api-gateway/controllers/gateway_controller_integration_test.go

- unskip halting test
- add JWT configurations to routes/gw for halting tests
Ran the tests
Read the code
Run the tests
Checklist:

[NET-5402] Halting Test with JWT

---

.github/workflows/build.yml

* build: remove last set-output from yaml
* add patch version for dataplane, now required.
---------
-
-
Checklist:

Mw/port dans changes from prepare 1 4 dev (#3104)

---

charts/consul/Chart.yaml

- Update the chart to have the lowest supported version.
- I missed this on main
Checklist:

Update chart version

---

charts/consul/Chart.yaml

Reverts hashicorp/consul-k8s#3152

main: revert k8s version to 1.22.x 

---

charts/consul/Chart.yaml

- Reverts https://github.com/hashicorp/consul-k8s/pull/3152
Checklist:

1.3.x: revert k8s version to 1.22.x

---

charts/consul/Chart.yaml

- Revert https://github.com/hashicorp/consul-k8s/pull/3152
Checklist:

1.3.0: revert k8s version to 1.22.x

---

CHANGELOG.md
acceptance/go.mod
acceptance/go.sum
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/go.mod
control-plane/go.sum
control-plane/version/version.go

Prepare release v1.2.3

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prepare release v1.1.7

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Post release 1.2.3

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Post release for 1.0.11

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

post release for 1.1.7

---

CHANGELOG.md

Updating changelog after release

Release 1.2.3, 1.1.7 and 1.0.11 changelog

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

- `$ make prepare-release`
Visual inspection
See above
**Checklist:**

NET-6303 Prepare for release of 1.3.0

---

.changelog/3180.txt
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/server-statefulset.bats
charts/consul/values.yaml

PR to run CI and then merge the following community contribution by @alemuro: https://github.com/hashicorp/consul-k8s/pull/3102
Refer to that PR for discussion and examples.

[NET-5025] Helm Chart: Support StatefulSet PVC retention

---

CHANGELOG.md

Port changelog entries for 1.3.0 over from #3182.
This includes adjusting the CHANGELOG as indicated by Dan in https://github.com/hashicorp/consul-k8s/pull/3182#discussion_r1385611738
Visual inspection
See above
**Checklist:**

NET-6303 Add 1.3.0 notes to changelog

---

control-plane/api/mesh/v2beta1/mesh_gateway_types.go
control-plane/config-entries/controllersv2/mesh_gateway_controller.go
control-plane/config-entries/controllersv2/mesh_gateway_controller_test.go

- Add `onCreateUpdate` and `onDelete` hooks to the `MeshGatewayController`
- Include `TODOs` for future implementation inside these hooks
- Added unit test coverage
- Visual inspection
- 🤖 tests pass
**Checklist:**

NET-6563 Stub CRUD hooks for MeshGatewayController

---

charts/consul/templates/gateway-resources-clusterrole.yaml
charts/consul/templates/gateway-resources-configmap.yaml
charts/consul/test/unit/gateway-resources-configmap.bats
control-plane/go.mod
control-plane/go.sum
control-plane/subcommand/gateway-resources/command.go
control-plane/subcommand/gateway-resources/command_test.go

- create gateway class and gateway class config for mesh gateway if mesh gateways are enabled
tests
:eye: 
:eye: 
Checklist:

[NET-6462] Update gateway resources job for mesh gw v2

---

charts/consul/templates/crd-gatewayclasses-external.yaml
charts/consul/templates/crd-gateways-external.yaml
charts/consul/templates/crd-grpcroutes-external.yaml
charts/consul/templates/crd-httproutes-external.yaml
charts/consul/templates/crd-proxyconfigurations.yaml
charts/consul/templates/crd-referencegrants-external.yaml
charts/consul/templates/crd-routetimeoutfilters.yaml
charts/consul/templates/crd-tcproutes-external.yaml
charts/consul/templates/crd-tlsroutes-external.yaml
charts/consul/templates/crd-udproutes-external.yaml
control-plane/config/crd/bases/mesh.consul.hashicorp.com_proxyconfigurations.yaml
control-plane/config/rbac/role.yaml

There is currently a diff when running `make ctrl-generate ctrl-manifests` on `main`. This makes development cycles tedious as we generally try to avoid including unrelated changes in new PRs.
The diff in this PR is the result of running `make ctrl-generate ctrl-manifests` directly on the `main` branch.
Run the command on this branch, verify there is no diff now.
See above
**Checklist:**

Update generated files and manifests

---

charts/consul/templates/gateway-resources-clusterrole.yaml
charts/consul/templates/gateway-resources-configmap.yaml
control-plane/subcommand/gateway-resources/command.go
control-plane/subcommand/gateway-resources/command_test.go

- create mesh gateway resource from gateway resources job
-
- :eye:  
- ran in kind cluster
:eye: 
run in kind cluster
Checklist:

[NET-6404] Create Mesh Gateway Resource from Gateway Resources Job

---

charts/consul/templates/crd-gatewayclassconfigs.yaml
control-plane/api/mesh/v2beta1/gateway_class_config_types.go
control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
control-plane/gateways/config.go
control-plane/gateways/deployment.go
control-plane/gateways/deployment_dataplane_container.go
control-plane/gateways/role.go
control-plane/subcommand/gateway-resources/command_test.go

- Updates gateway class config to be able to read in the port modifier value
- ran tests
- run tests
- :eye:

[NET-6769] Update GatewayClassConfig for PortModifier

---

control-plane/api-gateway/cache/consul.go

- The reason api-gateway previously required service write on everything because it would create intentions for any service that the gateway was configured to route to. This is no longer the case as we only need service write on the api-gateway
- This PR suggest only give service write on the API gateway 
- This is the first step into removing this completely to use templated policies

Reduce permissions of API gateway policy

---

.github/workflows/merge.yml

big change

---

.github/workflows/pr.yml

add github actor to merge

---

.github/workflows/merge.yml

test concurrency

---

.github/workflows/merge.yml
.github/workflows/pr.yml

add github actor to be used in workflows

---

control-plane/config-entries/controllersv2/mesh_gateway_controller.go

This adds some missing ownership declarations that support garbage collection
👀 visually verify that the type ownership declarations for the new resources we're creating with recent PRs match the one that was already there

Declare ownership of Deployment, Role and RoleBinding on MeshGateway controller

---

charts/consul/templates/gateway-resources-configmap.yaml
control-plane/gateways/deployment.go
control-plane/subcommand/gateway-resources/command.go
control-plane/subcommand/gateway-resources/command_test.go

- Adds support for tolerations for mesh gw
- :eye: 
- tests
- ran local kind cluster with tolerations set and checked the deployment to ensure it got copied over
- :eye: 
- tests
- ran local kind cluster with tolerations set and checked the deployment to ensure it got copied over

[NET-6756] Tolerations for MeshGW

---

charts/consul/templates/crd-gatewayclassconfigs.yaml
charts/consul/templates/gateway-resources-configmap.yaml
control-plane/api/mesh/v2beta1/gateway_class_config_types.go
control-plane/config/crd/bases/mesh.consul.hashicorp.com_gatewayclassconfigs.yaml
control-plane/gateways/deployment.go
control-plane/gateways/deployment_dataplane_container.go
control-plane/gateways/deployment_test.go

- Added hostPort support
- Ran local consul test

NET-6788 - Mesh Gateway Host Port Support

---

control-plane/gateways/service.go

CI is failing due to this [bug](https://github.com/hashicorp/consul-k8s/actions/runs/7231348088/job/19733070644#step:8:182) in Consul-K8s
Run unit tests
Run `make dev-docker` to ensure build complies
Ensure unit tests pass and linter catches type errors

fix build issues as a result of portModifier

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Updates the changelog
- Preps for the release of 1.2.4

Prepare 1.2.4 for release

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- Updates the changelog
- Preps for the release of 1.1.8

Prepare 1.1.8 for release

---

charts/consul/Chart.yaml
charts/consul/values.yaml

I set the wrong Consul dep version in the previous PR. This fixes that.

Fix the Consul dependency version

---

Makefile

This make command did not get backported to `release/1.2.x`. I need to add it to reset the branch for dev mode.

Add `prepare-release-dev` make command to `release/1.2.x`

---

acceptance/tests/sameness/sameness_test.go

- This PR syncs up changes made to the main sameness test with `1.2.x`. It avoids localities as that is a `1.3.x`+ feature.
-

Release 1.2.x Sync up sameness acceptance tests with main

---

CHANGELOG.md

- Update the changelog on `main` with patch releases

Add Changelog entries from patch releases

---

charts/consul/templates/gateway-resources-configmap.yaml
control-plane/gateways/config.go
control-plane/subcommand/gateway-cleanup/command.go
control-plane/subcommand/gateway-resources/command.go

- Delete meshgateways on resource cleanup if they exist
- Local helm install/helm uninstall and checked logs of resource cleanup pod
- local helm install/uninstall
- glance over

delete gateway in cleanup-gateway-resouces

---

control-plane/api-gateway/gatekeeper/init.go
control-plane/connect-inject/constants/constants.go
control-plane/connect-inject/webhook/container_init.go
control-plane/connect-inject/webhookv2/container_init.go
control-plane/gateways/deployment_dataplane_container.go
control-plane/gateways/deployment_init_container.go
control-plane/gateways/deployment_test.go
control-plane/subcommand/flags/consul.go
control-plane/subcommand/flags/consul_test.go

- Add tls support for mesh gateways
-
- ran tests
- ran the setup at https://github.com/hashicorp/shared-consul-examples/tree/main/k8s/meshgw-v2 and saw it all spin up correctly
- :eye: 
- ran tests
- ran the setup at https://github.com/hashicorp/shared-consul-examples/tree/main/k8s/meshgw-v2 and saw it all spin up correctly

[NET-6829] Add tls support for mesh gateways

---

charts/consul/templates/crd-meshgateways.yaml
charts/consul/templates/gateway-resources-configmap.yaml
control-plane/config/crd/bases/mesh.consul.hashicorp.com_meshgateways.yaml
control-plane/gateways/service.go
control-plane/gateways/service_test.go
control-plane/go.mod
control-plane/go.sum

- Add listeners to meshgateway CRD
- Local install, updating unit tests
- CI passes
- Local helm install

Net 6822 - consul consul k8s add listeners to mesh gateway consume for service

---

acceptance/ci-inputs/aks_acceptance_test_packages.yaml
acceptance/ci-inputs/eks_acceptance_test_packages.yaml
acceptance/ci-inputs/gke_acceptance_test_packages.yaml
acceptance/ci-inputs/kind_acceptance_test_packages.yaml

added comment about cloud test package

---

acceptance/framework/consul/helm_cluster.go

- Manual backport of https://github.com/hashicorp/consul-k8s/pull/3375
-

Manual backport of cleanup acceptance tests

---

CHANGELOG.md
acceptance/go.mod
acceptance/go.sum
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/go.mod
cli/go.sum
cli/version/version.go
control-plane/go.mod
control-plane/go.sum
control-plane/version/version.go

Prerelease 1.2.5

---

charts/consul/templates/connect-inject-clusterrole.yaml
control-plane/api/common/common.go
control-plane/api/mesh/v2beta1/api_gateway_types.go
control-plane/controllers/resources/api-gateway-controller.go
control-plane/subcommand/inject-connect/v2controllers.go

- stub api gateway controller for v2

[NET-7243] Stub APIGateway Controller for v2

---

control-plane/api/mesh/v2beta1/api_gateway_types.go

- Add fields to API Gateway required by kubesig
- This is a simple change to struct, logic will be tested in follow up PRs
- Ensure the fields added are correct.

Net 7376 Status struct on api gateway with required info from kubesig

---

control-plane/controllers/resources/mesh_gateway_controller_test.go

* Backport of https://github.com/hashicorp/consul-k8s/pull/3532
Fix meshgw tests

Fix meshgw tests (#3532)

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/build-support/functions/10-util.sh
control-plane/version/version.go

Mw/prepare main for 1.5 dev

---

control-plane/api-gateway/gatekeeper/deployment_test.go
control-plane/build-support/scripts/mod_tidy.sh

fixed copyright headers

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prerelease 1.3.3

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prepare release 1.2.6

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prepare release 1.1.10

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Set release/1.1.x to 1.1.11 dev mode

---

charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Set release/1.2.x to 1.2.7 dev mode

---

charts/consul/values.yaml

- Follow up to https://github.com/hashicorp/consul/pull/18759/files from @maksimnosal

values.yaml - tlsServerName docs

---

.changelog/3668.txt
.github/workflows/build.yml

- Manual backport of https://github.com/hashicorp/consul-k8s/pull/3668

1.2.x: Publish ECR images

---

.github/workflows/build.yml

- Follow up to https://github.com/hashicorp/consul-k8s/pull/3668. Typo on tags, forgot the `|`

build.yml: typo on tags

---

.changelog/3668.txt
.github/workflows/build.yml

- Backport of https://github.com/hashicorp/consul-k8s/pull/3668 without FIPS

1.1.x: Publish ECR images

---

.changelog/3668.txt
.github/workflows/build.yml

- Manual backport of https://github.com/hashicorp/consul-k8s/pull/3668

1.3.x: publish ECR images

---

control-plane/build-support/functions/10-util.sh

- NOTE is clobbering BREAKING changes in release notes

release: add \n to end of NOTE for releases 

---

charts/consul/values.yaml

See review comments in https://github.com/hashicorp/consul/pull/20770
Once this is approved and merged, I'll open a corresponding PR to sync changes to `consul` and backport to `release/1.18.x`.

docs: update 1.4.0 Helm docs per Docs team feedback

---

charts/consul/test/terraform/aks/variables.tf

-Fix azure CI error https://github.com/hashicorp/consul-k8s-workflows/actions/runs/8196549423/job/22417134801

updates k8s version

---

.changelog/3758.txt
control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go

https://github.com/hashicorp/consul-k8s/pull/3758

backport 1.4.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors

---

.changelog/3758.txt
control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go

https://github.com/hashicorp/consul-k8s/pull/3758

backport 1.2.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors

---

.changelog/3758.txt
control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go

https://github.com/hashicorp/consul-k8s/pull/3758

backport 1.1.x [net-8411] bug: fix premature token and service instance deletion due to pod fetch errors

---

.github/workflows/pr.yml

[prerelease-1.4.1] Add option to disable CE test

---

.github/workflows/pr.yml

[prerelease-1.2.7] Disable CE test

---

.github/workflows/pr.yml

[prerelease-1.3.4] Disable CE test

---

.github/workflows/pr.yml

[prerelease-1.1.11] Disable CE test

---

.github/workflows/merge.yml
.github/workflows/nightly-acceptance.yml
.github/workflows/weekly-acceptance-0-49-x.yml
.github/workflows/weekly-acceptance-1-0-x.yml
.github/workflows/weekly-acceptance-1-1-x.yml

[1.2.7] Disable all CE tests

---

.github/workflows/merge.yml
.github/workflows/nightly-acceptance.yml
.github/workflows/weekly-acceptance-1-1-x.yml

[1.4.1] Add flag to disable CE tests

---

acceptance/framework/consul/helm_cluster.go
control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
control-plane/connect-inject/webhook/container_init.go

- Cleanup some formatting that an overzealous go tool did in a previous PR.
CI
👀

Cleanup formatting to follow consul-k8s standard

---

.github/workflows/build.yml

Missed followup to https://github.com/hashicorp/consul-k8s/pull/3859
-
-

Re-add get-go-version

---

acceptance/framework/consul/helm_cluster.go
control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
control-plane/connect-inject/webhook/container_init.go

- Manual backport of #3852
-
CI
👀

Backport: Cleanup formatting to follow consul-k8s standard (#3852)

---

.github/workflows/merge.yml
.github/workflows/nightly-acceptance.yml
.github/workflows/pr.yml
.github/workflows/weekly-acceptance-1-1-x.yml
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/go.mod
cli/go.sum
cli/version/version.go
control-plane/version/version.go

[1.4.x] Post-release steps

---

.changelog/3873.txt
control-plane/controllers/configentries/configentry_controller.go
control-plane/controllers/configentries/configentry_controller_test.go

Fixes https://github.com/hashicorp/consul-k8s/issues/3406
-
-

GH-3406 - Only error for config entries from different datacenters when the config entries are different

---

.github/workflows/build.yml
control-plane/Dockerfile

Manually backport these two PRs into 1.1.x
https://github.com/hashicorp/consul-k8s/pull/3921/files
https://github.com/hashicorp/consul-k8s/pull/3942/files

Net 9069/add license backport 1.1.x

---

.github/workflows/build.yml
control-plane/Dockerfile

Manually backport these two PRs into 1.2.x
https://github.com/hashicorp/consul-k8s/pull/3921/files
https://github.com/hashicorp/consul-k8s/pull/3942/files

Net 9069/add license backport 1.2.x

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prepare release for 1.4.2 (https://github.com/hashicorp/engineering-docs/blob/main/consul/consul-k8s/release-process.md#prepare-the-point-release-branch)

Prepare release for 1.4.2

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prepare release for 1.3.5 (https://github.com/hashicorp/engineering-docs/blob/main/consul/consul-k8s/release-process.md#prepare-the-point-release-branch)

Prepare release for 1.3.5

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Prepare release for 1.2.8 (https://github.com/hashicorp/engineering-docs/blob/main/consul/consul-k8s/release-process.md#prepare-the-point-release-branch)

Prepare release for 1.2.8

---

CHANGELOG.md
Makefile
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Puts release/1.3.x back into dev mode after 1.3.5 release

Post release 1.3.5

---

CHANGELOG.md
Makefile
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

Puts release/1.2.x back into dev mode after 1.2.8 release

Post release 1.2.8

---

CHANGELOG.md

Updates changelog with changelogs from the releases of 1.4.2, 1.3.5, 1.2.8, and 1.1.12

Adds post release changelog for 1.4.2, 1.3.5, 1.2.8, and 1.1.12

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

prepare release 1.4.3

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

prepare release 1.2.9

---

CHANGELOG.md

Update Changelog in main

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

- Stage final changes for 1.5.0 release.

build: stage 1.5.0 release

---

hack/aws-acceptance-test-cleanup/main.go

- Currently we do not clean up volumes created as part of Consul-K8s Acceptance Tests that run nightly in CI
- Automate cleanup of all volumes that match the test resource tags
Ran the script locally to cleanup volumes.
**RESULT**: All volumes were cleaned up successfully

NET-9994: Cleanup volumes created as part of acceptance tests

---

control-plane/api-gateway/gatekeeper/gatekeeper_test.go

Add new test case for gateway referencing TLS `Secret` in a different namespace
🤖 tests pass
🤖 tests pass

[NET-9606] Add test case covering cross-namespace TLS certificate Secret ref

---

control-plane/api-gateway/binding/cleanup.go
control-plane/api-gateway/binding/cleanup_test.go
control-plane/api-gateway/controllers/gateway_controller.go
control-plane/subcommand/inject-connect/v1controllers.go

manual backport of #4067 
---------
-
-

[NET-9500] Cleanup orphaned inline-certs and acl role/policy (#4067)

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Stage release of 1.4.4

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Stage release of 1.5.1

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Stage release of 1.3.7

---

acceptance/ci-inputs/kind_acceptance_test_packages.yaml

release/1.3.x: remove v2 tests

---

acceptance/ci-inputs/kind_acceptance_test_packages.yaml

release/1.4.x: remove v2 tests 1.4

---

CHANGELOG.md
version/version.go

Prep branch for future release

---

CHANGELOG.md

This ports over the changelog entries from #4176 #4181 #4182 #4183 
N/A

Update changelog to reflect latest patch releases

---

.github/scripts/check_skip_ci.sh
.github/workflows/pr.yml

- When non-code files are changed don't run unit tests/acceptance tests as all should already be passing

Add non-code files/directories to skip for acceptance tests

---

.github/scripts/check_skip_ci.sh
.github/workflows/pr.yml

- manual backport of https://github.com/hashicorp/consul-k8s/pull/4194
-

update check skip ci to only run acceptance tests for code changes

---

acceptance/tests/consul-dns/coredns-original.yaml
acceptance/tests/consul-dns/coredns-template.yaml
acceptance/tests/fixtures/cases/terminating-gateway-destinations/terminating-gateway.yaml
acceptance/tests/fixtures/cases/terminating-gateway-namespaces/external-service.yaml
acceptance/tests/fixtures/cases/terminating-gateway-namespaces/terminating-gateway.yaml
acceptance/tests/fixtures/cases/terminating-gateway/external-service.yaml
acceptance/tests/fixtures/cases/terminating-gateway/terminating-gateway.yaml
charts/consul/templates/crd-tcproutes-external.yaml
hack/copy-crds-to-chart/main.go

Run generators

---

control-plane/Dockerfile

Fix the missing argument in the path of the LICENSE file
[ticket](https://hashicorp.atlassian.net/browse/NET-10782)
Follow-up to https://github.com/hashicorp/consul-k8s/pull/3939.

make missing changes in the backport

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

prepare release 1.1.15

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- 1.15.11 isn't an image you can pull, 1.15.10 is!
-

fix consul version

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

prepare release 1.4.5

---

.changelog/4287.txt
control-plane/Dockerfile

[release/1.1.x] update ubi image and go-discover

---

.changelog/4287.txt
control-plane/Dockerfile

[release/1.3.x] update ubi image and go-discover

---

.changelog/4287.txt
control-plane/Dockerfile

[release/1.4.x] update ubi image and go-discover

---

.changelog/4287.txt
control-plane/Dockerfile

[release/1.5.x] update ubi image and go-discover

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

prepare 1.5.3

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

prepare 1.4.6

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

prepare 1.3.9

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

prepare 1.1.16

---

.github/workflows/pr.yml
CHANGELOG.md

changelog 1.5.x

---

.github/workflows/pr.yml
CHANGELOG.md

changelog 1.3.x

---

.github/workflows/pr.yml
CHANGELOG.md

changelog 1.1.x

---

.github/workflows/pr.yml
CHANGELOG.md

changelog 1.4.x

---

.github/workflows/weekly-acceptance-1-6-x.yml

- Initialize 1.6 tests as outlined in this document https://github.com/hashicorp/engineering-docs/blob/main/consul/consul-k8s/release-process.md

Init 1.6 weekly tests

---

.github/workflows/pr.yml

- Add Unit test helm gen to check list

add exception to pr.yaml

---

version/version.go

Init 1.6.0 release branch

---

charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

- Update versions to reflect next patch release, 1.6.1, using `make prepare-release-dev`
👀 
👀

Prepare branch for future patch release

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

Update changelog, chart + values.yaml using `make prepare-release`
👀 
👀

Prepare 1.6.0 release

---

CHANGELOG.md

- Port over changelog entry for 1.6.0
👀 
👀

Update changelog to include 1.6.0

---

charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Update versions to reflect next minor release, 1.7.0, using `make prepare-release-dev`
👀 
👀

Prepare branch for future minor release

---

charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

post 1.4.7 - update versions

---

charts/consul/Chart.yaml
version/version.go

post 1.5.4 - update versions

---

charts/consul/Chart.yaml
version/version.go

post 1.6.1 - update versions

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

1.5.4 release

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

1.4.7 release

---

charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

post-1.1.17 - update versions in 1.1.x

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

1.1.17 release

---

CHANGELOG.md

add changelog entries from releases

---

.changelog/4520.txt
acceptance/go.mod
acceptance/go.sum
charts/go.mod
cli/go.mod
cli/go.sum
control-plane/cni/go.mod
control-plane/cni/go.sum
control-plane/go.mod
control-plane/go.sum
hack/aws-acceptance-test-cleanup/go.mod
hack/camel-crds/go.mod
hack/copy-crds-to-chart/go.mod
hack/helm-reference-gen/go.mod
version/go.mod

Fixed following CVEs:
GHSA-vvgc-356p-c3xw in golang.org/x/net@v0.37.0
GO-2025-3595 in golang.org/x/net@v0.37.0
GO-2025-3553 in github.com/golang-jwt/jwt/v4@v4.5.1 GHSA-mh63-6h87-95cp in github.com/golang-jwt/jwt/v4@v4.5.1 stdlib in Go GO-2025-3563@1.23.7
-
-

Fixed CVEs

---

.github/CODEOWNERS
.github/workflows/reusable-conditional-skip.yml

Codeowner change

---

.github/CODEOWNERS
.github/workflows/reusable-conditional-skip.yml

Codeowner change 1.5.x

---

.release/security-scan.hcl
CHANGELOG.md
acceptance/go.mod
acceptance/go.sum
control-plane/go.mod
control-plane/go.sum

- Update dependencies and security fixes for 1.7.0-rc2 release
-

CVE fix in release 1.7.0 rc2

---

.github/CODEOWNERS
.github/workflows/reusable-conditional-skip.yml

- changing CODEOWNERS and skipping CODEOWNERS from PR check
-

changing CODEOWNERS and skipping CODEOWNERS from PR check

---

.release/security-scan.hcl
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Post release 1.7.0

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- fixed charts after last release
-

fixed charts after last release

---

.changelog/4570.txt
control-plane/Dockerfile

- Updating base image for UBI containers
- Ran trivy scans locally to validate no high or critical bugs

update base image for ubi9-minimal for fixing sec vulns

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Preparation for release 1.7.1

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

Preparation for release 1.6.5

---

version/version.go

- update: version to next release 1.7.2 in version.go

update: version to next release 1.7.2 in version.go

---

CHANGELOG.md
version/version.go

Post release activity for v1.7.1:
- update: changelog from release 1.7.1
- update: version to 1.7.2 in version.go

Post release/1.7.1

---

.github/workflows/reusable-conditional-skip.yml

- update changed-files action to version 46.0.1 for CVE fix
-

update changed-files action to version 46.0.1 for CVE fix

---

control-plane/Dockerfile

- update: upgrade alpine version from 3.19 to 3.21 in Dockerfile

update: upgrade alpine version to 3.21 in Dockerfile

---

.release/security-scan.hcl
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

- updated changelog for release/1.5.9
- suppressed CVEs that are not fixed yet
n/a
n/a

stage v1.5.9

---

CHANGELOG.md
version/version.go

- updated changelog and version post release

update changelog and version for 1.5.9

---

version/version.go

Updating changelog and versions

---

.changelog/4679.txt
acceptance/go.mod
charts/go.mod
cli/go.mod
control-plane/cni/go.mod
control-plane/go.mod
hack/aws-acceptance-test-cleanup/go.mod
hack/camel-crds/go.mod
hack/copy-crds-to-chart/go.mod
hack/helm-reference-gen/go.mod
version/go.mod

- upgrade go version to 1.24.5 in all go.mods
-

update: go version to 1.24.5

---

.release/security-scan.hcl
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

- add: changelog for release
- update: versions in chart

Prepare Release 1.6.8

---

charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

- update: next version in version.go

update: next version in version.go

---

acceptance/ci-inputs/kind-inputs.yaml

Backport - kind version update to v0.27.0

---

.release/security-scan.hcl

Periodic clean up of vulnerabilities suppressed earlier. The fixes for these vulnerabilities will taken up as a separate activity.

Resolve & clean up vulnerability suppression - main

---

.release/security-scan.hcl

Periodic clean up of vulnerabilities suppressed earlier. The fixes for these vulnerabilities will taken up as a separate activity.

Resolve & clean up vulnerability suppression - 1.8.x

---

.github/workflows/pr-cloud-acceptance.yml
.github/workflows/pr.yml
acceptance/ci-inputs/aks_acceptance_test_packages.yaml
acceptance/ci-inputs/eks_acceptance_test_packages.yaml
acceptance/ci-inputs/gke_acceptance_test_packages.yaml
acceptance/ci-inputs/kind_acceptance_test_packages.yaml

- made each package re-runnable as a matrix job

granularity for package level concurrency and rerun availability

---

.changelog/4776.txt
.github/workflows/pr-cloud-acceptance.yml
.github/workflows/pr.yml
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/dns-proxy-deployment.yaml
charts/consul/templates/prometheus.yaml
charts/consul/templates/server-config-configmap.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/values.yaml

- feat: add dual stack support for Consul configuration
-

feat: add dual stack support for Consul configuration

---

.github/workflows/pr-cloud-accepance.yml
.github/workflows/pr.yml
acceptance/ci-inputs/aks_acceptance_test_packages.yaml
acceptance/ci-inputs/eks_acceptance_test_packages.yaml
acceptance/ci-inputs/gke_acceptance_test_packages.yaml
acceptance/ci-inputs/kind_acceptance_test_packages.yaml

granularity for package level concurrency and rerun availability (#4744)

---

.release/security-scan.hcl
CHANGELOG.md
charts/consul/Chart.yaml
version/version.go

Prepare 1.9.0 rc1

---

.release/security-scan.hcl
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

- Resolved the sec vuls
- Updated the changelogs
- Updated the consul k8, dataplane, k8s versions

Prepare 1.7.6

---

.github/workflows/pr-cloud-accepance.yml
.github/workflows/pr.yml
.github/workflows/reusable-conditional-skip.yml
acceptance/ci-inputs/aks_acceptance_test_packages.yaml
acceptance/ci-inputs/eks_acceptance_test_packages.yaml
acceptance/ci-inputs/gke_acceptance_test_packages.yaml
acceptance/ci-inputs/kind_acceptance_test_packages.yaml

Backport of [commit#4797](https://github.com/hashicorp/consul-k8s/pull/4797/commits/73b71c3e2595a40e2d5ee80e39a1ce8918b34d84)

Backport: granularity for package level concurrency and rerun availability (#4744)

---

.release/security-scan.hcl
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
version/version.go

- Resolved the sec vuls
- Updated the changelogs
- Updated the consul k8, dataplane, k8s versions

Prepare 1.6.10
