connect-inject/handler.go
connect-inject/handler_test.go

Currently, a default port is only set if it has an associated name.
This uses the first Pod's ContainerPort directly even if it doesn't
have an associated name.
All of the documentation already supports this design.
Adds a test case for this scenario, as well as tests for the `portValue`
function that parses the name or direct port string.

Support unnamed ports for annotation defaults

---

catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go
subcommand/sync-catalog/command.go

This takes the great [PR](https://github.com/hashicorp/consul-k8s/pull/18) from @jipperinbham that adds ClusterIP service sync support and adds a flag to make it optional. Since there are many Kubernetes environments where ClusterIPs aren't externally routeable, this allows people in those environments an easier way to only sync routeable services.

Add support for ClusterIP Services

---

catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go
subcommand/sync-catalog/command.go

This updates the NodePort sync logic to use the node's ip address, rather than the pod's ip. This puts a fully routable address into the sync, making it possible to externally sync with these services.
Additionally, it updates the port determination logic to take the first defined NodePort when there are multiples. It also now takes the first address when the ports are unnamed, as well as adding tests for this case.

Nodeport syncing updates

---

catalog/from-consul/source.go
catalog/from-consul/source_test.go
catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go
catalog/from-k8s/syncer.go
catalog/from-k8s/syncer_test.go
catalog/from-k8s/testing.go
subcommand/sync-catalog/command.go

Rebased version of #39 .
Notes from that PR:
Customizable Consul catalog sync tag makes it possible to share a single Consul cluster with more than one K8S cluster. With the hardcoded tag ("k8s"), all catalog-sync processes would delete each other's services from Consul.
Controlled via "-consul-k8s-tag" flag.

Customizable Consul sync tag

---

connect-inject/handler.go
connect-inject/handler_test.go

Fixes #20 .
Previously, the default annotations were added to the local Pod object, but
no patches were created to update the running pod. This meant we were bypassing
the check for empty annotations, causing errors when trying to add an annotation
to a nonexistent object.

Create patches for the default annotations that are being added

---

subcommand/sync-catalog/command.go

Fixes #61. Updates the message to include information on how to format the input.

Clarify help message for `consul-write-interval` flag

---

catalog/from-k8s/syncer.go

With the `default:` clause here, the time.After doesn't work and just
falls through to `default` causing a spin loop on the consul agent.

catalog/from-k8s: Don't spin loop on watchService

---

build-support/docker/Dev.dockerfile
connect-inject/container_init.go
connect-inject/container_init_test.go

From #62:
This PR adds support to specify the datacenter for a consul connect upstream from the K8s annotation.
https://www.consul.io/docs/connect/proxies.html#datacenter
The new format has the form of the following example:
```
annotations:
"consul.hashicorp.com/connect-service-upstreams": "[service]:[port]:[datacenter]"
```
`datacenter` is an optional parameter

Add datacenter support to inject annotation

---

connect-inject/handler.go
connect-inject/handler_test.go
subcommand/inject-connect/command.go

This removes the LoggingHandler and instead uses a normal handler
with specific logging for things that are useful to have in the logs.
Previously, the logs were completely overrun with health check logs,
making it difficult to find useful information.

Switch logging scheme to limit log spam from health checks

---

connect-inject/container_init.go
connect-inject/container_init_test.go

Fixes Git Issue on #70 
This PR adds support to specify the [prepared query](https://www.consul.io/docs/connect/proxies.html#upstreams) for consul connect upstream from the K8s annotation.
```
annotations:
"consul.hashicorp.com/connect-service-upstreams": "prepared_query:[query name]:[port]"
```
Services named `prepared_query` will caught in the prepared query logic, if that does occur.

Add prepared_query annotation support 

---

README.md

After running into an issue merging a PR where someone had
merged master into their branch, I realized it was important to
be explicit about the merging strategy we're following in this
repo. Hopefully this will help clarify things for future contributors.

Add information about PRs being merged using `rebase`

---

catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go

after this fix registration works when consul-k8s observe all namespaces

use service's namespace while get endpoints to register

---

connect-inject/container_init.go
helper/cert/notify.go
helper/coalesce/coalesce.go

These are just a few small changes while working on putting this repo into CircleCI. Govet had the following complaints:
```
helper/cert/notify.go:31: the cancelFunc function is not used on all paths (possible context leak)
helper/cert/notify.go:38: this return statement may be reached without using the cancelFunc var defined on line 31
helper/coalesce/coalesce.go:54: the curCancel function is not used on all paths (possible context leak)
helper/coalesce/coalesce.go:63: this return statement may be reached without using the curCancel var defined on line 54
```
Instead of deferring `curCancel()` after the context creation which could bubble up an _infinite_ number of `cancelFunc()` calls or placing it in the error check which is what `go vet` is complaining about (since I don't think it …

govet and gofmt cleanup

---

connect-inject/container_init.go

This allows both services and their proxies to show up in the Consul
catalog. It makes it easier to find services in the Intentions UI.
These services are registered through the client pod on their local node,
like the proxies are, so unlike services in the catalog sync, they
are not connected to the `k8s-sync` synthetic node.
Note: it looks like there are a couple of whitespace gofmt changes
included as well. They do not change any functionality.

Register Connect services along with their proxies

---

catalog/from-k8s/resource.go

This PR is to fix duplicated service ID. In my case, I would like to register my service with the same service name, but different deployments. Unfortunately, it is possible that those services are deploy on the same node. Then, the node IP is not unique enough to generate the service ID anymore and that’s why sometimes my registered services appear and disappear randomly from catalog API.
So I change the way to generate service ID from service name with node IP to service name with endpoints IP instead.

Fix duplicated service ID

---

.circleci/config.yml
Makefile
build-support/functions/20-build.sh

This PR adds CircleCI configuration to run a few things on all branches: 
* go fmt
* go vet
* run go tests
* build binaries for all our supported distros
* save all of these artifacts in CircleCI so they can be downloaded and tested if needed
Outside of CI configuration:
* removed gocov since `go test` can also produce coverage reports. Also added a new make target to run coverage reports if needed (`make cov`) 
* add an environment variable to pass the parallel flag to gox since `runtime.NumCPU()` reports the wrong CPU count on containers in CircleCI
* glob the binaries when copying out to support the `.exe` extension for windows
The most recent run of this pipeline is here: https://circleci.com/workflow-run/4430c58b-f6a4-46bd-9f5d-595e0b226796
The artifact uploading can be seen here:

Add CircleCI configuration

---

connect-inject/handler.go
connect-inject/handler_test.go

A pod's namespace is not present in the pod's metadata section at the
time of injection, so we must exclude based on the namespace included
in the AdmissionRequest that we decode.
This updates the test for this scenario, as well as updating the actual/
expected variable order in `require.Equal` to match the spec.

Exclude system namespaces from Connect injection

---

catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go
subcommand/sync-catalog/command.go

Add `K8sConsulPrefix` flag to be used to prepend K8s services in Consul with a prefix

Support Prefixes #140

---

connect-inject/container_init.go
connect-inject/handler.go
connect-inject/handler_test.go
go.mod
go.sum
subcommand/inject-connect/command.go

Added in Consul 1.5, proxy defaults allow users to define config
options that will be automatically applied to all injected sidecar
proxies.
Additionally, it is possible to enable Connect services to be centrally
registered.

Support central config and proxy defaults

---

connect-inject/container_init.go

The addition of the `-cas` flag to the `consul config write` keeps the
system from doing the additional work of writing the central config again
if it already exists. However, if the config does exist, this call
returns an error code. This update handles that case.

Handle error output from central config write command

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go

Allows users to add Consul tags to their services via a Kubernetes
annotation.

Add tag annotation to Connect service registration

---

connect-inject/container_sidecar.go

Fixes #120
I think I added this properly but let me know if it should have been somewhere else.

Add the —max-obj-name-len parameter to the injected Envoy container

---

catalog/from-k8s/resource.go
catalog/from-k8s/resource_test.go

Previously, we were registering the Service's port instead of the
underlying endpoint port (as specified by targetPort).
If the two were different, this would result
in traffic being directed to the wrong port.
Also handles edge cases around ports being overridden via annotations.
Fixes https://github.com/hashicorp/consul-k8s/issues/132
Some background:
* `ClusterIP` services can have a `targetPort` that specifies which port on the `Pod` that traffic should be routed to. We weren't taking that into account and always using `port`.
* We are registering each `Endpoint` as a service instance. The endpoints are the Pod IPs so obviously we need to use the Pod's port, i.e. `targetPort`.
* We support overriding which port we use via an annotation …

Register Endpoint ports for ClusterIP services

---

subcommand/acl-init/command.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go

This PR fixes #138 and https://github.com/hashicorp/consul-helm/issues/186
* The `server-acl-init` command would previously exit on any failure. Now it runs indefinitely, retrying each of its tasks until they are complete. It will retry every 1s.
* It can be run before Consul servers are up and will wait for a leader to be elected.
* It is now idempotent and will handle objects in Consul and Kubernetes that have already been created, either by bypassing those steps or updating the values (e.g. if the bootstrap Secret already exists it will update its data) 
* I've added tests for this behaviour using the Consul testagent and also a simple httpserver mock

Idempotent server-acl-init command

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go

Adding one commit to #135 that:
* added more tests and expanded existing tests to check the template more fully
* added back support for the old tags annotation but marked as deprecated
* fixed bug where the -default-protocol flag wasn't being used
* cleaned up whitespace in rendered init container script
Original PR description:
This PR is a roll up of previous PRs as I found a bug. The original code was not setting the tags and service metadata for the proxy. While the tests were passing for this as the test only searches for the existence of tags in the command. Since this data was present on the service config the test passed however for Consul L7 config tags and metadata need to be present on the proxy.
Content:
Add annotation to allow the configuration of service tags in Consul …

All creation of metadata and tags from k8s annotations

---

Makefile
build-support/docker/Dev.dockerfile

Previously it was building consul-k8s inside a new container. This meant
it had to download all its dependencies inside the container. This
change builds consul-k8s on the host machine and then copies the binary
to the new container. Since the host machine already has all the
dependencies this is much faster.

Make dev-docker target faster

---

.circleci/config.yml

Trying to fix these errors that have suddenly shown up in CI (https://app.circleci.com/jobs/github/hashicorp/consul-k8s/429)
```
2 errors occurred:
--> windows/amd64 error: exit status 2
Stderr: # golang.org/x/sys/windows
/go/pkg/mod/golang.org/x/sys@v0.0.0-20191007154456-ef33b2fb2c41/windows/dll_windows.go:21:6: missing function body
/go/pkg/mod/golang.org/x/sys@v0.0.0-20191007154456-ef33b2fb2c41/windows/dll_windows.go:24:6: missing function body
note: module requires Go 1.12
--> windows/386 error: exit status 2
Stderr: # golang.org/x/sys/windows
/go/pkg/mod/golang.org/x/sys@v0.0.0-20191007154456-ef33b2fb2c41/windows/dll_windows.go:21:6: missing function body
/go/pkg/mod/golang.org/x/sys@v0.0.0-20191007154456-ef33b2fb2c41/windows/dll_windows.go:24:6: missing function body
note: module …
```

Use go 1.13 in builds

---

build-support/functions/20-build.sh

If you have more than one binary in your `$GOBIN` already,
running make dev and make dev-docker will fail
because it tries to copy everything in the `$GOBIN`
with a glob. Instead, it should copy the binary
it just installed, namely `consul-k8s`.

Don't fail when there are many binaries in $GOBIN

---

commands.go
subcommand/delete-completed-job/command.go
subcommand/delete-completed-job/command_test.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go

Add new `delete-completed-job` command that is used to delete the `server-acl-init` Kubernetes Job once it's completed. This enables us to keep the `server-acl-init` job as **not** a Helm hook. When it was a helm hook it got deleted by Helm which was great, however as a helm hook it caused deadlock when users ran helm with `--wait` because it needs to run concurrently with everything coming up.
This command will run in its own Job and clean up the `server-acl-init` job.
Also fixes server-acl-init as follows:
- previously, if already bootstrapped it would still try to pass out the bootstrap token and reload all the servers. Now it assumes that if the bootstrap Secret is created, all the servers are bootstrapped. I think it's a safe assumption because the Job won't complete until it …

Delete completed job command and fix server-acl-init

---

catalog/from-consul/sink.go
catalog/from-consul/sink_test.go

When syncing from Consul to Kubernetes, lowercase the service names so
they're valid Kubernetes services.
Fixes https://github.com/hashicorp/consul-k8s/issues/110

sync-catalog tok8s lowercase service names

---

CONTRIBUTING.md
README.md

Most users that come to the readme won't be looking for docs on
contributing and they may be confusing. Moving them to Contributing.md.
Also added a description of our Connect Inject feature.

Move contributing docs to Contributing.md

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go
connect-inject/handler_test.go
subcommand/inject-connect/command.go

Previously, we would write a service-defaults config regardless of the
value of the -default-protocol flag or the Pod's protocol annotation. If
neither of these were set, we would write a config with protocol set to
the empty string. This is the same as setting it to tcp. So for every
service, we were by default setting its protocol to tcp.
If a user explicitly created a global proxy-defaults config and set the
protocol to, say, http. Then our service-defaults config would override
that protocol. This behaviour was unexpected because users had never
explicitly told us to write a service-defaults config and it wasn't
helping them.
This change will cause us to only write a service-defaults config if the
protocol is explicitly set–either via the -default-protocol flag or via
the Pod …

Only write service-defaults if protocol set

---

connect-inject/container_init.go
connect-inject/container_init_test.go

See https://github.com/hashicorp/consul-k8s/issues/163 for bug description.
The fix is to make the service id and proxy service id environment variables (since they're dynamic based on the pod name) so that they can be interpolated in the bash script without copy paste errors.
* Carries https://github.com/hashicorp/consul-k8s/pull/164. Just needed a rebase and a test update.
* Fixes https://github.com/hashicorp/consul-k8s/issues/163

fix: proxy's destination service id is not service id

---

commands.go
connect-inject/envoy_sidecar.go
connect-inject/handler.go
connect-inject/handler_test.go
connect-inject/lifecycle_sidecar.go
connect-inject/lifecycle_sidecar_test.go
go.mod
go.sum
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go
subcommand/lifecycle-sidecar/command.go
subcommand/lifecycle-sidecar/command_test.go

This command is expected to run in a sidecar in all Connect
injected Pods. The command ensures that the service is registered with
the node's Consul client by re-registering the service on a configurable
period. This is necessary because if the Consul Client is restarted,
e.g. during an upgrade, it loses its registrations. With this sidecar,
the service will be re-registered once the new Client starts.
The command is generically named "lifecycle-sidecar" (i.e. rather than
re-registerer) to make room for more functionality in the future, e.g.
renewing tokens.
This change also updates the mutating webhook code to add the
connect-sidecar as a sidecar to Connect injected Pods. It adds a new
required flag to connect-inject: `-consul-k8s-image` that controls the
image used for the sidecar. …

Add new lifecycle-sidecar command

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go

In the Helm chart there is an undocumented value that allows users to
override the prefix we usually apply to the resources. The default
prefix is <helm release name>-consul. This change adds two flags to the
server-acl-init command (the only command that is affected by the
prefix): `-resource-prefix` and `-server-label-selector`.
If set, we will use the correct prefix,
both for finding resources that we expect to be created by the helm
chart, e.g. Consul servers, and for creating our own resources, e.g.
Kubernetes secrets.
The flags are backwards compatible. Users can upgrade consul-k8s and not require any changes to their consul-helm version. There is a corresponding consul-helm update that uses these flags. That is only required if users want to take advantage of this bugfix (which now …

Support fullnameOverride

---

connect-inject/container_init.go
connect-inject/container_init_test.go

Fix bug where the lifecycle sidecar (which runs as user consul-k8s)
could not read the acl-token because it was owned by root

acl-token file readable by lifecycle sidecar

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/container_sidecar_test.go
connect-inject/envoy_sidecar.go
connect-inject/envoy_sidecar_test.go
connect-inject/handler.go
connect-inject/lifecycle_sidecar.go
connect-inject/lifecycle_sidecar_test.go
subcommand/inject-connect/command.go

* Add new flag -consul-ca-cert
* Make Consul addresses use HTTPS if CA is provided
* Provide CA certificate to the init and both sidecar containers,
so that service registration and envoy bootstrapping
can use TLS.
This PR has a slightly different approach to what was proposed in #30 and assumes the implementation in the hashicorp/consul-helm#313.
Fixes #79

Enable TLS for connect-inject

---

go.sum
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go

This PR makes the following changes
- Adds new flags: `-use-https`, `-consul-ca-cert`, and `-consul-tls-server-name`. The last one is specifically useful for the Helm chart since our certificates don't have Pod IPs as SANs. This allows us to set an SNI header with a custom server name.
- Bumps Consul version to 1.6.2 to use `tlsutil` package for certificate generation in tests.
Ideally, I wanted to change this job to use DNS names of the servers for bootstrapping rather than IPs. But I didn't know how to write tests for it without requiring root privileges to run them. More specifically, we could programmatically add Kubernetes DNS names to `etc/hosts` but that will require `sudo` on the machine where the tests are run. This seemed a bit awkward.

Support TLS-enabled servers for the server-acl-init command

---

connect-inject/lifecycle_sidecar.go
connect-inject/lifecycle_sidecar_test.go
subcommand/lifecycle-sidecar/command.go
subcommand/lifecycle-sidecar/command_test.go

For namespaces, the lifecycle sidecar needs access to Enterprise
features to be able to register and re-register services and proxies
correctly. This switches it to directly call the consul cli with the
consul version specified in the connect injector. If a user is running
enterprise, this is the enterprise version which allows namespaces.
Note: Several tests were deleted because their approach no longer
works with this registration strategy. They will need to be rewritten
in the future.

Update the lifecycle sidecar to shell out to Consul

---

.circleci/config.yml
subcommand/lifecycle-sidecar/command.go
subcommand/lifecycle-sidecar/command_test.go

This PR makes the following changes:
- Previously, we were calling `consul services register service.hcl -token-file ...`, but it needed to be `consul services register -token-file ... service.hcl`
- Additionally, we weren't passing any other HTTP flags to the underlying Consul command
- Adds tests back in
- Changes CI test job to download the Consul binary

Fixes to the lifecycle sidecar cmd, plus tests

---

.circleci/config.yml
subcommand/lifecycle-sidecar/command.go
subcommand/lifecycle-sidecar/command_ent_test.go
subcommand/lifecycle-sidecar/command_test.go

This PR adds enterprise namespaces tests to the lifecycle command.  
It also fixes a bug with sync period. After switching to `time.Duration`,
we didn't need to parse it anymore, however, validateFlags function
always instantiated and returned `syncPeriod` variable, which was 0 by
default.
Additionally, we no longer allow sync period to be equal to 0. If it is,
then it's impossible to stop command gracefully because the select loop
will always choose 'case <-time.After(c.flagSyncPeriod)' even if
the `SIGINT` signal has been sent.

Add namespace tests to the lifecycle sidecar command

---

.circleci/config.yml
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go

Add tests for the namespace changes of server-acl-init.
The tests that will fail are due to the binding rule not being able to have its namespace updated.
Tests:
* binding rule
* single dest namespace
* mirroring
* auth method
* single dest namespace
* mirroring
* updates (i.e. when the command is re-run it updates the binding rule/auth method)
* no ns => ns mirroring
* no ns => single dest namespace <= FAILS
* ns mirroring => single dest namespace <= FAILS
* single dest namespace => ns mirroing

Add tests for namespaces and acl bootstrapping

---

catalog/to-consul/syncer.go
catalog/to-consul/syncer_test.go

Previously, when the context was cancelled we would enter the error
handling clause and the loop would be re-executed. Then the
backoff.Retry would exit immediately because the context was cancelled
and we'd run in a tight loop until the program was killed.
With this change, when we exit the backoff.Retry with an error, we check
if the context is done. If so, we exit immediately.
This functionality already existed in `syncer.go`:
```go
// Get all services with tags.
var serviceMap map[string][]string
var meta *api.QueryMeta
err := backoff.Retry(func() error {
var err error
serviceMap, meta, err = s.Client.Catalog().Services(opts)
return err
}, backoff.WithContext(backoff.NewExponentialBackOff(), ctx))
// If the context is ended, then we end
if ctx.Err() != nil {
return
}
```

Don't retry when context cancelled.

---

connect-inject/handler_ent_test.go

This address the interactions the connect injector now has with Consul
where it checks and potentially creates a namespace. All namespace
permutations are tested both with and without ACLs enabled.

Add namespace tests to the connect inject handler

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

The ACL replication token is used for ACL replication between Consul
datacenters.

Add -create-acl-replication-token flag

---

catalog/to-consul/consul_node_services_client.go
catalog/to-consul/consul_node_services_client_ent_test.go
catalog/to-consul/consul_node_services_client_test.go
catalog/to-consul/syncer.go
catalog/to-consul/syncer_ent_test.go
catalog/to-consul/syncer_test.go
subcommand/sync-catalog/command.go

If namespaces are not enabled, use a Consul catalog API that is
available in older Consul versions instead of the API that's only
available in Consul 1.7+.
Design decisions:
* I've only implemented the adapter for the `NodeServiceList` endpoint rather than for the whole consul client API. This means `Syncer` needs both `ConsulClient` and `ConsulNodeServiceListClient` but it reduces the amount of code required vs needing to wrap the whole API of `ConsulClient`.
* Previously (before namespaces) the code used the `/catalog/services` endpoint to return just service names and then it filtered on those with the tag `k8s`. It never checked if those services were registered to the `k8s-sync` node. Rather than going back to that API, I've switched it to the `/catalog/node/:node_id` endpoint. I …

Support older versions of Consul in sync catalog

---

.circleci/config.yml
catalog/to-consul/consul_node_services_client.go
catalog/to-consul/consul_node_services_client_ent_test.go
catalog/to-consul/consul_node_services_client_test.go
catalog/to-consul/resource.go
catalog/to-consul/resource_test.go
catalog/to-consul/syncer.go
catalog/to-consul/syncer_ent_test.go
catalog/to-consul/syncer_test.go
subcommand/sync-catalog/command.go
subcommand/sync-catalog/command_ent_test.go
subcommand/sync-catalog/command_test.go

Add tests for catalog sync. Note that these tests currently require Consul 1.7.0. With the addition of https://github.com/hashicorp/consul-k8s/pull/205, the OSS tests will work with older versions of Consul.
There some important non-test changes to note here:
1. `logger` is being made a field of `Command`. This allows me to pass in a named logger in the tests with the name of the test. This results in logs like:
```
2020-02-13T11:18:06.779-0700 [DEBUG] TestRun_ToConsulChangingNamespaceFlags/mirroring-ns_=>_mirroring-ns-prefix-secondrun.to-consul/source: [generateRegistrations] generating registration: key=foo/foo
```
which make it possible to debug issues when there are tests running concurrently (which is always because we use `t.Parallel()`. This logging made it possible for me to fix …

Namespaces tests for catalog sync, fix races

---

.circleci/config.yml

This PR adds `lint-consul-retry` which checks to make sure `retry.Run` runs on `retry.R` rather than `testing.T`.

add lint-consul-retry tool

---

subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

Now that the inject-connect command has Consul's HTTP flags, we should use only one flag to control TLS communications with the local agents.
Currently, we set both flags. The `-consul-ca-cert` flag sets the CA cert for the init container, the envoy proxy sidecar, and the lifecycle sidecar, and they use that CA to talk to their local agent.
The `-ca-file` flag controls the CA cert that is used by the handler to talk to its local agent (this happens only if namespaces are enabled).
Although these agents could be on different hosts, the CA that singed their certificates must be the same, so there is no need to have two different flags.

Inject-connect command: deprecate the -consul-ca-cert flag

---

catalog/to-consul/syncer.go
catalog/to-consul/syncer_test.go

A race condition was occurring where we would delete services via the
`watchReapableServices` function if `Sync` wasn't called fast enough by
`resource.go`. This occurred because `watchReapableServices` makes a
call to the catalog and then deletes everything with a k8s tag that
isn't in its `s.services` map. If `Sync` isn't called, then this map
is empty and so it tries to delete everything.
I've solved this by blocking until `Sync` is first called.
Closes https://github.com/hashicorp/consul-k8s/pull/191

Fix initial sync race

---

subcommand/lifecycle-sidecar/command.go
subcommand/lifecycle-sidecar/command_test.go

Similar to the fix made for the sync catalog command, ensure that there
is no race condition between starting the command and setting an
interrupt. This race condition is triggered if the goroutine that calls
Run() runs after stopCommand() is run. In this case, the channel that
listens for a SIGTERM signal has not been initialized and so stopCommand
hangs forever writing to a nil channel.

Fix race condition in lifecycle-sidecar tests

---

catalog/to-consul/syncer_test.go

Needed to set the config in the closure instead of after the syncer
started. (https://github.com/hashicorp/consul-k8s/pull/208#discussion_r389070766)

Fix test configuration race.

---

catalog/to-consul/syncer_ent_test.go
catalog/to-consul/syncer_test.go
catalog/to-k8s/source_test.go
subcommand/sync-catalog/command_ent_test.go
subcommand/sync-catalog/command_test.go

Removes the TestAgent that was imported from OSS Consul. Instead,
makes use of the Consul TestServer that is part of the sdk.

Remove test agent from sync tests

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/create_or_update.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

- Adds flag -acl-replication-token-file for setting the ACL replication
token. This token is used by secondary dc's to create ACL policies.
This turns on ACL replication mode.
In this mode we will not bootstrap ACLs since we expect replication
to be running.
- Modifies various policies and tokens to only be applicable to the
local datacenter. These policies should have been only local before.
- If running in a secondary DC, append the datacenter name to the
policy name. This is required because policies must be globally
unique.
- Note: we aren't sharing policies between datacenters because
each server-acl-init could modify the policy depending on
its local config.
- Adds agent:read permissions to the replication token which is needed to get the current datacenter
I took an incremental …

Support ACL replication

---

commands.go
subcommand/load-balancer-address/command.go
subcommand/load-balancer-address/command_test.go

Command usage:
```
consul-k8s load-balancer-address \
-k8s-namespace default \
-name my-service-name \
-output-file address.txt
```
The command will run in a retry loop until the service has been assigned
an ingress IP or hostname. It will then write that address to file.
The command will be used in the helm chart in the init container for the mesh-gateway.

Add new load-balancer-address command

---

subcommand/acl-init/command.go
subcommand/acl-init/command_test.go

Add flag `-token-sink-file` to `acl-init` command. If `init-type=sync` (which is used for everything except consul agents) then if `-token-sink-file` is set, we will write the token to that file.
This is needed for the mesh-gateway lifecycle sidecar (https://github.com/hashicorp/consul-helm/pull/380)

Add -token-sink-file flag to acl-init

---

commands.go
subcommand/service-address/command.go
subcommand/service-address/command_test.go

- Support retrieving ClusterIP services with the load-balancer-address
command.
- Rename load-balancer-addresss to service-address since it no longer
applies to just load balancer services.

load-balancer-address support for ClusterIP

---

commands.go
go.mod
helper/cert/source_gen.go
helper/cert/source_gen_test.go
helper/cert/tls_util.go
subcommand/get-consul-client-ca/command.go
subcommand/get-consul-client-ca/command_test.go
subcommand/lifecycle-sidecar/command_test.go
subcommand/server-acl-init/command_test.go

When auto-encrypt is enabled, we need to retrieve Consul client CA from the Consul servers.
This command calls the `/agent/connect/ca/roots` endpoint, finds the currently active root CA, and writes it to the provided output file location.
This command allows you to provide a cloud-join string instead of the server address and this command will discover the servers. This allows us to re-use the `client.join` value in the Helm chart without requiring operators to provide the address of the server in addition to the join value.

Add get-consul-client-ca command

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

* node:write needs to be in the default namespace since nodes aren't
namespaced
* connect inject and catalog sync need global acl tokens and policies when namespaces are enabled because a global token is required to create namespaces

Update policies for namespaces

---

build-support/docker/Dev.dockerfile

To ensure that the dev docker image is the same as the release image
base it off of the latest consul-k8s image and just replace the binary.

Base the dev docker image on the release image

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/servers.go

This PR proposes to change the server-acl-init command to use user-provided server-address and server-port instead of discovering servers' Pod IPs and ports via Kubernetes API.
Currently, the `server-acl-init` command knows a lot about how the servers are deployed. It makes some assumptions about the resource names of the stateful set and uses Kubernetes API as its discovery mechanism for server addresses. This creates a fair amount of extra logic to correctly discover the server IPs and ports. In addition, we have some logic that checks if the stateful set rollout is currently in progress and waits until it's complete. The Statefulset logic was added specifically to prevent a situation when we would discover the IPs of the servers right before Kubernetes would kill and restart the …

server-acl-init: Add -server-address and -server-port

---

connect-inject/container_init.go
connect-inject/container_init_test.go

Fixes #224.
If a user puts spaces between their upstreams in the annotation,
the first section of a prepared query later in the list shows up
as ` prepared_query`. We were doing a direct comparison of this
value with `prepared_query`, which is incorrect. This change trims
the spaces on the first part of an upstream before checking its type.
Adds several different tests to verify the behavior with multiple
upstreams defined.

Trim spaces before checking if an upstream is a prepared query

---

helper/go-discover/discover.go
helper/go-discover/discover_test.go
helper/go-discover/mocks/mock_provider.go
subcommand/get-consul-client-ca/command.go
subcommand/get-consul-client-ca/command_test.go
subcommand/server-acl-init/anonymous_token.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/connect_inject.go
subcommand/server-acl-init/create_or_update.go
subcommand/server-acl-init/servers.go
subcommand/sync-catalog/command_ent_test.go

This PR proposes the following changes to support external servers:
1. Add a `bootstrap-token-file` flag to support "already-bootstrapped" external servers. This could also work for folks that want to do ACL bootstrapping themselves on the external server and just provide a bootstrap token so that the rest of tokens and policies for consul-k8s are set up. Some use-cases in hashicorp/consul-helm#413.
1. `-server-address` flag now supports cloud auto-join strings. This is similar to how `get-consul-client-ca` command behaves. Cloud auto-join support here was added for consistency.
1. `-inject-auth-method-host` and `-inject-auth-method-ca-cert` to allow configuring custom auth method parameters. This is needed because during the login workflow, consul servers are talking to the Kubernetes …

Support external servers

---

CHANGELOG.md
subcommand/acl-init/command.go
subcommand/acl-init/command_test.go

If the acl-init command is re-run, it needs to be able to overwrite the
previously written acl-token file.
In some testing, the `service-init` init container has later commands fail. Then Kubernetes restarts the init container and it continuously fails with the error:
```
Error writing token to file "/consul/service/acl-token": open /consul/service/acl-token: permission denied
```
because that file has already been written but it has 0400 permissions so can't be overwritten.
To reproduce, edit `mesh-gateway-deployment`:
```
ls -la /consul/service
{{- if (or .Values.global.acls.manageSystemACLs .Values.global.bootstrapACLs) }}
consul-k8s acl-init \
-secret-name="{{ template "consul.fullname" . }}-mesh-gateway-acl-token" \
-k8s-namespace={{ .Release.Namespace }} \ …
```

Change perms from 0400 to 0600 for acl-token

---

commands.go
go.mod
go.sum
subcommand/common/common.go
subcommand/common/test_util.go
subcommand/create-federation-secret/command.go
subcommand/create-federation-secret/command_test.go
subcommand/get-consul-client-ca/command_test.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/create_or_update.go
subcommand/server-acl-init/servers.go

This command will be run as a Kubernetes Job via a Helm hook. It creates
a Kubernetes secret that contains data needed by secondary datacenters
to federate with the primary. To set up a secondary dc, users will
export this secret from their primary and import it into secondaries.
They will then reference the secret in their Helm config for
secondaries.
The command works with ACLs enabled/disabled and with gossip encryption
enabled/disabled. The command only works when TLS is enabled because
federation requires TLS be enabled.
Flags worth noting:
* `-export-replication-token` will be set to true if ACLs are enabled. Helm chart will ensure this job can't run unless `createReplicationToken: true` is set (when acls are enabled) to ensure this secret exists
* `-gossip-key-file` will be set if …

Add create-federation-secret command

---

subcommand/service-address/command.go
subcommand/service-address/command_test.go

Consul does not support hostnames for mesh gateway wan addresses. For
now to support running on EKS we will resolve the EKS load balancer
hostnames to IPs.
In the future when Consul supports hostnames we will want to remove this
change because the IPs may change and the hostname won't.

Resolve hostnames in service-address command

---

connect-inject/envoy_sidecar.go
connect-inject/envoy_sidecar_test.go

The previous preStop hook would fail with
```
/bin/sh: syntax error: unexpected \"&&\"\n"
```
When acls were turned on. This would cause consul logout to not execute
and leave ACL tokens forever. This fix removes the && that was causing
the syntax issue. Since the prestop hook is executed in sh -ec, the -e
will cause the command to exit if any of the commands fail so && is not
necessary.
Testing: Create a connect-injected pod with ACLs on. Delete it, look at `kubectl get events`. You should see an error from the hook like shown in the issue. Now use `lkysow/consul-k8s-dev:may26-prestop`, there will be no error.
Fixes https://github.com/hashicorp/consul-k8s/issues/265

Fix bug where preStop hook was malformed

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/envoy_sidecar.go
connect-inject/envoy_sidecar_test.go
connect-inject/handler.go
connect-inject/handler_test.go
connect-inject/lifecycle_sidecar.go
connect-inject/lifecycle_sidecar_test.go
go.sum
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

* Set resource settings for init and lifecycle containers. These are set by default and not overridable. They're set by default to avoid needing a separate flag to turn them on. This is safe because they're set to more than double observed resource requirements so users that don't need resource settings won't be affected. They're not exposed for overriding because they won't change based on use-case, i.e. a service with a lot of throughput may need to customize its envoy proxy cpu/memory however the init container and lifecycle sidecar will need the same cpu/memory as all the other connect pods since they're doing the same job.
* Allow setting resource settings for envoy sidecar via default settings passed in through Helm chart values that will apply to all pods, overridable by …

Support resource settings

---

catalog/to-consul/resource.go
catalog/to-consul/resource_test.go
subcommand/sync-catalog/command.go

add option to sync LB Endpoints instead of LB external hostname
fixes https://github.com/hashicorp/consul-k8s/issues/254
@lkysow @ishustava i know that you are busy but since the diff is small I really would appreciate a CR on this one before i commit prod to it.

Sync LB endpoints

---

subcommand/lifecycle-sidecar/command.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/connect_inject.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

This allows the server acl init job to create base tokens for any
provided ingress and terminating gateway names.
For terminating gateways, users will need to update these created
tokens to include permissions to the services they represent. To
do this, they should add separate policies or attach service identities
to avoid having this job overwrite their configuration.
When Consul namespaces are enabled, users can provide a namespace with
each gateway name to specify which Consul namespace to scope the gateway
token to. In this case, the gateway flag values can be provided as
`<gateway-name>.<gateway-namespace>`. If a namespace is not provided,
the token will be created for the `default` namespace.

Update server acl init to create tokens for gateways

---

connect-inject/container_init.go
connect-inject/container_init_test.go

Previously we were setting the alias_service field of alias checks to
the service name instead of the service id. This check would then pass
because Consul would consider an alias for a non-existent service id to
be okay. With https://github.com/hashicorp/consul/pull/7384, now the
check will fail if the service id doesn't exist and so those connect
services will be considered unhealthy and be unroutable.

Fix bug with defining connect healthcheck

---

subcommand/service-address/command.go
subcommand/service-address/command_test.go

Add a -resolve-hostnames flag to the service-address command that
defaults to false. If true, any service with a hostname as its address
will have that hostname resolved and the first ip written.
If false, (default) the hostname will be written. Consul now supports hostnames for mesh gateway addresses so that's why we're adding this now.
This is useful in the case of EKS where load balancers have hostnames.
For WAN federation we want to use the hostname because the underlying
IPs can change. For ingress gateways this command is used to set the
address field in the service definition which only accepts IPs. This
flag allows the service-address command to be used so the service
registration is valid and then we document that in the EKS case users
shouldn't use the ingress consul DNS and …

Add -resolve-hostnames flag

---

build-support/functions/20-build.sh

Top level build `make all` was failing due to file extensions for windows.
This change checks if we need to modify binary extension at build time and appends to the binary if necessary.
```
consul-k8s % make
==> Building Consul - OSes: solaris darwin freebsd linux windows, Architectures: 386 amd64 arm arm64
Building sequentially with go install
--->   solaris/amd64
<snip>
--->   windows/386
cp: /Users/kyle/go/bin/windows_386//consul-k8s: No such file or directory
ERROR: Failed to build Consul for windows/386
make: *** [bin] Error 1
```

top level build was failing due to missing bin extension for windows

---

.circleci/config.yml
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/connect_inject.go

Previously, we would only update auth method in Consul
if Consul namespaces are enabled. This was necessary to make sure
that if namespace configuration changes, it is reflected in the auth method.
However, running Consul servers externally is another use case why it's important
to update the auth method. That is because if you run a Helm install, then uninstall
and install again, the auth method saved in Consul is out-of-date:
the service account JWT token saved in the auth method refers to the service account token
that has been deleted from Kubernetes when you ran helm uninstall.
This change proposes to always update the auth method to solve for the
external servers use case.

Always update auth method

---

connect-inject/container_init.go
connect-inject/container_init_test.go

This check only occurs when ACLs are enable with connectInject.
Tested that it only performs this check when ACLs are enabled. Screenshot of error when incorrect pod config is applied
Closes #237 
Signed-off-by: Ashwin Venkatesh <ashwin@hashicorp.com>

fail if service name != service account name

---

connect-inject/container_init.go
connect-inject/lifecycle_sidecar.go

Currently the initContainer for connect-inject has a resource limit of 25Mi, this was introduced as a feature in the 0.16.0 release.
As part of it's runtime the initContainer issues a cp of the consul binary (100Mi+). Normally this is fine but it is possible to get into a situation where the host is under resource pressure and enough dirty pages from the cp operation accumulate in memory such that an OOM is triggered.
The initContainer is short lived and we just need it to run, so increase the resource limit to the size of the consul binary.
Likewise the lifecycle sidecar's settings were set too low, we double the cpu resources to alleviate cpu constraints.
This resolves #283

Update resources for lifecycle sidecar and init container for connect-inject

---

CHANGELOG.md
connect-inject/handler.go
connect-inject/handler_test.go

Fixes #296
- Respect allow/deny list flags when namespaces are disabled.
Added tests to cover this scenario. Since the only functionality change is to the `shouldInject` method, this is sufficient.
Confirm that the `TestShouldInject` test in connect-inject/handler_test.go works as expected and covers all the desired scenarios.
Checklist:
- [ x ] Tests added
- [ x ] CHANGELOG entry added (*HashiCorp engineers only, community PRs should not add a changelog entry*)

Respect allow/deny lists even when namespaces aren't enabled

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go
connect-inject/lifecycle_sidecar.go
connect-inject/lifecycle_sidecar_test.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

Updates the work done in #289.
- Adds resource request and limit flags for both the injected init and lifecycle sidecar containers
Added and updated tests for the functionality. Changed default values to unique values and deployed to a cluster, verifying that they were applied and in the correct place.
Verify the tests function as expected and include all the relevant cases. Deploy the connect injector using the new flags and verify that any injected pods include the provided values.
Checklist:
- [ x ] Tests added
- [ x ] CHANGELOG entry added (*HashiCorp engineers only, community PRs should not add a changelog entry*)

Allow init and lifecycle containers resource limits to be configured

---

subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

- Update lifecycle sidecar memory limit flag default value to 50Mi
Updated default value test.
Verify the test functions as expected, includes the updated value and passes.
Checklist:
- [ x ] Tests added
- [ N/A ] CHANGELOG entry added (*HashiCorp engineers only, community PRs should not add a changelog entry*)

Update lifecycle sidecar memory limit flag default value

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go

Because the proxy service registers an alias health check that points to the service ID of the main service and we're registering the proxy service before the main service, the alias check starts out as red
because at that time the service doesn't yet exist. Consul runs this check every minute, and so this will become green only after one minute.
This is particularly bad in a case when a service is restarted either due to scheduled or unscheduled maintenance. For example, when you have deployment and you trigger a re-deploy (kubectl rollout restart), kubernetes by default will do a rolling deploy, where it won't terminate the old instance until the new one comes up and is healthy. But Consul will take an additional minute or so to mark this service as healthy, causing downtime, where …

connect: register the service before the proxy

---

Makefile

- In addition to `git rev-parse --short HEAD` commit hash docker images, this PR will push a `consul-k8s:crd-controller-base-latest` tag that gets updated on every new commit to the `crd-controller-base` branch

push latest image for crd-controller-base branch

---

config/default/webhookcainjection_patch.yaml

There is no validating webhook anymore.

Remove patch for validating webhook

---

subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

Will create an ACL token for controller. No Consul Enterprise support
right now.
- Check out this branch: https://github.com/hashicorp/consul-helm/pull/587 and follow the instructions there
- ☝️ 
Checklist:

Add -create-controller-token flag

---

subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/connect_inject.go
subcommand/server-acl-init/connect_inject_test.go

Kubernetes service account could have multiple secrets associated with it.
Previously, we were only looking at the first secret in the list and using
that secret to create or update the auth method in Consul.
However, on some platforms the service account may contain other types of secrets.
Specifically, in the case of Openshift, there are two secrets: one for the service account token
and the other for docker config credentials. This second secret gets injected automatically by Openshift.
This PR changes our implementation to use the first secret of type kubernetes.io/service-account-token.
Created a docker image (`ishustava/consul-k8s-dev:09-04-2020-5e7491d`) and ran connect acceptance tests with it on openshift.
No infrastructure tests required from the reviewers at this point. We can …

Connect: only look for service account secrets when creating/updating auth method

---

subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

- Companion to https://github.com/hashicorp/consul-k8s/pull/323. This updates the ACL token we create to make it work for consul enterprise namespaces.
How I've tested this PR: Ran the acceptance tests from https://github.com/hashicorp/consul-helm/pull/601 which tests with secure installation and a Docker image made with a merge of this branch and https://github.com/hashicorp/consul-k8s/pull/323.
How I expect reviewers to test this PR: You could run the acceptance tests yourselves or review the ones I wrote and see that CI/CD passes for them.
Checklist:

Update ACLs for consul ent and controller

---

api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/servicedefaults_webhook.go
api/v1alpha1/types.go

Add defaulting and validation for ServiceDefaults
Checklist:
How I tested the PR:
• Used the image `ashwinvenkatesh/consul-k8s:validation` to deploy consul via helm with the controller enabled.
• Tried creating service default resource with
• Invalid mesh gateway mode
• Invalid expose path protocol (not in "http" and "http2") and path value (not prefixed by "/")
This led to webhook errors which indicated the invalid fields
• Combinations of various invalid values for the above fields
This led to webhook errors that listed every single invalid field
How I expect people to test the PR:
• You can retry the above scenarios with multiple invalid values to verify every invalid value is mentioned in the returned error from the webhook.

Add defaults and validation for ServiceDefaults

---

subcommand/webhook-cert-manager/command.go
subcommand/webhook-cert-manager/command_test.go
subcommand/webhook-cert-manager/mocks/mocks.go

- helm upgrades will cause the caBundle to get reset on the mutating webhooks. By "reconciling" the state of the system every second, we ensure the drift in this state has a minimal impact on the uptime of the system. it will now verify that the certificates as well as the CA bundle are "correct" every second and update them if they arent.
- this will also ensure any edits made to the secret or the webhook configuration, which could lead to downtime in the system, are recovered from within a second.
- helm installed consul with the image.
- performed a helm upgrade once the system had reached a stable state.
- attempted the creation of a service default and it did not throw an x509 error.
- …

Ensure system recovers quickly from failures or drift in state

---

api/v1alpha1/servicedefaults_types.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/types.go

- Pass the path down to the validation methods so they don't need to know
where in the struct they are placed.
- Also use .Index() and .Key() instead of fmt.Sprintf to indicate where
in a slice/map we are.

Pass down path through validators

---

api/common/configentry_webhook.go
api/common/configentry_webhook_test.go
api/v1alpha1/servicedefaults_webhook.go
api/v1alpha1/serviceresolver_webhook.go
subcommand/controller/command.go

- if running ent and namespace mirroring is enabled then allow multiple
resources with the same name across namespaces.
- make Validator structs public and remove constructors
- I haven't
Checklist:
Not sure if we should make this a struct like we did for `ConfigEntryController` and set the EnableNamespaces and EnableNSMirroring as fields.

Implement webhook support for consul ent

---

subcommand/controller/command.go

- defaults to true
- replaces ENABLE_WEBHOOKS environment variable

Add -enable-webhooks flag

---

subcommand/controller/command.go

Remove metrics flag since we're not using it

---

api/v1alpha1/proxydefaults_types.go
api/v1alpha1/proxydefaults_types_test.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/serviceresolver_types_test.go
api/v1alpha1/servicerouter_types.go
api/v1alpha1/servicerouter_types_test.go
api/v1alpha1/servicesplitter_types.go
api/v1alpha1/servicesplitter_types_test.go
go.mod
go.sum
main.go

- go-cmp has a more robust library for compares as it allows ignoring
unexported fields.
- Refactored the MatchesConsul tests for serviceDefaults to resemble other MatchesConsul tests
- existing tests for MatchesConsul continue to pass.
- this is a refactor so existing tests passing should imply it was successful.

Replace reflect.DeepEqual with gocmp.Equal

---

api/common/common.go
api/common/configentry.go
api/common/configentry_webhook_test.go
api/v1alpha1/proxydefaults_types.go
api/v1alpha1/proxydefaults_types_test.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/serviceresolver_types_test.go
api/v1alpha1/servicerouter_types.go
api/v1alpha1/servicerouter_types_test.go
api/v1alpha1/servicesplitter_types.go
api/v1alpha1/servicesplitter_types_test.go
api/v1alpha1/types.go
controller/configentry_controller.go
controller/configentry_controller_test.go
go.mod
go.sum
main.go
subcommand/controller/command.go
subcommand/controller/command_test.go

This will determine if the resource is managed from outside the current cluster
- Add flag `datacenter` that is a required flag for the controller for startup. This string will be used in the meta() field of the config entries managed by Consul
- Add datacenter specific metadata on the Config Entry Meta field before creating the resource in Consul.
This field will be ignore when checking for equality between resources with `cmp.Equal()`.
- A config entry will only be update/deleted from Consul if the metadata on it indicates that it was created in the datacenter the controller is running in.
- Adding additional acceptance tests to validate this behavior.
- Ideally, one should be able to use the …

Use metadata field from configEntry

---

api/v1alpha1/servicesplitter_types.go
api/v1alpha1/servicesplitter_types_test.go

- Add support for service splits having 0 weight
How I've tested this PR: unit tests, Cody tested an image with this fix which worked for his demo
How I expect reviewers to test this PR: Try creating a service split that has 0 weight. The webhook should not prevent the resource from getting created.
Checklist:

Support split weights that have a value of 0

---

CHANGELOG.md
connect-inject/envoy_sidecar.go
connect-inject/envoy_sidecar_test.go

This flag was deprecated and ignored in Envoy 1.11 and will result
in an error for Envoy 1.15.
* Run with `ghcr.io/lkysow/consul-k8s-dev:oct06-envoy` against envoy versions 1.14.4, 1.13.4, 1.12.6, 1.11.2
* You can see here (https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.11.0#deprecated) that the flag is deprecated so unless you want to, there's no need to test it yourself that connect still works.
Checklist:

Don't set envoy flag `--max-obj-name-len`

---

api/v1alpha1/serviceintentions_types.go
api/v1alpha1/servicesplitter_types.go
config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
go.sum

Missing from service-intentions and splitter but on the rest
These show up on
```
$ k get servicesplitter
NAME   AGE
foo    7s
$ k get servicedefaults
NAME                     SYNCED
foo                      True
```

Add missing additional columns

---

api/v1alpha1/proxydefaults_types.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/servicerouter_types.go
api/v1alpha1/servicesplitter_types.go
config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
config/crd/bases/consul.hashicorp.com_servicerouters.yaml
config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
controller/configentry_controller.go
controller/configentry_controller_test.go
go.sum

- In case consul fails while attempting to delete a config entry, update the sync value to being failed. This can happen when there are other config entries that depend on the config entry being deleted. For example, a service-defaults entry being deleted before service-splitter/service-router/service-resolver entries that depend on the service-defaults.
- Add Age column to CRD printer columns
How I've tested this PR: Deployed it in local cluster and viewed the changes. Wasn't sure what a failing test case would look like for this particular error so I would like some feedback on that. Maybe just a standalone test for service-defaults with service splitters? Most of the existing tests test every config entry but that assertion will probably not be the case …

Fail sync if consul delete returns an error

---

CHANGELOG.md
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

If namespaces are enabled, the replication token will need to be able to
replicate all tokens and policies from all namespaces. Without this
functionality, users won't be able to use namespaced
tokens/policies/roles in secondary datacenters (since they won't be
replicated).
Fixes https://github.com/hashicorp/consul-k8s/issues/364
* Federated two clusters with ACLs enabled
* Created a namespace `luke`
* Created a policy and token in namespace `luke`:
```hcl
acl = "read"
```
* On secondary DC, exec'd into server and ran:
```bash
curl -H "X-Consul-Token: 5207f7dd-cfb0-7d7f-b0a5-964295bcb3a1" -k https://localhost:8501/v1/acl/token/self
ACL not found
```
* Modified replication ACL policy to have `namespace_prefix ""`
* Confirmed that (after a 5m delay) that the API …

Replication token needs acl write on all ns's

---

api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceintentions_types_test.go
api/v1alpha1/serviceintentions_webhook.go
api/v1alpha1/serviceintentions_webhook_test.go
controller/configentry_controller.go
controller/configentry_controller_ent_test.go
go.mod
subcommand/controller/command.go

- Fix support for service-intentions and Consul enterprise. Previously the defaults we were setting for the namespace fields weren't getting applied to the object in the webhook because we weren't returning any patches. When the entry got into the controller, its destination.namespace field was `""`.  We would then attempt to create a namespace with name `""` which would fail. In addition, if the namespace creation didn't error out, we would create the config entry in the namespace `"default"` instead of what we wanted to be the default namespace (e.g. if mirroring we wanted the namespace to equal the kube namespace).
- In this PR, we reject requests that have source.namespace or destination.namespace specified and consul namespaces are disabled.
- …

Support Consul namespaces for service-intentions

---

CHANGELOG.md
api/common/configentry.go
api/common/configentry_webhook.go
api/common/configentry_webhook_test.go
api/v1alpha1/proxydefaults_types.go
api/v1alpha1/proxydefaults_webhook.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceintentions_types_test.go
api/v1alpha1/serviceintentions_webhook.go
api/v1alpha1/serviceintentions_webhook_test.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/serviceresolver_types_test.go
api/v1alpha1/servicerouter_types.go
api/v1alpha1/servicerouter_types_test.go
api/v1alpha1/servicesplitter_types.go
api/v1alpha1/servicesplitter_types_test.go

ServiceRouters, ServiceResolvers, ServiceSplitters, and
ServiceIntentions should only have namespaces set in their spec when
consul namespaces are enabled. When consul namespaces are disabled, the
webhook now returns a validation error if these CRs have a namespace.
Previously, users could apply CRs with namespaces set even when consul
namespaces are disabled, causing them to think the namespaces might be
having an effect when they are not.
Co-authored-by: Ashwin Venkatesh <ashwin@hashicorp.com>
- ran unit tests (`make test`)
- ran acceptance tests in consul-helm using `gcr.io/nitya-293720/consul-k8s-dev@sha256:80044a89e92a32dc782117b7bc9626f8aebecf2b5253a6996d141969ef81bf7b`
- deployed consul-k8s with image …

Validate CR namespaces based on consul namespaces

---

subcommand/inject-connect/command_test.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/connect_inject.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

- server-acl-init will now add additional rules for the connect-inject-webhook when ACLs and health checks are enabled.
- deprecate `-create-inject-auth-method`
- deprecate `-create-inject-namespace-token`. This flag was always passed when `-enable-namespaces` was true so now we just look at`-enable-namespaces` and `-create-inject-token`
- undeprecate `-create-inject-token`. This will always be passed by helm if connect inject is enabled.
- move all namespaced server-acl-init/command_test.go tests that used `-create-inject-namespace-token` from oss to ent as these are now invalid for oss (they always were but they got away with being in oss because they weren't passing `-enable-namespaces`
- tests to validate backwards compatibility are added and coverage for …

add ACL support for health checks controller

---

CHANGELOG.md
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go

Controller token must be global because config entries are global and therefore all writes/reads
go to the primary datacenter. This means secondary datacenters need
a token that is known by the primary datacenters, i.e. a global token.
* federated two dcs using consul k8s image `ghcr.io/lkysow/consul-k8s-dev:oct29`
* created servicedefaults in secondary dc
```
cat <<EOF | kubectl apply -f -
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
name: api
spec:
protocol: http
EOF
servicedefaults.consul.hashicorp.com/api created
k get servicedefaults
NAME   SYNCED
api    True
```
* code review
Checklist:

Use global token for controller

---

connect-inject/health_check_resource.go

Stop errors being logged multiple times. See full example log below.
In two locations we were logging the error twice:
```
2020-10-30T21:47:26.653Z [ERROR] healthCheckResource: unable to get agent health check: <err>"
2020-10-30T21:47:26.653Z [ERROR] healthCheckResource: unable to update pod: err="unable to get agent health checks: <err>"
```
```
2020-10-30T21:47:26.653Z [ERROR] healthCheckResource: unable to get agent health check: <err>"
2020-10-30T21:47:26.653Z [ERROR] healthCheckResource: unable to update pod: err="unable to get agent health checks: <err>"
```
Instead we are now returning an error from those inner locations because we know our caller will log it.
In addition, I've changed the language slightly from "error doing an action" to "doing an action" since we know it's an …

De-duplicate error logs

---

connect-inject/handler.go
connect-inject/handler_ent_test.go
connect-inject/handler_test.go
connect-inject/health_check_resource.go
connect-inject/health_check_resource_ent_test.go
connect-inject/health_check_resource_test.go

[Consul-ENT only]
- connect-inject now adds a new annotation when Mutate is called "consul.hashicorp.com/consul-destination-namespace" when namespaces and mirroring are enabled.
- health checks are created in namespaces if they are supported+used
- existing unit tests are modified a bit to be able to re-use code between oss and consul-ent
unit tests have been added for the patch functionality as well as health checks resource.
Unit tests.
Alternatively running and end to end test manually by:
1. deploying with consul-helm consul-ent, along with 
```
global:
imageK8S: kschoche/consul-k8s-dev
enableConsulNamespaces: true
name: consul
image: hashicorp/consul-enterprise:1.9.0-ent-beta1
tls:
enabled: …
```

add support of consul namespaces to health checks

---

subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

- update the ACL rules for connect-inject when health checks are enabled alongside namespaces and update the unit tests to reflect this.
NOTE: dependency on the following PR to be merged first #376 
unit-testing
run the unit tests
it should be sufficient to test with ACLs+namespaces+mirroring enabled against consul-ent.
acceptance test coverage will be added to consul-helm
Checklist:

add namespace_prefix to acls rule for connect inject

---

CHANGELOG.md
namespaces/namespaces.go
namespaces/namespaces_test.go

- Do not attempt to create a wildcard namespace when verifying if it exists
Interestingly, the consul API does not return `*` namespace in a get request. This leads to us attempting to create the namespace when `*` is provided as a destination namespace for service intentions. This PR ensures we do not attempt to create the namespace when provided.
- Unit tests
- Created an image which i deployed with consul-helm and tried to create a service intention where the destination intention was "*"
- Code Review
Checklist:

Dont attempt to create '*' namespace

---

connect-inject/container_sidecar.go
connect-inject/container_sidecar_test.go
connect-inject/handler.go
go.mod
go.sum
subcommand/inject-connect/command.go

Allow extra envoy CLI option to be passed in.  One such use case is when I want to increase/decrease the log level of the envoy sidecar process, I need to run envoy with `--log-level xyz` or `--component-log-level xyz:level`

Allow extra envoy args to be passed in

---

connect-inject/container_init.go
connect-inject/health_check_resource.go
connect-inject/health_check_resource_ent_test.go
connect-inject/health_check_resource_test.go

Once the inject init container completes, the service instance is
registered with Consul. We want to immediately register a failing health
check at this time, otherwise the pod will receive traffic even though
its readiness check hasn't passed and its non-init containers might not
even be running yet.
* To test in a cluster, use Helm:
```yaml
global:
name: consul
imageK8S: ghcr.io/lkysow/consul-k8s-dev:nov04-early-reg3
connectInject:
enabled: true
healthChecks:
enabled: true
server:
replicas: 1
bootstrapExpect: 1
```
* Then create a Pod that will never start up. The below pod uses an invald image which can never be pulled.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: static-client
---
apiVersion: v1
kind: Pod
metadata:
name: …
```

Set failing check when pod is not yet running

---

.circleci/config.yml

This reverts commit 6f37b0170a3ce8f25004807d68e7c3e52e9fefe4.
The change reverted was a CI change to test against a development SHA build of consul for CRD development but now that that is merged, we don't need it anymore. I have also updated  the consul versions to `1.9.0-beta2`

Revert "Pull consul dev images (#344)"

---

api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceintentions_types_test.go
config/crd/bases/consul.hashicorp.com_serviceintentions.yaml

- Add inline descriptions for the various fields of service-intentions
- Add missing validations for service intentions
- Unit tests
This was work that was previously skipped as we did not have enough documentation regarding service-intentions.
- Code Review
Checklist:

Add descriptions and missing validation for service-intentions

---

connect-inject/health_check_resource.go
connect-inject/health_check_resource_test.go

The ordering for stopping pods is:
1. Kube invokes preStop hook
1. Kube sends SIGTERM's to all containers
1. Kube waits for gracePeriod, then sends SIGKILL to non-stopped containers
1. Kube sends event to reconciler where all containers have their state "terminated"
In step 4, previously we would then try and update the status of the health check to failing because the pod is no longer ready. This would result in an error because the service was deregistered in step 1.
* I investigated the state of the pods throughout the lifecycle and confirmed the state when the pod has been terminated. See JSON below.
* You can use image `ghcr.io/lkysow/consul-k8s-dev:nov06-hc-term`
* Start and stop a connect pod
* Observe no errors in …

Don't deregister checks on stopped pods

---

connect-inject/health_check_resource.go
connect-inject/health_check_resource_ent_test.go
connect-inject/health_check_resource_test.go

Purely aesthetic changes. None of these are required, more of just a conversation starter based on some discrepancies I've noticed with other built-in checks.
* Changed success output from title case `Kubernetes Health Checks
Passing` to sentence case `Kubernetes health checks passing` to match
other built-in check outputs.
* Removed `-ttl` from end of check id because the type of check doesn't
matter for users and is listed as a separate field in the API responses.
* Changed check id to use `namespace/service-id` instead of
`namespace_service-id` to match Consul and Kube's regular formats
* Changed `service-id_kubernetes-health-check` to
`service_id/kubernetes-health-check` for purely asthetic reasons: clashing
`_` and `-`'s looks jarring.
What it would look like (with `/` now instead of …

Tweak check id and output

---

CHANGELOG.md

update changelog for health checks

---

CHANGELOG.md

* Looks like Consul for the most part (https://github.com/hashicorp/consul/blob/master/CHANGELOG.md) uses
```
* area: **(Consul Enterprise only)** specific notes
```
for Enterprise features so standardizing on that. I didn't update old changelog entries because that seemed unnecessary but we can standardize on this going forward.
* Fixed some minor formatting.

Minor changelog formatting

---

api/v1alpha1/proxydefaults_types.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/servicerouter_types.go
api/v1alpha1/servicesplitter_types.go

Make the _types.go files the same. They diverged a bit and that makes it harder to make changes across all of them.
File ordering:
- consts
- init function at top
- then structs
- top-level CRD structs first, e.g. ServiceIntentions and ServiceIntentionsList
- then public functions
- then private functions
- toConsul
- validate
- others
No code changes made.

Reorg code in CRD files

---

subcommand/server-acl-init/command.go

If the user is running Consul OSS by accident it would be nice to give them a better error message than:
```
2020-11-19T16:12:17.514Z [INFO]  Bootstrap token is provided so skipping Consul server ACL bootstrapping
2020-11-19T16:12:18.416Z [INFO]  Success: calling /agent/self to get datacenter
2020-11-19T16:12:18.416Z [INFO]  Current datacenter: datacenter=gcp-us-central-1
2020-11-19T16:12:18.610Z [INFO]  Policy "cross-namespace-policy" already exists, updating
2020-11-19T16:12:18.710Z [INFO]  Success: creating cross-namespace-policy policy
2020-11-19T16:12:18.711Z [ERROR] Error updating the default namespace to include the cross namespace policy: err="Unexpected response code: 404 ()"
```
How I've tested this PR: I didn't test it, I looked at the logs from an internal issue.
How I expect …

Give better error if namespaces not enabled

---

CHANGELOG.md
connect-inject/health_check_resource.go
subcommand/common/common.go
subcommand/common/common_test.go
subcommand/create-federation-secret/command.go
subcommand/create-federation-secret/command_test.go
subcommand/delete-completed-job/command.go
subcommand/get-consul-client-ca/command.go
subcommand/get-consul-client-ca/command_test.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go
subcommand/lifecycle-sidecar/command.go
subcommand/server-acl-init/command.go
subcommand/service-address/command.go
subcommand/sync-catalog/command.go
subcommand/webhook-cert-manager/command.go

- Add `-log-level` flag to `inject-connect` so we can configure the health check log level
- Add debug logs to health checks so we can see when it's setting a check status
- Move logger construction to `common` so it can be reused
- I haven't yet!
- code
Checklist:

Add -log-level flag to inject-connect, healthchecks debug logs

---

CONTRIBUTING.md
Makefile
config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
config/crd/bases/consul.hashicorp.com_servicerouters.yaml
config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
config/webhook/manifests.v1beta1.yaml
hack/crds-to-consul-helm/main.go

- Add how to create CRDs to contributing.md.
- Add a script that will copy new CRDs to consul-helm in the format
expected. This will reduce manual copying errors.
I've tested this by running through the readme to create ingress and terminating gateway CRDs and the script was used for https://github.com/hashicorp/consul-helm/pull/714
Reviewers should review the script and suggest improvements to the instructions.

Document how to CRD. Add helm copier.

---

CHANGELOG.md
connect-inject/handler.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

These flags have been set in Helm for at least 9 months. If they aren't
set then our default versions were too old and wouldn't work. Making
them required means we won't need to update them here in addition to in
consul-helm.
I haven't but you can see the flags set here: https://github.com/hashicorp/consul-helm/blob/master/templates/connect-inject-deployment.yaml#L85-L86
Code
Checklist:

Make -consul-image and -envoy-image required

---

CHANGELOG.md
subcommand/lifecycle-sidecar/command.go
subcommand/lifecycle-sidecar/command_test.go

This fixes issues related to stale service registrations created when pods are terminated, causing services to be registered with no pods backing them. This was caused by a race condition in shutdown logic of the lifecycle-sidecar, so the fix address shutdown path for it.
- move signal handling to a go func in lifecycle sidecar so that it can exit cleanly and avoid race conditions if resync were to take a long time.
existing unit tests + manual tests
Spin up latest release of consul-k8s and deploy a sample app that is connect injected, it is helpful to see the issue in the UI so enable that as well. Once the app is online delete the application, you can watch the logs of the lifecycle-sidecar for …

fix signal handling for lifecycle sidecar

---

CHANGELOG.md
api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceintentions_types_test.go

Consul will internally sort the array of ServiceIntention sources by
precedence. For example, if it receives:
```
sources:
- name: "*"
action: allow
- name: bar
action: allow
```
It will return it in precedence sorted order:
```
sources:
- name: bar
action: allow
- name: "*"
action: allow
```
This sorting breaks our MatchesConsul function because we think the
resource has changed and so we will update it continually since it will
never match.
This change uses gocmp's SortSlices to re-sort the sources array so that
both the Kube resource and the Consul resource can be compared despite
Consul's sorting. We use a JSON encoded representation of the source
element with the fields that Consul set automatically zero'd out.
- unit tests
- tested with resource:
```yaml …
```

Ensure ServiceIntentions aren't resynced

---

CHANGELOG.md
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/create_or_update.go
subcommand/server-acl-init/create_or_update_test.go

In cases where a user creates a policy out-of-band with the same name as
one consul-k8s tries to update, give a better error.
This is definitely an edge case but has occurred when a user created the
cross-namespace-acl-policy manually when trying to work around another
issue. This will at least give a better error message in this case.
- unit tests
- code
Checklist:

Give better error when policy was created manually

---

CHANGELOG.md
api/common/configentry.go
api/common/configentry_webhook.go
api/common/configentry_webhook_test.go
api/v1alpha1/ingressgateway_types.go
api/v1alpha1/ingressgateway_types_test.go
api/v1alpha1/ingressgateway_webhook.go
api/v1alpha1/proxydefaults_types.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_webhook.go
api/v1alpha1/serviceintentions_types.go
api/v1alpha1/serviceintentions_types_test.go
api/v1alpha1/serviceintentions_webhook.go
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/serviceresolver_types_test.go
api/v1alpha1/serviceresolver_webhook.go
api/v1alpha1/servicerouter_types.go
api/v1alpha1/servicerouter_types_test.go
api/v1alpha1/servicerouter_webhook.go
api/v1alpha1/servicesplitter_types.go
api/v1alpha1/servicesplitter_types_test.go
api/v1alpha1/servicesplitter_webhook.go
api/v1alpha1/terminatinggateway_types.go
api/v1alpha1/terminatinggateway_types_test.go
api/v1alpha1/terminatinggateway_webhook.go
subcommand/controller/command.go

- Default the namespace fields of resources when namespaces are enabled so that the controller doesnt continuously attempt to reconcile them as the value presented by consul does not match the spec (because Consul defaults the namespace field where we don't).
How to test this PR:
- Code Review
- Deploy `consul-enterprise` with the consul-k8s image `ashwinvenkatesh/consul-k8s:default-ns`. Allow namespaces on the `consul` installation.
Verify that creating an `ingress-gateway`, `terminating-gateway` and `service-router` without namespace fields reconciles just once and does not lead to a reconcile loop.
Checklist:

Default namespaces for CRDs that support namespace when enabled

---

CHANGELOG.md
api/common/common.go
controller/configentry_controller.go
controller/configentry_controller_test.go

Support annotation consul.hashicorp.com/migrate-entry on custom
resources that will allow an existing config entry to be migrated onto
Kubernetes. The config entry from then on will be managed by Kubernetes.
This will support existing users of the Helm chart that already have
config entries in Consul and allow them to migrate to CRDs.
* code
* manual testing
1. spin up cluster with
```yaml
global:
name: consul
imageK8S: ghcr.io/lkysow/consul-k8s-dev:jan12
server:
replicas: 1
connectInject:
enabled: true
controller:
enabled: true
```
1. create a service-defaults config:
```bash
kubectl exec consul-server-0 -- echo '{"kind": "service-defaults", "name": "foo", "protocol": "http"}' | consul config write -
```
1. read it
```bash …
```

Migrating config entries into custom resources

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go
subcommand/server-acl-init/command_test.go

To prevent users from being confused as to why their traffic isn't being
routed, give an error on connect injection if they've configured an
upstream to use a datacenter but they don't have a proxy-defaults config
with mesh gateway mode set to local or remote.
NOTE: No ACL changes need to be made because `proxy-defaults` does not require an ACL for reads (https://www.consul.io/api-docs/config#get-configuration)
How I tested:
* Install with:
```yaml
global:
name: consul
imageK8S: ghcr.io/lkysow/consul-k8s-dev:jan20
acls:
connectInject:
enabled: true
controller:
enabled: true
server:
replicas: 1
```
* Apply
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: static-client
---
apiVersion: v1
kind: Pod
metadata:
name: luke
annotations: …
```

Error when mesh gateway mode not set

---

CHANGELOG.md
controller/configentry_controller.go
controller/configentry_controller_test.go

Previously if the config entry already existed in Consul we'd give an
error like:
config entry managed in different datacenter: "other-dc"
This worked well if the config entry had been created by a controller
running in another Kube cluster, but if the user had created the config
entry directly in Consul then it wouldn't have the datacenter annotation
and so the error would actually read:
config entry managed in different datacenter: ""
Which was confusing.
This change changes the error in that case to read:
config entry already exists in Consul
Checklist:

Give better error if config entry already created

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go

Consul [filtering]((https://www.consul.io/api/features/filtering#selectors)) API only supports ASCII character, numbers, and underscores
as selectors.
So if someone tries to use that meta key for e.g. a service-resolver,
it won't work.
- Switch the meta key for the pod name from `pod-name` to `pod_name`
- Steps outlined [here](https://github.com/hashicorp/consul-k8s/issues/373#issuecomment-769351345).
- code review
Checklist:

Use an underscore instead of a dash for the pod name meta key

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go

Reverts hashicorp/consul-k8s#427
We can actually just use `ServiceMeta["pod-name"]`, which specifically exists for the use case when your meta keys have non-valid selector characters (h/t @lkysow for this find).

Revert "Use an underscore instead of a dash for the pod name meta key"

---

catalog/to-consul/resource.go
catalog/to-k8s/sink.go
connect-inject/health_check_resource.go
helper/controller/controller.go
helper/controller/controller_test.go
helper/controller/resource.go

Refactor our controller implementation to include the resource as part
of the deletion event. During a delete event, we get the full object
however previously we would discard this object and record only the key
of the object that was deleted. Then later when we would dequeue this
event, the object could not be retrieved from our cache because it was
deleted from Kubernetes and our cache is usually up to date with the
state of Kubernetes.
This will be useful for cleaning up force deleted pods because we can
use the pod object from the event to determine which Consul service
instance that pod got registered as (and potentially delete it if it's
still registered).
Checklist:

Include object with delete events

---

subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

This refactor paves the way for adding the cleanup controller. It
removes the if/else statement around starting the mutating webhook
server when health checks are enabled vs when they're not and instead
starts it the same way in both cases.
Previously the code looked like:
```
if healthChecks {
// start goroutine for health checks
// start goroutine for webhook server
// use select{} to wait
} else {
// start webhook server
}
```
Now it looks like:
```
// start goroutine for webhook server
if healthChecks {
// start goroutine for health checks
}
// use select{} to wait
```
This makes it easier to later do the below because we're already starting everything in goroutines and using select to wait:
```
// start goroutine for webhook server
if cleanup {
// start goroutine for cleanup …
```

Refactor inject-connect command

---

CHANGELOG.md
connect-inject/cleanup_resource.go
connect-inject/cleanup_resource_test.go
connect-inject/container_init.go
connect-inject/container_init_test.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go
subcommand/server-acl-init/command.go
subcommand/server-acl-init/command_ent_test.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

* Runs by default
* Watches for pod delete events and ensures there are no stale Consul
service instances
* Runs a Reconcile loop on a timer that checks all Consul services
* Adds new connect-inject flags: `-enable-cleanup-controller`,
`-cleanup-controller-reconcile-period`.
* Adds new `k8s-namespace` meta key to connect service instances
* Adds new server-acl-init flag: `-enable-cleanup-controller` (default
true) and modifies the ACL templates.
* manually and with acceptance tests: https://github.com/hashicorp/consul-helm/pull/806
* reconcile can be tested by registering a service directly with a consul client:
* port-forward to consul client on 8500
* use `svc.json`:
```
{
"ID": "redis1",
"Name": "redis",
"Tags": ["primary", "v1"],
"Address": "127.0.0.1", …
```

Implement cleanup controller

---

connect-inject/health_check_resource.go
connect-inject/health_check_resource_test.go
subcommand/inject-connect/command.go

- refactor Run loop
- use ConsulPort and ConsulScheme instead of ConsulURL
- reconcile() does not return an error since it is logged during that
function
Matches https://github.com/hashicorp/consul-k8s/pull/433#discussion_r573365394

Refactor health resource to match cleanup resource

---

connect-inject/cleanup_resource.go
connect-inject/cleanup_resource_ent_test.go
subcommand/inject-connect/command.go

Checklist:
Implementation Notes:
* There's no Consul API to list all services in all namespaces so instead we need to first get all namespaces and then iterate through them and list all services.
* To keep the OSS and enterprise code paths as close as possible, we use a fake namespace in oss with value empty string `""` which can then be safely passed to `QueryOptions{Namespace: ""}` without error.
Acceptance tests: https://github.com/hashicorp/consul-helm/pull/826.
Docker image: `ghcr.io/lkysow/consul-k8s-dev:feb11`

Cleanup controller support for Consul NS's

---

connect-inject/consul_sidecar.go
connect-inject/consul_sidecar_test.go
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go
connect-inject/handler_test.go
subcommand/common/common.go
subcommand/common/common_test.go
subcommand/consul-sidecar/command.go
subcommand/consul-sidecar/command_test.go
subcommand/inject-connect/command.go

Adds metrics merging feature to consul-k8s.
- inject-connect takes default metrics flags
- supports annotations for overriding the default flags
- inject-connect passes metrics flags to connect-inject handler
- handler now has functions to grab configuration from the default flags or the overridden values from the annotations
- from the handler:
- init container adds envoy_prometheus_bind_addr and flags to consul connect envoy
- consul-sidecar is given the appropriate flags to run the merged metrics server
- added prometheus annotations to pod to scrape from
- consul-helm (`test-metrics` branch)
- consul-k8s (`merged-metrics` branch)
- consul (`metrics-merging` branch)
- Build the consul and consul-k8s images or use:
- …

Add metrics merging and Prometheus annotations to connect-injected Pods

---

subcommand/consul-sidecar/command.go
subcommand/consul-sidecar/command_ent_test.go
subcommand/consul-sidecar/command_test.go

Refactor merged metrics tests to use fewer ports and use freeport package.
- This will help the tests run in parallel and not conflict with other
tests using freeport.
Co-authored-by: Kyle Schochenmaier <kschoche@users.noreply.github.com>
- Run through steps in https://github.com/hashicorp/consul-k8s/pull/438
- Code review
Checklist:

Refactor merged metrics tests to use fewer ports and use freeport package

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go
connect-inject/handler_test.go

- split the existing connect init container into two init containers:  1 does the consul binary copy and the other does the existing leg-work for registration. This is part of the tproxy refactor which sees the existing init container functionality replaced by a new consul-k8s command (incoming PR).
manually deployed and confirmed connect inject still works with the correct init containers.
new and existing unit tests work.
deploy kschoche/consul-k8s-dev and a sample connect injected app to confirm it still mutates and now has 2 containers instead of 1.
```
Events:
Type     Reason     Age   From               Message
----     ------     ----  ----               -------
Normal   Scheduled  22s …
```

Tproxy split init containers

---

connect-inject/cleanup_resource_ent_test.go

- wait for serf checks to pass before proceeding with the testing because the creation of the `consul` service is driven by completion of the serf check. Without this wait or a manual validation of the consul service existing *in the catalog* the test will run reconcile and pass before the consul service exists in the catalog resulting in the ENT tests failing because they use `Catalog()` API calls to validate final states.
Unit test fix with ent consul binary
pass CI
Checklist:

wait for serf check before starting the test

---

CHANGELOG.md
api/v1alpha1/serviceresolver_types.go
api/v1alpha1/serviceresolver_types_test.go

- `ServiceResolver` validation: if hashPolicy.field is set fieldValue must also be set 
- `ServiceResolver` validation: hashPolicy.field can be empty if hashPolicy.sourceIP is true
- unit tests
- review tests & changes
Checklist:

Fix incorrect validation for ServiceResolver

---

connect-inject/container_init.go
connect-inject/container_init_test.go
subcommand/common/test_util.go
subcommand/connect-init/command.go
subcommand/connect-init/command_test.go

- Extends `connect-init` command to wait for the service to be registered. When the endpoints controller is added this will be allow the init container to wait for the service to be registered prior to bootstrapping envoy.
- Adds  `pod-name` , `pod-namespace` flags to `connect-init` as well as a flag to disable the new service registration polling feature to preserve backwards compatibility until the endpoints controller is merged.
Unit tests added and old ones passing.
Manually build consul-k8s dev image and deploy with ACLs enabled and connect inject an application.
code review and manually test by deploying consul and an injected app and seeing that it gets injected and started.
Checklist:

add service registration polling to connect-init

---

namespaces/namespaces_test.go

- Add a wait on the consul server so that we do not race on the bootstrap ACL existing.
This test previously failed in CI and locally but only about 1/10 times:
```    
namespaces_test.go:50: 
Error Trace:	namespaces_test.go:50
Error:      	Received unexpected error:
Unexpected response code: 403 (ACL not found)
Test:       	TestEnsureExists_AlreadyExists/acls:_true
```
unit tests pass
code review
Checklist:

add wait to test to prevent race on ACL read

---

connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go

- This watcher watches for Consul Agent pods to be in a running phase and the condition ready to be true and then reconcile all endpoints that have a ready/not-ready address that share a node name with that of the consul agent pod.
- Unit tests
- Iryna tested it
- Code review
Will link an acceptance test run to show that behavior hasnt been impacted.
Checklist:

Add watcher for agent pods to endpoints controller

---

connect-inject/container_init.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

The endpoints controller and test code is ready for review. 
The only things expected to change at this point are code and tests in handler (to remove always setting the service-name annotation) and inject-connect (to get the command unit tests to pass since the manager takes a kubeconfig that's hard to fake out).
Changes in this PR:
* supports creating, updating and deleting endpoints
* with different consul service name (using the service-name pod annotation) 
* updating endpoints supports adding and removing addresses from the endpoints object.
Todos:
* testing with new connect-init command
* testing end to end
Future PR:
* delete default annotation for service name (to not cause rebase issues with webhook refactor PR lined up after this one)
* inject-connect tests-- the webhook PR has …

Endpoints controller with tests

---

subcommand/connect-init/command.go
subcommand/connect-init/command_test.go

- when filter items have `-`'s we need to wrap the query in quotes when passing a filter to `consulClient.Agent().ServicesWithFilter()`.
- Update unit tests to use hyphenated names for pods and namespaces.
Changing `testPodName` from `counting` to `counting-foo` resulted in the unit tests failing, after the change they pass.
code review
Checklist:

tproxy use quotes in ServicesWithFilter's filter

---

subcommand/common/common.go
subcommand/common/common_test.go
subcommand/connect-init/command.go
subcommand/connect-init/command_test.go

- `ioutil.WriteFile()` will create the new file with the requested permissions prior to actually writing the file. This causes us to accidentally create it with "0444" which will not allow us to complete the write.
- Use `ioutil.WriteFile(.., .., 0666)` in combination with  `os.Chmod(0444)`  to create the file with the correct privs, and remove it first if it already exists in the event that we failed the command and the container is restarted.
- We missed this in the previous tests because we were using `WriteTempFile()` to create the files prior to passing them into the functions to be tested so that we could have easy cleanup, and that had default 0666 privs on it. In end to end testing this produced permission denied errors.
unit …

Tproxy writefile changes

---

.circleci/config.yml

- Update Consul version from 1.9.1-rc1 to 1.9.4 so that it matches consul-helm's default!
Ran it against a branch of mine and things looked good.
Checklist:

update circleci to use consul 1.9.4

---

connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
subcommand/inject-connect/command.go

- Adds support for ACLs and TLS to endpoints controller
- Minor change to how we deal with consul clients in the endpoints controller+tests.
Unit tests for ACLS+TLS have been added which cover normal paths as well as the three places that where we request a new consulClient:
1. processUpstreams()
2. 2x in Reconcile()  (deregisterServiceOnAllAgents() and regular Reconcile)
Manually run the connect-inject acceptance tests using https://github.com/hashicorp/consul-helm/pull/886/, with `imageK8S: "kschoche/consul-k8s-dev"` and uncommenting the TLS table tests.
Run unit tests / manually deploy and run acceptance tests.
Note: I'm willing to table-fy and add ACL/TLS support to all of the …

Add acls and tls to endpoints controller

---

connect-inject/consul_sidecar.go
connect-inject/consul_sidecar_test.go
connect-inject/container_init.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
connect-inject/handler.go
connect-inject/handler_test.go
connect-inject/metrics_configuration.go
connect-inject/metrics_configuration_test.go
subcommand/inject-connect/command.go

- Refactor metrics merging to work with endpoints-controller
Previously, all metrics configuration was dealt with in the mutating
webhook handler. Now, since service/proxy registration happens in
endpoints-controller, some of the metrics configuration needs to be used
in endpoints-controller as well. There is still some functionality in
the handler that also needs metrics configuration, such as adding
prometheus annotations and running the consul sidecar.
This refactor pulls out common configuration for metrics into a
MetricsConfiguration struct and adds the methods for getting values from
flags and annotations to that struct, so it can be commonly used between
endpoints-controller and the webhook handler.
~I wasn't able to E2E test this due to consul-k8s and …

Refactor metrics merging to work with endpoints-controller

---

connect-inject/annotations.go
connect-inject/cleanup_resource.go
connect-inject/cleanup_resource_ent_test.go
connect-inject/cleanup_resource_test.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
connect-inject/handler.go
connect-inject/handler_test.go

- change `annotationInject` to `keyInjectStatus` since its a duplicate key used in labels and annotations now.
unit tests pass
code review
Checklist:

change the annotationInject key since its a label as well now

---

connect-inject/endpoints_controller.go

- remove check for PodPending in `getReadyStatusAndReason()` as pods which are in PodPending phase are not part of the endpoints object and as such we would never be reconciling a pod from an endpoint object that is in this state.
Per @ishustava 's excellent investigation pods which are in PodPending phase are not included in the endpoints object list so we would never need to have this check.
https://github.com/hashicorp/consul-k8s/pull/476#discussion_r610080955
Unit tests still pass
Read background in link above, code review
Checklist:

remove processing of pods in PodPending phase in endpoints controller

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_ent_test.go
connect-inject/endpoints_controller_test.go
go.mod
subcommand/common/common.go
subcommand/common/common_test.go
subcommand/connect-init/command.go
subcommand/connect-init/command_ent_test.go
subcommand/inject-connect/command.go

- Register/Deregister services from the correct namespace.
- Ensure we create the ACL for the service in the correct namespace when creating it and we query for the service in the namespace it gets created in during connect init.
- Additionally, clean up logging in the endpoints controller to be less verbose
`controller.endpoints-controller	retrieved Kubernetes Endpoints	{"endpoints": "consul-dns", "endpoints-namespace": "default"}` -> `controller.endpoints retrieved {"name": "consul-dns", "ns":"default"}`
- Unit tests.
- Run the `connect` acceptance tests against it and it went green.
- Code review
Image for helm: `ashwinvenkatesh/consul-k8s@sha256:adfbb40eedb2943e3008d7f5bd57753784b94cf6a0d79c5f …

Support Consul ENT Namespaces in the endpoints controller

---

connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler.go
connect-inject/handler_test.go
subcommand/connect-init/command.go
subcommand/connect-init/command_ent_test.go
subcommand/connect-init/command_test.go

- Remove the default service name annotation
- ~There's a check in container_init.go to make sure the annotation and the service account name match. That check has been modified so it only compares the annotation and the service account name if the annotation is set.~
- ~If the annotation is *not* set, then the error handling moves to the connect-init command in the init container. When it polls for the matching service, if the k8s-service-name metadata does not match the service account name, it will fail to set up the init container so the user will continue to see the error before the pod comes up, rather than a mismatched token being created.~
- The connect-init command uses the values of the new `service-name` and `service-account-name` flags, and if …

Remove default service name annotation

---

build-support/docker/Dev.dockerfile
build-support/docker/Release.dockerfile
connect-inject/annotations.go
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
connect-inject/handler.go
go.mod
go.sum
subcommand/inject-connect/command.go

* add new -enable-transparent-proxy flag to inject-connect command,
which will enable all transparent proxy mode for all applications running
on the Consul service mesh.
* add a new pod annotation consul.hashicorp.com/transparent-proxy to allow
enabling or disabling transparent proxy mode.
* endpoints-controller will configure proxy service registrations to enable
transparent proxy when the above flag is passed or when tproxy annotation is set.
It will also add service's cluster IP to both the service and proxy registrations
as a tagged address so that Consul can configure Envoy filter traffic based on that IP.
* consul-connect-inject-init container will apply traffic redirection rules
via consul connect redirect-traffic command which runs iptables under the …

Enable tproxy for the Consul service mesh

---

connect-inject/consul_sidecar_test.go
connect-inject/handler.go
connect-inject/handler_ent_test.go
connect-inject/handler_test.go
subcommand/connect-init/command.go
subcommand/inject-connect/command.go
subcommand/inject-connect/command_test.go

- Previously the handler was using hclog, which logs the webhook logs to a different output from the controller logs. In order for them to be written to where the controller logs are, we update the handler to now use zaplogger over hclog.
How I've tested this PR: Run tests
How I expect reviewers to test this PR: Code review
Checklist:

Update the handler to use zap logger

---

connect-inject/endpoints_controller.go

- Add info logs to capture svcs getting deregistered and an error log when we fail to get the health of a pod.
- Ensure we populate the address map in the endpoints controller using the pod IP from the pod object and not from the endpoint to ensure consistency.
- Add pointers to the struct receivers to ensure we use them consistently as required by the Hashicorp style guide.
cc @lkysow 
How I've tested this PR: This is a refactor.
How I expect reviewers to test this PR: Code review
Checklist:

Fix logging

---

subcommand/connect-init/command.go

- While waiting for registered services to get listed in the connect init, it waits for 60 seconds before failing. Valid service
registrations could take longer than 60 seconds. Upping the wait time to 120 seconds to ensure we dont fail prematurely.
Checklist:

Increase the wait time in connect-init

---

CHANGELOG.md
api/v1alpha1/proxydefaults_types.go
config/crd/bases/consul.hashicorp.com_proxydefaults.yaml

Prior to `apiextensions.k8s.io/v1`, structured schema was [optional](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) for CRD spec, but now it is required. Since `config` field can have arbitrary keys, we need to tell Kubernetes to allow that explicitly now that we've upgraded from `v1beta1` to `v1`.
- Set `x-kubernetes-preserve-unknown-fields` to `true` for the `config` field in `ProxyDefaults`
by running acceptance tests
code review (acceptance tests in hashicorp/consul-helm#921)
Checklist:

Allow unstructured schema for the ProxyDefaults CRD

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/envoy_sidecar.go
connect-inject/envoy_sidecar_test.go
connect-inject/handler.go

- Add a security context to the init copy container and the envoy sidecar and ensure they run as non-root.
- Add `RunAsNonRoot: false` to the connt-init container so that it can run as root even if the Pod has this disabled. This should address https://github.com/hashicorp/consul-helm/issues/918. 
- Remove an unused param in the envoySidecar() function.
unit tests.
I've deployed this into a test cluster with a sample app that has:
(1) no pod security contexts  
and
(2) pod security context : 
```
securityContext:
runAsUser: 1000
runAsGroup: 3000
fsGroup: 2000
runAsNonRoot: true
``` 
and confirmed that the pod deploys succesfully with the changes to the init container and fails without them. 
unit …

use rootless containers where possible

---

build-support/docker/Release.dockerfile

- This adopts the new HashiCorp PGP key, as described at https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 and https://hashicorp.com/security. 
Please merge after reviewing 🙏 
Built the docker image locally
Build locally & run the container

Adopt new pgp key

---

CHANGELOG.md
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go

Previously, we were updating health check status based on the pod status
of the pod that the endpoints address is pointing to. However, since the
endpoints controller is not watching pod objects, it will not always have
the most updated pod information in the cache. This results in incorrect behavior
where sometimes the pod we get will have stale information and we update the
health check status in Consul incorrectly.
This PR changes this behavior to instead get the health check status from
the endpoints object. The endpoints object already has information about ready
and not ready addresses, and it will always have updated cache since we receive
events based on updates from the Kubernetes API server to the cached Informer.
Acceptance test …

Update health check status based on the endpoints object instead of pod

---

subcommand/connect-init/command.go
subcommand/connect-init/command_test.go

- Only use UI.Error/Info/etc for startup or validation logging, then switch to use hclog to log everything else.
- Update the command tests accordingly.
Manual testing + updated unit tests.
```
2021-04-22T13:18:07.053-0500 [INFO]  Consul login complete
2021-04-22T13:18:07.055-0500 [INFO]  Registered service has been detected: service=counting
2021-04-22T13:18:07.055-0500 [INFO]  Registered service has been detected: service=counting-sidecar-proxy
2021-04-22T13:18:07.055-0500 [INFO]  Connect initialization completed
```
code review, unit tests
Checklist:

use hclog instead of UI logging for connect-init

---

connect-inject/annotations.go
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/handler_test.go

This PR depends on hashicorp/consul#10134
We allow the exclusion of the following:
* Exclude inbound ports
* Exclude outbound ports
* Exclude outbound CIDRs
* Exclude UIDs
I tested it manually. Here are the steps I followed
Install the helm chart on kind: 
```
helm install iryna --set connectInject.enabled=true  --set server.replicas=1 hashicorp/consul --set global.imageK8S=ishustava/consul-k8s-dev:04-27-2021-b4826d4 --set global.image=ishustava/consul-dev:iptables-exclude --version 0.32.0-beta1
```
I've used the following to test these annotations:
1. To test inbound port exclude static-server's inbound port `8080` on the static-server deployment
2. To test outbound port exclude port `80` so we can reach google.com from the static-client deployment
3. To test outbound IPs set consul …

Allow to exclude inbound and outbound traffic when using tproxy via annotations

---

CHANGELOG.md
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go

Previously, we set a tagged address for each Kubernetes service port,
using the "virtual-" prefix for the tagged address key. For example,
if a service port is named "tcp", then we synced it to Consul with
the tagged address key "virtual-tcp".
However, since Consul doesn't really support multiple ports on a service yet,
this is unnecessary. So instead, we will find the service's target port
that is equal to the service port we are registering with Consul
and use that as the Port for the tagged address. Otherwise,
if we can't find the target port, we will set the tagged address's port to 0
(it will still have the cluster IP set).
- unit tests
- code review
Checklist:

Don't support syncing multiple addresses when k8s service has multiple ports

---

CHANGELOG.md
connect-inject/annotations.go
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_ent_test.go
connect-inject/endpoints_controller_test.go
connect-inject/handler.go
connect-inject/handler_ent_test.go
connect-inject/handler_test.go
connect-inject/metrics_configuration_test.go
subcommand/inject-connect/command.go

- Adds ability to define default tproxy mode settings at the k8s namespace level.
- ~~renames tproxy annotation to "consul.hashicorp.com/transparent-proxy-default"~~
Unit tests, manual testing via deploying a simple counting service with no tproxy annotations set, then toggling the namespace label true/false and redeploying:
```
% kubectl describe pod counting | grep redirect
/consul/connect-inject/consul connect redirect-traffic \
% kubectl get namespaces --show-labels| grep transparent
default           Active   261d   consul.hashicorp.com/transparent-proxy=true
% kubectl delete -f svc.yaml
service "counting" deleted
serviceaccount "counting" deleted
pod "counting" deleted
% kubectl label namespace default …
```

add namespace toggle to tproxy

---

CHANGELOG.md
connect-inject/endpoints_controller.go
subcommand/connect-init/command.go

- `connect-init` will now periodically log a message stating that the pod is waiting on a Kubernetes service to be registered against and direct the user to logs in the webhook.
- endpoints controller will now also log the serviceID and the remote agent's hostIP.
code review
code review
Checklist:

update tproxy logging messages to be a bit more informative

---

CHANGELOG.md
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go

- Allow the endpoints controller to fully process the endpoints object prior to returning error in the case where processing one of the target addresses fails.
unit test added which creates an address which does not have a backing pod so that when we reconcile it that address fails and then we assert that the others still got processed.
code review + unit tests
Note to reviewers: I thought about adding tests cases which cover other errors in the reconcile path aside from what is covered in the `TestReconcileCreateEndpoints()` but I'm not sure they are totally necessary to validate the code changes. I'd be happy to add additional test cases to other tests of course.
Checklist:

fully process the endpoints object before returning error

---

CHANGELOG.md
connect-inject/annotations.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
connect-inject/handler.go
connect-inject/handler_test.go
subcommand/inject-connect/command.go

When this is enabled, the mutating webhook will also overwrite the HTTP probes
of the application container to point them to Envoy, while saving the original
ports of the probes as annotations. The endpoints controller will set Expose
configuration for the proxy, setting the LocalPathPort to the port saved
in the annotation.
- Add a new flag -transparent-proxy-default-overwrite-probes (default to true)
to allow overwriting k8s probes.
- Allow setting this on a per-pod basis via the "consul.hashicorp.com/transparent-proxy-overwrite-probes"
annotation
- Add new annotations to allow for choosing custom ports for Envoy listeners to expose
readiness and liveness probes
- Also, rename the `-enable-transparent-proxy` to `-default-enable-transparent-proxy`
Acceptance test …

Overwrite k8s HTTP probes when transparent proxy is enabled.

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go
connect-inject/envoy_sidecar.go
connect-inject/envoy_sidecar_test.go
connect-inject/handler.go
subcommand/inject-connect/command.go

* Envoy container should not have security context set when on OpenShift
and when tproxy is disabled because we want to let OpenShift set a random
user/group. When tproxy is enabled though, we need to still set it on OpenShift
because we require Envoy to have a specific user for the traffic redirection to work.
* init-copy-container doesn't need to have security context set whenever running on OpenShift
(regardless of whether tproxy is enabled or not) so that OpenShift can set its own random user/group.
[acceptance tests on openshift](https://app.circleci.com/pipelines/github/hashicorp/consul-helm/3020/workflows/7784b7b3-dfea-4980-b52b-263a57f49ea8/jobs/12238)
code review
Checklist:

Don't set security context when on OpenShift

---

CHANGELOG.md
connect-inject/container_init.go
connect-inject/container_init_test.go

On OpenShift, if we don't set this value, the container will not provisioned with proper
privileges to run iptabels commands
manually, on openshift
code review
Checklist:

consul-connect-inject-init needs to run privileged: true when tproxy is enabled

---

.circleci/config.yml

- update consul-k8s ci config to use consul 1.10.0-beta3
Checklist:

update consul-k8s ci config to use consul 1.10.0-beta3

---

CHANGELOG.md
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go

When Consul namespaces are not enabled and we are processing a service
that already exists in Consul but with a different k8s namespace meta,
we skip service registration to avoid service name collisions.
unit-tests
code review
Checklist:

Don't register duplicate services from different k8s namespaces

---

CHANGELOG.md
subcommand/webhook-cert-manager/command.go
subcommand/webhook-cert-manager/command_test.go

When the certificate secret is created or updated, set an OwnerReference on the secret as the `webhook-cert-manager` deployment. This ensures that deletion of the deployment will also delete the secrets. This addresses the race condition bug that we sometimes see when re-installing consul on a cluster that had a consul deleted from it. This was because the helm delete would not delete the existing secrets with certificates. When the controller would get created with a new installation, it would mount the existing secret (which was stale) and the secret on disk would get rotated before the cert watcher started which would lead to the controller using certificates signed by a CA different from the CA bundle on the MWC which would lead to x509 errors.
This change …

Set owner reference to secrets created by webhook cert manager

---

CHANGELOG.md
connect-inject/annotations.go
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go
connect-inject/envoy_sidecar.go
connect-inject/handler.go
connect-inject/handler_test.go

- When tproxy is enabled, rewrite the probes on every container in the
pod spec.
- Remove support for annotations for originalPorts and
updatedListenerPorts.
- Save the original pod as an annotation as marshalled json.
Checklist:

Add support for multi-container probe overwrite

---

CHANGELOG.md
connect-inject/handler.go
connect-inject/handler_test.go

Fixes issue where we weren't setting the upstream environment variables
when the upstream annotation was set:
* `<NAME>_CONNECT_SERVICE_HOST`
* `<NAME>_CONNECT_SERVICE_PORT`
Since we're modifying a slice's values during iteration we must access
the element via reference using the index.
Fixes https://github.com/hashicorp/consul-k8s/issues/549
* unit tests
* code
Checklist:

Fix bug where upstream env vars not set

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- Added thumbs up verbiage to the feature and bug report issue templates. Best viewed in RAW file format due to instructions that are embedded as comments, which will not be displayed when filing. 
Checklist:

Add thumbs up template and revamp issue templates

---

CHANGELOG.md
subcommand/webhook-cert-manager/command.go
subcommand/webhook-cert-manager/command_test.go

Currently if you are running Kubernetes 1.19+ you will have the following logs flooding the the cert manager webhook:
```
W0709 18:25:22.612753       7 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```
- Use `clientset.AdmissionregistrationV1` instead of `clientset.AdmissionregistrationV1beta1` API as it was deprecated in k8s 1.16.
- Update tests accordingly.
manually deployed to k8s 1.20 and confirmed the warnings are gone
Unit tests updated and still pass.
code review
Checklist:

Update v1beta1 to v1 for webhook cert manager

---

CHANGELOG.md
api/v1alpha1/proxydefaults_types.go
api/v1alpha1/proxydefaults_types_test.go
api/v1alpha1/servicedefaults_types.go
api/v1alpha1/servicedefaults_types_test.go
api/v1alpha1/shared_types.go

There is a bug (https://github.com/hashicorp/consul-helm/issues/1023) where if you're on Consul <1.10.0 then proxy-defaults no longer works. This is because we were always setting the `transparentProxy` key, even when it was `nil` on the source CRD.
Fixing this bug then caused another issue where Consul always returns the `transparentProxy` key as an empty struct, even when it was written as a nil pointer (https://github.com/hashicorp/consul/issues/10595). To fix this for now, when we do our equals comparison we need to treat the empty struct and nil pointer as equal.
* This fix applies for `ServiceDefaults` and `ProxyDefaults` CRDs that
both allow setting the `transparentProxy` key.
* First, if `transparentProxy` is not set on the CRD, don't write the
empty struct into Consul, instead …

Handle TransparentProxy field CRD syncing

---

subcommand/connect-init/command.go

- After some feedback it seemed helpful to point users at the controller logs if connect-init is stuck in a wait loop, add this.
code review
code review
Checklist:

add some additional log msgs for connect-init

---

CHANGELOG.md
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_ent_test.go
connect-inject/endpoints_controller_test.go
connect-inject/handler.go
helper/test/test_util.go
subcommand/common/test_util.go
subcommand/connect-init/command_ent_test.go
subcommand/connect-init/command_test.go
subcommand/create-federation-secret/command_test.go
subcommand/get-consul-client-ca/command_test.go
subcommand/inject-connect/command.go
subcommand/server-acl-init/command_test.go
subcommand/server-acl-init/rules.go
subcommand/server-acl-init/rules_test.go

Fixes #540 
- Modify endpoints controller to delete ACL tokens for each service instance that it deregisters
- Remove TLS+ACLs table tests from endpoints controller tests. These tests were testing that endpoints controller works with a client configured to have TLS and ACLs. I thought this test was not necessary because there isn't any code in the controller that behaves differently if the consul client is configured with any of those and as a result there's no way these tests could fail. The tests testing to the new ACL logic are there but they are only testing the logic that was added and configure test agent to accommodate for that.
- Create test package under `helper` and move `GenerateServerCerts` function from `subcommand/common` there because it was …

connect: endpoints controller deletes ACL token when service is deregistered

---

connect-inject/container_init.go
connect-inject/container_init_test.go

Fixes #570,#568
- `redirect-traffic` command should use an ACL token that we get from running `consul login`
* unit tests
* acceptance tests in hashicorp/consul-helm#1058
- code review 👀 
Checklist:

connect: redirect-traffic command should pass ACL token when ACL are enabled

---

CONTRIBUTING.md

- Update the contributing guide to include information about running golangci locally.
-
Checklist:

update contributing guide with golangci info

---

CHANGELOG.md
connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_test.go

Previously, we would skip service registration if we find a duplicate service
even when the 'k8s-namespace' meta key is not present on the service.
However, that is not correct behavior since that would ignore any service
instance that could exist on other platforms (e.g. VMs) and that
doesn't have this meta key. We should instead only check services that
have the 'k8s-namespace' meta key.
- unit tests
- code review
Checklist:

connect: skip service registration only for duplicate services on k8s

---

connect-inject/endpoints_controller.go
connect-inject/endpoints_controller_ent_test.go
connect-inject/endpoints_controller_test.go
subcommand/connect-init/command.go

This is a follow-up to #571 
Endpoints controller may have stale cache for pod objects since it's only
watching the endpoints objects. As a result when we try to get a pod
from cache, it may be stale. For the case of deleting ACL tokens,
we can't tolerate stale cache reads since we need to know for sure
if the pod exists to determine if an ACL token for that pod should be deleted.
This commit changes it to instead use the pod info stored in the endpoints addresses
as TargetRef.
This can be seen in the failed acceptance tests build [here](https://app.circleci.com/pipelines/github/hashicorp/consul-helm/3477/workflows/85035325-7c4d-48ef-9ea2-fdbb3a9a83f3/jobs/15657).
Also, remove `fmt.Printf` and `fmt.Println` statements in tests and code as I think they were left accidentally.
How I've …

connect: don't get pods from the API to determine if ACL should be deleted

---

CHANGELOG.md
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/server-statefulset.bats

Previously we were executing consul directly via /bin/consul and we were
using the Kubernetes `command` key which overrides the default Docker
ENTRYPOINT.
This had no issues, however I propose that it's best to execute via the
entrypoint so we keep things consistent with how the Docker image was
supposed to be run. This is also consistent with Vault's Helm chart. If
you step through the entrypoint script, nothing actually changes with
how we execute consul because we don't trigger any of the `if`
statements. So there is no real effect right now.
In order to support using the entrypoint script, we need to disable part of the
script that attempts to change the ownership of the /consul directory
because the ownership is already set via Kube. To disable this we set the
`DISABLE_PERM_MGMT` env …

Use docker-entrypoint when running consul

---

CHANGELOG.md
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_ent_test.go
control-plane/connect-inject/endpoints_controller_test.go

Fixes #599 
- Instead of deleting any ACLs tokens for pods that the endpoints object doesn't point to, we now only delete tokens whenever services are deregistered. This is to fix an issue when endpoints controller has not yet processed the pod change for an endpoints object.
unit tests
code review
Checklist:

Delete ACL token only for services that are deregistered.

---

control-plane/build-support/functions/10-util.sh

- This script is being called from prod-upload-and-publish and is failing because changelog is top level but version/version.go is inside control-plane

fix make dev-tree to use module directory in set_dev_mode

---

control-plane/build-support/functions/10-util.sh

The makefile has to be called inside the control-plane directory so this fixes the path for changelog in make dev-tree

Fix make dev tree changelog path

---

control-plane/build-support/scripts/dev.sh

- The previous fix did not work because the git functions were still being called with the control-plane directory, and we need those to be called from the top level repo.
We actually tested locally except for pushing to git, 🤞

Fix make dev-tree to pass in the correct directory for git functions

---

control-plane/build-support/docker/Release.dockerfile
control-plane/build-support/docker/Release.ubi.dockerfile

- Add new Dockerfile for building OpenShift images based on redhat's UBI image
- Move Dockerfile for our regular image from the releases repo to here so that both the regular and UBI images are in the same repo
- Base image changes from alpine to registry.access.redhat.com/ubi8/ubi-minimal:8.4
- the license file must live at /licenses/mozilla.txt
- creating the user and group is moved to after the package installs since the groupadd utility is not available before the package installs
- microdnf is used instead of apk to install packages since apk is an alpine utility and microdnf is a smaller yum
- install wget, unzip to allow downloading from releases.hashicorp.com
- install shadow-utils to add the groupadd and adduser utilities
- don't install su-exec since …

Docker image for OpenShift

---

.circleci/config.yml

- Currently every job is put on hold, so we need to disable the helm chart pipeline trigger. We can comment it in as needed in a branch to trigger the pipeline, but it shouldn't be commented in in master right now.

Disable helm chart pipeline trigger so it doesn't put every job on hold

---

CHANGELOG.md
control-plane/version/version.go

- Usually the pipeline would do this but we had to comment out non-idempotent parts of the pipeline yesterday and didn't end up re-running this step. I've manually run `make dev-tree`
review

Putting source back into Dev Mode

---

CHANGELOG.md
charts/consul/templates/ui-service.yaml
charts/consul/test/unit/ui-service.bats
charts/consul/values.yaml

I followed the same pattern as for `nodePort`. This is generally useful for specifying load balancer ports and we have this option already for mesh gateways. This is also useful for running in Minikube because `minikube tunnel` will open up `localhost:<port>` and so you can have the Consul UI on `localhost:8500` rather than `localhost:80`.
Taken from https://github.com/hashicorp/consul-helm/pull/1062
* helm tests
How I expect reviewers to test this PR: code
Checklist:

Add ability to specify port for ui service

---

control-plane/build-support/docker/Release.ubi.dockerfile

tar is required for kubectl cp to work and it's also included by default
in our regular images through Alpine so makes sense to have it here.

Add tar to UBI image

---

control-plane/build-support/docker/Dev.dockerfile
control-plane/build-support/functions/20-build.sh

```
make dev-docker
==> Building Consul - OSes: linux, Architectures: amd64
Using gox for concurrent compilation
Number of parallel builds: 11
-->     linux/amd64: github.com/hashicorp/consul-k8s/control-plane
[+] Building 8.1s (8/8) FINISHED
=> [internal] load build definition from Dev.dockerfile                                                         0.0s
=> => transferring dockerfile: 180B                                                                             0.0s
=> [internal] load .dockerignore                                                                                0.0s
=> => transferring context: 2B                                                                                  0.0s
=> [internal] load metadata for …
```

Update dev dockerfile to use latest image

---

control-plane/catalog/to-consul/resource.go
control-plane/catalog/to-consul/resource_test.go

This PR fixed an issue where consul-sync will register NodePort services with wrong internal IPs when multiple internal IPs are reported on the node, and this is a common pattern when using the AWS CNI plugin.
When using the AWS CNI plugin, multiple ENIs could be used and the secondary ENI with multiple IPs are not used by the node itself, but assigned to individual pods. In this case kubelet will end up reporting all used IPs on all ENIs as internal IPs on the node. ([Detailed explanation](https://github.com/kubernetes/kubernetes/issues/61921#issuecomment-384089455))
Kubernetes has since [made sure the first IP would be equal to the IP on eth0](https://github.com/kubernetes/kubernetes/blob/fe099b2abdb023b21a17cd6a127e381b846c1a1f/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go) …

[sync-catalog] Fix NodePort register service with wrong internal IP when multiple internal IPs are reported on the node

---

CONTRIBUTING.md

- Change a single reference to the Consul repository that included the `master` branch to the `main` branch as they have changed their branch naming strategy.
I went to the new link in the CONTRIBUTING doc and it resolved correctly.
Go to the new link in the CONTRIBUTING doc and check if it resolves correctly.

Change reference to consul repository from master to main

---

charts/consul/templates/client-podsecuritypolicy.yaml
charts/consul/templates/client-securitycontextconstraints.yaml
charts/consul/templates/client-snapshot-agent-podsecuritypolicy.yaml
charts/consul/templates/connect-inject-leader-election-role.yaml
charts/consul/templates/connect-inject-leader-election-rolebinding.yaml
charts/consul/templates/connect-inject-podsecuritypolicy.yaml
charts/consul/templates/controller-deployment.yaml
charts/consul/templates/controller-leader-election-role.yaml
charts/consul/templates/controller-leader-election-rolebinding.yaml
charts/consul/templates/controller-mutatingwebhookconfiguration.yaml
charts/consul/templates/controller-podsecuritypolicy.yaml
charts/consul/templates/create-federation-secret-job.yaml
charts/consul/templates/create-federation-secret-podsecuritypolicy.yaml
charts/consul/templates/enterprise-license-job.yaml
charts/consul/templates/enterprise-license-podsecuritypolicy.yaml
charts/consul/templates/ingress-gateways-podsecuritypolicy.yaml
charts/consul/templates/mesh-gateway-podsecuritypolicy.yaml
charts/consul/templates/server-acl-init-cleanup-podsecuritypolicy.yaml
charts/consul/templates/server-acl-init-podsecuritypolicy.yaml
charts/consul/templates/server-podsecuritypolicy.yaml
charts/consul/templates/server-securitycontextconstraints.yaml
charts/consul/templates/sync-catalog-podsecuritypolicy.yaml
charts/consul/templates/terminating-gateways-podsecuritypolicy.yaml
charts/consul/templates/tls-init-cleanup-job.yaml
charts/consul/templates/tls-init-cleanup-podsecuritypolicy.yaml
charts/consul/templates/tls-init-job.yaml
charts/consul/templates/tls-init-podsecuritypolicy.yaml
charts/consul/templates/webhook-cert-manager-podsecuritypolicy.yaml
charts/consul/test/unit/helpers.bats

- Add namespace to all templates. We saw this error when deploying with the CLI to the `consul` namespace, and a few resources were getting created in `default`. This only occurs using the Helm Go SDK, not the Helm CLI.
- NOTE: The test is not a catch all. It only greps for "namespace: " in every file. This means, if that string exists anywhere in the file, it won't error out. We couldn't use `yq` because this is still templated yaml. It would catch a majority of cases. If you have suggestions for making this better please let me know!
acceptance and unit tests.
review, make any suggestions to testing
Checklist:

Add namespace to all templates

---

.circleci/config.yml
CONTRIBUTING.md
charts/consul/Chart.yaml
control-plane/Makefile
control-plane/build-support/functions/10-util.sh

> 🚨 Do not merge until `master` is renamed to `main`
- All meaningful references to `master` have been changed to reference `main`
I grepped for `master` in the repo and filtered out instances that did not refer to the repo itself (e.g. master token) or referred to other repositories. Then I replaced the remaining instances.
How I've tested this PR:  
This is a hard one to test. I'm very open to suggestions.

Change references of `master` to `main`

---

.circleci/config.yml
charts/consul/test/acceptance/framework/consul/consul_cluster.go
charts/consul/test/acceptance/framework/helpers/helpers.go
charts/consul/test/terraform/gke/main.tf

- Allow privileged containers in the test PSP used by services deployed in tests
Ran GKE tests [here](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/2435/workflows/5cbda3ca-0ab4-40e0-96b0-0e725cfc76bb/jobs/14252)
code review

Re-enable psps in accceptance tests

---

charts/consul/Chart.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/values.yaml

Envoy 1.18.3 has a security vulnerability outlined in this advisory:
https://github.com/envoyproxy/envoy/security/advisories/GHSA-6g4j-5vrw-2m8h
This PR updates the Envoy image version.
----
Depends on: https://github.com/hashicorp/consul/pull/10961

Update Envoy image to 1.18.4

---

CHANGELOG.md
charts/consul/templates/connect-inject-deployment.yaml

We did so in https://github.com/hashicorp/consul-helm/pull/885, but it never got released.
This adds the same probe now that we have a health endpoint in the webhook.
This also changes the periodSeconds for the liveness and readiness probes
to use the default of 10s instead of 2s we used previously.
That is because now with the startup probe in place,
we don't need to check for certs being present that frequently.
- code review
Checklist:

Add startup probe to connect inject deployment.

---

charts/consul/values.yaml

Describe that `connectInject.default` should be used if trying to enable/disable `connectInject` by default. Addresses: https://github.com/hashicorp/consul-k8s/issues/698
- Comment to describe you should use namespaceSelector with `connectInject.default
```
❯ cat config.yaml
global:
name: consul
tls:
enabled: true
server:
replicas: 1
ui:
enabled: true
meshGateway:
enabled: true
replicas: 1
connectInject:
enabled: true
default: true
namespaceSelector: |
matchLabels:
connect-inject : enabled
controller:
enabled: true
❯ kubectl describe ns foo
Name:         foo
Labels:       connect-inject=enabled
Annotations:  <none>
Status:       Active
Resource Quotas
Name:                              gke-resource-quotas
Resource …
```

values.yaml: Make it more clear how to utilize connectInject.namespaceSelector

---

control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/connect_inject.go
control-plane/subcommand/server-acl-init/connect_inject_test.go
control-plane/subcommand/server-acl-init/create_or_update.go
control-plane/subcommand/server-acl-init/servers.go

- Change to single `ctx` in `connect_inject_test`
- Use `ctx` from command struct
- Instead of using `context.TODO()` throughout the `server-acl-init` package, use the `ctx` (previously called `cmdTimeout`) which is created within the `Run` function.
I still see test failures when I run this locally. I think I have something configured improperly or am missing a dependency. I'll sync up with @lkysow tomorrow and figure it out.
Check that the rename of `cmdTimeout` to `ctx` doesn't break anything. I think it should be ok. Also just run the tests for `control-plane` 🤷 .

Use command struct ctx in server-acl-init

---

.circleci/config.yml
charts/consul/test/terraform/aks/main.tf

- 1.19.9 is no longer supported; switch to the latest supported 1.19.x which is 1.19.13
[acceptance tests](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/2507/workflows/fc68f21e-be84-4691-b56d-56743ec20416/jobs/15210)
code review
Checklist:

Update AKS version in tests

---

.github/pull_request_template.md

- Add note to use present tense in the changelog entries
Checklist:
> Entries should use present tense (e.g. Adds support for...)

Add present tense note to PR template

---

.circleci/config.yml

Currently, all tests fail because the user is not allowed to `mkdir /consul/extra-config` ([link](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/2503/workflows/2bf83d1d-baf1-4024-907a-7d2385dd08bc/jobs/15161)) in the consul server and client pods. We need to wait for UBI images as that problem is fixed in that docker image.
Checklist:

Disable openshift tests until we can use UBI images

---

control-plane/catalog/to-k8s/sink.go
control-plane/catalog/to-k8s/sink_test.go
control-plane/subcommand/sync-catalog/command.go

- Add a context to the `K8SSink` struct
- Use the context in the struct for processes spawned by `K8SSink`
- Update tests on `K8SSink` to pass in a `context.Background()`
- Update the `sync-catalog` command which instantiates and uses `K8SSink` to pass in the `ctx` created when in its `Run` function
I ran the unit tests for the `catalog` and `sync-catalog` packages. They passed :).
Unit tests
Checklist:
- [-] CHANGELOG entry added (*HashiCorp engineers only, community PRs should not add a changelog entry*)

Use root context in sync-catalog to-k8s

---

CHANGELOG.md
charts/consul/templates/webhook-cert-manager-deployment.yaml
charts/consul/test/unit/webhook-cert-manager-deployment.bats
charts/consul/values.yaml

- Add configuration for the webhook-cert-manager deployment tolerations
This work closes issue #655 where the user was running Consul on a private cluster in GKE.
Added bats and manually produced the deployment YAML using helm.
Run bats
Checklist:

Add config for `webhook-cert-manager` tolerations

---

charts/consul/hack/aws-acceptance-test-cleanup/main.go

https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/2549/workflows/e3f5e78a-3e2e-4203-b7af-32be048a4626/jobs/15798
failed so thinking maybe it just takes longer sometimes to resolve the
issue.

Retry every 5s for deleting VPC

---

README.md

* Fix broken link to helm chart
* Fix wrong binary name: replace `consul-k8s` by `consul-k8s-control-plane` (see https://github.com/hashicorp/consul-k8s/releases/tag/v0.33.0)
N/A
N/A
Checklist:

README: Fix broken link to helm chart and wrong binary name

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go
control-plane/subcommand/inject-connect/command.go

- set a flag on endpoints controller with the status of Admin Partitions being enabled.
- when Admin Partitions are enabled, that first part of the upstream will be attempted to be broken into 3 pieces, named `x.y.z` where x is the service name, y is the namespace and z is the admin partition. if there are only 2 pieces, service name and namespace are assumed. if there is only 1 piece, service name is assumed.
- unit tests.
- code review
Checklist:

Add support for Admin Partitions to endpoints controller

---

.circleci/config.yml
CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/README.md
charts/consul/templates/client-config-configmap.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/values.yaml
control-plane/connect-inject/endpoints_controller_test.go

-  Bump default Consul version to 1.10.2
- fix tests that were failing due to a change in how the
DestinationUpstream field is set in Consul OSS vs Enterprise.
- set use_streaming_backend to false for Consul clients because
streaming is not currently supported with mesh gateway federation
- code
Checklist:

Bump Consul version to 1.10.2

---

charts/consul/templates/client-daemonset.yaml
charts/consul/templates/partition-init-job.yaml
charts/consul/templates/partition-name-configmap.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/partition-name-configmap.bats
charts/consul/values.yaml

- Fail if the user attempts to update the admin partition name on the server cluster to a value that isn't "default"
- Create an immutable configmap with the partition name which will cause `helm upgrade` to fail if the admin partition name is updated between the install and the upgrade.
Questions:
Even though the helm upgrade fails when the partition name is changed, the partition-init job runs and the agents get reassigned. I could make the partition-init job a `pre-install` job and not a `pre-upgrade` job, BUT the drawback of doing so would be anyone trying to upgrade an existing non-partition cluster to a partitioned cluster cannot. Should we ignore this use case? Ignore the upgrade use-case will ensure that the partition-init job will not run thereby not …

Only support default partition in server cluster

---

control-plane/connect-inject/handler.go

Previously this would always log:
```
handler.connect received pod    {"name": "", "ns": ""}
```
* Ran it and saw the logs
Checklist:
- Tests added (logging so no tests needed)
- CHANGELOG entry added (not sure this is necessary)

Fix logging in controller

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
control-plane/connect-inject/container_init.go
control-plane/connect-inject/container_init_test.go
control-plane/connect-inject/handler.go
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/connect-init/command_ent_test.go
control-plane/subcommand/inject-connect/command.go
control-plane/subcommand/inject-connect/command_test.go

- Update the envoy bootstrap config with the partition name so that it can correctly generate the envoy config. This was causing an error for Consul Connect 
`Unexpected response code: 400 (request targets partition \"default\" which does not match agent partition \"alpha\"\n)`
- Unit tests
– Deploying it to k8s and testing connect
- Code review
Checklist:

Update connect-inject with partition name

---

cli/README.md
cli/cmd/common/utils.go
cli/cmd/install/install.go
cli/cmd/install/install_test.go
cli/cmd/uninstall/uninstall.go
cli/cmd/uninstall/uninstall_test.go
cli/commands.go
cli/go.mod
cli/go.sum

Based off of a demo branch @sadjamz worked on here: https://github.com/hashicorp/consul-k8s-cli/tree/uninstall
- `consul-k8s uninstall` uninstalls the Consul Helm installation with options to wipe all data
- If you don't provide the release name/namespace, it will find the release whose metadata.name matches "consul", and then prompt to uninstall that release and any pvcs/secrets based on that.
- You can provide the release name/namespace in a case where you have already `helm uninstall`'ed the consul helm installation, but still have PVCs, Secrets, etc to clean up.
- Note that this PR is difficult to unit test-- acceptance tests are coming as the next task after install/uninstall are complete. The Helm steps are difficult to mock out for reasons mentioned …

cli: uninstall command

---

CHANGELOG.md
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats
charts/consul/values.yaml

[Enable injecting sidecar container via helm configuration.](https://app.asana.com/0/1159647457614001/1200520400490111/f)
Based off Vault implementation https://github.com/hashicorp/vault-helm/pull/87/files#
- Add `server.extraContainers` and `client.extraContainers` to `values.yaml`
- Change `client-daemonset.yaml` and `server-statefulset.yaml` to check for extraContainers
- Add bats tests 
- ran bats tests locally
- tested locally that the additional containers were created when extraContainers was specified
- ```helm install -f config.yaml nicoleta charts/consul```
Sample `config.yaml` file used:
```
server:
replicas: 1
extraContainers:
- name: static-server
image: docker.mirror.hashicorp.services/hashicorp/http-echo:latest
args:
- …
```

Enable injecting sidecar container via helm configuration.

---

charts/consul/test/acceptance/framework/config/config.go
charts/consul/test/acceptance/framework/config/config_test.go

- ☝️ Previously we'd parse the consul version from Chart.yaml, but this is confusing if we're trying to test a consul version that hasn't been released yet when it wouldn't make sense to update chart.yaml with it. This could result in false positives if we run tests by setting `global.image` and pass `-enable-enterprise` flag, since that will overwrite `global.image` to the ent version of the Consul image from Chart.yaml.
Checklist:

acceptance-tests-framework: create ent image from values.yaml isntead of Chart.yaml

---

.circleci/config.yml

- Grab helm binary from releases page rather than apt installing it. 
- The apt install stopped working because of an expired certificate on baltocdn: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/2798/workflows/54156ea4-54c6-4622-a4ec-4a623a266cb5/jobs/18933 
acceptance tests should go green
acceptance tests should go green

ci: fix installing helm prerequisite

---

charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/values.yaml

- Congiure resource requests and limits for the service init container on the mesh gateway deployment. 
Checklist:

add resource config for ServiceInit

---

control-plane/build-support/functions/10-util.sh
control-plane/build-support/scripts/dev.sh

- When `set_dev_mode` is called in build-scripts, set CLI to dev mode as well.
- We (@ndhanushkodi and I) ran `make dev-tree` from `/control-plane` and saw that the correct files were modified and committed.
- You may also run `make dev-tree`.
Checklist:

When set_dev_mode is called, also set for CLI

---

.circleci/config.yml
acceptance/tests/controller/controller_namespaces_test.go
acceptance/tests/partitions/partitions_test.go
control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go

This reverts commit 28a637d2f129c9c1fdbe636bb3080852cd41eab6.
- Revert commit that adds ACL write
- Acceptance tests results. (vs acceptance test results on main)

Controller acls reenabled

---

.circleci/config.yml
acceptance/tests/controller/controller_namespaces_test.go
acceptance/tests/partitions/partitions_test.go

- Update images across acceptance tests and control plane to use the 1.11.0-beta2 binary
- pipelines
- 👀 
Checklist:

use image 1.11.0-beta2

---

CHANGELOG.md
cli/cmd/install/presets.go

- Enable `gossipEncryption` generation and `autoEncrypt` in the `secure` preset. 
- Remove `server.bootstrapExpect` from demo preset since it defaults to `server.replicas` as defined in our [docs](https://www.consul.io/docs/k8s/helm#v-server-bootstrapexpect)
- Add `controller.enabled` to `true` to demo preset. 
```
❯ consul-k8s install -preset=secure
==> Pre-Install Checks
No existing installations found.
✓ No previous persistent volume claims found
✓ No previous secrets found
==> Consul Installation Summary
Installation name: consul
Namespace: consul
Overrides:
connectInject:
enabled: true
controller:
enabled: true
global:
acls:
gossipEncryption:
autoGenerate: true
name: consul
tls:
enableAutoEncrypt: true …
```

cli: improve secure preset

---

CHANGELOG.md
README.md

- Remove duplicate entry referencing enabling metrics and Prometheus integration. 
- Change link at bottom of README to go to https://learn.hashicorp.com/collections/consul/kubernetes instead of the main Consul learn guide landing page. 
Checklist:

CHANGELOG: remove duplicate entry for CLI on 0.36.0

---

CHANGELOG.md
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/servers.go

If server-acl-init is re-run, ensure that server ACL tokens have been
created for each server and call the update token API for each server
again.
This ensures that if server-acl-init fails to pass out tokens to every
server that when it is re-run it won't assume that every server has a
token.
In addition this fixes a long-standing issue where if you increase your number of servers the new servers never get ACL tokens provisioned.
Fixes #825, #677
1. Brough up cluster with 3 servers:
```yaml
global:
imageK8S: ghcr.io/lkysow/consul-k8s-dev:nov02-2
acls:
server:
replicas: 3
```
1. Then updated to 5 servers and ran helm upgrade.
1. Confirmed that there are no "Coordinate update" errors in logs of new servers. This would indicate they didn't …

Always set server acl tokens

---

CHANGELOG.md
charts/consul/templates/controller-mutatingwebhookconfiguration.yaml
control-plane/subcommand/webhook-cert-manager/command.go
control-plane/subcommand/webhook-cert-manager/command_test.go

Fixes an issue where if the webhookconfiguration is updated after the
webhook cert manager starts, then it is never reset to the correct
configuration until the manager is restarted or the certificate expires.
The issue was occurring because in the loop where we check the
webhookconfiguration we are only checking the webhookconfiguration of
the last updated certificate bundle. If there are multiple webhook
configurations then we are only watching a single one at a time since
the loop always operates on one bundle.
The fix is for each webhook to run its own loop.
In addition, the reason this was causing issues is because during a helm
upgrade we were resetting the webhookconfiguration's caBundle fields.
I've removed the caBundle setting (which already didn't exist in the
connect injector's …

Fix bug where webhookconfig would not be updated

---

acceptance/framework/helpers/helpers.go

The wait time for pods to be ready was accidentally reduced to 3m here (https://github.com/hashicorp/consul-k8s/pull/629/files#diff-4e31c92ae1107b6f5baeb3ac84a55265254d58211a97d2ac12860edcd4414766R40) when the frequency was increased to 1s.
In one of my recent tests AKS took 3m to pull the image which then failed the test.

Increase wait time to 10m

---

CHANGELOG.md
control-plane/helper/cert/tls_util.go
control-plane/subcommand/tls-init/command_test.go

For server ca cert
Fixes https://github.com/hashicorp/consul-k8s/issues/575
Checklist:

Support PKCS1 and PKCS8 private keys

---

CHANGELOG.md
charts/consul/templates/_helpers.tpl
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/partition-init-job.yaml
charts/consul/templates/sync-catalog-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/partition-init-job.bats
charts/consul/test/unit/sync-catalog-deployment.bats

Some names are reserved by Consul and can't be used for namespaces or
partitions. Catching this early before the helm install is a better UX
than having the install fail (in the case of partitions) or succeed (in
the case of namespaces) and then fail during syncing or injection.
This code uses some tricks:
1. The code for failing on reserved names is extracted into a helper template so it can be re-used in other templates
2. The test code uses a helper function so there's less duplication in the tests
Fixes https://github.com/hashicorp/consul-k8s/issues/593
Checklist:

Prevent using reserved names for ns's/partitions

---

charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/server-statefulset.bats

- https://github.com/hashicorp/consul-k8s/issues/798#issuecomment-947907238
- Run the server-statefulset.bats unit tests

Truncate the statefulset pvc name to be max 63 chars

---

CHANGELOG.md
charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/server-config-configmap.bats
charts/consul/test/unit/server-statefulset.bats

Previously ui metrics would be enabled when
`global.metrics.enabled=false` and `ui.metrics.enabled=-`. Now that
would cause UI metrics to be disabled which makes sense since "-" means
inherit from `global.metrics.enabled`.
The logic is now to enable ui metrics when:
```
ui.enabled &&
(
(global.metrics.enabled == true && ui.metrics.enabled == "-") ||
(ui.metrics.enabled == true)
)
```
Fixes https://github.com/hashicorp/consul-k8s/issues/642
Checklist:

Fix logic for enabling ui metrics

---

CHANGELOG.md
control-plane/subcommand/connect-init/command.go

If consul login fails when the service account name is `default` then
give an explicit warning that the reason it failed is because in
default installations that is not a support service account name.
We can't fail during injection because we support modifying the binding
rule such that `default` _is_ a valid svc account name.
Fixes https://github.com/hashicorp/consul-k8s/issues/574
* built container and looked at logs
Checklist:

Give better error when using default service acct

---

CONTRIBUTING.md

- Change `consul-k8s` to `consul-k8s-control-plane` in contributing 101
- Remove `make dist` as make target is no longer available
- Add example of running dev Helm chart with images built from dev via `values.dev.yaml`
- Add section for building and running the `consul-k8s` CLI
- Reformat Tests section in TOC
Checklist:

CONTRIBUTING: change to consul-k8s-control-plane in Contributing 101 and formatting

---

CHANGELOG.md
acceptance/framework/config/config.go
acceptance/framework/config/config_test.go
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/client-snapshot-agent-deployment.yaml
charts/consul/templates/enterprise-license-job.yaml
charts/consul/templates/enterprise-license-podsecuritypolicy.yaml
charts/consul/templates/enterprise-license-role.yaml
charts/consul/templates/enterprise-license-rolebinding.yaml
charts/consul/templates/enterprise-license-serviceaccount.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/client-snapshot-agent-deployment.bats
charts/consul/test/unit/enterprise-license-job.bats
charts/consul/test/unit/enterprise-license-podsecuritypolicy.bats
charts/consul/test/unit/enterprise-license-role.bats
charts/consul/test/unit/enterprise-license-rolebinding.bats
charts/consul/test/unit/enterprise-license-serviceaccount.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/server-statefulset.bats
charts/consul/values.yaml

- Migrate the `enterpriseLicense` config from being under the `server` stanza to the `global` stanza.
- This change breaks backwards compatibility but prints an error stating the same. This will not cause existing installations to fail.
- bats
- code review
- would love to hear thoughts on the breaking nature of the change.
Checklist:

Migrate server.enterpriseLicense to global.enterpriseLicense

---

CHANGELOG.md
charts/consul/templates/create-federation-secret-job.yaml

- Check to see whether autoGenerate is set to true and use default secret name and secret key to export out gossipEncryptionKey for consul federation secret. Previously the generated gossip encryption key was not exported when setting `autoGenerate` to true. 
```
global:
name: consul
image: hashicorp/consul:1.10.3
tls: 
enabled: true
acls: 
createReplicationToken: true
federation: 
enabled: true
createFederationSecret: true
gossipEncryption:
autoGenerate: true
server:
replicas: 1
ui:
enabled: true
service:
enabled: true
connectInject:
enabled: true
controller:
enabled: true
meshGateway:
enabled: true
```
Export out consul-federation secret
```
kubectl get secret consul-federation -o yaml > …
```

Create federation secret with default `consul-gossip-encryption-key` secret when global.gossipEncryption.autoGenerate is set to true

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
control-plane/catalog/to-k8s/sink_test.go

- Update consul version
-
Checklist:

Update consul version to 1.10.4

---

acceptance/tests/fixtures/bases/admin-partitions/kustomization.yaml
acceptance/tests/fixtures/bases/admin-partitions/partitionexports-default.yaml
acceptance/tests/fixtures/bases/admin-partitions/partitionexports-secondary.yaml
acceptance/tests/fixtures/cases/crd-partitions/default-partition-default/kustomization.yaml
acceptance/tests/fixtures/cases/crd-partitions/default-partition-default/patch.yaml
acceptance/tests/fixtures/cases/crd-partitions/default-partition-ns1/kustomization.yaml
acceptance/tests/fixtures/cases/crd-partitions/default-partition-ns1/patch.yaml
acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-default/kustomization.yaml
acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-default/patch.yaml
acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-ns1/kustomization.yaml
acceptance/tests/fixtures/cases/crd-partitions/secondary-partition-ns1/patch.yaml
acceptance/tests/partitions/partitions_test.go

- Move the "in-partition" acceptance tests and "x-partition" acceptance tests into a single test to enable faster test times.
- running it in CI 🤞 
- The above has been tested and the test runtime has decreased from ~42 mins to ~28 mins.
- If the acceptance tests go 🟢  and the total time for running them is under 43 minutes for the partitions test, hit the like, comment, subscribe and merge button!!

Flatten partitions tests into a single test

---

CHANGELOG.md
charts/consul/templates/client-config-configmap.yaml
charts/consul/templates/create-federation-secret-job.yaml
charts/consul/test/unit/client-daemonset.bats

- re-enable streaming since these issues were fixed in Consul 1.10.3 (https://github.com/hashicorp/consul/issues/11086, https://github.com/hashicorp/consul/issues/10796)
- fix `Error: parse error at (consul/templates/create-federation-secret-job.yaml:129): unclosed action` error with Helm <3.5.3
- code
Checklist:

Re-enable streaming for clients

---

acceptance/tests/mesh-gateway/mesh_gateway_test.go

- Currently the tests against kind 1.22 break like [this](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/3430/workflows/4f84205b-bc1d-4348-9de1-50bff582bc67/jobs/28222/steps). We don't know the underlying issue yet, but this seems to work around this temporarily from testing this locally.
locally with kind 1.22 clusters
👀 
Checklist:

acceptance-tests: add a workaround to mesh gateway tests against kind 1.22

---

acceptance/framework/helpers/helpers.go
acceptance/tests/fixtures/bases/intention/intention.yaml
acceptance/tests/fixtures/bases/intention/kustomization.yaml
acceptance/tests/vault/vault_test.go
charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/server-config-configmap.bats
charts/consul/values.yaml

- Adds helm values to configure vault connect ca provider
- Uses k8s auth method to configure connect CA provider in consul (hashicorp/consul#11573)
- This PR does not work if vault is configured with TLS (this change will come as a separate PR)
👀 
Checklist:

Add configuration for the vault Connect CA provider

---

charts/consul/test/unit/ui-ingress.bats

- Add `cd chart_dir` to the ui-ingress tests that were missing it so they can be run cleanly from the root.
-
run bats test
code review
Checklist:

add cd chart_dir so tests can be run from root level

---

CHANGELOG.md

- Move Go 1.17 release note to correct place. 
Checklist:

CHANGELOG: Move go 1.17 bump to UNRELEASED

---

CHANGELOG.md
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/connect-init/command_test.go

Fixes #862
A consul client may reach out to a follower instead of a leader to resolve the token during the
call to get services. This is because clients talk to servers in the stale consistency mode
to decrease the load on the servers (see https://www.consul.io/docs/architecture/consensus#stale).
In that case, it's possible that the token isn't replicated
to that server instance yet. The client will then get an "ACL not found" error
and subsequently cache this not found response. Then our call
to get services from the agent will keep hitting the same "ACL not found" error
until the cache entry expires (determined by the `acl_token_ttl` which defaults to 30 seconds).
This is not great because it will delay app start up time by 30 seconds in most cases
(if you are running 3 servers, then …

Add a workaround to check that the ACL token is replicated to other Consul servers

---

CHANGELOG.md
control-plane/connect-inject/annotations.go
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go
control-plane/subcommand/connect-init/command.go

> Fixes #592 
- If a service has the label `consul.hashicorp.com/service-ignore: "true"`, it will not be registered by the endpoints controller. If is has been registered before, it will be deregistered.
- If the user does not have the correct number of services registered, they will get a log instructing them to add the "connect ignore" label to services which should not be routed.
- Some comments have been added where it took me time to understand what processes were doing.
- `mapAddresses` function created as a refactor. I spun off reading this "subprocess" in the `Reconcile` method and got sidetracked. I think it makes sense to abstract over it. Feel free to disagree.
- Unit tests.
- Manual test (detailed below).
How I expect …

Ignore services in endpoint controller using `consul.hashicorp.com/service-ignore`

---

CHANGELOG.md
charts/consul/templates/partition-init-job.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/partition-init-job.bats

How I've tested this PR: Compared code to using `useSystemRoots` across the project. Unit tests.
Checklist:

Do not mount consul-ca-cert to partition init if externalServers.useSystemRoots is true

---

Makefile

- Adds a makefile target to run bats tests in parallel. This shaves off about 5 minutes from a full run of the bats tests.
- This is the same command we run in CI.
`make bats-tests` passes.
Checklist:

add a makefile target for parallel bats

---

acceptance/tests/vault/vault_test.go
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats

- Add Vault TLS support for ingress and terminating gateways.
bats and acceptance tests added
review tests
Checklist:

add terminating and ingress gateways

---

charts/consul/templates/client-snapshot-agent-deployment.yaml
charts/consul/test/unit/client-snapshot-agent-deployment.bats
charts/consul/test/unit/sync-catalog-deployment.bats

- Support TLS with Vault for the client snapshot agent deployment
- Depends on #890 
manually
code review
Checklist:

Support TLS with Vault for the client snapshot agent deployment

---

CHANGELOG.md
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats

- Fail if Admin Partitions and WAN federation are both enabled as they are mutually exclusive.
- Fixup changelog.
- BATS
- 👀 
Checklist:

Fail if partitions enabled with federation

---

acceptance/tests/vault/vault_test.go
charts/consul/templates/client-snapshot-agent-deployment.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/sync-catalog-deployment.yaml
charts/consul/test/unit/client-snapshot-agent-deployment.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/sync-catalog-deployment.bats

- Support TLS with vault for the server-acl-init job
- depends on #881 
code review
Checklist:

Support TLS with vault for the server-acl-init job

---

CHANGELOG.md
control-plane/subcommand/consul-sidecar/command.go
control-plane/subcommand/consul-sidecar/command_test.go

Fixes some issues with metrics merging. Namely that if there were any errors getting metrics from Envoy then we'd return a 200 with empty metrics instead of a 500 _and_ that if the service returned an error, e.g. 400, we'd just stick the body of its response in our metrics output which would break Prometheus.
* If Envoy returns an error then also respond with a 500 in our merged
metrics response so that Prometheus will know that we had an error, not
that there are no metrics.
* If the service metrics return with a non-2xx status code then don't
include the response body in the merged metrics. This will stop issues
where users accidentally turn on metrics merging but they don't have an
exporter and so their metrics endpoint returns 404. I could have
responded with a 500 in this case in …

Change error handling when scraping metrics

---

cli/cmd/install/install.go
cli/cmd/install/install_test.go

In a case where users might have a Consul enterprise image that may not
contain the string "-ent" in the name, we don't want to fail the
installation. This is a fairly common case, so we've removed the check.
unit tests
👀 
Checklist:

cli: allow enterprise images to be named without the string "-ent"

---

CHANGELOG.md
charts/consul/templates/ui-ingress.yaml
charts/consul/test/unit/ui-ingress.bats
charts/consul/values.yaml

Work based on existing PR: https://github.com/hashicorp/consul-k8s/pull/780
Closes #897
- Add support for ingressClassName
- Test ingress UI with different Kube versions
Bats!
Bats!
Checklist:

Add ingressClassName for UI

---

control-plane/build-support/docker/Release.ubi.dockerfile

Update to the latest ubi-minimal base image
- Update to UBI Base image to ubi-minimal:8.5 from ubi-minimal:8.4 
Checklist:

Release.ubi.dockerfile: update to ubi-minimal:8.5

---

CHANGELOG.md
cli/cmd/install/install.go
cli/cmd/install/presets.go
cli/cmd/upgrade/upgrade.go
cli/cmd/upgrade/upgrade_test.go
cli/commands.go
cli/config/presets.go

This is a wrap-up of Saad's excellent work on the Upgrade command. There will need to be some refactors following this, but functionality is solid.
- Made an initial try at the consul-k8s upgrade command. Running into issues with the connect-injector webhook not starting on an install?
- Upgrade commit
- First pass at upgrade was successful.
- notes from sync with Saad on what's left
- Made an initial try at the consul-k8s upgrade command. Running into issues with the connect-injector webhook not starting on an install?
- Upgrade commit
- First pass at upgrade was successful.
- notes from sync with Saad on what's left
- Some basic cleanup
- Remove TestDebugger
- Remove validateLabels (unused)
- Add the namespace and install flags
- Add flag test and remove …

CLI Upgrade Command (fixed PR)

---

CHANGELOG.md
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go

Support the annotation
```
consul.hashicorp.com/service-tags: $POD_NAME
```
Where $POD_NAME will be replaced with the Pod's name.
This mimics support we had before the endpoints controller
where environment variable were interpolated for tags.
This PR only supports $POD_NAME for now because it's the only
environment variable we've been asked to support.
How I've tested this PR: unit tests
How I expect reviewers to test this PR: code
Checklist:

Support annotation service-tags: $POD_NAME

---

CONTRIBUTING.md
README.md

- Renamed consul-k8s to consul-k8s-control-plane where necessary
- Added link back to charts/consul in README.md
Checklist:

CONTRIBUTING: small typo for consul-k8s-control-plane binary

---

CHANGELOG.md
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/values.yaml

- duplicate of https://github.com/hashicorp/consul-k8s/pull/938 made by @Lord-Y, with some small updates to tests before merging
Checklist:

Pr/938: [charts/consul] - Enable terminationGracePeriodSeconds customization on ingressGateway

---

.circleci/config.yml
README.md
charts/consul/test/terraform/aks/main.tf
charts/consul/test/terraform/eks/main.tf
charts/consul/test/terraform/gke/main.tf

- Kubernetes 1.23 is now released so we need to bump our tested versions
[Ran tests](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/3860/workflows/6e5921c5-3d9f-44ed-89f3-a2d65c438657)
👀 
Checklist:

Bump k8s versions

---

charts/consul/templates/server-disruptionbudget.yaml
charts/consul/test/unit/server-disruptionbudget.bats

New version of consul helm chart is using apiVersion of "policy/v1" and deprecated "v1beata1" causing errors similar to below issues with cortex and argocd. Used the workaround mentioned to use Kind with apiVersion and that works.
https://github.com/cortexproject/cortex-helm-chart/pull/277
https://github.com/argoproj/argo-cd/issues/7291
Tested locally against the new version of consul 1.10.4 with helm chart 0.37.0 and had issues with PBD not syncing up in argocd and complaining about apiversion.
Create a release version and test it.
Checklist:

adding Kind to ApiVersion

---

.circleci/config.yml
acceptance/tests/partitions/partitions_test.go
charts/consul/test/terraform/eks/main.tf
charts/consul/test/terraform/eks/variables.tf

- Run partitions tests on EKS
- For cross partition communication, the networking setup needs to be such that the node ips of all clients need to be able to talk with the node ips of all servers and vice versa (traffic should be routeable and allowed). Clients across partitions do not need to be able to route to each other.
- To make this work on EKS, the terraform has been modified to:
- Set up a 2 clusters in 2 VPCs without overlapping IPs
- Set up peering between those VPCs
- Add security group ingress rules to each set of nodes' security group, to allow all TCP traffic from the other VPC
- Add route table entries such that traffic going to the other VPC is routed through the peer
- A few tweaks to partitions acceptance tests so that they pass
- Outside of …

Setup and run partitions tests on EKS

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/values.yaml

- Bump chart.yaml and values.yaml to point to Envoy 1.20.1
- Depends on merging of Core PR: https://github.com/hashicorp/consul/pull/11895 
Checklist:

chart: bump to envoy 1.20.1

---

CHANGELOG.md

typo in changelog link to PR
- Change link name to GH-958 instead of GH-935 (copy and pasta)
Checklist:

CHANGELOG: typo

---

.circleci/config.yml
acceptance/tests/partitions/partitions_test.go
charts/consul/templates/server-podsecuritypolicy.yaml
charts/consul/test/terraform/gke/main.tf
charts/consul/test/terraform/gke/variables.tf
charts/consul/test/unit/server-podsecuritypolicy.bats

- Update GKE terraform templates for partitions tests
- we create firewall rules that allow nodes and pods from each cluster to reach the nodes of the other.
- Update server podsercuritypolicy to allow hostports on specific ports if `server.exportGossipAndRPCPorts` is set to `true`
- ran tests: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/3926/workflows/1aeed2ff-40b4-4a7a-99cb-f84f751048a0
👀 
Checklist:

Add partitions test to GKE

---

cli/go.mod
cli/go.sum

Fixes #974 
- When building the CLI binary with go 1.17.5 or later (it worked with 1.17.2, but I haven't tested versions in-between), there's a segfault. Based on https://github.com/golang/go/issues/49992, updating `golang.org/x/sys` module fixes it.
built cli locally 
👀 
Checklist:

cli: fix panic with go 1.17.5 or greater

---

CHANGELOG.md
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/server-statefulset.bats
charts/consul/values.yaml

This value is used to set Consul's `ui_config.dashboard_url_templates`
config. I'm pulling it out as its own value rather than getting users
to just use `server.extraConfig` because these template strings always
use the characters `{{` and when used within `server.extraConfig`,
users need to escape those characters.
Before:
```yaml
server:
extraConfig: |
{
"ui_config": {
"dashboard_url_templates": {
"service": "http://grafana/service/{{ "{{" }}Service.Name}}"
}
}
}
```
Now:
```yaml
ui:
dashboardURLTemplates:
service: "http://grafana/service/{{Service.Name}}"
```
- tests and manual deployment
- code
Checklist:

Add new value ui.dashboardURLTemplates

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
control-plane/connect-inject/annotations.go
control-plane/connect-inject/consul_sidecar.go
control-plane/connect-inject/consul_sidecar_test.go
control-plane/connect-inject/handler.go
control-plane/subcommand/inject-connect/command.go
control-plane/subcommand/inject-connect/command_test.go

Hi
We are currently migrating our metrics polling to use merged metrics and we have one issue.
Some of our pods return lots of metrics (~150k) and the consul sidecar get OOM killed.
We bump the memory of the sidecar but dont want to waste memory where we dont need it.
- default resources are set via flags of the injector
- can be overriden with annotations on pods
I renamed the injector flags to mirror the envoy sidecar configuration.
The code is heavily inspired by envoy sidecar configuration but i kept the `consulSidecarResources` object in the subcommand.
If you want that i replicate the envoy stuff and split the resources into 4 vars when passing the settings to the handler, i can do it.
I am open to any ideas / modifications :)
- …

control-plane: Add possibility to manage consul sidecar resources with annotations

---

Makefile
charts/consul/Makefile
control-plane/Makefile

* Move make targets from control-plane Makefile to top-level Makefile
* leave targets that are needed for CI
* remove charts/consul/Makefile because its test-docker target was never
used
* add help text to all Makefile targets. You can see the help by running
`make` or `make help`
* Add `control-plane-` prefix to control plane targets
* Modify targets that download Go tools to use `go install` instead of
`go get` because using go get to download tools is deprecated
* modify the `ctrl-gen` target to also copy the generated CRDs to the chart
* ran each make target
* code

Move make targets to top-level

---

CHANGELOG.md
charts/consul/templates/crd-exportedservices.yaml
charts/consul/templates/crd-ingressgateways.yaml
charts/consul/templates/crd-proxydefaults.yaml
charts/consul/templates/crd-servicedefaults.yaml
charts/consul/templates/crd-serviceintentions.yaml
charts/consul/templates/crd-serviceresolvers.yaml
charts/consul/templates/crd-servicerouters.yaml
charts/consul/templates/crd-servicesplitters.yaml
charts/consul/templates/crd-terminatinggateways.yaml
control-plane/api/v1alpha1/exportedservices_types.go
control-plane/api/v1alpha1/ingressgateway_types.go
control-plane/api/v1alpha1/proxydefaults_types.go
control-plane/api/v1alpha1/servicedefaults_types.go
control-plane/api/v1alpha1/serviceintentions_types.go
control-plane/api/v1alpha1/serviceresolver_types.go
control-plane/api/v1alpha1/servicerouter_types.go
control-plane/api/v1alpha1/servicesplitter_types.go
control-plane/api/v1alpha1/terminatinggateway_types.go
control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml
control-plane/config/crd/bases/consul.hashicorp.com_proxydefaults.yaml
control-plane/config/crd/bases/consul.hashicorp.com_servicedefaults.yaml
control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
control-plane/config/crd/bases/consul.hashicorp.com_serviceresolvers.yaml
control-plane/config/crd/bases/consul.hashicorp.com_servicerouters.yaml
control-plane/config/crd/bases/consul.hashicorp.com_servicesplitters.yaml
control-plane/config/crd/bases/consul.hashicorp.com_terminatinggateways.yaml

For example allow both kubectl get ingressgateways and
kubectl get ingress-gateways.
When specified in .hcl or .json the config entries are dash-separated so
this makes it consistent if someone uses a dash by mistake after reading
our docs.
- edited a crd in my cluster to match and tested out the aliasname
- make sure I didn't typo or use the wrong name for a config entry
- also review if this is a good idea
Checklist:

Add - separated names for config entry crds

---

CHANGELOG.md
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go

- Support the annotation `consul.hashicorp.com/service-meta-pod_name: $POD_NAME` where $POD_NAME will be replaced with the Pod's name. This mimics the support we had before the endpoints controller where environment variables were interpolated for tags.
- This PR only supports $POD_NAME for now because it's the only environment variable we've been asked to support.
- Unit tests.
- Code Review
Checklist:

Support the value `$POD_NAME` for the annotation

---

.circleci/config.yml
CHANGELOG.md
acceptance/tests/vault/vault_test.go
charts/consul/templates/server-acl-init-podsecuritypolicy.yaml
charts/consul/test/terraform/gke/main.tf

- Update server-acl-init PSP to have access to mount emptyDir volumes for the vault injector
- Scale up gke cluster so accommodate for everything we're installing in the vault test
acceptance tests: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/4015/workflows/87c78757-4c96-4641-a2f0-d535bbe567fc/jobs/36509
👀 
Checklist:

Make sure vault integration works with PSPs

---

CHANGELOG.md

Changelog for #956

---

CHANGELOG.md
control-plane/catalog/to-consul/resource.go
control-plane/catalog/to-consul/resource_test.go

Commas can be set by escaping with backslash. Fixes https://github.com/hashicorp/consul-k8s/issues/719
Example:
annotation: "this,supports,commas\,now"
Becomes:
["this", "supports", "commas,now"]
* unit tests
* code
Checklist:

Support commas in tag annotation.

---

.circleci/config.yml
CHANGELOG.md
control-plane/connect-inject/endpoints_controller_ent_test.go
control-plane/connect-inject/endpoints_controller_test.go
control-plane/go.mod
control-plane/go.sum
control-plane/namespaces/namespaces_test.go
control-plane/subcommand/connect-init/command_ent_test.go
control-plane/subcommand/connect-init/command_test.go
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/create_or_update_test.go

- Ensure the anonymous token in the default partition is updated to support cross-partition DNS resolution even if the server-acl-init is running in a non-default partition. This ensures DNS lookups work even if the default partition is on VMs and hence does not have the requisite policy required to do the same.
- Update SDK to the latest version that update which updates ACL.Tokens.Master to ACL.Tokens.InitialManagement
- Acceptance tests don't break
- Tested on HCP with help from the cloud team.
- 👀 
Checklist:

Create anonymous-policy and token from non-default partitions.

---

charts/consul/values.yaml

-allow resources to show up in helm docs, but don't recurse further
Checklist:

Tweak sidecar resources comment to render in consul-helm docs

---

.circleci/config.yml
CHANGELOG.md
charts/consul/templates/connect-inject-authmethod-clusterrole.yaml
charts/consul/templates/connect-inject-authmethod-clusterrolebinding.yaml
charts/consul/templates/connect-inject-authmethod-serviceaccount.yaml
charts/consul/templates/connect-inject-clusterrole.yaml
charts/consul/templates/connect-inject-clusterrolebinding.yaml
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/connect-inject-leader-election-rolebinding.yaml
charts/consul/templates/connect-inject-mutatingwebhookconfiguration.yaml
charts/consul/templates/connect-inject-podsecuritypolicy.yaml
charts/consul/templates/connect-inject-service.yaml
charts/consul/templates/connect-inject-serviceaccount.yaml
charts/consul/templates/controller-mutatingwebhookconfiguration.yaml
charts/consul/templates/enterprise-license-job.yaml
charts/consul/templates/partition-init-role.yaml
charts/consul/templates/partition-service.yaml
charts/consul/templates/server-acl-init-role.yaml
charts/consul/templates/ui-ingress.yaml
charts/consul/templates/webhook-cert-manager-clusterrole.yaml
charts/consul/templates/webhook-cert-manager-configmap.yaml
charts/consul/test/unit/webhook-cert-manager-configmap.bats
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/connect_inject.go
control-plane/subcommand/server-acl-init/connect_inject_test.go

- Rename helm resources that have redundant resource-name suffixes.
- Update `server-acl-init` as the secret name was hard-coded to use the `-svc-aaccount` suffix.
- Pipelines.
- 👀 
Checklist:

Standardize resource names across the helm chart

---

CHANGELOG.md
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go

Fixes #779 
Based on work done in #795 
When Consul client is unavailable, it could slow down events processing in the endpoints controller because we always make *some* calls to consul (because `deregisterServiceOnAllAgents` is called on every `Reconcile`). When we can't reach a Consul client agent, it can take quite long (20-30sec) to process a single event because of the i/o timeout. This could cause your service mesh applications to be stuck in the init phase for longer than you'd expect.
This PR addresses the two cases when making those calls are unnecessary: 
1. When we are processing a service not on the mesh, i.e. when endpoints pods are not injected, we can skip any further processing of that endpoints object.
2. When we are deregistering services on …

connect: Avoid making unnecessary calls to Consul in the endpoints controller

---

CONTRIBUTING.md

- Fix the instructions for using the makefile now that the directives are in the root
- Change some wording to be more declarative
- Remove `$` from snippets so that the copy button gives the user something they can paste into their shell

Fix Makefile Contrib Instructions

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-deployment.yaml
charts/consul/test/unit/api-gateway-controller-deployment.bats

Previously it was using the pod IP of the controller and then when
gateways were created they were hardcoded to use that pod IP.
This was an issue because if the controller pod dies then there will be
a new pod IP and the gateway will lose its connection to the SDS
service. Instead, this PR changes it to use the kube dns url.
- bats
- manually deployed gateway following https://learn.hashicorp.com/tutorials/consul/kubernetes-api-gateway and looked at sds url
- code
Checklist:

Use kube svc dns for api gateway sds

---

cli/cmd/install/install.go
cli/cmd/install/install_test.go
cli/cmd/status/status.go
cli/cmd/upgrade/upgrade.go
cli/cmd/version/version.go

- Make the flags and outputs for commands more action-oriented and consistent
- Add a sweet little dividing line for overrides and the upgrade diff.
Running the commands to view the output and make sure they are clear.
Think about the commands from the perspective of a newcomer to Consul on Kubernetes. Are they clear, actionable, and consistent?
<details><summary>Expand screenshots</summary>
</details>

Clarify flags and output for CLI

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml

The k8s client abstraction in consul-api-gateway [expects](https://github.com/hashicorp/consul-api-gateway/blob/c82e707fb30bebf1a88980568e0f67e318f65496/internal/k8s/gatewayclient/gatewayclient.go#L67-L68) to be able to create **or update** k8s `Deployments` and `Services`; however, the `ClusterRole` as defined today does not allow for updates to these resources. This prevents the Consul API Gateway controller from successfully installing a new gateway to the cluster.
- Modify `ClusterRole` to allow controller to update k8s `Deployment`
- Modify `ClusterRole` to allow controller to update k8s `Service`
Applied changes to deployment on GKE
Follow the [Learn …

Allow API Gateway controller to update k8s Deployments + Services

---

CHANGELOG.md
charts/consul/templates/crd-ingressgateways.yaml
control-plane/api/v1alpha1/ingressgateway_types.go
control-plane/config/crd/bases/consul.hashicorp.com_ingressgateways.yaml

gatewayTLSConfig => tls
gatewayTLSSDSConfig => sds
- `s/old/new/g`
- code
Checklist:

Fix incorrect CRD field names

---

CHANGELOG.md
charts/consul/templates/_helpers.tpl
charts/consul/test/unit/server-statefulset.bats

- Add support customized IPSans and DNSSans for server-tls server cert for vault
manual verification in a consul/vault/k8s environment
Checklist:

Add support customized IPSans and DNSSans for server-tls server cert for vault

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

- Aligning labels with Consul Core labels on Issue Template 
Checklist:

ISSUE_TEMPLATE: update labels per new GH labeling recommendations

---

acceptance/framework/config/config.go
acceptance/framework/config/config_test.go
acceptance/tests/vault/vault_wan_fed_test.go
charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/server-config-configmap.bats
charts/consul/values.yaml

- Add `global.federation.primaryDatacenter` and `global.federation.primaryGateway` to allow users to specify these values directly rather than via `server.extraConfig` or `server.extraVolumes`
Note that we will keep the existing behavior of `create-federation-secret` that generates the serverExtraConfig with those values for the time being and will re-assess it when the ACL work to switch out tokens for auth methods will be complete as it will likely affect it. So at the moment we will allow using both methods, and if the user provides these values via any of the `server.extra*` values, they will take precedence.
vault acceptance tests
👀 
Checklist:
> HashiCorp engineers only, community PRs …

Allow configuring primary DC and gateways via designated Helm values

---

CHANGELOG.md

- Formatting details for Consul K8s Vault WAN Fed work. 
Checklist:

CHANGELOG: formatting consul k8s wanted vault

---

charts/consul/Chart.yaml
charts/consul/values.yaml

- update to latest consul release and update charts
-
Checklist:

update chart for release 0.41.0

---

.github/workflows/issue-context-bot.yml

- This PR adds an Issue Context Bot which will comment on issues which are transferred to this repository with a prompt to add additional K8s-specific context.
Unfortunately, I can't really test this unless it is in the main branch. However, it relies on standard GitHub Action triggers.
The main feedback I would like is _if_ this is a good addition and any changes to the comment copy that would make it clearer to the user what they are being asked to do.
Checklist:

Create an Issue Context Bot

---

charts/consul/Chart.yaml
charts/consul/templates/ui-ingress.yaml
charts/consul/test/unit/ui-ingress.bats

- bump kubeVersionAPI to 1.19 to reflect what we see in README
- default to using ingressClassName value
- remove bats tests for 1.19 on UI Ingress and remove --kube-version flags since tests run on 1.19+ by default
Checklist:

chart: bump k8s requirement to 1.19

---

CHANGELOG.md

- Follow up changelog PR to https://github.com/hashicorp/consul-k8s/pull/1049 
Checklist:

CHANGELOG: bump to k8s 1.19+

---

CHANGELOG.md
control-plane/build-support/docker/Release.dockerfile

- Bump `consul-k8s-control-plane` alpine base image to 3.15
Checklist:

Dockerfile: bump to alpine 3.15

---

charts/consul/values.yaml

- Escape `<ip>:<port>` in global.federation.primaryGateways comment due to JSX issues on Helm reference docs. Without this our Helm reference docs break on due to React thinking it is a valid JSX tag.
- Tested on Vercel with Github PR: https://github.com/hashicorp/consul/pull/12465
Checklist:

helm docs: Escape <ip>:<port> due to JSX issues on Helm reference docs

---

.circleci/config.yml
charts/consul/templates/connect-inject-clusterrole.yaml
charts/consul/templates/connect-inject-clusterrolebinding.yaml
charts/consul/templates/connect-inject-serviceaccount.yaml
charts/consul/templates/controller-deployment.yaml
charts/consul/templates/server-acl-init-role.yaml
charts/consul/test/unit/connect-inject-clusterrole.bats
charts/consul/test/unit/connect-inject-clusterrolebinding.bats
charts/consul/test/unit/connect-inject-serviceaccount.bats
charts/consul/test/unit/controller-deployment.bats
control-plane/commands.go
control-plane/helper/test/test_util.go
control-plane/subcommand/acl-init/command.go
control-plane/subcommand/acl-init/command_test.go
control-plane/subcommand/common/common.go
control-plane/subcommand/common/common_test.go
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/consul-logout/command.go
control-plane/subcommand/consul-logout/command_test.go
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/connect_inject.go
control-plane/subcommand/server-acl-init/connect_inject_test.go
control-plane/subcommand/server-acl-init/create_or_update.go

- Adds a new auth method called `release-name-consul-k8s-component-auth-method` which will be used for components to issue `ACL().Login()` at startup. 
- Modify the `acl-init` init container to issue an `ACL().Login()` to fetch the component's ACL token on startup and store it locally, using the aforementioned new authMethod.
- Modifies `server-acl-init` job to create the new auth method and also no longer provision Kube secrets for the controller.
- Modifies the `server-acl-init` unit tests to support cases where we do not have a 1:1 mapping of policies:kube tokens. 
- Adds a new subcommand `consul-logout` which is used as a `preStop` hook for component pods to destroy the ACL token that was created through `acl-init`.
- move the logic of `Login()` that …

Use kube auth method to provision ACL token for the crd controller

---

acceptance/framework/consul/consul_cluster.go
acceptance/framework/k8s/helpers.go

- Increase the timeout for pods to be in a ready state from 10 minutes to 11 minutes in acceptance tests
We've increased this wait time before, but I think it makes sense to increase it again after seeing this
test failure: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/4505/workflows/fe2c423d-47b5-493e-b3b2-9707655f77f6/jobs/43239/tests 
I haven't I'm hoping this reduces some flakiness I've observed in the nightly tests.
We'll see if this helps with the flakiness. 
Checklist:

Increase wait for all pods to be ready from 10 to 11 minutes

---

CONTRIBUTING.md
control-plane/build-support/functions/20-build.sh

- Update docs to require `gox` as a pre-requisite install so you can run `make control-plane-dev` and `make-control-plane-dev-docker`
- Update local build scripts to not exclude darwin/arm64, which was set 4 years ago, when it was probably not supported by gox at that time, but works now.
- update `helm` pre-requisited to denote pinned version of 3.6.3, otherwise helm changes its output in bats test to be non-cpaitalized and they fail.
- `make control-plane-dev` and `make-control-plane-docker` failed for me on my darwin/arm64 laptop.
- implemented changes and they worked
- 
👀

updating make control-plane-dev to work ondarwin/arm64.  Update helm version for bats tests

---

Makefile

-  Update Makefile for `control-plane-dev-docker` so that it sets DOCKER_DEFAULT_PLATFORM=linux/amd64.  This sets the proper architecture in the docker manifest. Without this if you build adocker image on an arm64 machine, it will set the docker manifest to arm64.  This then causes errors in kubernetes running the image.
- completely blocked from publishing images that i could use in acceptance tests running locally
- implemented this
- unblocked
👀

Set DOCKER_DEFAULT_PLATFORM for make control-plane-dev-docker so that images built on M1/arm64machines do not have failures in k8s.

---

.circleci/config.yml
acceptance/framework/vault/vault_cluster.go
acceptance/tests/vault/helpers.go
acceptance/tests/vault/vault_test.go
acceptance/tests/vault/vault_wan_fed_test.go
charts/consul/templates/_helpers.tpl
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/server-statefulset.bats
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/servers.go

Support providing a bootstrap token secret that is stored in Vault. Previously in our code, we assumed that the bootstrap token secret would only need to be provided when running with external servers (i.e. consul servers running outside of *this* Kubernetes cluster). This is no longer the case. 
To accomodate for the case when servers are running externally, there's now a new flag `-set-server-tokens` for the server-acl-init command. When servers are running in this cluster, we will set this flag to true so that we set server tokens. When servers are running externally, we don't want to set server tokens because we don't manage those servers.
To configure the bootstrap token for the server, we provide it via config (`initial_manangement` token: …

Support storing bootstrap token in Vault

---

.circleci/config.yml
acceptance/go.mod
acceptance/tests/mesh-gateway/mesh_gateway_test.go
charts/consul/templates/controller-clusterrole.yaml
charts/consul/templates/controller-deployment.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/test/unit/controller-clusterrole.bats
charts/consul/test/unit/controller-deployment.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/values.yaml
control-plane/helper/test/test_util.go
control-plane/subcommand/acl-init/command.go
control-plane/subcommand/common/common.go
control-plane/subcommand/common/common_test.go
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/connect_inject.go
control-plane/subcommand/server-acl-init/create_or_update.go

- Update server-acl-init to create authmethods in the primary datacenter when the job is run in a secondary datacenter during federation. This authmethod allows us to issue logins for global policies.
- Update the controller workflow in server-acl-init to use this global authmethod when run in a secondary DC.
- Update the mesh-gateway acceptance tests to create proxy defaults in the secondary DC to test above behavior works successfully.
- Updated logout to not pass in the partition flag as it is not required.
- Update server acl init tests to migrate from `require := require.New(t)` to `require.xyz(t, ...)` patterns.
- Unit tests
- Code Review
Checklist:
> HashiCorp engineers …

Global auth method

---

charts/consul/templates/connect-inject-clusterrole.yaml
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/controller-deployment.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/test/unit/connect-inject-clusterrole.bats
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/server-acl-init-job.bats
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go

- Refactor connect-injector to use the new auth-method workflow when ACLs are enabled so that Kubernetes secrets are not used.
- Unit tests.
- Acceptance tests.
- Code Review
Checklist:

Connect inject acl refactor

---

charts/consul/templates/server-acl-init-job.yaml
charts/consul/test/unit/server-acl-init-job.bats
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go

- renames -create-controller-token flag to -enable-controller for server-acl-init.
- This PR replaces PR #1072 because the rebase got really disgusting.
unit tests pass
👀 
Checklist:

Rename controller flag in server-acl-init to `-controller`

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml

Allow the Consul API Gateway controller to `get`, `list` and `watch` namespaces. This enables the controller to validate `HTTPRoutes` before attaching them to a `Gateway` that uses a namespace selector for `allowedRoutes`.
In this example, the `Gateway` only allows routes from a K8s `Namespace` with labels matching `amAllowed: sure`:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
name: example-gateway
namespace: consul
spec:
gatewayClassName: consul-api-gateway
listeners:
- allowedRoutes:
namespaces:
from: Selector
selector:
matchLabels:
amAllowed: sure
name: http
port: 80
protocol: HTTP
```
Before the controller attaches a route to this gateway, it needs to retrieve the namespace and see if the label selector matches, thus …

Allow API Gateway controller to get Namespaces

---

control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go

- wrap failing tests in retries
- these three tests work locally but fail intermittently but often in CI
- 👀

Fix flakey server-acl-init tests with retries

---

.github/workflows/build-and-test.yml

- Updating GitHub Actions config to use Consul v1.11.4
- Currently getting GH Action failures in unit tests for vault work that is related to a bug that is fixed in Consul 1.11.4.  The bug shows this error
```
agent.http: Request error: method=PUT url=/v1/acl/auth-method?dc=dc1 from=127.0.0.1:41136 error="Invalid Auth Method: TokenLocality 'global' can only be used in the primary datacenter"
```
- Also, we currently updated this version in CircleCI in the last week or so (after the GH migration work started).
👀

Updating GitHub Actions config to use Consul v1.11.4

---

charts/consul/templates/client-daemonset.yaml
charts/consul/test/unit/client-daemonset.bats

Give error for folks setting `imageK8s` instead of `imageK8S` (an easy mistake)
* unit tests
* unit tests
Checklist:

Give error if imageK8s is used

---

.circleci/config.yml

- I broke this change when I changed the build-and-test pipelines
- Change the acceptance tests to use SHA instead of :latest
- I ran the acceptance tests. The change has been tests in another PR also..
👀 
Checklist:

Use SHA instead of latest for acceptance tests

---

charts/consul/templates/_helpers.tpl
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/partition-init-job.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/tls-init-job.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/partition-init-job.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/server-statefulset.bats
charts/consul/test/unit/tls-init-job.bats
control-plane/subcommand/acl-init/command.go
control-plane/subcommand/acl-init/command_test.go
control-plane/subcommand/common/common.go
control-plane/subcommand/common/common_test.go
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/partition-init/command.go
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/create_or_update.go

*This PR is best viewed Commit by Commit to see the description/purpose and what got added.*
- `control-plane/subcommand/acl-init/command.go` 
- when using ACLs, retrieve the token secret from consul login rather than k8s secrets
- when external servers are configured, use them for the cases of partition set up
-  `control-plane/subcommand/common/common.go` 
- modify `ConsulLogin()` to also return the token (consul core code does this as well), in addition to storing it in the `tokenSinkFile`, so that it can be used in ACL init to write out the 
- modify `ConsulLogin()`to write the `tokenSinkFile` with 0644 permissions that was original used before ACLs refactor, in part to support [this bug fix] (https://github.com/hashicorp/consul-k8s/pull/248/files#diff-29d4 …

Enable ACL Client Token

---

acceptance/tests/vault/helpers.go
acceptance/tests/vault/vault_partitions_test.go
acceptance/tests/vault/vault_test.go
acceptance/tests/vault/vault_wan_fed_test.go
charts/consul/templates/_helpers.tpl
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/partition-init-job.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/helpers.bats
charts/consul/test/unit/partition-init-job.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/values.yaml
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/create_or_update.go

Support admin partitions with Vault:
- Add an ability to create partition token when provided from a secret in Vault
- Pass necessary vault annotations to the partition init job when TLS is enabled
- some acceptance test refactors
👀 
Checklist:

vault: add support for admin partitions

---

CHANGELOG.md
charts/consul/templates/client-podsecuritypolicy.yaml
charts/consul/templates/mesh-gateway-podsecuritypolicy.yaml
charts/consul/test/unit/client-podsecuritypolicy.bats
charts/consul/test/unit/mesh-gateway-podsecuritypolicy.bats

- fixes https://github.com/hashicorp/consul-k8s/issues/1037
- when `hostNetwork` is true, kube sets all containerPorts as hostPorts. We then need to allow those ports in our PSP.
- bats only
- bats
Checklist:

Support hostNetwork with pod security policies

---

control-plane/subcommand/acl-init/command.go
control-plane/subcommand/common/common.go
control-plane/subcommand/common/common_test.go
control-plane/subcommand/connect-init/command.go

- convert function args to a struct
- add some missing tests
- move logic that is only relevant for connect out
unit tests
👀 
Checklist:

Refactor logic in common.Login

---

acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
acceptance/tests/terminating-gateway/terminating_gateway_test.go
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/templates/terminating-gateways-podsecuritypolicy.yaml
charts/consul/templates/terminating-gateways-role.yaml
charts/consul/templates/terminating-gateways-rolebinding.yaml
charts/consul/templates/terminating-gateways-serviceaccount.yaml
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/test/unit/terminating-gateways-podsecuritypolicy.bats
charts/consul/test/unit/terminating-gateways-role.bats
charts/consul/test/unit/terminating-gateways-rolebinding.bats
charts/consul/test/unit/terminating-gateways-serviceaccount.bats
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go

- change terminating gateway deployment to pass `acl-auth-method` so it can properly call Consul login.
- add prestop for logout to terminating gateway container.
- refactor logic from `server-acl-init` command for terminating gateway so that it can also be used for upcoming ingress gateway work.
- unit tests
👀 
Checklist:

Enable terminating gateways to use ACL Auth Method

---

CONTRIBUTING.md

Found this while using these instructions, removing this step since `make ctrl-manifests` copies the crds into the chart directory

Update crd doc

---

CHANGELOG.md
charts/consul/templates/_helpers.tpl
charts/consul/test/unit/server-statefulset.bats

- When using vault secrets backend, don't set TTL for server certs explicitly so that they don't expire too early. This should be controlled via the [PKI role](https://www.vaultproject.io/api-docs/secret/pki#ttl-1) rather than hard-coded in the template so that the users can control the TTL that is suitable for them.
unit tests
👀 
Checklist:

Don't set TTL for server certs when using Vault

---

CHANGELOG.md
charts/consul/templates/_helpers.tpl
charts/consul/templates/client-snapshot-agent-deployment.yaml
charts/consul/test/unit/client-snapshot-agent-deployment.bats
charts/consul/values.yaml
control-plane/subcommand/common/common.go

- `charts/consul/values.yaml` - Add `global.secretsBackend.vault.consulSnapshotAgentRole` helm value so users can preconfigure the auth role in Vault with this service account and have snapshot agent retrieve the snapshot agent config secret from vault using this service account.
- `charts/consul/templates/client-snapshot-agent-deployment.yaml`
- configure snapshot agent with vault role annotation for new `global.secretsBackend.vault.consulSnapshotAgentRole` helm value
- set up vault annotations so injector downloads snapshot agent config to`/vault/secrets/snapshot-agent-config.txt`
- configure command for `consul-snapshot-agent` container to:
- base64 decode the contents of `/vault/secrets/snapshot-agent-config.txt` into …

Enable snapshot agent configuration to be retrieved from vault

---

.github/workflows/build-and-test.yml
.golangci.yml
charts/consul/templates/partition-init-podsecuritypolicy.yaml

When running with Vault, partition-init job needs its
PodSecurityPolicy to allow access to emptyDir so that
it can attach secret volumes.
ran acceptance tests on GKE with PSPs enabled
👀 
Checklist:

fix partition-init job when Vault and PSPs are enabled

---

CHANGELOG.md
cli/helm/chart.go

Previously would error about missing file `consul\Chart.yaml`. This
is because the go embedded filesystem must be accessed using `/`
delimiters but we were using `filepath` functions which on windows
use `\`.
- tested on windows
- code
Checklist:

Fix cli to work on windows

---

.github/workflows/build.yml
.github/workflows/test.yml
Makefile
control-plane/Dockerfile
control-plane/Makefile

- Added a multi-target Dockerfile for building all of our images
- Updated makefile to create control-plane dev image with Dockerfile
- Split build-and-test.yml into build.yml and test.yml to support CRT (CRT expects a build.yml file)
- build.yml
- Build all of the architectures that we support for both cli and control-plane
- Builld docker images for control-plane (and test that they work)
- Build the rpms and debs for the cli
- CI pipleines
- The images are tested to see if control-plane displays the correct version
- Validated that the cli works
👀 
Checklist:

[CRT] Build docker images, rpms and debs

---

charts/consul/templates/api-gateway-controller-clusterrole.yaml

This is a prerequisite for https://github.com/hashicorp/consul-api-gateway/pull/142 being included in a release.
Allow the Consul API Gateway controller to `get`, `list` and `watch` `ReferencePolicy` from the k8s Gateway API. This will allow the controller to verify that a route is allowed to send traffic to a service in a different namespace.
In this example, the `ReferencePolicy` allows any `HTTPRoute` in the gateway-conformance-infra namespace to attach to the web-backend service in the gateway-conformance-web-backend namespace. Without this policy, cross-namespace routing will be blocked at some point in the future.
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferencePolicy
metadata:
name: reference-policy
namespace: …
```

Allow Consul API Gateway controller to read ReferencePolicy

---

CHANGELOG.md
cli/cmd/install/install.go
cli/validation/kubernetes.go
cli/validation/kubernetes_test.go

- The install command will only look for secrets in the namespace the install is targeting.
This fixes the issue raised by @lkysow.
> another one, it's complaining I have a secret in my default ns but I'm installing consul into the consul ns:
> ``` bash
> consul-k8s install
> ==> Checking if Consul can be installed
> ✓ No existing Consul installations found.
> ✓ No existing Consul persistent volume claims found
> ! Found Consul secrets, possibly from a previous installation.
> Delete existing Consul secrets from Kubernetes:
> 
> kubectl delete secret consul-federation --namespace default
> ``` 
Extended existing unit tests to cover this case.
:eyes: and running unit tests.
Checklist:
> HashiCorp …

Only lookup secrets in the namespace where the install is targeting.

---

CHANGELOG.md
control-plane/connect-inject/annotations.go
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go

So, I was helping someone go through the process of setting up an Elasticsearch instance on the service mesh so it could be routed to via the API Gateway. All of the pods and services are created via a CRD specified by [this project](https://github.com/elastic/cloud-on-k8s).
One of the pain points of this is that the CRD + controller create a single deployment that has multiple services targeting it. You can override parts of the pod spec template in the CRD and some of the service templates, but not all of them. This makes things difficult because our only way of properly specifying which service we want to use in Consul registration when a pod is using `connect-inject` and has multiple services targeting it is through the service label …

Add annotation for explicitly specifying which service you want registered

---

CHANGELOG.md
cli/cmd/install/install.go
cli/cmd/install/install_test.go
cli/helm/values.go
cli/release/release.go
cli/release/release_test.go

- When installing a federated cluster, the install command will look in all of the places the name of the federation secret could be set and return the first set value it finds.
Added unit tests, ran the install tests which exercise the presence of the fed secret.
Running the unit tests as well if you like.
Checklist:

Get federation secret from any of the places it is set.

---

.release/ci.hcl
.release/security-scan.hcl

- This PR needs to be merged before I can start testing the orchestrator
- Note: This will not break anything as it is the orchestrator that needs these files
- Turning on builds, slack notifications, signing/notarizing, security scanning of artifacts we create 
- Will test post merge and probably make changes
👀 
Checklist:

[CRT] Enable Orchestrator

---

CHANGELOG.md

- Move changelog for merged PR from 0.42.0 to UNRELEASED: https://github.com/hashicorp/consul-k8s/pull/1150
Checklist:

CHANGELOG: move changelog entry for GH-1150 to unreleased

---

.release/ci.hcl
.release/security-scan.hcl

- Disable security scans for now so that I can test CRT
- CRT only runs on merges so testing with a branch is not possible
👀 
Checklist:

[CRT] Disable security scans (for now)

---

CHANGELOG.md
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go

- fixes https://github.com/hashicorp/consul-k8s/issues/1143
- reverts some of https://github.com/hashicorp/consul-k8s/pull/991
- what was happening was that if any endpoint was a non-mesh pod we would short circuit and not look at the rest of the pods
- in addition, when you're removing the mesh annotation, if we saw a pod that wasn't injected we would short circuit and not try to delete any service instances
- unit tests
- built an image and tested
- code
Checklist:

Fix bug when upgrading from non-mesh to mesh

---

control-plane/connect-inject/annotations.go
control-plane/connect-inject/handler.go
control-plane/connect-inject/handler_test.go

- Add annotation to mount connect inject volume to other containers
Discussion in https://github.com/hashicorp/consul-k8s/issues/761
Fixes https://github.com/hashicorp/consul-k8s/issues/761
How I've tested this PR: Unit tests and manual tests
How I expect reviewers to test this PR: Manually add annotation to pods and see if volume gets mounted.
Checklist:

Add annotation to mount connect inject volume to other containers

---

CHANGELOG.md
charts/consul/templates/_helpers.tpl
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/partition-init-job.bats
charts/consul/test/unit/sync-catalog-deployment.bats

With upcoming consul-enterprise this ns will be valid.
- unit tests
- code
Checklist:

Allow the consul namespace to be a destination.

---

CHANGELOG.md
charts/consul/templates/create-federation-secret-job.yaml
charts/consul/test/unit/create-federation-secret-job.bats

The job requires access to a consul client so it must respect the placement
requirements for the consul client pods.
Fixes https://github.com/hashicorp/consul-k8s/issues/1108
- unit tests
- code
Checklist:

Respect client placement reqs for fed secret job

---

.github/workflows/build.yml
.release/ci.hcl

- Disable the CRT orchestrator from running against main
- Set it up so that I have a testing branch to work with when we are ready to test.
- 🐦  🐦  🗿 
- Nothing to test
👀 
Checklist:

Stop orchestrator from messaging on pushes to main

---

CHANGELOG.md

- Move GH-1111 from 0.42.0 to UNRELEASED
Checklist:

CHANGELOG: move GH-1111 to UNRELEASED

---

.circleci/config.yml
acceptance/framework/consul/helm_cluster.go
control-plane/Makefile

- Add checks to verify deletion of resources in Destroy method on Helm Cluster
I set up this PR run nightly-acceptance-tests.
Watch the nightly-acceptance-tests and see if they succeed.
Checklist:

Improve Nightly Test Debugging and Reliability with Docker Uploads

---

hack/aws-acceptance-test-cleanup/main.go

- Currently if you run terraform apply with cluster count of 2, and then run our cleanup script, it will fail because VPCs can't get deleted since they have a dependency on peering connections
- This allows you to run the cleanup script successfully, by deleting peering conns
- Ran script after terraforming 2 eks clusters, and saw it succeed.
👀

Cleanup EKS VPC peering connections

---

acceptance/framework/consul/cli_cluster.go
acceptance/framework/consul/cluster.go
acceptance/framework/consul/helm_cluster.go
acceptance/framework/vault/helpers.go
acceptance/tests/basic/basic_test.go
acceptance/tests/connect/connect_helper.go
acceptance/tests/connect/connect_inject_namespaces_test.go
acceptance/tests/connect/connect_inject_test.go
acceptance/tests/controller/controller_namespaces_test.go
acceptance/tests/controller/controller_test.go
acceptance/tests/example/example_test.go
acceptance/tests/ingress-gateway/ingress_gateway_namespaces_test.go
acceptance/tests/ingress-gateway/ingress_gateway_test.go
acceptance/tests/mesh-gateway/mesh_gateway_test.go
acceptance/tests/partitions/partitions_test.go
acceptance/tests/snapshot-agent/snapshot_agent_vault_test.go
acceptance/tests/sync/sync_catalog_namespaces_test.go
acceptance/tests/sync/sync_catalog_test.go
acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
acceptance/tests/terminating-gateway/terminating_gateway_test.go
acceptance/tests/vault/vault_partitions_test.go
acceptance/tests/vault/vault_test.go
acceptance/tests/vault/vault_tls_auto_reload_test.go
acceptance/tests/vault/vault_wan_fed_test.go
charts/consul/templates/client-config-configmap.yaml
charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/client-config-configmap.bats
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-config-configmap.bats
charts/consul/test/unit/server-statefulset.bats

*NOTE:  This looks like more files at first glance but there are many files that changed because of a signature change to `SetupConsulClient`*
- Added TestVault_TlsAutoReload to verify that certificates get rotated
- had to change signature of `SetupConsulClient` to also return the portward address
- Acceptance test added
- 👀 
Checklist:

Adding Acceptance test for Auto Reload Config

---

.circleci/config.yml
acceptance/framework/vault/helpers.go
acceptance/framework/vault/vault_cluster.go
acceptance/tests/snapshot-agent/snapshot_agent_vault_test.go
acceptance/tests/vault/vault_namespaces_test.go
acceptance/tests/vault/vault_partitions_test.go
acceptance/tests/vault/vault_tls_auto_reload_test.go
acceptance/tests/vault/vault_wan_fed_test.go

- an acceptance test that sets up vault using namespaces and confirms that the pods come up and an app deployed on the cluster works
- a signature change to `vaultCluster.Create()` to allow passing in a namespace
- running the test
👀 
Checklist:

Adding acceptance test for Vault Namespaces

---

cli/go.mod
cli/go.sum
control-plane/go.mod
control-plane/go.sum

Bump `golang.org/x/crypto` and `golang.org/x/text` dependencies to address CVE-2022-27291 and CVE-2021-38561 respectively.
There's no known exposure of this issues within the consul-k8s context, but adopting updates for hygiene sake & to reduce vulnerability scanner noise.
Proposed changes are the result of running `go get -u golang.org/x/crypto`, `go get -u golang.org/x/text`, and `go mod tidy` in both of the `consul-k8s/control-plane` and `consul-k8s/cli` directories.
- Reviewed results of CI-driven tests.
- Review results of CI-driven tests.
Checklist:

bump golang.org/x/crypto & golang.org/x/text deps to address CVEs

---

.circleci/config.yml

- I believe that nightly acceptance tests are failing because we need to build the binary first
- I am taking a shot at this as it is difficult to test
:eyes:
👀  & 🙏 
Checklist:

build the distro so that nightly-dev-docker runs

---

CHANGELOG.md
acceptance/tests/partitions/partitions_connect_test.go
acceptance/tests/partitions/partitions_sync_test.go
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/sync-catalog-deployment.yaml
charts/consul/test/unit/sync-catalog-deployment.bats
control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go

- Update rules.go to support partitions when Sync catalog is used.
- Add an acceptance test to validate sync catalog works when partitions are enabled in the default and non-default partitions.
- Units tests.
- Acceptance tests.
- Code Review.
Checklist:

Add support for ACLs for sync catalog and partitions.

---

.circleci/config.yml

- The scheduled jobs in circle ci cannot have context
- This removes this so that a new container will be built for nightly acceptance jobs
- Need to wait for the scheduled job to run
👁️ 👁️ 
Checklist:

Scheduled jobs in CircleCI cannot have context

---

CHANGELOG.md

- Changelog for CVE fix. Added a separate section as this covers both CLI and Control Plane. 
Checklist:

CHANGELOG: add entry for dependency bump that removes CVEs from binaries

---

acceptance/tests/partitions/partitions_sync_test.go

- Remove use of controller from TestPartitions_Sync
- running acceptance test locally
- 
👀 
Checklist:

Resolving flakey behavior in TestPartitions_Sync with Controller by removing Controller because it is not needed for the test.

---

charts/consul/test/terraform/eks/main.tf

- Add 20m timeout for VPC on EKS in Nightly acceptance job terraform
👀 
👀 
Checklist:

Adding timeout to EKS terraform for VPC due to it timing out at 20 minutes in nightly run

---

CHANGELOG.md

- CHANGELOG entry for breaking change
-
👀 
👀 & ✍️ 
Checklist:

Updating CHANGELOG to include breaking change in 0.43 with the reliance on consul 1.12 due to -auto-reload-config

---

.circleci/config.yml
charts/consul/test/terraform/eks/main.tf

Background:
- I added this timeouts section last night when we had a nightly EKS job fail when trying to destroy and it timeout on destroying the VPC.
- It turns out that this module does not expose timeouts
- Also the [aws_vpc resource does not either](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L20) compared to [others that do](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/41da6881e295ff5e94bbf97b41018e7c550c7285/main.tf#L148).
-  Removing timeouts as it is not a valid option
- re-run tf apply locally
👀 
Checklist:
> Entries should use present tense (e.g. Add support …

Remove timeouts from EKS vpc tf module definition

---

CHANGELOG.md
charts/consul/templates/client-config-configmap.yaml
charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/client-config-configmap.bats
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-config-configmap.bats
charts/consul/test/unit/server-statefulset.bats

- Enable auto_reload_config only when Vault is enabled.
- Bats tests
- 👀 
Checklist:

Enable auto_reload_config only when Vault is enabled.

---

control-plane/Makefile

- adding the `nightly-`prefix to the tag that gets pushed.  CI currently fails with the below. It should try to push image `hashicorpdev/consul-k8s-control-plane:nightly-875319b2`
```
The push refers to a repository [docker.io/hashicorpdev/consul-k8s-control-plane]
tag does not exist: hashicorpdev/consul-k8s-control-plane:875319b2
make: *** [Makefile:57: ci.nightly-dev-docker] Error 1
```
👀 
👀 
Checklist:

Fixing make ci.nightly-dev-docker to push the correct tag

---

control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/servers.go

- give httpclient that calls bootstrap ACLs a 5 minute timeout since this is one area where we have to wait and we can't retry.
- our nightly acceptance tests have gone from basically green to close to a dozen failures per cloud provider.
- CI runs of acceptance tests
👀 
Checklist:

Exempt ACL Bootstrap logic from`global.consulAPITimeout` by giving it a 5 timeout

---

cli/common/flag/flag_int.go

This is intended to fix alerts flagged by CodeQL: https://github.com/hashicorp/consul-k8s/security/code-scanning
Whereby we are using `strconv.ParseInt` with 64bits length and then casting it to a 32bit value without error checking.
- Updates `flags_int.go`'s use of `parse_Int` and `parse_Uint` to specify 32bit length for `strconv.ParseUint/Int` so that it will return error on overflow instead of actually overflow.
When `ParseInt` overflows it will return :
`value out of range`
Example:
```
func main() {
a := "100000000000000000000000000000000000000"
v, err := strconv.ParseInt(a, 0, 32)
fmt.Println("%v", err)
}
```
Results in : `strconv.ParseInt: parsing "100000000000000000000000000000000000000": value out of range`
👀
Should I add a …

update the flags library to prevent overflows

---

.circleci/config.yml
control-plane/Makefile
control-plane/connect-inject/endpoints_controller_test.go

Recently we've seen cases when a nightly dev image is not uploaded due to a CI failure.
To fix this, we're going to run the `dev-upload-docker` job again before the nightly acceptance tests run
This commit also removes the `nightly-dev-upload-docker` job and its corresponding makefile target as we don't need a separate tag for these images and can re-use the same ones.
Enabled nightly pipeline (w/o the cleanup jobs) on this commit: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/5857/workflows/c8e6a9d0-1ba5-47d4-9238-eab66b890368
👀 
Checklist:

Fix nightly dev docker upload

---

acceptance/framework/vault/helpers.go
acceptance/framework/vault/vault_cluster.go
acceptance/go.mod
acceptance/go.sum
acceptance/tests/connect/connect_helper.go
acceptance/tests/connect/connect_inject_namespaces_test.go
acceptance/tests/connect/connect_inject_test.go
acceptance/tests/ingress-gateway/ingress_gateway_namespaces_test.go
acceptance/tests/ingress-gateway/ingress_gateway_test.go
acceptance/tests/mesh-gateway/mesh_gateway_test.go
acceptance/tests/metrics/metrics_test.go
acceptance/tests/partitions/partitions_connect_test.go
acceptance/tests/snapshot-agent/snapshot_agent_vault_test.go
acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
acceptance/tests/terminating-gateway/terminating_gateway_test.go
acceptance/tests/vault/vault_namespaces_test.go
acceptance/tests/vault/vault_partitions_test.go
acceptance/tests/vault/vault_test.go
acceptance/tests/vault/vault_tls_auto_reload_test.go
acceptance/tests/vault/vault_wan_fed_test.go

Over time, the Vault acceptance test have organically grown where multiple helper functions would encapsulate what should be shared knowledge.  For example, all of the tests have helm chart configurations that look like this:
```
"global.secretsBackend.vault.connectCA.rootPKIPath":         "connect_root",
"global.secretsBackend.vault.connectCA.intermediatePKIPath": "dc1/connect_inter",
"global.acls.bootstrapToken.secretName": "consul/data/secret/bootstrap",
"global.acls.bootstrapToken.secretKey":  "token",
"global.gossipEncryption.secretName":    "consul/data/secret/gossip",
"global.gossipEncryption.secretKey":     "gossip",
"global.tls.caCert.secretName": "pki/cert/ca",
```
For each of these, it can be confusing to know where and how this get set previously to arriving here.  It is also …

Refactor Vault tests to allow more flexibility in mounting PKI and also be more representative of the integration experience of the user

---

charts/consul/templates/client-snapshot-agent-deployment.yaml
charts/consul/test/unit/client-snapshot-agent-deployment.bats
charts/consul/values.yaml

- enable possibility to set custom interval for snapshot agent
- default set to `1h` as stated in the docs https://www.consul.io/commands/snapshot/agent#interval
unit tests
the same way as I did ;)
Checklist:

Allow customization of snapshot agent interval

---

charts/consul/templates/crd-exportedservices.yaml
control-plane/api/v1alpha1/exportedservices_types.go
control-plane/api/v1alpha1/exportedservices_types_test.go
control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
control-plane/go.mod
control-plane/go.sum

- add peerName to ExportedServices CRD
- add validations to ensure both peername and partition cannot be specified but at least one of them needs to be specified.
- unit tests
- deploying locally on kubernetes
- 👀 
Checklist:

Add peerName to ExportedServices.

---

CHANGELOG.md
control-plane/build-support/docker/Release.ubi.dockerfile

- ubi-minimal:8.6 is now out and should be used for RedHat UBI Images
Checklist:

Dockerfile: Bump UBI minimal image to ubi-minimal:8.6

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-deployment.yaml
charts/consul/test/unit/api-gateway-controller-deployment.bats

- Adds vault agent annotations to `api-gateway-controller-deployment`
- This resolves #1246 
bats tests
👀 
Checklist:

add vault agent annotations to apigw

---

control-plane/catalog/to-consul/resource.go
control-plane/catalog/to-consul/resource_test.go

- Add more metadata when creating a service in Consul. It adds the name of the node name (on kubernetes) and the references of the entries in the endpoints of the kubernetes service.
- manually
Checklist:

Add more metadata about the target if possible

---

acceptance/framework/config/config.go
acceptance/framework/flags/flags.go
acceptance/tests/vault/vault_namespaces_test.go
acceptance/tests/vault/vault_partitions_test.go
acceptance/tests/vault/vault_test.go
acceptance/tests/vault/vault_tls_auto_reload_test.go
acceptance/tests/vault/vault_wan_fed_test.go

- Adds a new flag "-consul-version" to the acceptance test framework that will be used to prevent tests from running against incompatible consul releases.
- Forces Vault acceptance tests to be skipped if consul-1.12+ is not used.
- In the follow-on PR which uses this feature, the acceptance tests will be enhanced to have 2 new jobs which each target specific consul versions and will pass this flag to indicate that.
* Manually validated the version comparison code.
* Manually tested that the Vault tests pass (are skipped) when consul-1.11.6 is used and "1.11.6" is passed in as a flag.
👀 
Checklist:
> Entries should use …

Add consul-version flag to acceptance test framework

---

.github/workflows/test.yml
control-plane/api/v1alpha1/exportedservices_types.go
control-plane/api/v1alpha1/exportedservices_webhook_test.go
control-plane/connect-inject/peering_acceptor_controller.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller.go
control-plane/connect-inject/peering_dialer_controller_test.go
control-plane/controller/configentry_controller.go
control-plane/go.mod
control-plane/go.sum

- Update api module and corresponding function signature changes for peering API endpoints
- Update exported services CRD validation: it is no longer an ENT-only CRD, so the validation behavior now accounts for each of those cases, and won't reject the CR in OSS.
- Only when namespaces are enabled, you can specify the namespace of an exported service
- Enforces that the name of the CR is "default" in OSS or in the default partition, or equal to the partition name if partitions are enabled.
- unit tests
- 👀 
Checklist:
- [-] CHANGELOG entry added 

Update api module and exported services validation

---

charts/consul/values.yaml

- there were some invalid URLs in the values.yaml that referenced consul.io pages that were incorrect.
- These links get auto-gen'd to consul.io docs for the k8s helm chart so they need to be correct
👓 
Manually clicked the links :)
👀 
Checklist:

update agent config urls in values.yaml

---

CHANGELOG.md
charts/consul/templates/api-gateway-gatewayclassconfig.yaml
charts/consul/test/unit/api-gateway-gatewayclassconfig.bats
charts/consul/values.yaml

> **Note**: This will need to be included in a tagged release before consul-api-gateway v0.3.0 becomes available
- Allow chart consumers to configure Consul API Gateway's new High Availability values on the `GatewayClassConfig`
- **Please note that this functionality will not be available until the release of Consul API Gateway `0.3.0` in the near future.**
For example:
```yaml
deployment:
defaultInstances: 3
maxInstances: 8
minInstances: 1
```
`helm install` with various combinations of deployment config
- Without updating gateway CRDs (`$ kubectl apply --kustomize "github.com/hashicorp/consul-api-gateway/config/crd?ref=v0.2.1"`)
- No `deployment` at all without updating gateway CRDs
- This matches the situation users will be in after consuming the release with this code change but …

Expose new options for API Gateway's High Availability feature

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/crd-exportedservices.yaml
charts/consul/templates/crd-peeringacceptors.yaml
charts/consul/templates/crd-peeringdialers.yaml
charts/consul/templates/crd-serviceintentions.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/values.yaml
control-plane/api/v1alpha1/exportedservices_types.go
control-plane/api/v1alpha1/serviceintentions_types.go
control-plane/config/crd/bases/consul.hashicorp.com_exportedservices.yaml
control-plane/config/crd/bases/consul.hashicorp.com_serviceintentions.yaml
control-plane/subcommand/inject-connect/command.go

- when global.peering.enabled is true, and connectInject.enabled is true, enable the peering controllers and the peering CRDs. 
unit tests
👀 
Checklist:

Add helm value to enable cluster peering

---

CHANGELOG.md

- Update the changelog to note breaking change of Envoy version changes in 0.44.0 and reference docs.
- This should merge along-side https://github.com/hashicorp/consul/pull/13432
- Resolves https://github.com/hashicorp/consul-k8s/issues/1262
Checklist:

update changelog to note breaking change for Envoy images.

---

acceptance/framework/k8s/debug.go

- Add Services to debug output on acceptance test failure to help us see any helpful diagnostic information
👀 
👀

Add Services to debug output on acceptance test failure

---

CHANGELOG.md

Changelog peering

---

Makefile
control-plane/Dockerfile
control-plane/Makefile

When using kind on an arm64 architecture locally
and installing consul-k8s with tproxy,
the service-mesh init container will fail to apply iptables rules.
This is because kind is running on an arm64 architecture but uses
amd64 docker image for consul-k8s. If we switch to arm64 images instead,
the error goes away.
built a dev image and deployed to kind running arm64. Then tried to deploy a service with tproxy enabled and saw that iptables are applied correctly
👀 
Checklist:

Allow building arm64 dev docker images

---

CHANGELOG.md

This reverts commit 136d3126e01658a032efe6c7d7accd037920cc21.
-
-
Checklist:

Revert "Add changelog for cluster peering (#1279)"

---

acceptance/framework/consul/helm_cluster.go

- Updating retry from 10 to 60 seconds for cloud clean up because of AKS failure.
If this does not solve things, we might even consider just doing like 5, 10, or 15 minutes since we are just trying to clean up and if its not ready, having a low number is not helpful when your signal gets corrupted with noise.
👀 
👀 
Checklist:

Updating retry from 10 to 60 seconds for cloud clean up because of AKS failure.

---

CHANGELOG.md

Changelog for peering

---

control-plane/connect-inject/annotations.go
control-plane/connect-inject/peering_acceptor_controller.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller.go
control-plane/connect-inject/peering_dialer_controller_test.go

- Add watches to both the Peering Acceptor and Dialer controller. These watch secrets with a specific label and reconcile the associated acceptor/dialer when the secret that matches their status/spec secret is updated. Additionally, when the acceptor creates the token secret, it now adds that label to the created secret.
- Unit tests.
- Created a peering acceptor and dialer in different clusters. After the secret was created and copied over, deleted the contents of the secret in the secret on the acceptor side. This generated a new token. Copied this secret over again and observed the reconcile happen on the dialer end as well.
- 👀 
- attempt to perform the above as well.
Checklist:
> HashiCorp …

Add secret watchers on Peering Acceptor/Dialer Controllers

---

.circleci/config.yml
acceptance/framework/helpers/helpers.go
acceptance/framework/k8s/helpers.go
acceptance/tests/fixtures/bases/peering/peering-acceptor.yaml
acceptance/tests/fixtures/bases/peering/peering-dialer.yaml
acceptance/tests/fixtures/cases/crd-peers/default-namespace/kustomization.yaml
acceptance/tests/fixtures/cases/crd-peers/default-namespace/patch.yaml
acceptance/tests/fixtures/cases/crd-peers/default/kustomization.yaml
acceptance/tests/fixtures/cases/crd-peers/default/patch.yaml
acceptance/tests/fixtures/cases/crd-peers/non-default-namespace/kustomization.yaml
acceptance/tests/fixtures/cases/crd-peers/non-default-namespace/patch.yaml
acceptance/tests/fixtures/cases/static-client-peers/default-namespace/kustomization.yaml
acceptance/tests/fixtures/cases/static-client-peers/default-namespace/patch.yaml
acceptance/tests/fixtures/cases/static-client-peers/default/kustomization.yaml
acceptance/tests/fixtures/cases/static-client-peers/default/patch.yaml
acceptance/tests/fixtures/cases/static-client-peers/non-default-namespace/kustomization.yaml
acceptance/tests/fixtures/cases/static-client-peers/non-default-namespace/patch.yaml
acceptance/tests/partitions/partitions_connect_test.go
acceptance/tests/partitions/partitions_sync_test.go
acceptance/tests/peering/main_test.go
acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go
charts/consul/values.yaml

- Add acceptance tests for Cluster Peering
- Temporarily migrate nightly acceptance tests to test with t-proxy enabled as Peering does not currently support T-Proxy. The nightly tests will run with it enabled once we have support for the in Peering which is expected in the beta timeframe.
- Acceptance tests 😅 
- Code review
- 🟢 acceptance tests
Checklist:

Acceptance Tests for Cluster Peering

---

hack/helm-reference-gen/fixtures/full-values.golden
hack/helm-reference-gen/main.go
hack/helm-reference-gen/main_test.go

- Uses anchor link alias for table of contents.
- Used to generate latest helm docs, see https://github.com/hashicorp/consul/pull/13527 for additional details.
👀 
👀 
Checklist:

use anchor link alias for TOC

---

CHANGELOG.md
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats
control-plane/connect-inject/annotations.go
control-plane/connect-inject/container_init.go
control-plane/connect-inject/container_init_test.go

- Adds annotations for pointing to CA/cert/key files for Envoy to use to enable TLS on the Prometheus metrics endpoint. Corresponding Consul PR here: https://github.com/hashicorp/consul/pull/13481
- Updated a container_init test to make sure the CLI flags get passed through correctly to the Envoy bootstrap command.
- Testing this out manually with a CSI volume to make sure Envoy watches the cert paths correctly when they're updated on disk.
- The surface area of the change is pretty small; it should be covered by the updated unit test.
Checklist:

Add annotations for enabling TLS on Envoy Prometheus endpoint

---

charts/consul/values.yaml

- fixes a broken link to k8s api docs for resource requirements
-
clicked the link
👀 
Checklist:

fix a broken link in values.yaml

---

CHANGELOG.md
control-plane/connect-inject/annotations.go
control-plane/connect-inject/envoy_sidecar.go
control-plane/connect-inject/envoy_sidecar_test.go
control-plane/connect-inject/mesh_webhook.go
control-plane/connect-inject/mesh_webhook_ent_test.go
control-plane/connect-inject/mesh_webhook_test.go

- Adds 2 new annotations `consul.hashicorp.com/consul-sidecar-user-volume` `consul.hashicorp.com/consul-sidecar-user-volume-mount` that accept JSON objects that define Volumes and VolumeMounts which will be attached to the envoy sidecar.
- This will allow the user to pass in an arbitrary mount that can be used to for example mount the TLS certs/keys via a Kube secret, CSI volume, etc, for prometheus scraping.
- This should work in the same manner that istio's `sidecar.istio.io/userVolumeMount` and `sidecar.istio.io/userVolume`
annotations work.
* unit tests
* built a test image under `kyleschochenmaier/consul-k8s-prom-tls` and deployed consul-k8s with a demo application that used the annotation …

Add annotations to support specifying userVolumes and userVolumeMounts for the envoy sidecar

---

.circleci/config.yml
acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go

- Nightly tests run the enterprise tests and so need a consul-ent image.
- adds support for consul-1.13 nightlies
- disables peering tests for < consul-1.13
- disable nightlies until the images are available
manually using the included images.
👀 
Checklist:

use ent images for nightlies and add consul-1.13 nightlies

---

charts/consul/values.yaml

Related to issues found in https://github.com/hashicorp/consul-k8s/issues/1309 when setting this in the primary datacenter.
- Updating values docs to only set  global.federation.primaryDatacenter outside of the primary datacenter.
N/A
👀

Updating values docs to only set  global.federation.primaryDatacenter outside of the primary datacenter.

---

charts/consul/templates/gossip-encryption-autogenerate-job.yaml
charts/consul/test/unit/gossip-encryption-autogenerate-job.bats

If running on OpenShift, these settings cause problems because the
user and group ids are below the range OpenShift expects. If not
specified, they're automatically handled by OpenShift.

don't set securitycontext on openshift/okd

---

CHANGELOG.md

- add a changelog entry for #1308 
Checklist:

update changelog for community PR 1308

---

acceptance/framework/consul/helm_cluster.go
acceptance/tests/connect/connect_external_servers_test.go
acceptance/tests/connect/connect_inject_test.go
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
control-plane/connect-inject/mesh_webhook.go
control-plane/subcommand/inject-connect/command.go

With agentless, connect-injector now needs to be able to talk to servers directly even when they live outside the cluster. Previously, connect-injector always needed to talk to clients and so this deployment did not need to worry about external servers. 
- Enable connect-injector talk to external servers. This involves providing both acl-init and inject-connect commands with external server configuration
- The `inject-connect` command has been changed to accept external server configuration similar to other commands (e.g. `server-acl-init`) that already support external servers
👀 
Checklist:
> Entries …

Enable connect-injector to talk to external servers.

---

acceptance/tests/controller/controller_test.go
acceptance/tests/controller/main_test.go
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/controller-deployment.yaml
charts/consul/test/unit/controller-deployment.bats
control-plane/subcommand/controller/command.go

- Change CRD controller to talk to servers instead of clients so that it can work with agentless
👀 
Checklist:

Enable CRD controller to talk to Consul servers

---

hack/aws-acceptance-test-cleanup/main.go

* Fix a bug with ELB deletion where we were comparing pointer values for VPC ID instead of strings
* Delete VPCs and their resources even if there's no associated EKS cluster. This so that if EKS cleanup fails in the middle and we
re-run it, it will continue deleting resources it couldn't on a previous run.
* Fix a bug with deleting security group rules where we tried to delete them if there are no rules (AWS API will return an error in that case)
ran it locally
👀 
Checklist:

Fixes for AWS acceptance tests cleanup

---

charts/consul/templates/_helpers.tpl
charts/consul/templates/connect-injector-disruptionbudget.yaml
charts/consul/test/unit/connect-injector-disruptionbudget.bats
charts/consul/values.yaml

Related to: https://github.com/hashicorp/consul-k8s/issues/1278
- Added podDisruptionBudget to the consul helm chart 
1. Via Unit-test
1. Via Unit-test
Checklist:
- [✅ ] Tests added

Adding podDistruptionBudget to consul helm chart

---

CHANGELOG.md

- update changelog for community PR #1316
Checklist:

update changelog for community PR 1316

---

charts/consul/templates/cni-clusterrole.yaml
charts/consul/templates/cni-clusterrolebinding.yaml
charts/consul/templates/cni-daemonset.yaml
charts/consul/templates/cni-podsecuritypolicy.yaml
charts/consul/templates/cni-resourcequota.yaml
charts/consul/templates/cni-serviceaccount.yaml
charts/consul/templates/connect-inject-clusterrole.yaml
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/cni-clusterrole.bats
charts/consul/test/unit/cni-clusterrolebinding.bats
charts/consul/test/unit/cni-daemonset.bats
charts/consul/test/unit/cni-podsecuritypolicy.bats
charts/consul/test/unit/cni-resourcequota.bats
charts/consul/test/unit/cni-serviceaccount.bats
charts/consul/test/unit/connect-inject-clusterrole.bats
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/values.yaml
control-plane/subcommand/install-cni/testdata/ZZZ-consul-cni-kubeconfig.golden
control-plane/subcommand/server-acl-init/command.go

This PR contains the base helm charts for installing CNI.
- A daemonset for the cni installer
- Service account for the cni plugin
- Clusterrole and clusterrolebinding for the service account
- Bats tests for all of the above.
Note: Helm changes coming in follow on PRs
- Openshift support (SCC)
- Disabling redirect-traffic in connect-inject
- bats tests
- manual installing in my kind cluster
👀
Checklist:
[x] Tests added
[ ] CHANGELOG entry added
HashiCorp engineers only, community PRs should not add a changelog entry.
Entries should use present tense (e.g. Add support for...)

CNI Helm Charts

---

acceptance/tests/mesh-gateway/main_test.go
acceptance/tests/vault/vault_wan_fed_test.go

Currently, WAN federation tests are flaky on kind. We need more time
to investigate. Because these tests run on other clouds and are not flaky,
we are disabling them on kind until we can investigate and re-enable them.
👀 
Checklist:

Disable wan federation tests on kind because of flakiness

---

cli/cmd/proxy/command.go
cli/cmd/proxy/read/command.go
cli/cmd/proxy/read/command_test.go
cli/cmd/proxy/read/config.go
cli/cmd/proxy/read/config_test.go
cli/common/flag/set.go

After clarifying with @david-yu on the best way forward for the JSON flag, we decided to have an `output` flag which takes `table`, `json`, or `raw` to set the output.
This matches with David's original intent in the PRD.
- Add GetSetFlags method which allows access to groups of flags.
- Add `-output` (`-o`) flag which takes `table`, `json`, or `raw` for configuring output.
- Set config values to empty slices by default.
- Added a unit test for the new flag.
- Unit tests or manually.
Checklist:

Set output with `-output` flag.

---

acceptance/tests/mesh-gateway/main_test.go

Actually disable mesh gateway tests on kind!

---

.circleci/config.yml
acceptance/framework/config/config.go
acceptance/framework/flags/flags.go
acceptance/tests/peering/main_test.go
charts/consul/test/terraform/aks/main.tf

* On AKS, we cannot run peering tests yet because the pod network is not flat
* Add a flag to acceptance tests framework to disable peering tests (to be removed once non-flat networks are supported)
* Update AKS version to the supported 1.21.x version (1.21.7 is no longer supported)
* Run AKS nightly acceptance tests with -disable-peering flag
ran tests in the pipeline: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/6636/workflows/b7132391-db97-41af-b2f0-a75a0ab447b7/jobs/55267
👀 
Checklist:

Skip peering tests on AKS and update AKS version

---

.circleci/config.yml
Makefile
control-plane/Dockerfile
control-plane/Makefile

- Add new makefile target to build multi-arch dev images locally 
- Update ci dev image build to build multi-arch images
Built it locally or in the pipeline ran `docker manifest inspect` on the image to see that it has both architectures
👀 
Checklist:

Build multi-arch dev-images

---

.github/workflows/build.yml

- Having UBI images on docker hub will make them easier to test because you don't need credentials to use them
Checklist:

Add a job to build and publish UBI images to dockerhub

---

control-plane/Makefile

- We also push to `latest` image tag and so we need to adjust the `ci.dev-docker` target to also build those with multi-arch
ran it in the pipeline
👀 
Checklist:

Use buildx to push latest image tag from main

---

acceptance/tests/peering/peering_connect_test.go
charts/consul/templates/connect-inject-clusterrole.yaml
control-plane/connect-inject/peering_acceptor_controller.go

- Avoid reading objects from the cache immediately after creating them as they are not guaranteed to exist. This leads to a bug caused by the race condition.
- Add update RBAC to the secrets for the connect inject controller.
- Assert that the created secret has a resource version upon creating.
- 👀 and faith
Checklist:

Read created secrets from the API object

---

acceptance/framework/consul/helm_cluster.go
hack/aws-acceptance-test-cleanup/main.go

- Add retry to resource deletion. Previously, the retry logic we added was only applied to listing resources. This PR moves it so that we retry deleting all resources too if they haven't been deleted.
- Add more time for ELB deletion to propagate. Hopefully, this will fix errors like: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/6688/workflows/b82ad9d6-c05b-4048-b93f-35554e6c3dae/jobs/55476
Checklist:

acceptance: Add retry to resource deletion and wait for more for ELB deletion to propagate

---

control-plane/Dockerfile

- Add required Red Hat labels so that it will work with our prod release process (https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.45/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction)
- Also bump ubi image to 8.6 (this is what we used to use before)
Ran `preflight` tool on a locally built image and saw it pass
👀 
Checklist:

Add required UBI labels

---

acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-config-configmap.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-config-configmap.bats

- Allow TLS to be enabled with peering tests.
- Use updated TLS config on Servers and Clients when peering is enabled.
- Acceptance tests & updates BATS tests.
The updated TLS config was work that had already been done that needed to be reverted in order to continue to support Consul 1.11.
- 👀 
Checklist:

Enable TLS on Consul Peering

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml

- Bump default Envoy version to 1.23.0 which was released on 15 July 2022.
- Relying on CI.
- This mimics previous PRs such as #1276 to update a default value in the chart.
Checklist:
Signed-off-by: Evan Culver <eculver@hashicorp.com>

Bump default Envoy version to 1.23.0

---

.circleci/config.yml
.github/workflows/test.yml
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
control-plane/connect-inject/peering_acceptor_controller.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller_test.go
control-plane/go.mod
control-plane/go.sum
control-plane/subcommand/inject-connect/command.go

- Support setting externalServers hosts in peering token for non-default partitions
- Set up 4 clusters in 2 datacenters and tested peering across non-default partitions across datacenters with this [reference config and steps](https://github.com/ndhanushkodi/cluster-peering-demo/tree/main/non-default-non-flat)
- 👀 
Checklist:

peering: support setting externalServers hosts in peering token for non-default partitions

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/values.yaml

- only requires helm changes because the logic to support non-default partitions also involves just passing in addresses to the token, so this only requires that we set the flags using the appropriate address source
Checklist:

peering: support static addresses for exposing servers

---

CHANGELOG.md

peering: changelog for expose server work

---

charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/server-config-configmap.bats

- set peering server config only when peering Helm value is true
- This is because Consul now defaults to false: https://github.com/hashicorp/consul/pull/13963
Checklist:

peering: set peering server config only when peering Helm value is true

---

cli/cmd/proxy/read/command.go
cli/cmd/proxy/read/command_test.go
cli/cmd/proxy/read/format.go
cli/cmd/proxy/read/format_test.go
cli/commands.go

📹 Demo
https://user-images.githubusercontent.com/29112081/180005754-694d5aa4-7c81-44fb-b07a-a7d63d2b4995.mov
- Get admin port for all services
- Add UI to all commands
- Output config for each service
- Separate out formatting of tables
- Add fake pod to fix command_test
- Add tests for formatting
- New unit tests, and I ran this on a multiport pod.
- Unit tests or multiport pod manual tests.
Checklist:

Envoy debugging multiport support

---

cli/cmd/proxy/read/command.go
cli/cmd/proxy/read/command_test.go
cli/cmd/proxy/read/config.go
cli/cmd/proxy/read/config_test.go
cli/cmd/proxy/read/filters.go
cli/cmd/proxy/read/filters_test.go

🎥 Demo!
https://user-images.githubusercontent.com/29112081/179610040-87e38340-4f40-49db-a069-743d2c59bfcc.mov
- Add functions for filtering by FQDN, port, and address.
- Use those functions in the output.
- Add a note to the header that shows which filters are being applied.
- Unit tests!
- If you pull and build this branch's CLI, you can pass `-fqdn`, `-port`, and/or `-address` to filter the output.
Checklist:

Add filters to debugging output.

---

cli/cmd/proxy/read/config.go
cli/cmd/proxy/read/config_test.go
cli/cmd/proxy/read/envoy_types.go
cli/cmd/proxy/read/test_clusters.json

📹 Demo
https://user-images.githubusercontent.com/29112081/180920660-81191d1c-ee12-4628-8770-d3a325ce9b15.mov
- Add a second request in the `EnvoyConfig.FetchConfig` function to get cluster status configuration
- Add mappings of clusters to endpoints and vice-versa
- Extend the parsing for clusters and endpoints to use the added mappings for populating both with EDS data
- Update tests to match the change
Updated unit tests
Manual and unit testing
Checklist:

Envoy Debugging: Fix EDS

---

CHANGELOG.md

- Re-order changelog sections
- Remove trailing FEATURES on one line 
Checklist:

CHANGELOG: re-order changelog and remove extraneous trailing FEATURES

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml

- Add ReferenceGrant permissions to Consul API Gateway ClusterRole, refs https://github.com/kubernetes-sigs/gateway-api/pull/1188
- Doesn't remove ReferencePolicy yet, as we want to allow backwards compatibility until the Gateway API v0.6.0 release, refs https://github.com/kubernetes-sigs/gateway-api/pull/1205
- Refs #1148 
- Deployed Consul API Gateway from Helm chart from this branch and ran Gateway API conformance tests.
```
[INFO]  k8s/logger.go:30: consul-api-gateway-server.controller-runtime: Starting EventSource: controller=tcproute controllerGroup=gateway.networking.k8s.io controllerKind=TCPRoute info="Starting EventSource" source="kind source: *v1alpha2.ReferenceGrant"
```
- Consul API Gateway is able to deploy successfully from this branch using the Helm chart, with the changes …

charts: add ReferenceGrant permissions to Consul API Gateway ClusterRole

---

.circleci/config.yml
CHANGELOG.md
acceptance/framework/k8s/kubectl.go
acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go
control-plane/connect-inject/peering_acceptor_controller.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller.go
control-plane/connect-inject/peering_dialer_controller_test.go

Previously, we will call generate token endpoint when secret contents change,
i.e. when the resource version in the status of the Acceptor CR doesn't match
the resouce version in the existing secret version. However, this results in a race
condition when multiple reconciles run concurrently. When that happens, one of them ends
up with an outdated CR object and as a result decides that it needs to re-generate the peering
token because those resource versions don't match. This is also undesirable because now
peering tokens have an establishment secret that can only be used one time. If we re-generate
tokens without user knowing, this could result in errors because the dialer will use an outdated secret.
Also, make sure we always update the latest version of the …

peering: generate new token only on user-triggered events 

---

charts/consul/templates/_helpers.tpl
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats

On openshift/okd you might not have permissions to create directories
everywhere. But you can introduce mounts.
Here we're just creating insignificant mount-points for the extra-config
to do it's thing, thus eliminating the need for creating the directory,
which the user running the container might not have permissions to do.
Fixes #1306

fix permissions for /consul/extra-config

---

cli/cmd/proxy/list/command.go
cli/cmd/proxy/list/command_test.go

- Fix an issue where pods running API Gateway were being mis-labeled as "Sidecar" pods
- Edited the unit test to test the correct behavior.
- Manual testing against a cluster
- Running the unit tests
Checklist:

Fix issue where API gateways were being mis-labeled as Sidecar proxies

---

acceptance/framework/cli/cli.go
acceptance/framework/consul/cli_cluster.go
acceptance/tests/connect/connect_inject_test.go
cli/cmd/proxy/list/command.go
cli/cmd/proxy/read/command.go

- Use context as set by user for Kubernetes
- Pass in context using Kube options to CLI run commands
- Acceptance tests in CircleCI
- Acceptance tests in CircleCI
Checklist:

Fix context handling for the CLI

---

charts/consul/values.yaml

realized I forgot to add ticks for the helm values docs :(

peering: add code blocks for helm docs

---

.release/ci.hcl

- Trigger release pipeline via CRT process
- The new workflow has been tested generate the same parameters when invoking the existing pipeline for publishing helm charts

Add stanza to ci.hcl to trigger helm pipeline

---

control-plane/connect-inject/container_init.go
control-plane/connect-inject/container_init_test.go
control-plane/connect-inject/envoy_sidecar.go
control-plane/connect-inject/envoy_sidecar_test.go
control-plane/connect-inject/peering_acceptor_controller.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller.go
control-plane/connect-inject/peering_dialer_controller_test.go
control-plane/go.mod
control-plane/go.sum

- replace our BYO versions of `pointerTo*` with the `pointer` util package from k8s, just a cleanup.
acceptance/unit tests should pass
👀 
Checklist:

Use the pointer pkg instead of BYO functions everywhere

---

README.md

- GitHub added a [new syntax for notes and warnings](https://github.com/community/community/discussions/16925). This PR uses that instead of the Emoji.
I think the note rendering looks prettier 💅🏻. Example:
> **Note**  
> This is a note!
> **Warning**  
> This is a warning!

Use new GitHub Markdown note syntax

---

.circleci/config.yml
acceptance/framework/consul/helm_cluster.go
acceptance/framework/k8s/helpers.go
acceptance/tests/peering/peering_connect_test.go
hack/aws-acceptance-test-cleanup/main.go

- parallelize nightly tests (they now take ~5h which is the max time circleci will allow us to run w/o output)
- re-establish port forwarding if we lose connection. Sometimes, we lose port-forwarding connection and never re-establish it, which leads to any calls to consul to fail. Instead, we now monitor the local port, and if we can't connect to it, we re-establish port-forwarding
- Add retries to aws cleanup script
ran them in ci: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7036/workflows/0f11f813-0c69-4090-a9ae-63ba844e101e
👀 
Checklist:

Various acceptance tests fixes

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
control-plane/go.mod
control-plane/go.sum
control-plane/subcommand/inject-connect/command.go

- The flag was initally named `server-address` but the `server-address` flag has been used across the project to imply ONLY the address of the external server when they are enabled. This meaning is overloaded in the context of the server address used for generating the peering token. This leads to errors (specifically in the agentless context), where the deployment needs to explicitly know the list of external servers.
- bats
- 👀 
- comments on the name of the flag.

Rename flag for peering token server addresses.

---

.circleci/config.yml
acceptance/framework/cli/cli.go

- This fixes the root cause of this [error](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7053/workflows/c79a773b-2ba0-4b8a-9192-d19c70550bd4/jobs/57273) where the Kubeconfig was being passed to the CLI as `-config path` when it should be `-kubeconfig path`.
- Running an acceptance test suite for a public cloud host on this PR (Kind acceptance tests don't set a kubeconfig, that's why this got missed).
[GKE Acceptance Test run](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7063/workflows/2596f37d-6b54-4ad7-bf1e-85a56c3950e8/jobs/57311)
- Watch the acceptance tests to verify correctness.
Checklist:
> HashiCorp engineers only, community PRs should not add a …

Fix acceptance tests passing "-config" instead of "-kubeconfig" to CLI

---

control-plane/Dockerfile

In `actions-docker-build` we [pass](https://github.com/hashicorp/actions-docker-build/blob/05c370a26e61b06be46c5095d6e914c9f0ea4f3d/scripts/docker_build#L49) `PRODUCT_VERSION` to the docker build command. Since this was not set, the label did not populate properly which is used in a comparison to determine the `minor-latest` and `latest` docker image tags. 
```
docker inspect hashicorp/consul-k8s-control-plane:latest -f={{json '.Config.Labels'}} | jq
{
"description": "consul-k8s-control-plane provides first-class integrations between Consul and Kubernetes.",
"maintainer": "Team Consul Kubernetes <team-consul-kubernetes@hashicorp.com>",
"name": "consul-k8s-control-plane",
"release": "",
"summary": "consul-k8s-control-plane provides first-class integrations …
```

[RELENG-20] set PRODUCT_VERSION for default docker build

---

acceptance/tests/fixtures/bases/static-server-https/anyuid-scc-rolebinding.yaml
acceptance/tests/fixtures/bases/static-server-https/configmap.yaml
acceptance/tests/fixtures/bases/static-server-https/deployment.yaml
acceptance/tests/fixtures/bases/static-server-https/kustomization.yaml
acceptance/tests/fixtures/bases/static-server-https/privileged-scc-rolebinding.yaml
acceptance/tests/fixtures/bases/static-server-https/psp-rolebinding.yaml
acceptance/tests/fixtures/bases/static-server-https/service.yaml
acceptance/tests/fixtures/bases/static-server-https/serviceaccount.yaml
acceptance/tests/terminating-gateway/common.go
acceptance/tests/terminating-gateway/terminating_gateway_destinations_test.go
acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
acceptance/tests/terminating-gateway/terminating_gateway_test.go

- Adds acceptance tests for the egress Destinations #1352 
- Some refactoring to support extended usage of common functions in the t-gateway acceptance tests
- Adds a server that supports HTTPS, because right now we need an SNI or IP address to route the traffic. HTTP-only will be added before the 1.13 release.
- I've been running the acceptance test against a 3-node k3d cluster with some development images for Consul 1.13. All the necessary changes should be in the Consul 1.13 release branch.
- Running the tests
Checklist:

test: egress destination tests

---

.circleci/config.yml
acceptance/framework/config/config.go
acceptance/framework/consul/helm_cluster.go
acceptance/framework/flags/flags.go
acceptance/tests/snapshot-agent/snapshot_agent_vault_test.go

- disable snapshot-agent-vault acceptance test for consul < 1.12
- enable nightlies for 1.11 and 1.12 and 1.13
* 1.11 passes: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7104/workflows/d708428f-e5f3-4e77-b767-57f2612ab970
* 1.12 passes: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7103/workflows/78e25a2b-bdcc-447e-8339-8bb013a79a31 
* 1.13 passes: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7102/workflows/84394645-d4af-4107-adb3-6f5ee950bf02
Manually tested the new flags:
```
$ go test ./tests/connect/... -p 1 -timeout 2h -failfast -use-kind -no-cleanup-on-failure -kubecontext=kind-dc1 -secondary-kubecontext=kind-dc2 -enable-enterprise -enable-multi-cluster …
```

enable nightlies for 1.11 and 1.12 and 1.13

---

charts/consul/test/terraform/aks/main.tf
charts/consul/test/terraform/eks/main.tf
charts/consul/test/terraform/gke/main.tf

- Bump the K8s version on every platform by 1.
- Ran the nightlies. The few failures were unrelated to the infrastructure.
- 👀

Update Kubernetes versions for nightlies.

---

.circleci/config.yml
acceptance/framework/consul/helm_cluster.go

Nightlies were failing due to not being able to download the `hashicorp/consul` chart.
- Runs `helm repo add` and `helm repo update` prior to doing the helm install when  not using the chartDir as the helm template location.
CI fails when specifying a chart version, here is an example which includes the `-helm-chart-version` flag without the proposed fix:
https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/7237/workflows/0bf2a6c3-e8c3-4976-abd6-3ff567851432
CI passes with the proposed fix.
This is identical to what we do for the Vault tests which use Helm to install vault.
Checklist:
> Entries should use …

update the helm repo prior to running helm install in acceptance tests.

---

CHANGELOG.md

- adds note about required changes for multiport users.
Checklist:

update chagnelog for kube-1.24

---

README.md
charts/consul/README.md

- Update versions
- Remove Connect references
Checklist:

README.md: update K8s versions

---

.github/workflows/build.yml
.release/ci.hcl
control-plane/Dockerfile

This PR is an attempt to get the CNI added to the release process using CRT.
- Use the current build matrix for control-plane to also build the CNI plugin
- The build generates a separate zip file for the CNI plugin
- Add a step to the docker build that downloads the consul-cni artifact so that the docker build can COPY it
Checklist:

Add CNI to CRT

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-deployment.yaml
charts/consul/test/unit/api-gateway-controller-deployment.bats

Fixes #1344 
When federation is enabled and the API Gateway controller is deployed in a secondary datacenter:
- use correct `acl-auth-method`
- configure the `primary-datacenter`
This matches what we do today for [mesh gateway](https://github.com/hashicorp/consul-k8s/blob/4b630fc687c82860a5fece2a148f82db6f495ab9/charts/consul/templates/mesh-gateway-deployment.yaml#L157-L162) and [consul controller](https://github.com/hashicorp/consul-k8s/blob/a16c4ee0a02320c812f78bc2f33d192f409f62be/charts/consul/templates/controller-deployment.yaml#L110-L115) deployments.
Shout out to @t-eckert for pointing me in the right direction. Since he sent me this patch, I've included him as a co-author on the change commit.
**How I expect reviewers to …

api-gateway: configure ACL auth appropriately in secondary dc

---

CHANGELOG.md
acceptance/tests/connect/connect_inject_test.go
cli/cmd/proxy/read/command.go
cli/cmd/proxy/read/command_test.go
cli/cmd/proxy/read/config.go
cli/cmd/proxy/read/config_test.go
cli/cmd/proxy/read/envoy_types.go
cli/common/portforward.go

- Extend the timeout for port-forward (I was seeing some unneeded failures when connecting to AWS).
- Expand the set of [Envoy Listener Filters](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto) that may be parsed and output to the Listeners table.
- Fix [Proxy read: terminating gateway listeners show up weird](https://hashicorp.atlassian.net/browse/NET-707?atlOrigin=eyJpIjoiNGM4OGMzYzhhZDgxNGEzNTlkZDVhNzdjMzllZWYwODAiLCJwIjoiaiJ9)
- Fix [Proxy read: blank filters being displayed](https://hashicorp.atlassian.net/browse/NET-709?atlOrigin=eyJpIjoiMWZiZGY2NTM2ZmZkNDkzNzljN2U0MzZjOTVlNTBiZDciLCJwIjoiaiJ9)
- Change `to` back to `->` in filter formatting output.
- Unescape `>` in JSON output so it doesn't show up weird. …

Fix Listener Filter bugs and cover more Envoy Listener Filter Types

---

CHANGELOG.md

- Matching release notes: https://github.com/hashicorp/consul/pull/14414
- Adding missing links to merged PRs
Checklist:

CHANGELOG: formatting and missing links

---

cli/cmd/proxy/read/config.go
cli/cmd/proxy/read/config_test.go

- When a cluster uses Logical DNS, omit the endpoint defined by the domain. Fixes [Proxy read: logical DNS reports an endpoint that could be clearer](https://hashicorp.atlassian.net/browse/NET-708).
- Manually against a terminating gateway that uses logical DNS.
- :eyes:
Checklist:

Omit non-IP defined endpoints from clusters

---

control-plane/go.mod
control-plane/go.sum

- update the cni package version
-
Running `make control-plane-dev-docker` or `make control-plane-dev` was causing this error
👀

Update the reference to cni package to the current on main to fix building image.

---

.circleci/config.yml
acceptance/tests/consul-dns/consul_dns_test.go
charts/consul/test/terraform/eks/main.tf
charts/consul/test/terraform/gke/main.tf

- Update Kube versions + job names so that we test Kubernetes 1.21, 1.22, 1.23, 1.24 only.
- Remove excess nightly jobs as it is already covered by per-commit jobs.
- Lowers parallelism due to resource issues.
many many times on CI.
Checklist:

update Kubernetes versions throughout CI

---

.circleci/config.yml

- Use `#feed-consul-k8s-ci` for notifications about Consul on Kubernetes CI failures
- I have not. Should be simple enough that it should just work.
Checklist:

Notify #feed-consul-k8s-ci

---

.circleci/config.yml

- Only run CNI nightly tests if the non-CNI nightly tests pass. This is done to cut down on seeing errors twice when the CNI is not the differentiating factor.
- We'll see. 
Checklist:

Make CNI tests dependent on non-CNI tests passing

---

CONTRIBUTING.md
Makefile

- Create a make target for the CLI binary. This builds the `consul-k8s` CLI binary and adds it to `<consul-k8s_project_root>/cli/bin` and to your `$GOPATH`
- change instructions for building CLI binary in contributing documentation to use make
- built cli using `make cli-dev`
- confirmed version in path by running `consul-k8s version`
- try out `make cli-dev` locally
- 👀 
Checklist:

Add makefile cli

---

.github/workflows/backport.yml

- Add backport pipeline
Usage:
When you merge a PR into with the label such as `backport/0.48.x`, it will cherry pick the commits from the PR and create a new PR against the branch `release/0.48.x` with those commits. If the cherry pick fails, you'll need to manually cherry pick your commits into the appropriate release branches and make PRs. 
- Ran it against my consul-k8s fork to test it out with a personal PAT. We have an existing consul-ecosystem PAT which seems to have the same permissions I used in my fork, in the worst case we may need to create a new PAT with full "repo" and "workflow" permissions if this doesn't work the first time we run it.
- 👀 
This can be merged as is, and it won't …

ci: add backport pipeline

---

CHANGELOG.md
cli/cmd/install/install.go
cli/cmd/install/install_test.go
cli/cmd/proxy/command.go
cli/cmd/proxy/list/command.go
cli/cmd/proxy/list/command_test.go
cli/cmd/proxy/read/command.go
cli/cmd/proxy/read/command_test.go
cli/cmd/status/status.go
cli/cmd/status/status_test.go
cli/cmd/uninstall/uninstall.go
cli/cmd/uninstall/uninstall_test.go
cli/cmd/upgrade/upgrade.go
cli/cmd/upgrade/upgrade_test.go
cli/common/flag/set.go
cli/main.go

- see description
- ran through auto-completions tabbing through commands
- unit tests written to make sure that number of flags matches the number of auto-completion suggestions
- run consul-k8s, activate autocomplete, and try it out
Checklist:
- Added tab autocompletion to the `consul-k8s` CLI. Commands are automatically supported, but flags require implementing the completion interface per command
example for `consul-k8s install`:
```Go
// AutocompleteFlags returns a mapping of supported flags and autocomplete
// options for this command. The map key for the …
```

Add cli autocomplete

---

.circleci/config.yml
.github/workflows/test.yml
charts/consul/test/docker/Test.dockerfile

NOTE: consul-helm-test v0.12.0 has already been published.
- Update consul-helm-test image and CI to go 1.18
👀 && CI
👀 
Checklist:

Update consul-helm-test image and CI to go 1.18

---

.release/ci.hcl

- branches with a leading `release/` will be categorized as release branches
- Will be tested with next release
- N/A
Checklist:

add `release/**` wild card to ci.hcl

---

acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go
charts/consul/templates/expose-servers-service.yaml
charts/consul/templates/server-podsecuritypolicy.yaml
charts/consul/templates/server-service.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/server-podsecuritypolicy.bats
charts/consul/values.yaml
control-plane/connect-inject/container_init_test.go
control-plane/connect-inject/peering_acceptor_controller_test.go

- Update the configuration to support peering with agentless. This required migrating all the grpc ports that were configured to use 8503 to use 8502.
- Ran the acceptance tests locally on GKE.
- Approve if the acceptance test for Peering goes 🟢

Support peering on agentless

---

charts/consul/values.yaml

- Update value.yaml for syncCatalog.aclSyncToken stanza so that it references Kubernetes secrets since this is only supported for BYO ACL tokens.
Checklist:

update docs for helm for global.syncCatalog.aclSyncToken

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-deployment.yaml
charts/consul/test/unit/api-gateway-controller-deployment.bats

> **Note** This is the third of three in the chain of PRs required to get Consul API Gateway working in a secondary federated datacenter:
> - https://github.com/hashicorp/consul-k8s/pull/1481
> - https://github.com/hashicorp/consul-api-gateway/pull/368
> - https://github.com/hashicorp/consul-k8s/pull/1511
- When deployed into a secondary datacenter with federation enabled, populate the `primary-datacenter` flag added to Consul API Gateway's controller in https://github.com/hashicorp/consul-api-gateway/pull/368
Install a federated setup as described in [this guide](https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/multi-cluster/kubernetes), making sure that API Gateway is enabled in both datacenters and …

Populate primary dc flag for APIGW controller in secondary federated dc

---

CHANGELOG.md
charts/consul/templates/_helpers.tpl

- Fixes a typo in the helper template for pod disruption budget for connectInject
- Fixes #1529.
👀 
👀 
Checklist:

fix a typo in the helper template for pdb

---

.circleci/config.yml

- I'm not sure how this got upgraded after we downgraded it, maybe a merge conflict that wasnt caught. Anyways it's my fault so lets get it back to where it was.
CI should not throw 
```
Error: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "[client.authentication.k8s.io/v1alpha1](http://client.authentication.k8s.io/v1alpha1)"
```
Checklist:

downgrade helm version in CI

---

CHANGELOG.md
charts/consul/templates/create-federation-secret-job.yaml
charts/consul/test/unit/create-federation-secret-job.bats

fixes #1466
- CreateFederationSecret Job should not run when UpdatePartition is not 0.
I ran the below commands to verify  the change
1. job does not run when updatePartition is 1.
```
helm template \
-s templates/create-federation-secret-job.yaml  \
--set 'global.federation.enabled=true' \
--set 'global.federation.createFederationSecret=true' \
--set 'global.acls.createReplicationToken=true' \
--set 'global.acls.manageSystemACLs=true' \
--set 'global.tls.enabled=true' \
--set 'meshGateway.enabled=true' \
--set 'connectInject.enabled=true' \
--set 'server.updatePartition=1' \
.
```
2. CreateFederationSecret job runs, when updatePartition is 0.
```
helm template \
-s templates/create-federation-secret-job.yaml  \
--set …
```

create-federation-secret job runs only when server.updatePartition is 0

---

Makefile

- spacing issue with `ifndef` check in makefile was causing unexpected results
Checklist:
- [ N/A] Tests added
- [ N/A] CHANGELOG entry added 

Pipeline fix makefile spacing issue

---

CHANGELOG.md
control-plane/catalog/to-consul/resource.go
control-plane/catalog/to-consul/resource_test.go
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_test.go
control-plane/helper/parsetags/parsetags.go
control-plane/helper/parsetags/parsetags_test.go

- Moves the tag parsing functionality from `control-plane/catalog` to `control-plane/helpers`.
- Uses this to parse `consul.hashicorp.com/connect-service-tags` in the endpoints_controller and sync catalog.
Fixes #1531 
unit tests
👀 + unit tests should pass.
Checklist:

Support escaped commas in service tags for connect

---

.circleci/config.yml
CHANGELOG.md
charts/consul/templates/cni-clusterrole.yaml
charts/consul/templates/cni-daemonset.yaml
charts/consul/templates/cni-networkattachmentdefinition.yaml
charts/consul/templates/cni-securitycontextconstraints.yaml
charts/consul/test/unit/cni-daemonset.bats
charts/consul/test/unit/cni-networkattachmentdefinition.bats
charts/consul/test/unit/cni-securitycontextcontstraints.bats
charts/consul/values.yaml
control-plane/cni/main.go
control-plane/subcommand/install-cni/cniconfig.go
control-plane/subcommand/install-cni/cniconfig_test.go
control-plane/subcommand/install-cni/command.go
control-plane/subcommand/install-cni/testdata/00-chained-plugins.conflist
control-plane/subcommand/install-cni/testdata/00-chained-plugins.conflist.golden
control-plane/subcommand/install-cni/testdata/00-single-plugin.conf

This PR adds support for OpenShift and Multus in CNI. OpenShift uses Multus as the base CNI plugin.
- Added SecurityContextConstraints CRD so that CNI has the permissions to run on OpenShift and gave the consul-cni service account permissions to reach OpenShifts SCC CRD.
- Added a --multus flag to the CNI installer so that the flag can be used by the CNI plugin.
- When --multus flag is set, create a default Network Attachment Definition CRD for Multus to use. Note, Pods require an annotation in order for Multus to run the consul-cni plugin. Please see [Multus documentation](https://github.com/k8snetworkplumbingwg/multus-cni) for more information about how to use Multus.
- Fix: Fixed installer to rename .conf file .conflist file when consul-cni is added to a …

CNI: Add support for OpenShift and Multus

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml

- Allow the Consul API Gateway controller to create + update Secrets so that it can store the Consul CA cert alongside each Gateway deployment. Long-term, this enabled Consul API Gateway to run on "distroless" Envoy images once https://github.com/hashicorp/consul-api-gateway/pull/391 is released.
Deployed Consul API Gateway using this branch and https://github.com/hashicorp/consul-api-gateway/pull/391
See above
**Checklist:**

Allow the API Gateway controller to create and update Secrets

---

README.md
charts/consul/README.md

- Bump Helm CLI requirement to 3.6+ to match Vault Helm requirements
Checklist:

README: bump Helm CLI requirement to 3.6+

---

acceptance/tests/ingress-gateway/ingress_gateway_namespaces_test.go
acceptance/tests/ingress-gateway/ingress_gateway_test.go
acceptance/tests/ingress-gateway/main_test.go
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/values.yaml
control-plane/connect-inject/annotations.go
control-plane/connect-inject/endpoints_controller.go
control-plane/connect-inject/endpoints_controller_ent_test.go
control-plane/connect-inject/endpoints_controller_test.go
control-plane/go.mod
control-plane/go.sum
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/inject-connect/command.go

- Register Ingress Gateways using the endpoints controller.
- Use Consul Dataplane instead of Envoy
- Unit and BATS tests.
- Code Review
Checklist:

Ingress Gateways integration with Agentless and Consul Dataplane

---

CHANGELOG.md
charts/consul/templates/client-daemonset.yaml

- provide new grpc TLS auto-encrypt config
👀 
Checklist:

bug: provide new grpc TLS auto-encrypt config

---

.circleci/config.yml
charts/consul/test/docker/Test.dockerfile

- build and publish consul-helm-test image with gke-gloud-auth-plugin
- use new image in CI
This passing nightly [GKE test](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/8047/workflows/8d34b238-fc6b-47ec-8540-41e6a9ada4ff/jobs/61509/parallel-runs/1?filterBy=ALL) in my branch: 
👀 
Checklist:

Install gke-gcloud-auth-plugin into acceptance test image to fix warnings on GKE

---

.circleci/config.yml

Tproxy is not yet supported with agentless, so disabling it in nighlies until GA

Disable tproxy nightly tests until GA

---

CHANGELOG.md
control-plane/go.mod
control-plane/go.sum

- Update changelog with `EnforcingConsecutive5xx` update since it is an external facing change
Checklist:

add EnforcingConsecutive5xx to changelog

---

.github/workflows/backport.yml

- The squash command for the backport assistant created unexpected issues when auto-creating PRs involving merge conflicts when backporting. Recommendation from Rel-Eng is to remove the squash command.
Checklist:

reverted addition of squash to backport assistant

---

acceptance/tests/partitions/partitions_connect_test.go

- change service name in TestPartitions_Connect to have `<release name>-<chart.Name>-expose-servers` to match the `template.fullName` helm template function and also [what is in CI](https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/8088/workflows/12f63bd2-b37d-4718-91d7-572e986cc1dc/jobs/61643) and what is in [other tests that use the ServiceHost function](https://github.com/hashicorp/consul-k8s/blob/b40b8a1893c493b704fdff106b28fa5568967950/acceptance/tests/partitions/partitions_sync_test.go#L149).
-
- run acceptance tests
👀 
Checklist:

Correct partitionServiceName in TestPartitions_Connect to fix failures in nightly acceptance runs.

---

charts/consul/Chart.yaml
charts/consul/values.yaml

Currently the chart points to an invalid docker image:
```
Failed to pull image "hashicorp/consul-k8s-control-plane:1.0.0-dev": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/hashicorp/consul-k8s-control-plane:1.0.0-dev": failed to resolve reference "docker.io/hashicorp/consul-k8s-control-plane:1.0.0-dev": docker.io/hashicorp/consul-k8s-control-plane:1.0.0-dev: not found
```
- use the correct image in our chart for 1.0.0-dev
acceptance should pass
Checklist:

use hashicorp mirror image for 1.0.0-dev

---

.circleci/config.yml

- remove hardcoding -consul-image in run acceptance job template
- add hardcoding -consul-image for nightly acceptance tests so that the nightly-acceptance-tests-consul that actually pass -consul-image will be respected.
👀 
👀 
Checklist:

Remove -consul-image from -run-acceptance-tests job template so that nightly consul version tests can send the correct image.

---

.circleci/config.yml

Background:
Ci for nightly-acceptance-tests-consul are failing because it is using a current control-plane that no longer has consul-api-timeout specified for inject-connector-deployment.
This fixes, version mismatches as you can see here the failed tests go from 12 to 6 (there are still 3more failed tests/subtests that have individual reasons for failing that need to be investigated individually.)
- set consul-k8s-image directly through consul-k8s-image parameter for consul nightly tests instead of setting it through additional flags.
-
CI
👀

set consul-k8s-image directly through consul-k8s-image parameter for consul nightly tests instead of setting it through additional flags.

---

cli/cmd/status/status.go
cli/cmd/status/status_test.go

- Remove the check for Consul clients in the `consul-k8s status` command. Clients don't exist in agentless (RIP).
- Unit tests
- Manual install -> status check -> uninstall
- Unit tests
- Manual install -> status check -> uninstall
- :eyes:
Checklist:

Remove check for clients in status command

---

CHANGELOG.md
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/controller-deployment.yaml
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/templates/partition-init-job.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/controller-deployment.bats
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/partition-init-job.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
cli/version/version.go
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/version/version.go

- configure -tls-server-name for consul-k8s components that use connection manager when global.cloud.enabled = true so that it matches the server certificate minted from HCP 
-
- bats tests
- manual integration testing with HCP
👀 
Checklist:

configure -tls-server-name when global.cloud.enabled=true so that it matches the server certificate minted from HCP

---

.circleci/config.yml
acceptance/framework/config/config.go
acceptance/framework/flags/flags.go
acceptance/tests/consul-dns/consul_dns_test.go

The consul dns tests have been flaky ever since we upgraded AKS from 1.21.14 to 1.22.11 on August 24th. I have been able to reproduce the problem on a new AKS cluster and one that has sat around for a while thus eliminating the chance that this was caused by something kube not starting.
Sometimes the tests pass, sometimes they fail and I do not know why.
Research:
- The problem still happens on newer versions of AKS (1.23.12)
- I could not find anything in the Kubernetes or AKS release notes/CHANGELOGs
- I have not been able to find any issues in Github for both Kubernetes and AKS related to the problem.
- Added `sh -c` to the dig command so that the TTY wasn't swallowed but it didn't make a difference. Reverted because it is probably not a good idea to output networking things in tests. …

Add flag to disable dns tests on AKS

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml

Allow the API Gateway controller to `get`, `list` and `watch` the `MeshService` resource. This allows the controller to verify that a `MeshService` referenced as a route backend actually exists.
Set up a `Gateway` with `HTTPRoute` targeting a `MeshService` as a backend. This is especially useful in a peering setup where you need to reference an imported Consul service.
:eyes:
Checklist:

api-gateway: Allow controller to read MeshService resource

---

CHANGELOG.md
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/controller-deployment.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/sync-catalog-deployment.bats
charts/consul/values.yaml

- `syncCatalog.consulNamespaces.mirroringK8S` now defaults to `true`
- `connectInject.consulNamespaces.mirroringK8S` now defaults to `true`
- Instead of failing when `connectInject.consulNamespaces.mirrorK8S=true` and `global.enableConsulNamespaces=false`, the `connect-inject-deployment.yaml` template instead checks for both to be true in order to pass the `-enable-k8s-namespace-mirroring=true` flag. That means, `connectInject.consulNamespaces.mirrorK8S=true` and `global.enableConsulNamespaces=false` is now a valid deployment configuration that will simply not tell Consul to perform mirroring given that Consul namespaces is not `true`.
- Modified BATS tests to accommodate this change
- Modified BATS tests
- Run Acceptance tests
How I …

Helm namespace mirroring

---

CHANGELOG.md
cli/cmd/status/status.go
cli/cmd/status/status_test.go
cli/common/terminal/basic.go
cli/common/terminal/ui.go

Previously, if a user had servers deployed outside of a given K8s cluster, the `status` command would fail when it attempted to show the health status of servers. We recently removed a similar feature for clients which had the same problem when we moved to the "agentless" architecture. 
This PR changes the status command to only print the health status of clients and servers if they are expected to be present in the K8s cluster. If the user is running with the agentless architecture or has servers deployed outside of the cluster (e.g. HCP). The `status` command will simply not show the health status instead of failing.
- Only show health status for servers if they are expected to be present in the K8s cluster.
- Move some constants and vars up to the top of a …

Show server statuses only when they are deployed into the Kubernetes cluster

---

CHANGELOG.md
charts/consul/Chart.yaml
charts/consul/values.yaml
cli/version/version.go
control-plane/version/version.go

- PR from [this step](https://github.com/hashicorp/engineering-docs/blob/main/consul/consul-k8s/release-process.md#prepare-main-for-next-dev-cycle) in the release process
👀 
👀 
Checklist:

1.0.0-beta3 post release - Put main back in dev mode

---

charts/consul/templates/connect-injector-disruptionbudget.yaml
charts/consul/test/unit/connect-injector-disruptionbudget.bats
charts/consul/values.yaml

It looks like the PDB for the connect injector has copied the logic from the Server PDB.
In that it is extremely conservative and attempts to maintain n+1 pods, which makes complete sense for Consul Servers as you do want to maintain a quorum at all times.
The injector deployment uses leader election and only 1 pod is actually active at any one time, requiring n/2-1 pods to be available is unnecessary.
Furthermore, with the default 2 replicas `maxUnavailable` is set at 0, which requires manual human operator intervention to, for example, drain a node running an injector pod.
See [Single-instance Stateful Application](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#think-about-how-your-application-reacts-to-disruptions) 
For the connect injector deployment a `minAvailable` …

Helm: Support minAvailable on connect injector PDB

---

CHANGELOG.md
charts/consul/templates/server-service.yaml
charts/consul/test/unit/server-service.bats

- We previously relied on setting an annotation ` service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"` which has been deprecated for 5 years and replaced with `spec.publicNotReadyAddresses` which we also already use.
- Remove it and continue to use the correct spec field on the server-service.yaml.
https://github.com/kubernetes/kubernetes/pull/63742
https://github.com/kubernetes/kubernetes/issues/63741
CI and Unit tests should pass.
Bats test updated.
👀 
Checklist:

remove deprecated annotations in server-service template

---

charts/consul/templates/server-acl-init-cleanup-job.yaml
charts/consul/templates/server-acl-init-job.yaml
charts/consul/templates/webhook-cert-manager-deployment.yaml
charts/consul/test/unit/server-acl-init-cleanup-job.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/webhook-cert-manager-deployment.bats
charts/consul/values.yaml

This solution is in response to an ask from a customer who wants to set `nodeSelector` for all Pods in their cluster. This adds that capability to `server-acl-init` jobs and `webhook-cert-manager`.
- Add a Helm stanza, `global.acls.job` for configuring `server-acl-init` and `server-acl-init-cleanup` jobs.
- Add the Helm value `global.acls.job.tolerations` for setting tolerations on `server-acl-init` and `server-acl-init-cleanup` jobs.
- Add the Helm value `global.acls.job.nodeSelector` for setting the nodeSelector on `server-acl-init` and `server-acl-init-cleanup` jobs.
- Add the Helm value `webhookCertManager.nodeSelector` for setting the nodeSelector on `webhook-cert-manager-deployment`.
- Add BATS tests for all of the above changes. …

Add `tolerations` and `nodeSelector` to Server ACL init jobs and `nodeSelector` to Webhook cert manager

---

charts/consul/values.yaml

The provided example for `apiGateway.managedGatewayClass.copyAnnotations` doesn't work. If you use the example, the Helm installation fails.
This PR fixes it.
1. add a copy-list of annotations to your `values.yaml` in the format of the updated example
2. helm install
3. create a `Gateway` w/ the copy-listed annotation
4. the resulting K8s `Service` should have the annotation from the `Gateway
<details>
<summary>Example</summary>
```yaml
global:
name: consul
tls:
enabled: true
image: hashicorppreview/consul:1.14-dev
server:
replicas: 1
ui:
enabled: true
service:
type: NodePort
connectInject:
enabled: true
default: true
controller:
enabled: true
apiGateway:
enabled: true
image: …
```

Update inaccurate example for API gateway's copyAnnotations

---

acceptance/framework/config/config.go
acceptance/framework/config/config_test.go
acceptance/framework/connhelper/connect_helper.go
acceptance/tests/cli/cli_install_test.go
acceptance/tests/cli/cli_upgrade_test.go
acceptance/tests/cli/main_test.go
acceptance/tests/connect/connect_external_servers_test.go
acceptance/tests/connect/connect_inject_namespaces_test.go
acceptance/tests/connect/connect_inject_test.go

Separate CLI tests into their own package for acceptance tests.
Having CLI tests to be in the same package as connect has become a bit hard to deal with for a few reasons:
- It's hard to run just the connect tests when you're working through some cross-cutting feature (e.g. agentless). You need to comment out the CLI tests just so they don't get in the way when you're just trying to check the basic service mesh functionality. 
- Having them run in one test makes the connect package take even longer to run and therefore tests harder to parallelize. 
- When we want to add more CLI features (like the CLI upgrade test which adds an ingress gateway on upgrade), it doesn't necessarily make sense to add them in the connect package.
acceptance …

Separate CLI tests into their own package

---

.github/workflows/build.yml

- [LICENSE.md was renamed to LICENSE](https://github.com/hashicorp/consul-k8s/commit/86c3baa3a6098b605cd9d8d405cb2a42618fc9ae) causing the builds on main to fail (eg. https://github.com/hashicorp/consul-k8s/actions/runs/3237929430/jobs/5305787047). This modifies the builds to use `LICENSE` instead of `LICENSE.md`
👀
👀
Checklist:

Fix License name in build action

---

.circleci/config.yml
.github/workflows/reusable-acceptance.yml
.github/workflows/test.yml
acceptance/framework/consul/helm_cluster.go
acceptance/tests/basic/basic_test.go
acceptance/tests/connect/connect_external_servers_test.go
acceptance/tests/metrics/metrics_test.go
acceptance/tests/partitions/main_test.go
acceptance/tests/peering/main_test.go
acceptance/tests/wan-federation/main_test.go
control-plane/connect-inject/container_init.go
control-plane/connect-inject/container_init_test.go
control-plane/connect-inject/mesh_webhook.go
control-plane/connect-inject/redirect_traffic.go
control-plane/connect-inject/redirect_traffic_test.go
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/connect-init/command_test.go
control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go

- Make `connect-init` command apply traffic redirection rules instead of calling consul CLI. This allows us to get rid of the init container that copies the consul binary.
- The `connect-init` command now accepts `iptables.Config` as JSON string in  a flag or env variable, parses it and calls `iptables.Setup` with that config
- It also applies additional rules based on proxy configuration (partially adopted from consul's `redirect-traffic` command implementation)
- The webhook now provides the iptables configuration as json to the `connect-init` command at injection times. The rules are based on the work we've done as part of the Consul CNI plugin.
acceptance and unit tests
👀 
Checklist:
> …

agentless: enable transparent proxy when running within a single k8s cluster

---

cli/preset/cloud_preset.go
cli/preset/cloud_preset_test.go

Background:
The cloud preset is solely used for installing HCP self managed clusters.  We want this to be as seamless for the user to do a one click install so that they can get to the value moment as soon as possible.  A common scenario for kicking the tires on a new feature is to use a local isntallation of k8s with kind/minikube/etc which by default only have 1 virtual host configured.  
HCP self managed clusters already expects 3 replicas will get created (it is configured in HCP and passed down in a bootstarp_expect value).  So currently when you try to install an HCP self managed cluster with 3 replicas into a cluster configured with 1 host, then you will get a scenario where the helm install fails because 1 replicas was created and the other 2 are pending waiting for two more …

Setting server affinity to null in coud preset to allow easier local kubernetes installations of GNM.

---

.circleci/config.yml
.github/workflows/test.yml
CHANGELOG.md
acceptance/framework/connhelper/connect_helper.go
acceptance/framework/consul/helm_cluster.go
acceptance/tests/consul-dns/consul_dns_test.go
acceptance/tests/partitions/main_test.go
acceptance/tests/peering/main_test.go
acceptance/tests/peering/peering_connect_test.go
acceptance/tests/wan-federation/main_test.go
charts/consul/templates/_helpers.tpl
charts/consul/templates/client-daemonset.yaml
charts/consul/templates/server-statefulset.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/server-statefulset.bats
control-plane/cni/go.mod
control-plane/cni/go.sum
control-plane/connect-inject/consul_dataplane_sidecar.go
control-plane/connect-inject/consul_dataplane_sidecar_test.go
control-plane/connect-inject/container_init.go
control-plane/connect-inject/dns.go
control-plane/connect-inject/dns_test.go
control-plane/connect-inject/mesh_webhook.go
control-plane/connect-inject/peering_acceptor_controller_test.go
control-plane/connect-inject/peering_dialer_controller_test.go
control-plane/connect-inject/redirect_traffic.go
control-plane/connect-inject/redirect_traffic_test.go
control-plane/go.mod
control-plane/go.sum
control-plane/subcommand/inject-connect/command.go

- Redirect traffic to the consul-dataplane's DNS proxy when DNS redirection is enabled. This means we no longer need to configure recursors for the clients and servers
- To fall back to kube dns when consul cannot resolve names, we define our own DNSConfig on the pod that uses Consul first, but falls back to the config from `/etc/resolv.conf` in the cluster.
👀 
Checklist:

agentless: Multi-cluster tproxy

---

CHANGELOG.md
control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go

- Remove unnecessary `agent_prefix` ACL policy for mesh gateways.
- This is only necessary to look up the gRPC port but since we're setting CONSUL_GRPC_ADDR we don't need this permission
* acceptance tests
* code
Checklist:

Removing agent:read ACL permissions from mesh gateways

---

CHANGELOG.md

- The mesh gateway changes were added to the wrong changelog, and also peering requires tls to be enabled now.
Checklist:

move changelog message to right spot

---

cli/preset/cloud_preset.go
cli/preset/cloud_preset_test.go

- set `connectInject.transparentProxy.defaultEnabled: false` in cloud preset since t-proxy work is still in progress.
-
- unit tests
- 👀 
- manual install of HCP self-managed clusters
👀 
Checklist:
- ~[ ] CHANGELOG entry added~ N/A since this is s new feature in beta and this feature already has a changelog.

CLI - cloud preset - Disable transparent proxy by default during beta

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml
charts/consul/templates/api-gateway-controller-podsecuritypolicy.yaml
charts/consul/test/unit/api-gateway-controller-clusterrole.bats
charts/consul/test/unit/api-gateway-controller-podsecuritypolicy.bats

- Add a `PodSecurityPolicy` for the API gateway controller when both
- API Gateway is enabled in `values.yaml`
- PodSecurityPolicies are enabled in `values.yaml`
- Policy mimics the one already in place for the controller at `controller-podsecuritypolicy.yaml`
- Slight adjustment to disable write access to the local file system since the API gateway controller does not require this
> **Note** `PodSecurityPolicy` was removed with Kubernetes 1.25, so this change must be tested on <= 1.24. I'm planning to work with @kschoche on supporting Pod Security Admission, the 1.25-friendly replacement, in the coming weeks.
> **Note** This adds a `PodSecurityPolicy` for the API gateway controller but not for the `Deployments` created by the controller for every …

Add PodSecurityPolicy for Consul API Gateway controller

---

.circleci/config.yml

- Since the build cli job was separated out, the clouds need the cli to be built so TestInstall will stop failing on main during the nightly acceptance tests.
This fix worked in another branch I was testing in: https://app.circleci.com/pipelines/github/hashicorp/consul-k8s/9020/workflows/4c4c9c1d-e526-4ada-ad3c-f3b93948e74c

acceptance: cloud tests need the cli to be built

---

.gitignore
charts/consul/templates/server-acl-init-job.yaml
charts/consul/test/unit/server-acl-init-job.bats
control-plane/consul/consul.go
control-plane/go.mod
control-plane/helper/test/test_util.go
control-plane/subcommand/acl-init/command_test.go
control-plane/subcommand/common/common.go
control-plane/subcommand/common/common_test.go
control-plane/subcommand/common/test_util.go
control-plane/subcommand/connect-init/command_ent_test.go
control-plane/subcommand/connect-init/command_test.go
control-plane/subcommand/consul-logout/command_test.go
control-plane/subcommand/create-federation-secret/command_test.go
control-plane/subcommand/flags/consul_test.go
control-plane/subcommand/get-consul-client-ca/command_test.go
control-plane/subcommand/install-cni/binary.go
control-plane/subcommand/server-acl-init/command.go
control-plane/subcommand/server-acl-init/command_ent_test.go
control-plane/subcommand/server-acl-init/command_test.go
control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go
control-plane/subcommand/server-acl-init/servers.go
control-plane/subcommand/webhook-cert-manager/command_test.go

- Integrate server-acl-init with consul-server-connection-manager to enable it to work in agentless environments
- Migrate usages of os.Remove() to os.RemoveAll()
acceptance and unit tests
👀
Checklist:

agentless: migrate server-acl-init to use server connection manager

---

control-plane/Dockerfile

- It looks like our license file changed, so updating our UBI dockerfile to use correct file.
in CI: https://github.com/hashicorp/consul-k8s/actions/runs/3379774271
Checklist:

Use correct file name for license

---

cli/cmd/uninstall/uninstall.go
cli/cmd/uninstall/uninstall_test.go

- When uninstalling, the CLI was informing the user that there was no consul demo cluster twice. I changed it so it only tells the user about it once.
- Manually
- By updating the unit tests
- :eyes:
Checklist:

Remove second printing of info that the Consul demo is not found when uninstalling

---

.circleci/config.yml
control-plane/subcommand/server-acl-init/servers.go

- The call to the bootstrap endpoint of the server can take some time to respond when running on cloud platforms. This commit re-introduces the 5min timeout to the HTTP client from the default 5 seconds.
- acceptance tests against the clouds
- 👀 
Checklist:

Set 5min timeout on HTTP Client

---

CHANGELOG.md
charts/consul/templates/api-gateway-controller-clusterrole.yaml
charts/consul/templates/api-gateway-gatewayclassconfig.yaml
charts/consul/templates/api-gateway-podsecuritypolicy.yaml
charts/consul/test/unit/api-gateway-controller-clusterrole.bats

> **Note** This builds on #1656 
When a user has both `global.enablePodSecurityPolicies=true` and `apiGateway.enabled=true`:
- Create a `PodSecurityPolicy` for use by all `Deployments` that the API gateway controller creates to back a `Gateway`
- Allow the API gateway controller to use `PodSecurityPolicies`
When `global.acls.manageSystemACLs=true` is also set:
- Provide the name of the `PodSecurityPolicy` to the `GatewayClassConfig` so that the API gateway controller can bind the policy to the `ServiceAccount` created for each `Gateway`. It does this by creating a `Gateway`-specific `Role` and `RoleBinding`.
The API gateway controller could create the `PodSecurityPolicy` itself; however, this isn't nearly as flexible as any user requiring a slight change …

api-gateway: allow controller to bind PodSecurityPolicy to ServiceAccounts that it creates

---

acceptance/tests/partitions/partitions_sync_test.go

- Fix service name for the servers in the partitions sync test
acceptance tests: they all failed because of the server-acl-init changes, but partitions sync non-secure test passed!
👀 
Checklist:

Fix sync partitions acceptance test

---

CHANGELOG.md
acceptance/tests/peering/peering_connect_namespaces_test.go
acceptance/tests/peering/peering_connect_test.go
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/expose-servers-service.yaml
charts/consul/test/unit/client-daemonset.bats
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/connect-inject-mutatingwebhookconfiguration.bats
charts/consul/test/unit/expose-servers-service.bats
charts/consul/test/unit/server-acl-init-job.bats
charts/consul/test/unit/server-config-configmap.bats

- Expose servers service is only needed when partitions are enabled, since peering now requires mesh gateways. So this PR makes it so the helm chart doesn't deploy the expose servers service when only peering (and not partitions) is enabled. 
- Fail fast in the helm chart if tls or mesh gateways are not enabled since they are required for peering
- In acceptance tests- fix flakiness due to mesh configuration not being recognized before the applying the acceptor resource (which generates the token), to ensure that the token is generated with mesh gateway addresses rather than server pod ips. 
acceptance tests, unit tests
👀 
Checklist:
> HashiCorp engineers only, community PRs should not add a …

peering: remove unnecessary expose servers service, add error cases, fix flaky test

---

CHANGELOG.md
control-plane/subcommand/server-acl-init/rules.go
control-plane/subcommand/server-acl-init/rules_test.go

- Add peering:read permissions that are compatible with OSS and ENT Consul images. The comment next to the rule explains this further. 
- Fix this log line that shows up in acceptance tests by adding peering permissions to the mesh gateway token. This makes the peering connection actually go through both mesh gateways (as opposed to just the remote mesh gateway)`agent.proxycfg: Failed to handle update from watch: kind=mesh-gateway proxy=test-dyqcwc-consul-mesh-gateway-556fd7855b-fzjq7 service_id=test-dyqcwc-consul-mesh-gateway-556fd7855b-fzjq7 id=peer-servers error="error filling agent cache: Permission denied: token with AccessorID 'c2c7bd05-0e5d-45b2-f2c1-36455c4977e5' lacks permission 'peering:read'"`
How I expect reviewers to test …

peering: fix acl issue

---

charts/consul/templates/_helpers.tpl
charts/consul/templates/connect-inject-deployment.yaml
charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/values.yaml
control-plane/connect-inject/consul_dataplane_sidecar.go
control-plane/connect-inject/consul_dataplane_sidecar_test.go
control-plane/connect-inject/mesh_webhook.go
control-plane/subcommand/flags/consul.go
control-plane/subcommand/flags/consul_test.go
control-plane/subcommand/inject-connect/command.go

- Add helm value of `externalServers.skipServerWatch`
- Add the environment variable CONSUL_SKIP_SERVER_WATCH to helm _helpers.tpl so that the environment variable will get automatically picked up by connection manager when talking to consul servers
- Even though not directly needed there, add the check that `externalServers.enabled` is also set when `externalServers.skipServerWatch=true` in connect-inject-deployment.yaml
- Bats tests for connect-inject-deployment to make sure that it fails the condition above and that the CONSUL_SKIP_SERVER_WATCH is set in the environment.
- Read the env variable in flags/consul.go so that it can be passed to connection manager and down into discover.Config (used by partition-init, catalog-sync, server-acl-init, …

Add externalServers.skipServerWatch to helm for working with load balancers

---

charts/consul/templates/_helpers.tpl
charts/consul/templates/client-daemonset.yaml
charts/consul/test/unit/client-daemonset.bats
control-plane/subcommand/acl-init/command.go
control-plane/subcommand/acl-init/command_test.go

- Migrate `acl-init` job to use the `netaddrs` library to resolve the address passed in instead of go-discover in order to align it with changes being made in the project.
- This migrates acl-init to use the new consul flags but uses a traditional Consul login instead of the watcher as the watcher cleans up the token when the process stops. Using the Consul login allows the client to use the correct token when they come up and their `preStop` hook logouts and cleans up the token.
- Unit tests are still 🟢 
- Acceptance tests for the basic case as that running clients with ACLs enabled.
- 👀 
Checklist:
> Entries should use …

Use netaddrs instead of go-discover in acl-init

---

CHANGELOG.md
cli/cmd/upgrade/upgrade_test.go
cli/helm/install.go
cli/helm/upgrade.go
cli/helm/upgrade_test.go

- When a user is promped to install Consul, if they give no answer (e.g. just hit enter) the install will occur.
- Manually by running an install.
- You may also run an install.
Checklist:

Default install and upgrade to "Y" when no answer is given

---

charts/consul/templates/ingress-gateways-deployment.yaml
charts/consul/templates/mesh-gateway-deployment.yaml
charts/consul/templates/terminating-gateways-deployment.yaml
control-plane/connect-inject/constants/constants.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller_ent_test.go
control-plane/connect-inject/controllers/endpoints/endpoints_controller_test.go
control-plane/connect-inject/webhook/consul_dataplane_sidecar.go
control-plane/connect-inject/webhook/consul_dataplane_sidecar_test.go
control-plane/connect-inject/webhook/container_init.go
control-plane/connect-inject/webhook/container_init_test.go
control-plane/subcommand/connect-init/command.go
control-plane/subcommand/connect-init/command_ent_test.go
control-plane/subcommand/connect-init/command_test.go

- Map k8s nodes to consul nodes for service registration instead of using one node per cluster
acceptance and unit tests
👀 
Checklist:

agentless: map k8s nodes to consul nodes instead of using one node

---

charts/consul/templates/gossip-encryption-autogenerate-podsecuritypolicy.yaml
charts/consul/templates/partition-init-podsecuritypolicy.yaml
charts/consul/test/unit/gossip-encryption-autogenerate-podsecuritypolicy.bats
charts/consul/test/unit/partition-init-podsecuritypolicy.bats

- Check for `global.enablePodSecurityPolicies` exists in other PodSecurityPolicy manifest, but missing in `gossip-encryption-autogenerate-podsecuritypolicy.yaml` and `partition-init-podsecuritypolicy.yaml` files.
- Update unit tests in `gossip-encryption-autogenerate-podsecuritypolicy.bats` and `partition-init-podsecuritypolicy.bats` to cover the variable `global.enablePodSecurityPolicies`.
- Via Unit-test
- Via Unit-test
Checklist:

Disable PodSecurityPolicy when global.enablePodSecurityPolicies set to false

---

charts/consul/templates/connect-inject-deployment.yaml
charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/values.yaml

- Allow to apply additional labels to the connect inject pods
We run this in our production.
I've added a unit tests.
Checklist:

Allow to apply additional labels to the connect inject pods

---

charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/server-config-configmap.bats
charts/consul/test/unit/server-statefulset.bats

In Consul 1.14, the grpc_tls port will be enabled by default on servers. This explicitly disables the port if encryption is not configured so that the defaults do not affect installations.

Explicitly disable grpc_tls when not using encryption.

---

charts/consul/templates/server-config-configmap.yaml
charts/consul/test/unit/server-config-configmap.bats

- Only support TLS config that is per-listener.
- BATS
- Acceptance
- 👀 
Checklist:

Update per-listener tls config

---

charts/consul/test/unit/connect-inject-deployment.bats
charts/consul/test/unit/ingress-gateways-deployment.bats
charts/consul/test/unit/mesh-gateway-deployment.bats
charts/consul/test/unit/terminating-gateways-deployment.bats
charts/consul/values.yaml

- Set the gateway anti-affinity defaults to null.
- Set the gateway default replicas to 1.
- 👀 
Checklist:

Gateway anti-affinity and replicas
